### PR TITLE
 DYN-7480 Merge master_cl-localization into master_cl

### PR DESCRIPTION
**Pull request by escbuild**
Hi , could you please review and merge this PR?

================== Word Count Statistics begin ==================

GMT Thu Sep 19 10:06:38 2024: Localization Engineer Lead for this PR is lilian.rossi@autodesk.com,MOR-REVIT-SLEs@moravia.com.

Vendor Engineer for this PR is MOR-REVIT-SLEs@moravia.com.

Localization branch is updated. 
New/Updated strings status
	CHS: all strings are translated
	CHT: all strings are translated
	CSY: all strings are translated
	DEU: all strings are translated
	ESP: all strings are translated
	FRA: all strings are translated
	ITA: all strings are translated
	JPN: all strings are translated
	KOR: all strings are translated
	PLK: all strings are translated
	PTB: all strings are translated
	RUS: all strings are translated

Please note that If the word count above shows some words in English, it is because the localization team hasn't processed all the new/updated strings yet. These words will be translated in the next translation loop.

Please merge this PR anyway as it will align the localizable file(s) content with the English file(s) content and prevent any functionality issue caused from misaligned localized file(s) versus English file(s).

If you are about to release and you are concerned about these strings showing up in English, please contact your localization contact/project team. Thanks.

=================== Word Count Statistics end ==================

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
Hi Team, About this changes I have two questions:
1. The resources were added manually using Visual Studio (Add -> New Item -> Resources File), right?
2. I can see that the Access Modifier for the Resources is "No code generation" while most of the resource files inside Dynamo solucion have the Access Modifier = Public, was this intentional?
Thanks

**Comment by QilongTang** [comment]
@lilian-rossi Are you able to answer the questions above?

**Comment by ZbynekHanak-RWS** [comment]
Hi @RobertGlobant20,

1. No, these localized files were not added via Visual Studio. CL takes as source the Resources.en-US.resx files, process it in our translation tool Passolo (replacing entries with translations) and generates the localized Resources.*.resx.
2. No Visual Studio related settings is done in CL, I believe the settings for the localized Resources.*.resx files should be the same to Resources.en-US.resx file.

Thank you

**Comment by RobertGlobant20** [comment]
> Hi @RobertGlobant20,
> 
> 1. No, these localized files were not added via Visual Studio. CL takes as source the Resources.en-US.resx files, process it in our translation tool Passolo (replacing entries with translations) and generates the localized Resources.*.resx.
> 2. No Visual Studio related settings is done in CL, I believe the settings for the localized Resources.*.resx files should be the same to Resources.en-US.resx file.
> 
> Thank you

@ZbynekHanak-RWS just by chance do you know how the Dynamo solution is built by the CI job using the resources that you added? or did you tested that your changes were working for other languages?

I'm asking because due that you didn't use Visual Studio for adding the .resx file (**so the tag <EmbeddedResources> is not added in the .csproj file**) I'm not sure how we are managing to build the Dynamo solution and use the resources added when Dynamo is in a different language.

Just for testing purposes in my local dev setup added the files **Resources.es-ES.resx** and **Resources.fr-FR.resx** in the path `....Dynamo\src\DynamoCoreWpf\Properties` the first one was added using VS2022 and the other one was added using an external tool (an app that just creates the .resx file in a specific location) but when using fr-FR the value was **NOT** found and used the default one so that's why I guess during the build process we are doing something specific for indicating the location of resx files in different language than english but not sure.

**Comment by ZbynekHanak-RWS** [comment]
Hi @RobertGlobant20 , unfortunately, I have no visibility how the Dynamo solution works. Seems this is not connected CI/solution build and localized files delivery from CL. Looks to build localized resources these localized .resx need to be added to the solution by Visual Studio first. CL process then just monitors changes in sources - Resource.en-US.resx files and delivers aligned/synced localized Resource.*.resx files. Thanks

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Re-running selfServe at https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16518/

**Comment by QilongTang** [comment]
We are ready to consume this change but ran into some pipeline problem

**Comment by QilongTang** [comment]
Since the PR checks keeps failing and the errors are related to some out of date dependencies, merging master into this branch to give it another try. Will merge once all checks passing

**Pull request merged**
