### PR TITLE
Replace local NUnit v2.6.2 dependency with NuGet NUnit v.2.6.3

### PR DESCRIPTION
**Pull request by alfarok**
### Purpose

[QNTM-4186](https://jira.autodesk.com/browse/QNTM-4186)

This PR removes a local dependency on NUnit v2.6.2 and replaces it with NuGet v2.6.3.  It was discovered that the Dynamo Core NuGet package used by developers requires v2.6.3 even though v2.6.2 is used in Core.  This was causing issues with running unit tests that also referenced the Dynamo Core NuGet package (such as Dynamo Samples).  This should also allow upgrading in the future to be more intuitive and provides the opportunity to more easily test newer versions of NUnit (latest is v3.10.1).

### Testing
All tests in Dynamo Samples are now passing and the Dynamo self-serve CI is now running to verify no additional issues were introduced or references missed.  Will post results when completed.

image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 

### FYIs

@QilongTang

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@alfarok what about the DynamoVisualProgamining Test nuget package. Do we need to update anything there or for RTF?

https://www.nuget.org/packages/DynamoVisualProgramming.Tests/

https://github.com/DynamoDS/RevitTestFramework/tree/Revit2019/lib/NUnit

**Comment by alfarok** [comment]
@mjkkirschner @QilongTang Everything builds correctly locally for me but it seems the self-serve relies on `C:\...\Dynamo\extern\NUnit`.  I also see some strange files in that folder such as `Rhino.Mocks.dll` and a few others.  I am not too familiar with the history here and was wondering if NUnit may have intentionally been kept as a local dependency in order to more easily accommodate the self-serve or something similar.

**Comment by alfarok** [comment]
And good points @mjkkirschner I still need to verify those

**Comment by alfarok** [comment]
Seems like deleting the old `C:\...\Dynamo\extern\NUnit` directory is causing a bunch of issues so I think I am going to restore it, leave the NuGet references, and copy the new `nunit.framework.dll` and `nunit.framework.xml` files from the NuGet package folder which have been updated to v2.6.3.  The additional files in the NUnit folder are not part of this update but are still used for other testing purposes

**Comment by alfarok** [comment]
I have a different approach I am going to take in a different branch, closing this PR to avoid confusion.

**Pull request closed without merging**
