### PR TITLE
MAGN-7277 Where possible, change tests in DynamoCoreTests to use DynamoModelTestBase

### PR DESCRIPTION
**Pull request by pbidenko**
### Purpose

This PR changes tests in `DynamoCoreTests` to use `DynamoModelTestBase` as described in `MAGN-7277`. It will help to remove all WPF references from DynamoCoreTests.

### Reviewers

@pboyer

### CODE REVIEW

**Comment by pboyer** [comment]
Thanks @pbidenko.  Have you run the tests successfully?

**Comment by pboyer** [comment]
Ping @pbidenko

**Comment by pboyer** [comment]
Sorry, I forgot you were on holiday today.  Let me know when you get the chance to take a look.

**Comment by pbidenko** [comment]
Hi @pboyer,
Yes, I have run the tests successfully, except those which have attribute `Category("Failure")`. And also there is a couple of tests in `NodeMigrationTests` that can't find `dyn` files for tests, so I added   attribute  `Category("Failure")` for them.
List of missing files:
-TestMigration_Analyze_Color.dyn
-TestMigration_Analyze_Structure.dyn
-TestMigration_Core_Evaluate.dyn
-TestMigration_Core_Functions.dyn
-TestMigration_InputOutput_Hardware.dyn

**Comment by pboyer** [comment]
I'm running the tests locally to validate, but the code changes look good.

**Comment by pboyer** [comment]
Hi @pbidenko, This looks good, but I'm going to commit this tomorrow so that I can oversee any possible regressions over the course of the day.

**Pull request merged**
