### PR TITLE
Added AvalonEdit Source, license files, and updated the installer bat & iss files

### PR DESCRIPTION
**Pull request by sh4nnongoh**
### Purpose

-Submitting of license files, and Avalonedit source code to Dynamo Open Source Repository.
-Editing of Installer BAT & ISS files to include source files and licenses into user's local directory after installation.
YouTrack link: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9353

-Editing of AppID to solve overriding issues.
YouTrack link: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9314

### Reviewers

@aparajit-pratap  Reviewer 1  

### FYIs

@Benglin

### CODE REVIEW

**Comment by RodRecker** [comment]
@sh4nnongoh Thanks for taking care of this. What is the destination folder?

**Comment by sh4nnongoh** [comment]
Hi @RodRecker I have set the destination to be:
C:\Program Files\Dynamo 0.9\3rdParty\OpenSourceComponents\Licenses
C:\Program Files\Dynamo 0.9\3rdParty\OpenSourceComponents\Source

**Comment by RodRecker** [comment]
Great - thanks you @sh4nnongoh

**Comment by aparajit-pratap** [comment]
Thanks @sh4nnongoh! Great job. @RodRecker should we cross-merge this into RC0.9.1 as well?

**Pull request merged**
