### PR TITLE
NodeAutocomplete UI fix

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

JIRA:  https://jira.autodesk.com/browse/DYN-4454

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers
@QilongTang @zeusongit

### CODE REVIEW

**Comment by QilongTang** [comment]
@reddyashish Any screenshot of what it looks like now?

**Comment by reddyashish** [comment]
Screen Shot 2022-04-11 at 10 46 06 AM

**Review by QilongTang — APPROVED** [review]

**Comment by reddyashish** [comment]
Looking into it now.

**Comment by zeusongit** [comment]
As per AC for this task, does this PR also handle long strings and truncate them using the ellipsis(...)?
Also, aabi pointed out that this happens in a localized setting, is this fixed in a localized environment as well?

**Comment by reddyashish** [comment]
@zeusongit yes this is fixed in a localized environment. If the string is long, it does use ellipsis like in the screenshot below
Screen Shot 2022-04-12 at 10 18 27 AM


The tests have passed here: https://master-15.jenkins.autodesk.com/view/DYN/job/DYN-DevCI_Self_Service/956/

**Comment by QilongTang** [comment]
@reddyashish The screenshot looks a bit strange, the entry highlight is less wide than the dialog overall?

**Review by zeusongit — APPROVED** [review]

**Comment by Amoursol** [comment]
> Yes, that is because the width of the dialog is different for different languages to compensate the header text. Using Auto for width, does't work here because it will highlight only till the width of the item string. So this width is fixed. what do you think?

The static size of the width, is that "Limited" by the other components, or fixed by itself? For example, if we were to make it say, twice as long currently, would the English UI look the same? And then would the German UI look complete? 

If possible we would want the full horizontal background color to sit appropriately.

**Comment by Amoursol** [comment]
> @Amoursol If we make it twice as long currently, the english UI would be too long in width.

Ok gotcha, so it's not bound and will overlap and look funny. If there are no other viable options, we can run with this.

**Comment by QilongTang** [comment]
Discussed with @reddyashish that we may want to make the internal entry width more dynamic

**Comment by reddyashish** [comment]
@QilongTang @Amoursol 

Looks like this with the new changes:

Screen Shot 2022-04-20 at 8 54 56 AM
Screen Shot 2022-04-20 at 8 55 26 AM
Screen Shot 2022-04-20 at 8 55 34 AM

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
