### PR TITLE
Fix regression issue open custom node and then open dyn mess up workspace

### PR DESCRIPTION
**Pull request by ke-yu**
This pull request is for fixing defect [MAGN-5919 Regression: open custom node and then open dyn mess up workspace](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-5919)

That's because view model (``DynamoViewModel``) has a list of workspace view model (``WorkspaceViewModel``) and model (``DynamoModel``) has a list of workspace model (``WorkspaceModel``) The position of workspace view model and workspace model in these two lists are important because they are binding to workspace tabs on the UI. 

Home workspace is always the first tab, so home workspace model and home workspace model/view model should always be the first item in both lists, but it isn't in model, therefore UI is messed up.

@Benglin for your review.

### CODE REVIEW

**Comment by Steell** [comment]
I disagree with the method used to implement this fix. The fact that the Home Workspace is always the first tab is a UI-specific implementation detail that should not reside in the Model layer. The Model layer also has support for multiple Home Workspaces, the fact that there is only one is again to be considered a UI implementation detail.

In my opinion, this is better fixed by introducing a dictionary in DynamoViewModel that can map WorkspaceModels to WorkspaceViewModels, so that the two lists do not need to be lined up by index.

Or, if this fix does go in, at least put in a TODO and YouTrack task to eventually remove the one Home Workspace assumption.

**Comment by jnealb** [comment]
@Steell @ke-yu @Benglin  Thanks Stephen, a.k.a "Refactor Man" one of the Masters of the Universe!

**Comment by Benglin** [comment]
Thanks for the background, @Steell. Hi @ke-yu, let's talk about this in the office tomorrow (and thanks anyway for fixing).

**Comment by ke-yu** [comment]
Thanks @Steell ! I

**Pull request closed without merging**
