### PR TITLE
Update number node output tooltip

### PR DESCRIPTION
**Pull request by pboyer**
### Purpose

**Before**

screen shot 2018-02-05 at 10 58 17 am

**After**

screen shot 2018-02-05 at 11 16 25 am

**Precedent**

screen shot 2018-02-05 at 11 01 32 am

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 

### FYIs

@Racel @jnealb

### CODE REVIEW

**Comment by jnealb** [comment]
LGTM

**Comment by Racel** [comment]
@pboyer - We have tried to remove all mention of double in Dynamo. Can you please just specify "number" instead?

**Comment by jnealb** [comment]
@Racel @pboyer Sliders still sport "double".

**Comment by Racel** [comment]
really? can we change that too?

**Comment by jnealb** [comment]
task is needed

**Comment by jnealb** [comment]
and everybody's favorite: 
image

**Pull request merged**
