### PR TITLE
Fix for Point Node Crash when Frozen

### PR DESCRIPTION
**Pull request by ramramps**
## Purpose

The purpose of this PR is to fix the crash on Point nodes freeze. 

 This PR refers to the below tasks 
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8958

## Design Document
 https://docs.google.com/a/adsk-oss.com/presentation/d/1MUhSzoDo-QFPysDv1E6gRslpq2pnb6eoPjKSsJN6g-o/edit?usp=sharing  

## Declaration
Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

## Reviewers
 @mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@ramramps LGTM, only thought is: is there another test suite that already loads protogeometry.dll so we don't increase the load time and memory for every test here?

**Comment by ramramps** [comment]
@mjkkirschner - oops. I will remove it and then merge.

**Comment by mjkkirschner** [comment]
@ramramps having the test if better than not :) I was just wondering if there was another applicable test project that already loaded protogeometry.dll

**Comment by ramramps** [comment]
@mjkkirschner - protogeometry is not required here.I got an error and thought it is because of Protogeometry. but it is not.;

**Pull request merged**
