### PR TITLE
Remove icons from Geometry class sub-categories

### PR DESCRIPTION
**Pull request by alfarok**
### Purpose

[QNTM-2675](https://jira.autodesk.com/browse/QNTM-2675)

[Supplemental Librarie PR](https://github.com/DynamoDS/librarie.js/pull/108)

The purpose of this PR is to remove the icons from the Geometry class sub-categories.  The icons beside the Geometry categories is confusing as they look like nodes and not sub-categories. 

This PR simply includes the updated `Librarie.min.js` file.  The modifications take place in this Librarie PR where any Element Type categorized as `none` does not load an icon.  This is the same logic `group` types follow.

### Documentation

[Updated Wiki](https://github.com/DynamoDS/Dynamo/wiki/Adding-or-Updating-Built-In-Library-Icons)

For more info on Element Types see the [Librarie Docs
](https://github.com/DynamoDS/librarie.js/blob/master/docs/layout-specs.md)
image

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] All tests pass using the self-service CI.
- [X] Snapshot of UI changes, if any.
- [X] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 

### FYIs

@Racel

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@alfarok - instead of altering the items in the layout spec - I think it makes sense to approach this generally - would we ever want categories like this to have icons? @Racel  - can you look into simply not generating an image element on categories like this?

**Comment by alfarok** [comment]
@mjkkirschner @Racel okay, no problem.  The task description and AC discussed removing them or making them visually distinct for clarity so I wasn't sure if we wanted to completely remove all referenced code or if it's something that was going to be revisited down the line.

**Comment by mjkkirschner** [comment]
Can this be merged ?

**Comment by alfarok** [comment]
@mjkkirschner yes will merge now along with [this](https://github.com/DynamoDS/librarie.js/pull/108) librarie PR

**Pull request merged**
