### PR TITLE
move dynamoPerf packages.config

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

noted that the build does not succeed for dynamoPerfTests as nuget config is not in project root. I am sure we can figure out how to repoint to `configs` folder - for now I need the build to succeed to get unblocked.

@QilongTang

### CODE REVIEW

**Comment by QilongTang** [comment]
LGTM

**Comment by QilongTang** [comment]
Moving forward, I would like to try this for all of our sln: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#benefits-of-using-packagereference

**Comment by QilongTang** [comment]
Can we discuss with the team and decide if we want to go with https://github.com/DynamoDS/Dynamo/pull/9664?

**Comment by mjkkirschner** [comment]
@QilongTang I'm going to merge this to get unblocked for now, lets talk about your solution tomorrow, I will comment more there.

**Pull request merged**
