### PR TITLE
add try catch to CLR Object Marshaler getStringValue

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

Address the situation where a `ToString` call on a clr object that is not null results in an exception - it turns out this happens quite frequently in Autocad and Revit.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
@mjkkirschner can we verify that the ToString calls on these Revit/AutoCAD objects are throwing the exceptions and that they are the reason for the crash?

**Comment by mjkkirschner** [comment]
I can try to reproduce locally with Revit, but the stack trace seems to imply that:
https://github.com/DynamoDS/Dynamo/issues/10816

**Comment by mjkkirschner** [comment]
Screen Shot 2020-07-30 at 5 01 25 PM

crashed before - after seems to execute ok.

**Comment by aparajit-pratap** [comment]
@mjkkirschner it looks like the exception for occurring for only certain parameters and not all. In cases, where the exception is being thrown and caught, there should be empty strings, am I right?

**Comment by mjkkirschner** [comment]
yep!

**Pull request merged**
