### PR TITLE
Remove Target Path From Publish Package Dialog

### PR DESCRIPTION
**Pull request by OliverEGreen**
### Purpose

Note: @QilongTang are you able to update the target branch please? This should reduce the number of files that this PR 'changes'. 

This PR removes the Target Path column in the `PublishPackageView` and its associate properties in the `PackageItemRootViewModel`.

SbA58DVHmV

@Amoursol regarding the above GIF, should the Publish Online button be enabled as shown here? This looks a bit odd to me given that the required fields haven't been filled in yet.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Removes a redundant column from the Publish Package dialog.

### Reviewers

@QilongTang @mjkkirschner 

### FYIs

@Amoursol
@SHKnudsen

### CODE REVIEW

**Comment by reddyashish** [comment]
This PR is to merge into master, right?. It shows other changes that are already in master.

**Comment by OliverEGreen** [comment]
> This PR is to merge into master, right?. It shows other changes that are already in master.

Correct, it will eventually need to be cherrypicked into master. 
This branch just makes it possible to open the Publish Package dialog.

**Review by reddyashish — APPROVED** [review]
Changes look good to me. Let's just make sure, it is cherrypicked into master and 2.13.

**Comment by Amoursol** [comment]
> @Amoursol regarding the above GIF, should the Publish Online button be enabled as shown here? This looks a bit odd to me given that the required fields haven't been filled in yet.

@OliverEGreen - Yes, can we please have the background greyed out until you are actually able to publish online? Ditto for Publish locally.

**Comment by OliverEGreen** [comment]
> > @Amoursol regarding the above GIF, should the Publish Online button be enabled as shown here? This looks a bit odd to me given that the required fields haven't been filled in yet.
> 
> @OliverEGreen - Yes, can we please have the background greyed out until you are actually able to publish online? Ditto for Publish locally.

I have a feeling it's to do with this code, which actually looks ok. Might just be because I'm accessing the dialog in a strange development use case. @QilongTang Any idea if this is correct?

image

**Comment by Amoursol** [comment]
@OliverEGreen - Yes, you need to be authenticated even to see this window. My point was around "Until you satisfy the requirements" could the color be grey, then change to blue? i.e minimum requirements are:

1. Name of package
2. Description of 10 characters or more
3. Version number

Until you satisfy this you cannot technically publish the package, so it would be cool to grey it out until then and "pop" up to blue when you are able to do so.

**Comment by QilongTang** [comment]
@OliverEGreen Just updating the base branch would not work because your changes are all based on the `EnablePublishDialog` branch... We need to keep the branch base clean and you will need to cherry pick your changes to a branch based on master to make PR.. Sorry about this process, our team will make it a debug mode in the future

**Comment by OliverEGreen** [comment]
> @OliverEGreen Just updating the base branch would not work because your changes are all based on the `EnablePublishDialog` branch... We need to keep the branch base clean and you will need to cherry pick your changes to a branch based on master to make PR.. Sorry about this process, our team will make it a debug mode in the future

Oh ok then - sure will get that over imminently

**Comment by QilongTang** [comment]
> > @OliverEGreen Just updating the base branch would not work because your changes are all based on the `EnablePublishDialog` branch... We need to keep the branch base clean and you will need to cherry pick your changes to a branch based on master to make PR.. Sorry about this process, our team will make it a debug mode in the future
> 
> Oh ok then - sure will get that over imminently

Appreciate it!

**Pull request closed without merging**
