### PR TITLE
Dyn 4825 2 output port colors

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose

Changing the OutputPort color instead of hiding it.
https://jira.autodesk.com/browse/DYN-4825)](https://jira.autodesk.com/browse/DYN-4825

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers
@QilongTang 

### FYIs
@filipeotero @RobertGlobant20

### CODE REVIEW

**Comment by jesusalvino** [comment]
nodeXY

**Comment by QilongTang** [comment]
@Amoursol Is this the expected behavior in your mind?

**Comment by Amoursol** [comment]
@QilongTang Looks good to me! Thanks so much for doing this guys.

**Comment by jesusalvino** [comment]
> @QilongTang Looks good to me! Thanks so much for doing this guys.

@avidit FYI

**Pull request merged**
