### PR TITLE
QNTM-5415 Expose ToJson() and OpenJsonFileFromPath() in DynamoCore as Public methods

### PR DESCRIPTION
**Pull request by saintentropy**
### Purpose

The purpose of this PR is to expose methods related to Json as public methods to allow interactions with the Dynamo API's that do not require interactions with the file system.  The PR does the following specifically.

- Changes `OpenJsonFileFromPath()` from private to public method and allows the API user to open a Model with only the json string.  This change also modifies the method parameters...   
previous: `(string fileContents, string filePath, bool forceManualExecutionMode)` 
new:        `(string fileContents, bool forceManualExecutionMode, string filePath = null)` 
The filepath is now marked as optional as it is only utilized to provide a path to scan for .dyf files.  

- Change the `ToJson()` methods on `WorkspaceModel` and `WorkspaceViewModel` to public.  This allows access to the serialized representation of this data.  Previously only the `JsonConverter`'s were public.

- Create an API method on the `DynamoViewModel` called `GetCurrentWorkspaceModelAndViewJson()` to get the combined Json of the `WorkspaceModel` and `WorkspaceViewModel` as would be saved to the file system as .DYN or .DYF file.  Currently we don't have a runtime object that represents this combined data set where a traditional `ToJson()` method would more logically apply.  I located this method in the `DynamoViewModel` so that it is adjacent to current API's for `Save()` and `SaveAs() that relate to the same combined json data model.

### TODO
- [ ] Discuss naming :-)
- [x] Add tests
- [x] Pass CI

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner @QilongTang 

### FYIs

@sm6srw

### CODE REVIEW

**Comment by QilongTang** [comment]
@saintentropy Understand the need of exposing the method to get the whole Json, but can you talk more about the use case of exposing `toJson()` on both model and ViewModel?

**Comment by saintentropy** [comment]
@QilongTang There are some cases where the user will only have a WorkspaceModel and will still need access to the json.  This also gives the developer opportunity to get access to the serialized data for there own purposes (ie alternate views of the graph data, etc)

**Comment by QilongTang** [comment]
@saintentropy Understood, originally I thought we only need to expose API for the whole json export, but I see no harm giving that flexibity to users. The only hope I have currently is not binding the export function to DynamoViewModel and maybe move it to WorkspaceView. Because this implementation could be less flexible when we introduce multiple workspace running again in the future, and user should still be able to get json of each workspaces without switching current workspace.

I am thinking of two APIs on WorkspaceView level
```
WorkspaceViewModel.toJson()
WorkspaceViewMode.getWholeGraphJson()
```
This should give us the flexibity that user getting the json of both currentWorkspace and customnodeWorkspace or any backgroundWorkspace.

My 2 cents

**Comment by saintentropy** [comment]
@QilongTang I think you suggesting makes sense as well... I think we just need to decide which is the least confusing.

**Comment by saintentropy** [comment]
@mjkkirschner do you have a strong preference if we move this functionality to the WorkspaceViewModel as @QilongTang suggests

**Comment by mjkkirschner** [comment]
@saintentropy is this required for 2.0.2?

**Comment by QilongTang** [comment]
@saintentropy Can you confirm this is still needed for Dynamo 2.1? Our code freeze will be before mid Jan so we need to put this in if it is required.

**Pull request closed without merging**
