### PR TITLE
Update Default Name format to save image

### PR DESCRIPTION
**Pull request by chuongmep**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

I want update save image should be become come just name of script, no include date time after.

Why I do this ? 

- Let see, my Package need Save image for 1000 Script with origin name of Script, I need to remove date time every time file name to update, can't override correctly, In case user want save image with some picture, I believe it is not problem with them if they can add for them self.

Let see preview my problem, my package needs to save for more than 1000 image with correct name of script, and after that it automation deploy in web : https://chuongmep.github.io/OpenMEP/api/OpenMEPRevit.Element.CableTray.html

ảnh

Let say, I have one script, I just need to save correct name of this script : 
ảnh

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

@Amoursol 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by Amoursol** [comment]
@QilongTang any thoughts on how we can help @chuongmep with his issue, but not affect current users who use this feature for things like Generative Studies that do require date-time stamping?

**Comment by QilongTang** [comment]
@Amoursol I would prefer making this part of preferences instead of touching the default name, maybe a  checkbox to include timestamp?

**Comment by Amoursol** [comment]
> @Amoursol I would prefer making this part of preferences instead of touching the default name, maybe a checkbox to include timestamp?

Agreed @QilongTang 😄 

@chuongmep would you be interested in amending your PR to make it an option, situated inside the Preferences Panel? If so please put it under "General" and use a button similar to the "Pause Splash Screen" to toggle use of DateTime suffix or not. 

image

**Comment by QilongTang** [comment]
@chuongmep Let us know if you are comfortable making that change, or our team can take over this PR

**Comment by chuongmep** [comment]
I agree with that if this change affect to another process like generative design and some user

**Comment by QilongTang** [comment]
@chuongmep I am taking over and working on this

**Comment by QilongTang** [comment]
Closing this PR in favor of https://github.com/DynamoDS/Dynamo/pull/14082

**Pull request closed without merging**
