### PR TITLE
MAGN-9042 Customizer MVP: Customizer code in Dynamo Studio

### PR DESCRIPTION
**Pull request by marimano**
### Purpose

Remove publish customizer code and move it to dynamo studio

### Declarations

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.

### Reviewers

@sharadkjaiswal

### CODE REVIEW

**Comment by marimano** [comment]
Hi @sharadkjaiswal, could you please take a look?

**Comment by sharadkjaiswal** [comment]
Hi @marimano, This looks good, except that you need to remove reference to removed modules from tools/install/InstallSpec.xml file.

**Comment by marimano** [comment]
hi @sharadkjaiswal, I have removed modules from tools/install/InstallSpec.xml file and updated publish code with using AssemblySharedInfo.cs. Please take a look again

**Comment by sharadkjaiswal** [comment]
Thanks @marimano, it looks good.

**Pull request merged**
