### PR TITLE
Remember position of Python editor windows & fix crash when deleting a Python node with an open editor

### PR DESCRIPTION
**Pull request by Dewb**
### Purpose

Python editor windows that are moved or resized from the initial location will remember their new size/position for the duration of the Dynamo session. This size information will not be persisted to the workspace, so closing and reopening the workspace, or Dynamo, will reset the window locations back to their default position.

If an editor window is on a secondary display when it is closed, and the secondary display is disconnected, the editor window will be restored to the default position if it is opened.

This also fixes a crash issue when the user deletes a Python node while the editor window is still open. The user will be shown a warning dialog giving them the opportunity to cancel the deletion, or hit OK to close the window and delete the node. ([QNTM-2533](https://jira.autodesk.com/browse/QNTM-2533)).

image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@aparajit-pratap 

### FYIs

@Racel

### CODE REVIEW

**Comment by Racel** [comment]
Thanks for doing this @Dewb. Just linked it to the OP about resizing Python windows. When this is merged, we should close that issue.

**Comment by aparajit-pratap** [comment]
@Dewb LGTM!

**Comment by Dewb** [comment]
@Racel image added!

**Comment by mjkkirschner** [comment]
Hey @Dewb I'm just curious what happens when you close a python node on an external monitor, and then later reopen it when the monitor doesn't exist?

**Comment by Dewb** [comment]
I finally got some "free time" (ha!) to investigate, and as I expected, the window is offscreen. Just pushed a fix that I tested on my 3-display desktop, but it could use some additional testing on a high-DPI display.

**Comment by mjkkirschner** [comment]
@Dewb I will try to test this this weekend.

**Comment by Racel** [comment]
@mjkkirschner - is this good to merge?

**Comment by mjkkirschner** [comment]
@Racel LGTM

**Pull request merged**
