### PR TITLE
Fixed parsing of typed identifiers for rank information

### PR DESCRIPTION
**Pull request by aparajit-pratap**
@junmendoza PTAL

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
Total Run time for all TestCases: 00:08:52.0955699 
Summary Infomation for NUnit:
________________________________________
Result for DLL: ProtoTest
Result	No. of TCs
Total	7695
Fail	0
Not-run	145
Errors	0
Inconclusive	1
Ignored	145
Skipped	0
Invalid	0
List of Failed TC's
Hooray…! There is no Failure or Error 

No regressions in `ProtoTest`

**Comment by junmendoza** [comment]
Cool. i think its exactly as designed. Plan to get at least 1 parse test in?

**Comment by junmendoza** [comment]
At least one test that will regress if this parse logic is not implemented should b fine

**Comment by aparajit-pratap** [comment]
@junmendoza I've added the test. Thanks.

**Comment by junmendoza** [comment]
LGTM

**Pull request merged**
