### PR TITLE
MAGN-9206 Change In-Canvas Search text box to match Library text box

### PR DESCRIPTION
**Pull request by marimano**
### Purpose

In-Canvas Search textbox matches styling of Library Search:
image

### Reviewers

@ramramps

### CODE REVIEW

**Comment by ramramps** [comment]
@marimano - Check racel comments.

**Comment by marimano** [comment]
@ramramps @Racel now it looks like next:
image

**Comment by Racel** [comment]
I think this blue border is better, but can we get the drop shadow behind it too? It looks like the drop shadow is only around the context menu. Also, please make sure to check the lone in-canvas search box that appears when you (shift+double-left-click). See below for current implementation.

image

**Comment by ramramps** [comment]
@marimano - Did you check the comment from Racel?

**Comment by marimano** [comment]
@ramramps @Racel if to put textbox inside shadow border it looks like next:
image

Single search textbox will look the same:
image

**Comment by ramramps** [comment]
@Racel - PTAL

**Comment by Racel** [comment]
@marimano - Can you take a larger screenshot? I want to see this over other nodes, etc.

**Comment by marimano** [comment]
@Racel, here are nodes and context menu opened in different places
image
image
image

**Comment by Racel** [comment]
Thanks, @marimano. This LGTM. 

Please check with @ramramps before merging.

**Comment by ramramps** [comment]
@marimano - Please test with  Preview bubble. Zindex is changed in preview bubble. I believe the search should always come infront, irrespective of Zindex..Can you post the snapshot?

**Comment by marimano** [comment]
@ramramps it is not needed to change ZIndex for the textbox anymore, because ZIndex was changed to make textbox in front of menu with shadow (so shadow was behind). Now textbox is inside shadow border too and ZIndex change is removed

**Comment by marimano** [comment]
the context menu is still in front of everything
image

**Pull request merged**
