### PR TITLE
Adding links to Dynamo Dictionary in start page and help menu

### PR DESCRIPTION
**Pull request by yeexinc**
### Purpose

This PR is to address [DYN-304](https://jira.autodesk.com/browse/DYN-304) and [DYN-305](https://jira.autodesk.com/browse/DYN-305)
A link to the [Dynamo Dictionary](http://dictionary.dynamobim.com/) is added on the start page and the help menu.
capture1

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@aparajit-pratap 

### FYIs

@riteshchandawar @Racel

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
@yeexinc this looks good. Please check with @Racel for the positioning of the dictionary link in the help menu. I think the task mentions to place it under "Getting Started". @riteshchandawar does this need to be cross-merged to either 1.2.2 or 1.2.3?

**Comment by Racel** [comment]
@yeexinc @aparajit-pratap - I think the link is fine where it is in the help menu. 

@riteshchandawar - If it is not too much trouble, it would be great to get it into the 1.2.3 build, but I am fine with leaving it for 1.3.

**Comment by aparajit-pratap** [comment]
@yeexinc please cross-merge this into RC1.2.3 branch. Thanks!

**Comment by yeexinc** [comment]
@aparajit-pratap , thanks very much for the review! PRs have been created as discussed.

**Pull request merged**
