### PR TITLE
Extract DynamoCore and DynamoRevit  Localization resources into different folders

### PR DESCRIPTION
**Pull request by monikaprabhu**
### Purpose

As part of Dynamo builds should be made more modular, the Localization resources needs to be separated into different folders. The PR addresses the same and removes the code related to Revit 
files.  

### Declarations

Check these if you believe they are true

- [x ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@sharadkjaiswal Please review the code.

### CODE REVIEW

**Comment by sharadkjaiswal** [comment]
Thanks @monikaprabhu, this looks good.

**Comment by QilongTang** [comment]
Ping @monikaprabhu

**Comment by QilongTang** [comment]
@sharadkjaiswal @monikaprabhu Do you think we still need this change? Otherwise I am going to close this PR because of the DNM lable.

**Comment by Racel** [comment]
Due to lack of response. Closing for now. @tanga - could this be related to the missing Revit samples?

**Comment by QilongTang** [comment]
@Racel  This looks unrelated.

**Pull request closed without merging**
