### PR TITLE
Removed "DynamoCoreWpf" reference from "DynamoCore"

### PR DESCRIPTION
**Pull request by Benglin**
Few things inspired by @junmendoza's [pull request](https://github.com/DynamoDS/Dynamo/pull/4362):

1. Stuff that read `DynamoCoreWpf` has no place in `DynamoCore`, moving them out.
2. `DynamoCoreWpf/Resource1.resx` is not used anywhere, removed it.

Hi @pboyer, I don't think you'll disapprove this, and @ikeough just FYI that I'm removing the `Resource1.resx` you added, probably by mistake. Shout at me if it shouldn't be removed and I'll bring them back.

Hi @junmendoza, PTAL. Thanks!

### CODE REVIEW

**Comment by ikeough** [comment]
None of this looks familiar. One thing to note, which is possibly unrelated...Loading cursors is really slow. On the IRenderPackageFactory branch, soon to be merged, I'm seeing several seconds to load the cursor files.

**Comment by Benglin** [comment]
Does it really take several seconds? If so, that's really bad. I have made [a maintenance task](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7310) for this to be worked on. Good point.

**Comment by ikeough** [comment]
@Benglin I just noticed what is causing this. I had my Macbook (with SSD) set to "Power Saver" mode. In "Balanced" mode it works fine. Really strange. Disk access must be severely crippled to save power, although I can't understand with an SSD why this would be a problem.

**Comment by junmendoza** [comment]
LGTM

**Pull request merged**
