### PR TITLE
Icons for surface booleans

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

some new icons for the new nodes
Screen Shot 2019-06-06 at 1 12 50 PM
Screen Shot 2019-06-06 at 1 12 53 PM

removes the localization files as well.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@aparajit-pratap @scottmitchell 

### FYIs

@smangarole

### CODE REVIEW

**Comment by mjkkirschner** [comment]
note I've also corrected the description to say `multi-faced`

**Comment by aparajit-pratap** [comment]
@mjkkirschner which icon are you reusing? At first I thought you created a new one :)
Also do you want to remove the part about "returns polysurface if non-manifold" from the node description?

**Comment by mjkkirschner** [comment]
@aparajit-pratap the description is still correct - if the the resulting union/difference would be non-manifold or multi-faced then a polysurface is returned instead. This is subtly different than the issue we discussed before (about the polysurface itself).

**Comment by mjkkirschner** [comment]
myself or @scottmitchell will take a look at creating new icons before merging this.

**Comment by mjkkirschner** [comment]
@aparajit-pratap created unique icons and added the small and large versions to the resx files.

**Comment by QilongTang** [comment]
icons looking good!

**Pull request merged**
