### PR TITLE
[Fix-3] Localize Graphic Scale Unit

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

The settings file save the unit in english, hence the bug when moving to another language. Created a Map from english to localized environment. This should fix all edge cases. The settings file will always save in english language to avoid any breaking changes.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

@avidit @QilongTang

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Somehow self serve did not trigger on this PR, I created job https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/13692/

**Comment by QilongTang** [comment]
The second run also failed

**Comment by zeusongit** [comment]
> The second run also failed

Yep, as tibi mentioned in slack, it is because of the polling job failure.

**Review by avidit — APPROVED** [review]

**Comment by QilongTang** [comment]
Thanks, looks like passing at https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/13696/

**Pull request merged**
