### PR TITLE
MAGN-5508 "Ctrl Z" daily builds 0.7.5.2014.11.20T1328

### PR DESCRIPTION
**Pull request by ramramps**
Double.TryParse method is not using invariant culture , this causes the double value to look like a string when the system is not US. 

Before this fix, any undo on the nodes (after the node is deleted) causes the node to move to infinity.

The fix to this was made in Double.TryParse method to use invariant culture.  when doing this fix, I saw that in few other places invariant culture was not used with Double.TryParse, hence changed all those places as well. 

- [ ] @pboyer

### CODE REVIEW

**Comment by ramramps** [comment]
- [ ] @jnealb - Is this something that you can test on VM's?

**Comment by jnealb** [comment]
@ramramps Not necessary - can reproduce on my machine (see steps in MAGN-5508).

**Comment by ramramps** [comment]
@jnealb  - This is fixed. Can you please test and confirm?

**Comment by jnealb** [comment]
@ramramps @root @ian @pboyer @RodRecker @sharadkjaiswal  LGTM - very curious as to the scope of other issues/symptoms that this PR fixes. Will report on that.

**Pull request merged**
