### PR TITLE
Revert "Fix for missing file ProtoGeometry.xml"

### PR DESCRIPTION
**Pull request by QilongTang**
Reverts DynamoDS/Dynamo#11218

FYI: @mjkkirschner Need to revert this one then https://github.com/DynamoDS/Dynamo/pull/11049

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I'm not clear we need to revert this one @QilongTang - I thought we still needed this to correctly consume protogeometry from nuget even without the PackageReferences changes?

**Comment by aparajit-pratap** [comment]
@QilongTang I don't think we need to revert these PR's (#11218 and #11049) as these are still required for LibG NuGets.

**Comment by QilongTang** [comment]
@aparajit-pratap Understood, but the master build is not in a release ready state after https://github.com/DynamoDS/Dynamo/pull/11049. We have known issues as:
1. extra binaries
2. Devs not easy to build it

After discussion with @mjkkirschner , we would like to revert it for now and put a more robust implementation in Dynamo 2.11.

**Comment by aparajit-pratap** [comment]
@qilongtang I'm not sure I understand. We had been integrating libg from nugets for several weeks without any issues before we decided to go with the package references. And the only reason we explored package refs was because we thought we could avoid having to make manual PRs to Dynamo to integrate the latest LibG builds.

**Comment by QilongTang** [comment]
Correction. We intend to revert https://github.com/DynamoDS/Dynamo/pull/11186 and deliver it part of Dynamo 2.11, not the libG nuget part

**Pull request merged**
