### PR TITLE
Improvements to Node Autocomplete UI

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

This PR is to make Node Autocomplete UI match the Dynamo Visual Refresh styling.
Task: https://jira.autodesk.com/browse/DYN-3359

Screen Shot 2021-05-04 at 8 37 22 AM

Screen Shot 2021-05-04 at 8 37 14 AM

**Things to do:**
1) We need a new more information icon as we don't have it being used anywhere else
2) Review with the UX team 

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@QilongTang @mjkkirschner @zeusongit @Amoursol

### CODE REVIEW

**Comment by Amoursol** [comment]
Hi @reddyashish - Looking pretty awesome so far! A few comments on what can be improved:

1. It looks like the Search icon in the bar is truncated at the top and bottom (Flattened off). We probably need a little more breathing room here?
2. Looks like the search text is also not centre justified? Would it look better if so? Or maybe center justified and a little smaller?
3. Looks like we have a lot of white space (Grey in this case) on the left hand margin of the results, and no white space (Grey space) on the right. Can we shift the results more to the left, and build in the same border / white space for the results? 
4. Can we make the "X" in the upper right white please? And also the same overall size as the "Autocomplete" header text? Also confirm they are justified the same.

**Comment by Jingyi-Wen** [comment]
Looking good! I agree with @Amoursol 's comments above, also covered everything!

**Comment by reddyashish** [comment]
@Amoursol I have made some changes based on your comments. This is the current look:
Screen Shot 2021-05-05 at 9 10 32 AM

1) Addressed the search icon issue. 
2) Made the search text little smaller and center-spaced(vertically).
3) Moved the results to the left and aligned it with other components.
4) Regarding the 'X' icon, I am actually using the image from here:https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/UI/Images/closetab_normal.png, which is used in other Dynamo locations. We do not have a white close icon as of now. What do you think?

**Comment by Amoursol** [comment]
> 1. Addressed the search icon issue.
> 2. Made the search text little smaller and center-spaced(vertically).
> 3. Moved the results to the left and aligned it with other components.
> 4. Regarding the 'X' icon, I am actually using the image from here:https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/UI/Images/closetab_normal.png, which is used in other Dynamo locations. We do not have a white close icon as of now. What do you think?

Awesome, thank you @reddyashish! Search icon and bar text looks great now. 

Would it be possible to give a little more breathing room (i.e. grey/white space) for both sides of the results? It's very close, I'm thinking only a few pixels here. 

@Jingyi-Wen are you able to provide a white cross Icon for this work? We don't currently have one 😊

**Comment by Jingyi-Wen** [comment]
Here's a white close icon (16*16 pixels, same as current one)
closetab_normal_white

**Comment by QilongTang** [comment]
You guys rock! I will take a look tomorrow

**Comment by Amoursol** [comment]
> You guys rock! I will take a look tomorrow

Make sure you enjoy your vacay first man 🙌

**Comment by reddyashish** [comment]
@Amoursol @Jingyi-Wen Addressed the suggested changes. Here is the current look:
Screen Shot 2021-05-06 at 9 25 06 AM

Let me know if you think of any changes.

**Comment by QilongTang** [comment]
@Amoursol @Jingyi-Wen @reddyashish I found `Search all nodes` misleading in this case because what it really does is searching through all autocomplete suggestions, anyway we can capture that?

**Comment by reddyashish** [comment]
Yes, I agree. Something like "Search Node Results"?

**Comment by Jingyi-Wen** [comment]
Agreed! I'd suggest "Search Autocomplete Results", or just "Search" would work

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@reddyashish @Jingyi-Wen Nice, I vote for `Search Autocomplete Results` so we can be specific

**Comment by Amoursol** [comment]
LGTM with the 'Search Autocomplete Results' in the search bar amendment @reddyashish !

**Comment by reddyashish** [comment]
Yes, changed it. 
Screen Shot 2021-05-06 at 12 14 24 PM

Merging this PR.

**Pull request merged**
