### PR TITLE
Remove Node Font Size Setting UI

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

per https://jira.autodesk.com/browse/DYN-4891, remove Node Font Size setting from Preferences Panel per customers' request. Customers intend to rely on graph zoom level instead.

Notice there is no effect on serialization because Dynamo does not serialize such a setting currently.
Before:
image

After:
image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

 remove Node Font Size setting from Preferences Panel per customers' request

### Reviewers

@DynamoDS/dynamo 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by avidit** [comment]
Can we keep `Default Run Settings` and `Show Run Preview` next to one another?

**Comment by Jingyi-Wen** [comment]
> > Can we keep `Default Run Settings` and `Show Run Preview` next to one another?
> 
> @Jingyi-Wen How do you feel about that?

I did think about that. From the visual design perspective though - the toggle is only taking one line whereas the radio button for run mode takes 2 lines, so they don't really line up. 
Maybe we can switch the position of the `Pause splash screen` and `Run preview` so those two are closer

**Comment by Jingyi-Wen** [comment]
> > > > Can we keep `Default Run Settings` and `Show Run Preview` next to one another?
> > > 
> > > 
> > > @Jingyi-Wen How do you feel about that?
> > 
> > 
> > I did think about that. From the visual design perspective though - the toggle is only taking one line whereas the radio button for run mode takes 2 lines, so they don't really line up. Maybe we can switch the position of the `Pause splash screen` and `Run preview` so those two are closer
> 
> Can we put the toggles on the same line?

I wouldn't recommend that. I think putting two irrelated items in the same line could be confusing. In a perfect world, it's better for both the `number format` and `number of recent files` should be in their own line too. (I do understand we are trying to save space and avoiding having to scroll to much)

**Comment by QilongTang** [comment]
@Jingyi-Wen @avidit Updated. PTAL

**Review by zeusongit — APPROVED** [review]

**Comment by QilongTang** [comment]
Reported regression is sporadic and @RobertGlobant20 is working on fixing it. Merging

**Pull request merged**
