### PR TITLE
8473 packagepublisherror

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

This PR fixes an issue where null or non success responses from the package manager would still close the window confusing the user and not displaying the error message.

If we encounter a null or non success response we return from the publish method - the publish window will stay open and the error message will be displayed correctly.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@ramramps 

##### FYI

@jnealb - for a new test

### CODE REVIEW

**Comment by ramramps** [comment]
Should the return be in catch too? Otherwise LGTM.

**Comment by mjkkirschner** [comment]
@ramramps I don't think it is necessary since if an exception is caught the method will stop execution at that point, the aim is to avoid calling ``packageUploadHandle.Done(null);`` which sets the state to uploaded and closes the window.

**Comment by mjkkirschner** [comment]
I'm going to merge this after running on the self serve CI

**Comment by mjkkirschner** [comment]
merging this as the self serve CI had only two errors which I've seen sporadically fail before on the self serve and nowhere else.

**Pull request merged**
