### PR TITLE
added methods the retrieve file path and directory of the active work…

### PR DESCRIPTION
**Pull request by plindjo**
### Purpose

A small addition to DSCore.IO.File that add two new nodes which enables the user to retrieve the file path and directory of the active workspace. Useful when working with relative file paths (e.g. sat import/export, etc.)
### Reviewers
- [](FILL ME IN) Reviewer 1

My first ever PR. Not sure who to assign as reviewer

### CODE REVIEW

**Comment by mjkkirschner** [comment]
Hi @plindjo - I'm not sure what at @Benglin thinks but I'm not sure this belongs in the core File.IO library. 

Instead I would imagine these nodes living in `Dynamo Services` or some other type of wrapped DynamoModel interaction/reflection library capable of creating DynamoModels in Dynamo. DynamoMeta?

**Comment by sharadkjaiswal** [comment]
@mjkkirschner, I think the intention of this PR is to have a node to get the path of the main workspace. If such a node would be useful for the users then I think this is the right place. @kronz, what do you think?

If any zero touch library developer is interested in getting this path then he may get it by linking to DynamoServices, using `Dynamo.Events.ExecutionEvents.ActiveSession.CurrentWorkspacePath` property.

**Comment by kronz** [comment]
What if we simply make any new Directory or File Path node start in the directory of the active workspace file?  @plindjo does that address the uses that you are thinking about?

**Comment by wynged** [comment]
To me, this node would be useful as away of creating explicitly relatively
file paths.

**Comment by plindjo** [comment]
@kronz if this would affect the default output (when no file/directory is selected), then yes. 
dsworkspacepaths

**Comment by sharadkjaiswal** [comment]
File Path and Directory Path nodes do have a notion of working directory and it stores relative path of the selected file or directory wrt the working directory, so when user moves both the DYN and the selected files together, the script will continue to work and user won't have to change the selection again to reflect the new path.
I am not sure if it makes sense to return current working directory as output when nothing is selected.

**Comment by plindjo** [comment]
I wasn't aware of that @sharadkjaiswal - thank you for clarifying! This makes the PR redundant so I'll close it :)

**Pull request closed without merging**
