### PR TITLE
Fix warnings for type mismatched calls on properties

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

After the switch to static method compilation of methods and properties, the warning messages weren't updated properly and were confusing:
image

This PR fixes the warning messages in these cases:
image
image
image

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [X] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@pboyer 

### FYIs

@jnealb @kronz

### CODE REVIEW

**Comment by pboyer** [comment]
LGTM, why the DNM?

**Comment by jnealb** [comment]
Is this part of an existing JIRA task?

**Comment by aparajit-pratap** [comment]
@jnealb I just created the JIRA task: https://jira.autodesk.com/browse/QNTM-3665. This is a regression from 1.3 due to static method compilation of nodes.

**Comment by jnealb** [comment]
@aparajit-pratap Thanks!

**Comment by aparajit-pratap** [comment]
Is this ok to merge then?

**Comment by QilongTang** [comment]
@aparajit-pratap Please feel free to merge

**Pull request merged**
