### PR TITLE
get ready for removal of  sys.win.int - manually hookup events

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

One approach to removing system.windows.Interactivity - 
it's ugly and brittle but it does load - and mostly works...

when the portViewModel collection is modified we hook up some event handlers and redirect these to the commands they are intended to call on the portViewmodel... 

We need to keep track of the observableCollection of `portViewModels` and remove the handlers etc etc.

meh.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
@mjkkirschner what is the change you've made to the `sys.win.int` binary? Should it not be removed in this PR?

**Comment by mjkkirschner** [comment]
Hey @aparajit-pratap - I forgot to include this in the PR descriptions, but have mentioned it a few times - it's arguable if we can remove the dll at this time completely as we still have a public type that inherits from it


`HandlingEventTrigger : System.Windows.Interactivity.EventTrigger`

it's kind of an odd case as it's in DynamoCoreWPF and is used in our views, but someone could have used or derived from this type.

**Comment by aparajit-pratap** [comment]
> Hey @aparajit-pratap - I forgot to include this in the PR descriptions, but have mentioned it a few times - it's arguable if we can remove the dll at this time completely as we still have a public type that inherits from it

Oh so you've just updated the version here?

**Comment by mjkkirschner** [comment]
yes updated the version - and while the `HandlingEventTrigger` type is still here, it's no longer used.

**Pull request closed without merging**
