### PR TITLE
Legal text updates to Package Manager workflows

### PR DESCRIPTION
**Pull request by Amoursol**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Text updated for both the Package Manager Authoring and Consumption workflows after conversation with Legal. 

Changes:
- Package Manager - Authoring license text updated, wrapping enabled.
- Package Manager - Consumer Details Extension license text updated, changed to vertical stack panel to enable license underneath the header, and added bold to all headers.

LegalTextUpdates

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Updated license text to better represent the license situation on packages on both Package creation and consumption.

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by Amoursol** [comment]
@QilongTang @jasonstratton - Submitted a PR here to update legal text and change slightly some WPF with the help of @OliverEGreen and @mjkkirschner.

Can we delete all the Package Manager changes/by-pass stuff from the "EnablePublishDialog" branch rather than merge? Just let me know 😄 Beyond that, the changes are pretty simple.

**Comment by QilongTang** [comment]
> @QilongTang @jasonstratton - Submitted a PR here to update legal text and change slightly some WPF with the help of @OliverEGreen and @mjkkirschner.
> 
> Can we delete all the Package Manager changes/by-pass stuff from the "EnablePublishDialog" branch rather than merge? Just let me know 😄 Beyond that, the changes are pretty simple.

hmm you will need to cherry-pick your changes to a new branch, or simply revert the changes you dont want

**Comment by QilongTang** [comment]
hi @Amoursol I will cherry-pick your changes to a new branch based on master and ask you to open up the PR again.

**Comment by Amoursol** [comment]
> hi @Amoursol I will cherry-pick your changes to a new branch based on master and ask you to open up the PR again.

Ok cool - sounds good!

**Comment by QilongTang** [comment]
Changes cherry-picked to https://github.com/DynamoDS/Dynamo/tree/UpdatePMLegaclTexts, closing this one for now

**Pull request closed without merging**
