### PR TITLE
update greg - this changes the name of zipped temp package files

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

update greg (package manager client) nuget package to avoid zipping bug caused by running the tests in parallel to avoid multiple processes trying to access the same zip file.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### CODE REVIEW

**Comment by QilongTang** [comment]
LGTM. However notice it takes sometime for the newly published nugets to appear in the downloadable list. I suggest wait a bit to merge this.

**Comment by mjkkirschner** [comment]
@QilongTang yes, I also want to see if this causes any regressions.

**Comment by mjkkirschner** [comment]
😒 - some properties got reversed in order in the csproj files, will fix it.

**Comment by alfredo-pozo** [comment]
LGTM

**Pull request merged**
