### PR TITLE
[DYN-7466] Follow up - Zoom to fit to nodes/groups selected in TuneUP and GraphNodeManager

### PR DESCRIPTION
**Pull request by ivaylo-matov**
### Purpose

This PR is related to [DYN-4766](https://jira.autodesk.com/browse/DYN-7466) and is a follow up to [this thread](https://autodesk.slack.com/archives/CPJ5UQW0Z/p1726605504746209) and point 4 of [this Mural](https://app.mural.co/t/autodesk2145/m/autodesk2145/1726671147065/f22bbd9296463ee3376ffd3c5be0a9e68028b323?sender=u63a4c10277115ad8dc555082).

Now, clicking on a node or group in TuneUp or GraphNodeManager will trigger a zoom-to-fit action for the selected node or group. Previously, the behavior only centered on the selected node.

Additionally, I have removed the `x is AnnotationModel` check from the `    public partial class WorkspaceViewModel : ViewModelBase
.GetSelectionMinX()`, `GetSelectionMinY()`, `GetSelectionMaxX()`, and `GetSelectionMaxY()` methods. This change allows the functionality to work with groups, and I couldn't find any reason for keeping that check in place.

**_Before:_**

DYN-7466_Before

**_Afrer:_**

DYN-7466_After

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Adds zoom-to-fit functionality for nodes or groups selected in TuneUp and GraphNodeManager.

### Reviewers
@reddyashish 
@QilongTang 

### FYIs
@dnenov 
@Amoursol

### CODE REVIEW

**Review by reddyashish — APPROVED** [review]

**Comment by reddyashish** [comment]
@ivaylo-matov This test 'DynamoCoreWpfTests.CoreUserInterfaceTests.PreferenceSetting' is failing. Can you check it.

**Comment by ivaylo-matov** [comment]
@reddyashish , could you please check the test again? I've run it several times, and it keeps passing on my end.😶

Screenshot 2024-10-16 062857

**Comment by reddyashish** [comment]
Running again https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16569/

**Comment by reddyashish** [comment]
Now that the seff-serve is stable, running again https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16597/. Last runs failed.

**Comment by reddyashish** [comment]
Merging this, test passed.

**Pull request merged**
