### PR TITLE
Add Pause Splash Screen Tooltip and Run Preview Tooltip

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose
Implementing the improvement https://jira.autodesk.com/browse/DYN-5721

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Reviewers
@QilongTang 

### FYIs
@RobertGlobant20
@Enzo707

### CODE REVIEW

**Comment by jesusalvino** [comment]
pref-tooltips

**Comment by zeusongit** [comment]
Does this work with localized strings? Can you test that as well?

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
> > > Does this work with localized strings? Can you test that as well?
> > 
> > 
> > Do you mean when the tooltip is localized?
> 
> No I mean when the preference option is localized, I saw some examples where when localized the location of the question mark will not change while the string is now longer than it is in English.

Gotcha, do you recall which ones? I guess for @jesusalvino Please just sanity check other languages to see if the position is good

**Comment by zeusongit** [comment]
> > > > Does this work with localized strings? Can you test that as well?
> > > 
> > > 
> > > Do you mean when the tooltip is localized?
> > 
> > 
> > No I mean when the preference option is localized, I saw some examples where when localized the location of the question mark will not change while the string is now longer than it is in English.
> 
> Gotcha, do you recall which ones? I guess for @jesusalvino Please just sanity check other languages to see if the position is good

German / de-DE

**Comment by reddyashish** [comment]
@Jingyi-Wen Looks like there is extra space between the label name and the icon. Probably reduce that a little? Also not icon is not center aligned vertically in some cases.

**Comment by jesusalvino** [comment]
de-DE lang looks good IMHO

image

**Review by zeusongit — APPROVED** [review]

**Comment by Jingyi-Wen** [comment]
> @Jingyi-Wen Looks like there is extra space between the label name and the icon. Probably reduce that a little? Also the icon is not center-aligned vertically in some cases.

Good catch! We definitely should have them center-aligned vertically. And agree with reducing the space, the icon next to the Max Number of Recent Files text box is a good reference

**Pull request merged**
