### PR TITLE
Replication guide won't do list promotion

### PR DESCRIPTION
**Pull request by ke-yu**
### Purpose

Replication guide is used to do iteration over input. An input may have multiple replication guides which represent multiple levels of iteration, so for some inner iteration, if value is not a list, it will be promoted to a list so that it could be iterated.

For example, the following code is expected to generate a point array which contains a single point because `x` is promoted to a list because of its replication guide `<1>` (NOTE: due to some bug, this code only generates a single point instead of an array in Dynamo, this is *not* expected!):
```
x = 0;
pt = Point.ByCoordinates(x<1>, 0, 0);
```

The following code will generate a 3D array in Dynamo, because `y` and `z` are both promoted to arrays, so the dimension of final output in cross-product case is 1 + 1 + 1 = 3. 
```
xs = 1..5;
y = 0;
z = 0;
pts = Point.ByCoordinates(xs<1>, y<2>, z<3>);
```

Or its graph representation (Again, due to some defect, the right-hand side node generates different result, which is *not* expected).:

capture2

The problem is this kind of array promotion will easily generate unexpected high dimensional list, and frequently users have to use `Flatten()` node to flatten the list. This PR disable this behavior. So replication guide won't promote a single value to a list. Or, in the other word, the dimension of output list wont exceed the sum of dimensions of all inputs.

The following node shows new behavior, note two nodes now have same output:
capture3 

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@kronz @Racel @riteshchandawar 

### FYIs
@gregmarr

### CODE REVIEW

**Comment by sharadkjaiswal** [comment]
Wow, I liked this PR. removing the code fixes the behavior.

**Comment by kronz** [comment]
the default state "bug" adds a layer of confusion, so it's good to see that explicitly.  My only hesitancy to give this a big thumbs up is needing to recover the history around what I suspect are some corner conditions that this enabled.  @Racel  is back now from vacation so we will confer on this.

**Comment by Racel** [comment]
@ke-yu - This PR looks good to me and is what most users would expect the behavior to be. As Zach mentioned, are there any edge cases where not promoting a single value to a list would cause an issue? What happens with nodes that call for a list input instead of a single value? If I use a single value for those nodes, will it not be promoted to a list? See the example below...

image

Would the List.Count and List.Cycle nodes now error because of this change? 

In general, I think this brings some clarity to the inconsistent behavior we were seeing with the default values bug. Just want to know what could fail or change in behavior once this is implemented...

**Comment by ke-yu** [comment]
@Racel @kronz this PR is only about list promotion in replication guide case, it doesn't change the behaviour of passing a single value to a function which takes a list ( single value will be promoted to a list).

**Comment by aparajit-pratap** [comment]
@ke-yu could you run self-service to verify it doesn't break anything and merge this.

**Comment by Racel** [comment]
@aparajit-pratap @ke-yu @kronz - Can we have a meeting about this before merging? It is important that we understand why the behavior was defaulted to auto promotion in the first place. There were UX language decisions that were made early on that I think it would be good for us to consider before making this change.

**Comment by aparajit-pratap** [comment]
image

image

I would expect the above cases to continue to work as expected, which they do. In all cases the highest rank of the inputs is preserved (not less, not more) after being passed into the functions irrespective of the replication guides.

**Comment by Racel** [comment]
@lukechurch - Can you please take a look at this since you worked on this before? Want to understand the initial design decisions around this before making any changes.

**Comment by Randy-Ma** [comment]
With the change, the graph fails as illustrated:
image

Originally, it succeeds:
image

@ke-yu @Racel @kronz @sharadkjaiswal @aparajit-pratap 
Is this something that we can ignore?

**Comment by ke-yu** [comment]
@Randy-Ma that's not expected.

**Comment by Racel** [comment]
@ke-yu - Let's add @Randy-Ma 's example as a consideration for whether or not we change the behavior. 

So, in @Randy-Ma 's example, is the node failing because the "y" input was not being promoted to a list?

**Comment by aparajit-pratap** [comment]
Closing this PR as it has been cherry-picked in #8073

**Pull request closed without merging**
