### PR TITLE
DYN-5782-PrePopulate-CustomColorPicker

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

This fix will be pre-populating the custom colors in CustomColorPicker with the colors added in the Preferences->GroupStyles section (just for custom Styles). This fix is not applicable for the Color Palette node.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

Pre-populating the custom colors in CustomColorPicker with the colors added in the Preferences->GroupStyles section.

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
GIF showing the behavior of the CustomColorPicker.
PreLoadedCustomColorPickerColors

**Comment by QilongTang** [comment]
Hi @RobertGlobant20 This does not apply to color picker node because there is no access to Preferences Panel?

**Comment by QilongTang** [comment]
> > Hi @RobertGlobant20 This does not apply to color picker node because there is no access to Preferences Panel?
> 
> @QilongTang well If you are referring to the Color Palette node, I think is more logical to add it in the color picker that is used in the GroupStyles section (due that is reading colors from the custom Group Styles). It can also be applied to Color Palette node I just need to check if we have a way to access preferencesSettings instance, please let me know if I should add this functionality (by the way I've asked that question in the Jira task yesterday).

Understood, I think both cases are what customer asked, please give it a check. Thanks!

**Comment by RobertGlobant20** [comment]
> > > Hi @RobertGlobant20 This does not apply to color picker node because there is no access to Preferences Panel?
> > 
> > 
> > @QilongTang well If you are referring to the Color Palette node, I think is more logical to add it in the color picker that is used in the GroupStyles section (due that is reading colors from the custom Group Styles). It can also be applied to Color Palette node I just need to check if we have a way to access preferencesSettings instance, please let me know if I should add this functionality (by the way I've asked that question in the Jira task yesterday).
> 
> Understood, I think both cases are what customer asked, please give it a check. Thanks!

@QilongTang functionality added for the Color Palette node and I've added a unit test. Thanks
see the next commit:
https://github.com/DynamoDS/Dynamo/pull/13903/commits/93d356e910d61f8606e1c165a18c7fab289dafce

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
