### PR TITLE
New Icon for Display Color

### PR DESCRIPTION
**Pull request by YanmengLi**
### Purpose

Reference: [MAGN-9872](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9872)
This PR is to add two missing icons for nodes in the Display Library:
Display.ByGeometryColor
Display.BySurfaceColors

bygeometrycolor
bysurfacecolors

And add two missing icons for ColorRange2D nodes:
ColorRange2D.ByColorsAndParameters
ColorRange2D.GetColorAtParameter

New Icon:
bycolorsandparameters
getcoloratparameter

Old icon:
bycolorsandparameters
getcoloratparameter-2

And add large icon for Core.Math.Log10
ln10

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.

### Reviewers

@Racel 

### FYIs

@riteshchandawar

### CODE REVIEW

**Comment by Racel** [comment]
@YanmengLi @riteshchandawar @kronz - These icons look good to me. Please make sure they are added into the appropriate illustrator files and are of the correct resolution. Please add the links in the YT.

**Comment by YanmengLi** [comment]
All of the work has been done.

**Comment by YanmengLi** [comment]
Add two more icons for ColorRange2D nodes.

**Comment by Racel** [comment]
@YanmengLi - These look good to me, but you may want to consider either increasing the size of the UV in the second image or dropping that text all together. It is not legible in the smaller icon. You may also consider dropping one row and column to increase the individual UV box size. It could make it easier to read.

**Comment by YanmengLi** [comment]
@Racel I update the icon. Thanks for helping check.

**Comment by Racel** [comment]
@YanmengLi - That is better, but the letters in both the ColorRange images are still not legible in the the small icon. I would suggest getting rid of them all together or increasing the font size even more so that they are informative in the small icon. The small icon is what the user will be seeing the most. The user should be able to tell at a glance the difference between the 2 icons.

**Comment by YanmengLi** [comment]
I have double check this and the font could be seen in small icons. The image resolution is not high enough so it look a bit blur. Ok I will fine tune and send again.

**Comment by YanmengLi** [comment]
@Racel Please check whether two new icons for ColorRange2D look fine. Thanks.

**Comment by Racel** [comment]
Thanks, @YanmengLi. These are better 👍

**Comment by YanmengLi** [comment]
Update already. Thanks @Racel for helping check.

**Comment by riteshchandawar** [comment]
@YanmengLi  Why the Travis CI build failing?

Do you need to do anything to fix that?

- Ritesh

**Pull request merged**
