### PR TITLE
Dyn 4156 update tool tip styling

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose

Update the Generic Tooltip Style and the connector dot size

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers
@QilongTang

### FYIs
@RobertGlobant20 @filipeotero

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by jesusalvino** [comment]
imagen
Connector Dot resized

**Comment by QilongTang** [comment]
@jesusalvino A few questions. For the tooltips already following our new styles, do you have style defined inline? Do we need to update to use the new `GenericToolTipLight`? And also do we need to update font used as well for `GenericToolTipLight`?

**Comment by zeusongit** [comment]
I have a similar concern as Aaron, I see that you have targeted the Tooltip property itself, does this overwrite any custom styles applied to the tooltip in any of the views?

**Comment by jesusalvino** [comment]
> @jesusalvino A few questions. For the tooltips already following our new styles, do you have style defined inline? Do we need to update to use the new `GenericToolTipLight`? And also do we need to update font used as well for `GenericToolTipLight`?

The SLightToolTip already had the expected styling , a different structure and is being used in specific cases, so it's out of scope for this change, it's no necessary update it. The GenericToolTipLight used across the solution keeps the same font as the previous definition.

**Review by zeusongit — APPROVED** [review]
:shipit:

**Comment by QilongTang** [comment]
@jesusalvino Let's check with @Jingyi-Wen tomorrow if the new font is preferred in this generic tooltip style as well

**Review by QilongTang — APPROVED** [review]

**Comment by Jingyi-Wen** [comment]
Yes, the Artifakt Element Regular would be the universal font for tooltips.

**Comment by QilongTang** [comment]
Thanks for confirmation @Jingyi-Wen , @jesusalvino I'm afraid we need to apply that somehow in the `GenericToolTipLight` style as well, would you do that?

**Pull request merged**
