### PR TITLE
check path as part of readOnly getter

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

readonly property should be true if path is readonly.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@QilongTang 

### FYIs

@smangarole @jnealb

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I still need to run the self serve ci.

**Comment by mjkkirschner** [comment]
@QilongTang yes, it should become non-readonly if they remove all dummy nodes.

**Comment by QilongTang** [comment]
@mjkkirschner So read-only will be removed once all dummy nodes are resolved or removed. Can you add that to the AC of the Jira task?

**Comment by mjkkirschner** [comment]
yes, can do.

**Comment by mjkkirschner** [comment]
@QilongTang has pointed out some more edge cases - never simple :)

**Comment by mjkkirschner** [comment]
@QilongTang I've amended my comments above - here is what I have found:

* version 1.3 - open graph with dummy node, import package or dll with that node in it - node error disappears but does not run (still null) - dummy node is not replaced

* version 2.x - same behavior except node error is not resolved.

In both cases the graph still has dummy nodes in it and must be manually reloaded to resolve the dummy nodes, so I remove my comment above which stated that the readonly state would be removed automatically, it won't since the graph will need to be reloaded.

Can you review again given that information and let me know if there are tests you want or changes?

**Comment by QilongTang** [comment]
OK. Given the information above, I am assuming version 2.x - same behavior except node error is not resolved. (node stays yellow) at this point, `workspace.containsXmlDummyNodes()` still returns true and workspace in memory is still read-only, is that true? Which means there is no-way this graph suddenly become non-readonly, then I am fine with this change in the PR. If not, what would happen?

**Comment by mjkkirschner** [comment]
yep, theres no way for this graph to become non-readonly via library import - BUT a user could delete the unresolved nodes and then I guess we should have the state become non-readonly....I know that the model state is correct (there is a test for this) but the tab does not update - I will fix this tomorrow.

**Comment by QilongTang** [comment]
@mjkkirschner Thanks, that's all I wish to be resolved

**Comment by mjkkirschner** [comment]
@QilongTang ... actually, I think we need to talk about how important this is, I'm not seeing a good way of having this update unless it updates whenever the graph is changed, that means everytime the graph is changed we need to scan the whole graph to see if we find any xml dummy nodes... this seems like a bad trade off in terms of potential slow down for some more information for a very limited usecase. Let's talk tomorrow - apologies this one is dragging on.

**Pull request merged**
