### PR TITLE
NodeSearchTags

### PR DESCRIPTION
**Pull request by zora-wang**
Hi Ben, NodeSearchTags has been updated. Please check it.

Thanks

### CODE REVIEW

**Comment by Benglin** [comment]
Hi @zora-wang, are these still required? Or are they replaced by the work of @holyjewsus?

**Comment by zora-wang** [comment]
I think we donot need it anymore. But let me check it tomorrow morning .

**Comment by Benglin** [comment]
Sure, since you'll be preoccupied in training tomorrow, @holyjewsus might be able to weigh in here ;)

**Comment by holyjewsus** [comment]
hi @Benglin and @zora-wang the github diff may be incorrect but, I believe the only overlap between Pull requests was Watch and Watchimage.

**Comment by Benglin** [comment]
Thanks a lot @holyjewsus, I think @zora-wang will take care of the others after the trainings :)

**Comment by pboyer** [comment]
@Benglin @zora-wang What's the status here?

**Comment by Benglin** [comment]
This pull request has been superseded by [another newer pull request](https://github.com/DynamoDS/Dynamo/pull/4404). Closing this one.

**Pull request closed without merging**
