### PR TITLE
QNTM-1965: Fix for zipped lacing post list promotion changes

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

This is a fix for regressions caused by changes in #8073 to disable list promotion of arguments when passed into nodes with lacing. 
JIRA Link: https://jira.autodesk.com/browse/QNTM-1965

**Note:** There is a pending defect with differences of behaviour found with the use of default argument as described below. This bug has also been referred to in #7773 and does not surface so glaringly in 1.3 and earlier as older versions precede the introduction of the "shortest lacing" option that has been added to nodes in 2.0:

image

image

Both the scenarios are expected to return the same result but as can be seen in the second example, the reason for the difference is that in the case of a default argument, the replication guide (lacing) is not applied to the default argument, which explains the difference in behaviour. This needs to be addressed by generating the correct DS code that applies the relevant lacing options to the default argument as well.

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate - adding unit tests in progress ...
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [X] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### FYIs

@Racel @QilongTang @jnealb @smangarole

### CODE REVIEW

**Comment by QilongTang** [comment]
@aparajit-pratap Any reviewer of this? Or you will just merge it as is and watch for the test failure?

**Comment by aparajit-pratap** [comment]
@QilongTang I am waiting for the self-service results to come back before merging this.

**Comment by mjkkirschner** [comment]
@aparajit-pratap you may want to restart the job - I think my previous PR had them stuck with a dialog that needed to be dismissed.

**Comment by aparajit-pratap** [comment]
@mjkkirschner I have restarted the job twice and it has timed out both times. Any idea why the self-service isn't going through?

**Comment by mjkkirschner** [comment]
@aparajit-pratap have you merged my latest commit into your branch before running the self service?

**Comment by aparajit-pratap** [comment]
@QilongTang @smangarole I'm merging this as I got the green signal from you that the 2 tests this was supposed to fix have been fixed, namely,  `MAGN_122` and `EdgePlaneIntersection`. All self-service tests are passing and I've added new test cases, not originally existing, to be able to catch such lacing scenarios.

**Pull request merged**
