### PR TITLE
Dyn 4640 display copyright fields

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose

Display the Copyright info in the Package detail and update the Greg version

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers
@QilongTang

### FYIs
@RobertGlobant20 @filipeotero

### CODE REVIEW

**Review by reddyashish — APPROVED** [review]

**Comment by QilongTang** [comment]
Looks like this PR does not build?

**Comment by jesusalvino** [comment]
> Looks like this PR does not build?

Fixed, the Greg version has been updated in the test projects

**Comment by QilongTang** [comment]
@jesusalvino Please also attach a screenshot of UI difference

**Review by QilongTang — APPROVED** [review]

**Comment by jesusalvino** [comment]
> @jesusalvino LGTM but please also attach a screenshot of UI difference

imagen

**Comment by QilongTang** [comment]
@jesusalvino Would you make `CopyRight holder` and the other column wider?

**Review by QilongTang — APPROVED** [review]

**Comment by jesusalvino** [comment]
> @jesusalvino LGTM but please also attach a screenshot of UI difference

imagen

**Pull request merged**
