### PR TITLE
Update Helix Toolkit from 2.11 to 2.15

### PR DESCRIPTION
**Pull request by saintentropy**
### Purpose

This PR is to update the Helix Toolkit (and by association the Cyotek.Drawing.BitmapFont dependency) from version 2.11 to version 2.15. The purpose of this PR is to address a memory optimization related to the https://github.com/DynamoDS/Dynamo/pull/11395 PR (Generating a single render package per node).  Specifically the https://github.com/helix-toolkit/helix-toolkit/pull/1494 PR modifies the behavior of the `VertexArrayBuffer` which was being retained in memory as a sparse array based on the largest size mesh to be rendered in the session.  In 2.15 this buffer is not pinned to the largest allocation size in session.    

As a point of interest.  This Helix PR fix was triggered due to the issue filed by @aparajit-pratap.  https://github.com/helix-toolkit/helix-toolkit/issues/1449

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@aparajit-pratap @mmisol 

### FYIs

@mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I must be misunderstanding that PR - because it still looks like the default is to create a buffer(vertexCount) ?

Also since the default for `isTransient` is false, we're not taking advantage of the buffer be cleared - and if we were, then hit testing would be broken it seems.

**Comment by saintentropy** [comment]
@mjkkirschner for our purposes the new `ThreadBufferManager` is what affects us. Here are the relevant changes to the `MeshBufferModel` and `LineBufferModel`:

image

and
image

The original local `vertexArrayBuffer` was always retained and would just keeping getting larger based on the largest array of the session.  Now per their documentation -> per their notes _/// If requested size is larger than this value, buffer will be temporary instead of being retained for reuse._

**Comment by saintentropy** [comment]
The `isTransient` optimization can be looked at in the future but not related to the memory issue we were addressing

**Review by mjkkirschner — APPROVED** [review]

**Comment by mjkkirschner** [comment]
It looks good to me, but it's probably good to run the view comparison tests.

**Comment by saintentropy** [comment]
Image comparisons are pass @mjkkirschner @aparajit-pratap

**Pull request merged**
