### PR TITLE
Revert Project Reference Changes

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

This PR reverts https://github.com/DynamoDS/Dynamo/pull/11186 and also was trying to
1. Fix the `processorArchitecture` for all the instances of `AMD64` to `MSIL`
2. Remove `Microsoft.VisualStudio.CodeCoverage.Shim` which is a pending action per Global Launch from previous comment. Confirmed done. FYI: @mjkkirschner 
3. Maintain maximum binary compatibility with Dynamo 2.9.0. Only binaries supposed to be removed are removed. By my manual verification, no new binaries introduced. We can run binary_diff job again after merge.
4. Still target to latest libG nugets

But found the following problem
1. The  `processorArchitecture` was automatically set to `AMD64` after nuget update, I suspect our nuspec for libG is wrong on that. Let's follow up @alfredo-pozo 
2. LibG is still v2.9, I am not sure if libG version still need to map Dynamo in the new setup. @aparajit-pratap @mjkkirschner 

Steps for dev to build locally:
1. Delete all obj folders
2. Build Dynamo.all.sln

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@DynamoDS/dynamo 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mmisol** [comment]
I was able to build this from Visual Studio. One thing I noticed though is ProtoGeometry still appears repeated in the nodes folder, even after making sure I deleted all bin and obj folders.

**Comment by QilongTang** [comment]
> I was able to build this from Visual Studio. One thing I noticed though is ProtoGeometry still appears repeated in the nodes folder, even after making sure I deleted all bin and obj folders.

Good point. Let me take a look and also the failing regressions.

**Comment by QilongTang** [comment]
@mmisol Addressed the issue you found. Running self CI manually for now, will update later

**Comment by mjkkirschner** [comment]
regarding MSIL vs AMD64 - the references I have been able to dig up on this so far indicate that AMD64 - really just means 64bit (not intel v AMD) - and indeed LibG is built on top of x64 binaries.

https://forums.autodesk.com/t5/net/warning-about-mismatch-of-amd64-vs-msil/td-p/6058618
https://www.hanselman.com/blog/back-to-basics-32bit-and-64bit-confusion-around-x86-and-x64-and-the-net-framework-and-clr

```
That 64-bit process is also having its code JIT compiled to use not the x86 instruction set we're used to, but the AMD64 instruction set. This is important to note: It doesn't matter if you have an AMD or an Intel processor, if you're 64-bit you are using the AMD64 instruction set. The short story is - Intel lost. For us, it doesn't really matter.
```

**Comment by QilongTang** [comment]
Thank you @mjkkirschner Then the `processorArchitecture` thing is not an issue for now. The only thing left is the a few regressions there.. I am not sure why there would be regressions coming from these changes yet

**Comment by mjkkirschner** [comment]
@QilongTang here is a diff between 2.9 and this PR - please see these differences:

https://github.com/DynamoDS/Dynamo/compare/RC2.9.0_master..RevertPackageReferenceChanges#diff-5f6661fa862b773649466e7562e8b239664a2fa2a654ea9882870a2a78ece76fL153

https://github.com/DynamoDS/Dynamo/compare/RC2.9.0_master..RevertPackageReferenceChanges#diff-86991af46eaf6582b37b3918fca009433e5bb090714661259eb4ce7e7c5bba9dL52

https://github.com/DynamoDS/Dynamo/compare/RC2.9.0_master..RevertPackageReferenceChanges#diff-0fca5ee353e866171cee2dac15146b530b6ceb2674107a4a652b541f731e161dL76

https://github.com/DynamoDS/Dynamo/compare/RC2.9.0_master..RevertPackageReferenceChanges#diff-7fd20771f8ddfee0ecb9526e0e0bebd1e3587e5bda89a9dc8ef5a7b869760507L43

https://github.com/DynamoDS/Dynamo/compare/RC2.9.0_master..RevertPackageReferenceChanges#diff-d59c07d24eb8dad17f4dddafe34d87a308cd57923d2e9c608b725923477410ecR69

you can try searching this diff for `private` to find other changes - might be useful.

**Comment by QilongTang** [comment]
@mjkkirschner Thanks I will look at them. I found the regressions around missing IronPython std folder.

**Comment by QilongTang** [comment]
The latest commit should fix regressions because I missed a copy step of IronPython std

**Review by mmisol — COMMENTED** [review]
Thanks @QilongTang . From my end it looks good but I'll leave it for Mike and Alfredo to take a look and comment.

**Comment by QilongTang** [comment]
@mjkkirschner The only regression left is `RemovesScriptTagsFromLoadedHtml` in DynamoCoreWpfTests\ViewExtensions\DocumentationBrowserViewExtensionTests.cs. I don't think this PR touched DocumentationBrowser other than removing the unused reference.. I can't really figure out what's happening. When I test DocumentationBrowser manually, everything looks OK.

**Review by mjkkirschner — APPROVED** [review]

**Pull request merged**
