### PR TITLE
Added shift + click to nodes and notes to remove from current group

### PR DESCRIPTION
**Pull request by johnpierson**
### Purpose

This PR adds shift-click remove from group features to nodes and notes.

https://user-images.githubusercontent.com/15744724/150603074-e8e0af34-194c-4668-9d23-62a51d0f1886.mp4

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Drag adding nodes to groups is awesome. This adds the ability to remove nodes and notes from groups with shift+left click. 

### Reviewers

@QilongTang 

### FYIs

@Amoursol

### CODE REVIEW

**Comment by mjkkirschner** [comment]
just my two cents - 
* how does this work when the node is inside a nested group?
* automated test would be good to make sure this keeps working though I can see that being difficult.

**Comment by johnpierson** [comment]
Thanks for taking a look! Nested groups behave how I would expect/want them to. If the node or note is the last in a group it drops the whole group

https://user-images.githubusercontent.com/15744724/150603581-dce6a488-a37e-4a6d-8571-aa6cf339851c.mp4

.

**Review by QilongTang — APPROVED** [review]

**Comment by johnpierson** [comment]
😱 oh my gosh. My first real contribution to dynamo's code.

**Comment by Amoursol** [comment]
> 😱 oh my gosh. My first real contribution to dynamo's code.

The first of many hopefully dude 💪

**Pull request merged**
