### PR TITLE
change .8 to .9 in all import/export samples

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

MAGN-8751
samples need to update their hardcoded file paths to use .9 folder

### Reviewers

@kronz 

### FYIs

@jnealb

### CODE REVIEW

**Comment by jnealb** [comment]
@mjkkirschner @kronz Localization?

**Comment by mjkkirschner** [comment]
@jnealb in what context, what should be localized?

**Comment by jnealb** [comment]
@mjk The samples are localized, just due diligence that they continue to be as we move to 0.9

**Comment by kronz** [comment]
@mjkkirschner code changes LGTM, but I see that there are engine ops problems?  Please go ahead and merge and cherry-pick to 0.9.0

**Pull request merged**
