### PR TITLE
MAGN-6572 Refactor ModelSpecificRecordableCommand class

### PR DESCRIPTION
**Pull request by pbidenko**
### Purpose
This PR refactors `ModelSpecificRecordableCommand` and `NodeSpecificRecordableCommand` classes. Now we have new class - `ModelBasedRecordableCommand` which can support multiple ModelBase  internally.
Also test cases were added.

### Reviewers
@Benglin 

### FYIs
@pboyer

### CODE REVIEW

**Comment by ramramps** [comment]
@pbidenko 
Is there any scenario where you get two models with first model as empty?  
command.ModelGuids.Count() == 1 && command.ModelGuids.First() == Guid.Empty 

Also I think the check !command.ModelGuids.Any() is always false, since you get the first GUID as empty. This can be refactored to check for only Empty GUID.

**Comment by ramramps** [comment]
@pbidenko  

CreateAnnotationCommand:

string annotationText = helper.ReadString("NoteText"); 
Should be AnnotationText and not NoteText

In CreateAnnotationCommand : Rename the Parameter nodeId to annotationId

Rename IsAttributeExist to HasAttribute

**Comment by ramramps** [comment]
@pbidenko  - Command.ModelGuids.First() - this is used in every other place. Is there any situation where you get more than one ModelGuid's?  Why this has to be IEnumerable?  If you are going to take only "First", then you can't be just ModelGuid ?

**Comment by pbidenko** [comment]
Hi @ramramps,

We need `command.ModelGuids.Any()` check in case of deserrializing of corrupted file with missed Guid.
About your question why it has to be IEnumerable - it will allow us to support multiple ModelBase for one command. Now we already have `UpdateModelValueCommand` which supports work with multiple ModelBase at the same time.
In this PR I tried to make everything as it was described in this task http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6572

**Pull request merged**
