### PR TITLE
New filter popup UI.

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-8891](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8891) Allow users to select all categories or only a single category from the Library filter UI

Results:
image
image
image

### Declarations

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.

### Reviewers

@ramramps 

### FYIs

@Racel

### CODE REVIEW

**Comment by Racel** [comment]
@aosyatnik - This is great. One thing, can you add some padding above "Select All" and  make it right align with the "only" text?

**Comment by aosyatnik** [comment]
@Racel 
image

**Comment by Racel** [comment]
@aosyatnik - Much better! Thanks. This looks ready to merge. After the merge, I will review this and all the new Search UI updates.

**Comment by Racel** [comment]
Reassigning to @ramramps for review.

**Comment by ramramps** [comment]
This is OK. 
@Racel 
I would suggest to add a checkbox before selectall. That helps the user to know when to selectall. Many websites have that kind of design. 

LGTM!!

**Comment by Racel** [comment]
Thanks, @ramramps. I will review the latest build and consider your suggestion. 

Thanks, @aosyatnik. By the way, does the underline appear when you hover over "Select All"? It is should. Can you answer before we merge? This is a necessary affordance.

**Comment by aosyatnik** [comment]
@Racel , yes it does.
image

**Comment by Racel** [comment]
@aosyatnik, and does the cursor change to the pointer (hand) on hover over "Select All"?

**Comment by aosyatnik** [comment]
OOoops, forgot :)
@Racel , added this functionality just now.

**Comment by Racel** [comment]
@aosyatnik - Ok. great! 

@ramramps - I think this is ready to merge now. Please merge and reassign the task to me for testing.

**Comment by Racel** [comment]
@kronz - Can you please take a look at the "Select All" button. @ramramps and I disagree on the design. Please let us know your thoughts.

**Comment by aosyatnik** [comment]
As we discussed during daily meeting: let's merge it, but keep eye on it, in case if users won't understand functionality right.

**Pull request merged**
