### PR TITLE
UI fix for Dictionary label in node preview

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

This fixes the `Dictionary` top-level label in the node preview. The text was partially cut-off - more specifically the `D` in `Dictionary`. The reason was that the top-level label had a different margin setting than nested labels. This fix removes the special setting for top-level labels and keeps just one margin setting for both top and nested labels. 

Before:
image

After:
image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 
@Racel - this requires your UX review as the top-level labels for both `List` and `Dictionary` texts are shifted 4 units to the right and are the same as nested labels. Note that I couldn't find an alternative way of fixing this UI issue.

### CODE REVIEW

**Comment by mjkkirschner** [comment]
LGTM

**Comment by Racel** [comment]
@aparajit-pratap Where did the arrow next to the top level Dictionary go? Was it never there? If that is too difficult to add back. This is fine with me.

**Comment by Racel** [comment]
@aparajit-pratap Was just reviewing this UI with Keith and we can not reproduce the hidden letters on his machine. Please do not merge as it is working fine on his.

**Comment by alfarok** [comment]
Strange it looks okay on my machine
image

**Comment by aparajit-pratap** [comment]
Ok, thanks. I'll close this one. There's something weird that could be going on with my display. Please let me know if any of you can reproduce this at a later point of time.

**Pull request closed without merging**
