### PR TITLE
DYN-6864 undo renaming and collapsing group

### PR DESCRIPTION
**Pull request by ivaylo-matov**
### Purpose

PR to address [DYN-6864](https://jira.autodesk.com/browse/DYN-6864)
Undo group collapsing as well as renaming. Includes test.

DYN-6864_fix

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

PR to address [DYN-6864](https://jira.autodesk.com/browse/DYN-6864)
Undo group collapsing as well as renaming.
Please note that the first click on renaming is recorded to the Undo stack as selection so undo renaming requires two clicks. This is existing condition. Usure if it should be changed.
Includes test.

### Reviewers

@dnenov
@reddyashish

### FYIs

@Amoursol

### CODE REVIEW

**Review by reddyashish — APPROVED** [review]

**Comment by QilongTang** [comment]
There are 9 regressions for this PR:
[DynamoCoreWpfTests.JSONSerializationTests.SerializationNonGuidIdsTest("C:\\Jenkins\\workspace\\Dynamo\\DynamoSelfServe\\pullRequestValidation\\Dynamo\\test\\core\\NodeStates.dyn")](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/DynamoCoreWpfTests/JSONSerializationTests/SerializationNonGuidIdsTest__C___Jenkins__workspace__Dynamo__DynamoSelfServe__pullRequestValidation__Dynamo__test__core__NodeStates_dyn__/)
[DynamoCoreWpfTests.JSONSerializationTests.SerializationNonGuidIdsTest("C:\\Jenkins\\workspace\\Dynamo\\DynamoSelfServe\\pullRequestValidation\\Dynamo\\test\\core\\dsevaluation\\regress9297.dyn")](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/DynamoCoreWpfTests/JSONSerializationTests/SerializationNonGuidIdsTest__C___Jenkins__workspace__Dynamo__DynamoSelfServe__pullRequestValidation__Dynamo__test__core__dsevaluation__regress9297_dyn__/)
[DynamoCoreWpfTests.JSONSerializationTests.SerializationTest("C:\\Jenkins\\workspace\\Dynamo\\DynamoSelfServe\\pullRequestValidation\\Dynamo\\test\\core\\NodeStates.dyn")](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/DynamoCoreWpfTests/JSONSerializationTests/SerializationTest__C___Jenkins__workspace__Dynamo__DynamoSelfServe__pullRequestValidation__Dynamo__test__core__NodeStates_dyn__/)
[DynamoCoreWpfTests.JSONSerializationTests.SerializationTest("C:\\Jenkins\\workspace\\Dynamo\\DynamoSelfServe\\pullRequestValidation\\Dynamo\\test\\core\\dsevaluation\\regress9297.dyn")](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/DynamoCoreWpfTests/JSONSerializationTests/SerializationTest__C___Jenkins__workspace__Dynamo__DynamoSelfServe__pullRequestValidation__Dynamo__test__core__dsevaluation__regress9297_dyn__/)
[Dynamo.Tests.GraphLayoutTests.GraphLayoutConnectedGroups](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/Dynamo.Tests/GraphLayoutTests/GraphLayoutConnectedGroups/)
[Dynamo.Tests.GraphLayoutTests.GraphLayoutConnectedOneGroup](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/Dynamo.Tests/GraphLayoutTests/GraphLayoutConnectedOneGroup/)
[Dynamo.Tests.GraphLayoutTests.GraphLayoutCyclicGroups](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/Dynamo.Tests/GraphLayoutTests/GraphLayoutCyclicGroups/)
[Dynamo.Tests.GraphLayoutTests.GraphLayoutIsolatedOneGroup](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/Dynamo.Tests/GraphLayoutTests/GraphLayoutIsolatedOneGroup/)
[Dynamo.Tests.GraphLayoutTests.GraphLayoutUnconnectedGroups](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15964/testReport/junit/Dynamo.Tests/GraphLayoutTests/GraphLayoutUnconnectedGroups/)

**Comment by ivaylo-matov** [comment]
sorry, will try to resolve this today or over the weekend

**Comment by ivaylo-matov** [comment]
@QilongTang that should fix the regressions 🤞

**Comment by reddyashish** [comment]
Tests passed here: https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/15987/. Harmony stage has failed but that doesn't seem related to this.

**Review by reddyashish — APPROVED** [review]

**Pull request merged**
