### PR TITLE
Package manager extensions - WIP

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

This PR enables the Dynamo `package manager extension` to load other extensions from packages. If a package contains an extension manifest file, a request to load that extension and then add it to extension manager is made.

The `DynamoModel` subscribes to the `extension added` event on the `extensionManager` and will call the ready method on the extension when it is added if `DynamoModel` has gone into a ready state- (is at the end of the `DynamoModel` constructor).

This ensures that even if a package containing an extension is loaded after Dynamo starts, the extension will still have it's ready method called.

This PR does not yet have tests, nor does it touch ViewExtensions Loading, which I am thinking should be initiated from the Package Manager View. 

The other thing to note is the collapse of the StartParameters for ViewExtensions and Extensions into a single type.

here is an image of a silly test extension running that adds a warning to every node added to the graph - it was loaded via the package manager extension - and appears in the loaded packages.

screen shot 2016-11-17 at 10 26 19 pm

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@ikeough @saintentropy -  we were discussing this a while ago, appreciate your thoughts.

### FYIs
@ColinDayOrg

### CODE REVIEW

**Comment by mjkkirschner** [comment]
FYI @pboyer - since this was designed by you initially.

**Comment by sharadkjaiswal** [comment]
@mjkkirschner we are planning to use view extension to implement new PackageManager UI, please see https://github.com/DynamoDS/Dynamo/pull/7353. @jitnev please keep a watch on this PR.

**Comment by mjkkirschner** [comment]
@sharadkjaiswal thanks for the heads up, theres no task associated with this work right now, but it's something we've been talking about doing for a long time.

**Comment by mjkkirschner** [comment]
@ikeough ping if you have a chance.

**Comment by Racel** [comment]
@mjkkirschner @QilongTang  - Can we reopen this? It would be good to try and get this wrapped up in the near-term future. We are considering doing some extension work with customers that this would be useful for. Also, there was a bunch of extensions that were made recently by our team and others that could benefit from this functionality...

Also, @mjkkirschner do you have the code for your silly extension test? want to take a look at how you integrated with with the canvas...

**Comment by mjkkirschner** [comment]
This needs grooming as there was never a task for this.

the extension pictured here just calls one of the warning methods in the dynamoServices project whenever any node executes.

**Comment by Racel** [comment]
did you have to touch anything in package manager to get this to work?

**Comment by mjkkirschner** [comment]
we can discuss this week yep. I have not tried uploading or downloading one of these packages or creating one using the UI. I've only created them manually.

**Pull request closed without merging**
