### PR TITLE
Consolidate all File Path node under Import/Export Category

### PR DESCRIPTION
**Pull request by fanwgwg**
### Purpose

*[DYN-719](https://jira.autodesk.com/browse/DYN-719) Consolidate all File Path node under Import/Export Category.*

**Old Nodes:**
FilePath > ChangeExtension
FilePath > Combine
FilePath > DirectoryName
FilePath > Extension
FilePath > FileName
FilePath > HasExtension

**New Nodes:**
File.ChangePathExtension
File.CombinePath
File.DirectoryName
File.FileExtension
File.FileName
File.FileHasExtension

capture

### Declarations
Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### FYIs

@riteshchandawar @Randy-Ma @yeexinc

### CODE REVIEW

**Comment by Randy-Ma** [comment]
@fanwgwg 
Great! I am a bit curious about why there are so many changes in the resx file?

**Comment by fanwgwg** [comment]
@Randy-Ma I'm not quite sure either. After I did the renaming in the resource file and save it, some image entries got a space prepended in front.

**Comment by Randy-Ma** [comment]
One other thing is that it will be good if you can add some test cases for migration from old nodes to new nodes.

**Comment by fanwgwg** [comment]
@Randy-Ma I've just added a testcase for the migration.

**Comment by Randy-Ma** [comment]
Thanks a bunch! LGTM

**Comment by Randy-Ma** [comment]
@fanwgwg 
One thing is that the category should be "Import/Export" instead of "ImportExport". Right?

**Comment by fanwgwg** [comment]
@Randy-Ma I've just updated the code so that it will be shown as `Import/Export` on UI. 

capture

**Comment by fanwgwg** [comment]
Close this because of the duplicate #7776

**Pull request closed without merging**
