### PR TITLE
Added clearing events to DynamoService

### PR DESCRIPTION
**Pull request by k-u-s**
Exposed clearing events, it can be useful during itegretion

### CODE REVIEW

**Comment by manuKrakow** [comment]
Hi Ian @ikeough any comments or suggestion for this pull request?

**Comment by pboyer** [comment]
@k-u-s Can you please use the pull request template? It is found here: https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template

It may seem a bit overkill right now, but is the best way for us to enforce coding standards and quality.

**Comment by ikeough** [comment]
@k-u-s @manuKrakow Thanks for the PR.

The changes look fine, but I have one warning. During the current sprint we are upgrading Dynamo to support multiple open home workspaces. This means that whereas you currently "clear" the current home workspace when opening a new workspace, you will now be able to open a new workspace alongside your current workspace. The concept of "clearing" a workspace is going to go away. When it does, we will also remove the `WorkspaceClearing` event. I would recommend then, that we not implement this change, and instead focus on getting your code to work with new multiple home workspace support.

Can you give me an idea of when your next release is? The work mentioned above will be available in Dynamo 0.8.3.

**Comment by manuKrakow** [comment]
@ikeough  @pboyer @k-u-s Thanks for pinging us about the multiple workspaces support. 
Could you let us know where we could find some design documents/discussions around this topic and which branch to use if we would like to have a look at the current state. 
For our release, we have few new features but nothing critical so far. We may wait the 0.8.3. When do you plan to push live the 0.8.3?

**Comment by RodRecker** [comment]
@manuKrakow we are targeting mid-October for next stable release. We will name it 0.9.0. Revit 2014 will no longer be supported.

**Comment by manuKrakow** [comment]
@RodRecker -  thanks for this update.

**Comment by ikeough** [comment]
@k-u-s @manuKrakow Please be advised, we are running this PR on our CI right now. When the tests complete successfully it will be merged and cherry-picked to the RC0.9.0_master branch for inclusion in the 0.9.0 release. Thanks!

**Comment by ikeough** [comment]
@k-u-s @manuKrakow This PR is now part of master and RC0.9.0.

**Pull request merged**
