### PR TITLE
pm-update-ui-cherrypick

### PR DESCRIPTION
**Pull request by dnenov**
### Purpose

Merging the last changes of the package manager PR has been difficult because of continuous test failures caused by the changes. This PR cherry-picks only the UI-related changes inside this https://github.com/DynamoDS/Dynamo/pull/14655 (which was reverted here https://github.com/DynamoDS/Dynamo/pull/14689)

This PR should not trigger any test issues, as the changes are only on the UI xaml side.

image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [x] This PR modifies some build requirements and the readme is updated
- [x] This PR contains no files larger than 50 MB

### Release Notes

- only UI related cherrypick which should not trigger any test issues

### Reviewers

@reddyashish 
@QilongTang 

### FYIs

@mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@dnenov please run this branch on the self serve on master-15.

**Comment by dnenov** [comment]
> @dnenov please run this branch on the self-serve on master-15.

@mjkkirschner I have asked @reddyashish to help with this one, as my account does not let me post jobs it seems. If there is someone I can ask to let me do that, it would help lessen the impact on you guys, and speed up my work I think. Could you maybe tell me who I can approach with this request?

**Comment by reddyashish** [comment]
self-serve CI job https://master-15.jenkins.autodesk.com/view/DYN/job/DYN-DevCI_Self_Service/1328/

**Comment by dnenov** [comment]
It passed on master-15 https://master-15.jenkins.autodesk.com/view/DYN/job/DYN-DevCI_Self_Service/1328/

**Pull request merged**
