### PR TITLE
DYN-5426 Setting different font size when the height of the library is smaller

### PR DESCRIPTION
**Pull request by filipeotero**
### Purpose

Sets the font size depending on the height of the library

**Scale at 350% and resolution 3840 x 2160**
image (3)

**Scale at 150% and resolution 1920 x 1080**
image

**Scale at 100% and resolution 1920 x 1080**
image

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@QilongTang 

### FYIs

@RobertGlobant20

### CODE REVIEW

**Comment by QilongTang** [comment]
Hi @filipeotero Is it because height is a direct reflection of the screen resolution?

**Comment by mjkkirschner** [comment]
@filipeotero @QilongTang .... but what if I change the size of the dynamo window?

**Comment by QilongTang** [comment]
> @filipeotero @QilongTang .... but what if I change the size of the dynamo window?

My understanding is that the size of the library does not change, when Dynamo window size changed, user will have to scroll more or less depending on the new window size. @filipeotero What do you think?

**Comment by filipeotero** [comment]
> @filipeotero @QilongTang .... but what if I change the size of the dynamo window?
It changes the size of the font too

ezgif-2-645fe244c0

**Comment by QilongTang** [comment]
> > @filipeotero @QilongTang .... but what if I change the size of the dynamo window?
> 
> It changes the size of the font too
> 
> ezgif-2-645fe244c0 [ ezgif-2-645fe244c0 ](https://user-images.githubusercontent.com/89042471/204584176-31d863c3-8771-465e-b4dd-28809cb6bc58.gif) [ ](https://user-images.githubusercontent.com/89042471/204584176-31d863c3-8771-465e-b4dd-28809cb6bc58.gif)

Then I guess I am wrong then.. And this is not desirable..

**Comment by mjkkirschner** [comment]
@Jingyi-Wen what do you think?

**Comment by Jingyi-Wen** [comment]
> @Jingyi-Wen @hwahlstrom what do you think?

Hmm...Changing the library font size like this seems very confusing to me since the intention of making the window would most likely be wanting to see more content instead of making the font bigger

**Comment by filipeotero** [comment]
If I set the font size through the dpi resolution, the font is not affected since through CSS it gets the browser's dpi, not the system's.
The dpi only changes if I zoom in to the Library.
A solution that I was thinking of is that we can grab the screen height of the user from Dynamo (using `SystemParameters.PrimaryScreenHeight`) and calculate the font size based on that. 
Let me know what you guys think. @QilongTang @mjkkirschner

**Comment by mjkkirschner** [comment]
@filipeotero you could also pass the DPI to the javascript side from c# and then use that to do your calculations.

**Comment by filipeotero** [comment]
@QilongTang @mjkkirschner I'm calculating now the font size in the `SetLibraryFontSize` method.
Here are some examples of how it's working

**1920x1080:**
scaleCalculation
librarySizeChang

**3840x2120 at 350%**
Sem título

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
The reported failure should be sporadic

**Pull request merged**
