### PR TITLE
Focus extension when activated

### PR DESCRIPTION
**Pull request by mmisol**
### Purpose

Modifies the mechanism used to add/display extensions to make sure the
extension bar is actually visible and that the right tab is actually
displayed.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [x] This PR modifies some build requirements and the readme is updated

### Reviewers

@QilongTang @reddyashish

### CODE REVIEW

**Review by QilongTang — COMMENTED** [review]
This LGTM. @mmisol I am wondering if it would be worth for a view level unit test. We have sample view extension there maybe we could guard this API. What do you think? If checking the visibility of right panel is tricky we can probably add UI automation for this.

**Comment by mmisol** [comment]
@QilongTang Added a unit test for this. Let me know if it looks good now.

**Comment by QilongTang** [comment]
@mmisol Perfect! Thanks for doing it

**Comment by QilongTang** [comment]
The regressions on self CI does not seem related but rather ASM related. I am merging to result from BRE pipeline

**Pull request merged**
