### PR TITLE
Update icons for new PolyCurve.ByThickeningCurveNormal node

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

This PR sets the icon for the old `PolyCurve.ByThickeningCurve` node on the new one as the old one is deprecated.

image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
Test failure: ViewExtensionLibraryTests.DynamoLibraryItemsTests.VerifyIconsForLibraryItems

**Comment by QilongTang** [comment]
`DynamoCoreWpfTests.JSONSerializationTests.NewCustomNodeSaveAndLoadPt2` This test look irrelevant but failing, can you verify locally?

**Comment by aparajit-pratap** [comment]
@QilongTang the test passes for me locally but it is supposed to run right after `NewCustomNodeSaveAndLoadPt1`.

**Comment by QilongTang** [comment]
OK if https://master-15.jenkins.autodesk.com/view/DYN/job/DYN-Dynamo/job/DynamoBuildscripts/job/master/772/ pass, I will merge this after.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
