### PR TITLE
MAGN-8308 Change default camera angle/zoom so more geometry is visible on startup

### PR DESCRIPTION
**Pull request by ikeough**
### Purpose

This PR addresses [MAGN-8303](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8308). The default camera position is moved to achieve the following:
* When a geometry-creating node is placed in a clean workspace, the node should not visually overlap the geometry which it creates.
* The camera should be far enough from the origin that more of the scene can be viewed.
* The camera should be positioned in a way that makes the x,y, and z axes visible.

Two nodes placed in a clean workspace. Geometry is visible:
image

Cubes at (0,0,0) and (50,50,50) are both visible:
image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

_NOTE: This is a small change to the default camera position.

### Reviewers

@ramramps 

### FYIs

@Racel

### CODE REVIEW

**Comment by Racel** [comment]
Looks good, @ikeough. Just being super picky now...can you make sure the back edge of the grid is completely horizontal? It looks just a tiny bit off to me. See attached image with horizontal lines.
screen shot 2015-09-02 at 4 16 17 pm

**Comment by ikeough** [comment]
@Racel Yes, but only if we want to align the camera parallel to the Y axis, and perfectly level, which would mean we were no longer looking at the origin. There is a -2 unit offset in X, and we are looking back towards the origin which causes the grid to be ever-so-slightly "turned" with regards to the viewer. This causes the far edge of the grid to veer slightly away from the horizon line because you no longer have two point perspective.

**Comment by Racel** [comment]
@ikeough- I think we should try to make the effect more dramatic then. The slight offset makes it look like the camera position isn't entirely intentional. What do you think?

**Comment by RodRecker** [comment]
I agree with @Racel

**Comment by jnealb** [comment]
Nice catch @Racel

**Comment by ikeough** [comment]
@Racel As mentioned this morning, make a dyn file that has the camera exactly where you think it should be, and I'll use those camera values as the default.

**Comment by Racel** [comment]
@ikeough-Added the .dyn to the YT: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8308

**Pull request merged**
