### PR TITLE
Fix blackslash issue in code block for 1.2.3

### PR DESCRIPTION
**Pull request by fanwgwg**
### Purpose

Fix the issue related to #7425 #2396 and [DYN-424](https://jira.autodesk.com/browse/DYN-424), as shown in the image below
Cherry pick changes from PR #7255 
capture

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### FYIs

@Benglin @riteshchandawar

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
@fanwgwg if this is cherry-picked from #7255 why does this have only 4 files changed while #7255 has 11?

**Comment by fanwgwg** [comment]
@aparajit-pratap just updated the remaining files!

**Comment by aparajit-pratap** [comment]
@fanwgwg please test your changes locally.

**Comment by aparajit-pratap** [comment]
@fanwgwg what is the update on this? Are you still seeing the crashes on RC1.2.3?

**Comment by fanwgwg** [comment]
Today I fixed sth, and the crash no longer happened on my desktop, however, I'll try it on my laptop tmr, just to confirm that the crash is really fixed.

**Comment by aparajit-pratap** [comment]
@fanwgwg please let me know once you've verified that all tests barring the ones under `Failure`category, in `ProtoTest` pass successfully. Once that's done, I'll merge this. Thanks!

**Comment by fanwgwg** [comment]
@aparajit-pratap All the tests excluding those under `failure` passed! Thanks for help!

**Comment by aparajit-pratap** [comment]
Thanks @fanwgwg, merging ...

**Pull request merged**
