### PR TITLE
MAGN-7568 Cannot open dyn file from German user

### PR DESCRIPTION
**Pull request by ramramps**
### Purpose
For any Groups around Dummy Nodes, Dynamo Crashes silently. If the group is created on Dynamo, then this is not an issue. But if the same group is created around a different compiler, say Revit, then opening the same file in Dynamo , all the Revit nodes (dummy nodes in Dynamo) will get a new GUID. Ideally, the GUID's have to be preserved (like how the positions are preserved today).

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
       GUID's are preserved for Dummy nodes.
- [ ] The level of testing this PR includes is appropriate

### Reviewers
@pboyer

### CODE REVIEW

**Comment by pboyer** [comment]
Would be good to have a regression test here.  If it's extra painful, this LGTM.

**Comment by ramramps** [comment]
@pboyer - I will have one regression test here.

**Comment by pboyer** [comment]
Thanks ram!

**Comment by ramramps** [comment]
@pboyer - Added a Regression test.

**Comment by pboyer** [comment]
:+1:

**Pull request merged**
