### PR TITLE
Changed gizmo widget sizes and added colors to plane widgets

### PR DESCRIPTION
**Pull request by aparajit-pratap**
@kronz @Racel  I have changed the widget to look like this:
image

Let me know what you think.

### CODE REVIEW

**Comment by Racel** [comment]
@aparajit-pratap - can you show the before and after? The gizmo's axis arrows look to be the same size and appear to be hiding the selected point.

**Comment by aparajit-pratap** [comment]
The issue is that if I make the axes any thinner, the arrow heads become thinner too and hard to spot. I'll try leaving a gap between the base point and each of the axes like in the case of the Revit gizmo:
image

**Comment by aparajit-pratap** [comment]
@Racel does this look better?
image

**Comment by Racel** [comment]
@aparajit-pratap - This looks much better. Thank you. I still think that we should put some more thought into the gizmos for direct manipulation, but I think this is a good solution for now. FYI - @kronz

**Pull request merged**
