### PR TITLE
Add more information to the workspace dependency view extension.

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

This PR is to add more information to the workspace dependency view extension. 

Workspacereferencesupdated

For some reason, the header bar color is showing a difference during recording but verified that hasn't been changed. So ignore that.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Add more information to workspace dependency view extension.

### Reviewers

@QilongTang @zeusongit @Amoursol

### CODE REVIEW

**Comment by reddyashish** [comment]
@Amoursol Let me know if think of any changes to the tooltip text.

**Comment by Amoursol** [comment]
@reddyashish text looks great! Can we change the style of the pop-up to match all the new styling that @OliverEGreen has submitted? You can refer to https://github.com/DynamoDS/Dynamo/pull/12329

**Comment by reddyashish** [comment]
Updated the tooltip styling to align with https://github.com/DynamoDS/Dynamo/pull/12329

**Comment by QilongTang** [comment]
> Updated the tooltip styling to align with #12329

@reddyashish Is this PR depending on that then?

**Comment by reddyashish** [comment]
No, that styling is already present in DynamoModern.xaml. Just making it uniform.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
