### PR TITLE
Upgrade to 1.1

### PR DESCRIPTION
**Pull request by sh4nnongoh**
### Purpose

To upgrade master branch to 1.1.

### Reviewers

@Benglin 

### FYIs

@sharadkjaiswal

### CODE REVIEW

**Comment by sharadkjaiswal** [comment]
We need similar changes for DynamoRevit and DynamoPro

**Comment by sharadkjaiswal** [comment]
Oops the version should be 1.0.1

**Comment by sh4nnongoh** [comment]
@riteshchandawar

**Comment by riteshchandawar** [comment]
@sharadkjaiswal I think the version should be 1.1.0.xxx and not 1.0.1.xxx

Why do you think we should have 1.0.1?

- Ritesh

**Pull request merged**
