### PR TITLE
obsolete nodehelp control

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

When markdown docs for nodes were added to the docs browser - the old `NodeHelpPrompt` control was no longer displayed. It's not used anywhere in Dynamo today and likely will not be.

~~This PR just obsoletes it, so we get rid of it later at a major release.~~

This PR removes the control, but leaves the test as it doesn't really have anything to do with the control - it tests a function on NodeModel and still passes.

- [x] update APIChanges docs. https://github.com/DynamoDS/Dynamo/wiki/API-Changes-in-Dynamo-2.12

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@Astul-Betizagasti noted that currently they are obsoleting the old controls, so I think it's fine to do the same here for now until we discuss API surface rules.

**Comment by RobertGlobant20** [comment]
@mjkkirschner, related about what you were saying about WPF Controls (not sure if you are just talking about Properties in the ViewModel or controls in the XAML file), some days ago I created a new pull request for enabling the Geometry Scaling and Render Precision features in the Preferences panel, so I deleted the old code  related to the Geometry Scaling functionality (xaml, code behind, events, commands, methods .....), is that ok? or should I marked as Obsolete?
This is the pull request:
https://github.com/DynamoDS/Dynamo/pull/11657

Thanks
cc: @Astul-Betizagasti

**Comment by mjkkirschner** [comment]
@RobertGlobant20 - I'm not sure - I think the safest thing to do for now is to obsolete anything public, add a TODO and we should discuss with @QilongTang how to approach it.

 If we are going to start treating public methods and classes in `DynamoCoreWPF` as excluded from our API we should message this out, and at the minimum it must be documented it in the github readme or dev docs. 
AFAIK we do treat some extensions like this already - but it's not consistent or documented well.


for this PR -  that was what I was going to do - 
1. obsolete the unused controls for now.
2. file a task to remove them at 3.x time in any case.
3. discuss with teams if we want to create a new policy and how we should message it.

**Comment by QilongTang** [comment]
Hey @mjkkirschner What we used to do was that:

Currently, we are treating DynamoView out of API scope, which means we can move/delete XML wpf controls as we want. For any public properties exposed under `DynamoViewModel`, we were only obsoleting them.

If you have any preference, feel free to update here or on slack conversation: https://autodesk.slack.com/archives/C01C2AGPSG2/p1620055650102300

**Comment by mjkkirschner** [comment]
@QilongTang okay - will proceed as Morpheus team is doing, filed a task for the messaging.

**Comment by josh2kand8** [comment]
maybe if merged iwt wil work

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
