### PR TITLE
Update bin-diff pipeline

### PR DESCRIPTION
**Pull request by avidit**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

- change solution from Dynamo.All.Net6.sln to Dynamo.All.sln for master
- change target from NET60_Windows back to AnyCPU for master

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]
Round of applause! 👍🏻

**Review by zeusongit — APPROVED** [review]

**Comment by QilongTang** [comment]
> ⚠️ **[run-bin-diff]** - Files Added/Deleted::72 new file(s) have been added and 154 file(s) have been deleted! ⚠️ **[run-bin-diff-net60-windows]** - Files Added/Deleted::11 new file(s) have been added and 29 file(s) have been deleted!

@avidit @zeusongit It looks like the bot comment is still not comparing the right build though??

**Comment by zeusongit** [comment]
I think more changes are required: https://github.com/DynamoDS/Dynamo/pull/14293/files#diff-263aa4623d6c59ca2927bbcd35ce9ae90ee58536cbfa3aa8598142a71a0634ccR169

The build has changed so many times that I have lost track, will take a look tomorrow.

**Comment by QilongTang** [comment]
@zeusongit Or if it is not worth it to make bin diff on PRs for RC2.19 jobs, I would say as long as it works on master it is fine. The remaining PRs on RC2.19 should not touch files anymore.

FYI: @mjkkirschner

**Pull request merged**
