### PR TITLE
DYN-4617 : use biginteger from pythonnet directly

### PR DESCRIPTION
**Pull request by BogdanZavu**
### Purpose
No need to have our own decoder and encoder anymore for the BigInteger since pythonnet 3.1.0 has added support for this.
Operations with BigInteger works as before in a python script in Dynamo.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### CODE REVIEW

**Review by twastvedt — APPROVED** [review]
Makes sense to me. Should there be a test on Dynamo side, or are the tests we have already in PythonNet enough?

**Comment by pinzart90** [comment]
Are you planning to use the https://github.com/DynamoDS/Dynamo/tree/pythonnet_3.1.0 branch to implement all pythonnet3 changes ? Then take out the cpython project into a separate dynamo package ?

**Comment by pinzart90** [comment]
Just to give another heads up, some of the changes that I made to https://github.com/DynamoDS/Dynamo/tree/pythonnet_3.1.0 have not been properly validated/tested.

**Comment by BogdanZavu** [comment]
> Makes sense to me. Should there be a test on Dynamo side, or are the tests we have already in PythonNet enough?
I don't think so, what we have on python side should do it.

**Comment by BogdanZavu** [comment]
> Are you planning to use the https://github.com/DynamoDS/Dynamo/tree/pythonnet_3.1.0 branch to implement all pythonnet3 changes ? 

I think so yes.

> Then take out the cpython project into a separate dynamo package ?

Not sure but that sounds plausible, we have a task to decide on this.

**Comment by BogdanZavu** [comment]
> Just to give another heads up, some of the changes that I made to https://github.com/DynamoDS/Dynamo/tree/pythonnet_3.1.0 have not been properly validated/tested.

We'll figure it out if something it's not working but since you brought this up just to confirm : the changes related to pythonnet3.1 are your last 3 commits ?

**Comment by pinzart90** [comment]
> > Just to give another heads up, some of the changes that I made to https://github.com/DynamoDS/Dynamo/tree/pythonnet_3.1.0 have not been properly validated/tested.
> 
> We'll figure it out if something is not working but since you brought this up just to confirm : the changes related to pythonnet3.1 are your last 3 commits ?

Correct

**Pull request merged**
