### PR TITLE
DYN-6009-Extended-Node-Help-Missing 3rd

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

I've added the documentation (md, dyn, jpg files) for the next list of 15 nodes (using Monocle package):

- Unit.AreUnitsConvertible
- Math.DegreesToRadians
- Convert By Units
- BoundingBox.ByMinimumVolume
- CoordinateSystem.Rotate (coordinateSystem, origin, axis, degrees)
- CoordinateSystem.Translate (coordinateSystem, xTranslation, yTranslation, zTranslation)
- CoordinateSystem.Scale (coordinateSystem, plane, xamount, yamount, zamount)
- CoordinateSystem.Scale (coordinateSystem, xamount, yamount, zamount)
- CoordinateSystem.Scale (coordinateSystem, amount)
- CoordinateSystem.Translate (coordinateSystem, direction)
- CoordinateSystem.Scale (coordinateSystem, basePoint, from, to)
- CoordinateSystem.Translate (coordinateSystem, direction, distance)
- Vector.Scale (vector, scale_factor)
- Vector.Rotate (axis, degrees)
- Vector.Rotate (vector, plane, degrees)

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

@QilongTang 

### FYIs

@avidit

### CODE REVIEW

**Comment by QilongTang** [comment]
@DynamoDS/dynamo Who would know best how to fix the syntax issue on `Check file size` action?

**Comment by avidit** [comment]
I can take a look. @RobertGlobant20 can you try to rebase your branch against master?

**Comment by avidit** [comment]
@QilongTang @RobertGlobant20 I have updated check_file_size workflow to accommodate file names with special characters https://github.com/DynamoDS/Dynamo/pull/14551

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Dynamo SelfServe job passed before I merge `master` into this branch, merging

**Pull request merged**
