### PR TITLE
DYN-4654 Revert IO node development for 3.1

### PR DESCRIPTION
**Pull request by twastvedt**
### Purpose

We're only part-way on IO node development. We'll keep the development in a feature branch until after 3.1. (See https://github.com/DynamoDS/Dynamo/tree/DYN-4654-io-node).

This reverts the two PRs so far merged for the IO node:
#14987 
#15037 

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@twastvedt have you evaluated a feature flag or DEBUG condition instead so more eyes, and daily build users get on this earlier?

**Comment by twastvedt** [comment]
We'd be interested in a feature flag for the node itself. We were concerned though about some of the apis we're adding that may need to be public but that aren't fully baked yet.

**Review by saintentropy — APPROVED** [review]

**Comment by saintentropy** [comment]
Still need to validate the testing... Not sure why it is still pending

**Comment by saintentropy** [comment]
FYI @QilongTang

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Looks like this PR is opened when master-5 checks were not reporting regressions. I found the following regressions in this PR:
[Dynamo.Tests.Configuration.PreferenceSettingsTests.TestImportCopySettings](https://master-15.jenkins.autodesk.com/job/DYN-Dynamo/job/DynamoBuildscripts/job/master/2654/testReport/Dynamo.Tests.Configuration/PreferenceSettingsTests/TestImportCopySettings/)
[NodeDocumentationMarkdownGeneratorTests.MarkdownGeneratorCommandTests.ProducesCorrectOutputFromCoreDirectory_preloadedbinaries](https://master-15.jenkins.autodesk.com/job/DYN-Dynamo/job/DynamoBuildscripts/job/master/2654/testReport/NodeDocumentationMarkdownGeneratorTests/MarkdownGeneratorCommandTests/ProducesCorrectOutputFromCoreDirectory_preloadedbinaries/)

**Pull request merged**
