### PR TITLE
Fix nested dictionary preview

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

This fixes QNTM-3947. Nested dictionaries will not have any information about preferred dictionary ordering. Therefore when the same ordering from the outer dictionary is passed into the nested dictionary preview, the ordering of the outer dictionary does not apply to the nested one resulting in an `key not found exception`. In this case, we therefore pass null to the nested dictionary all the time. And we add a null check for `preferredDictinoaryordering` argument so that we check it only if a non-null argument for it is passed.

Related Github issue: https://github.com/DynamoDS/Dynamo/issues/8665
image
image
### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@mjkkirschner 

### FYIs
@jnealb

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@aparajit-pratap this seems good, is it worth it to add a test? I know the view tests are sometimes time consuming.

@QilongTang @ramramps I believe this will break binary compatibility as a public method has changed its signature. I think we should definitely re-release the2.0 nugets if this is merged.

IMO: Nested dictionaries seem like a general enough problem that this should be merged.

**Comment by jnealb** [comment]
no nested dictionaries would be no good

**Comment by aparajit-pratap** [comment]
@mjkkirschner I can revert the public method signatures if needed as I've only changed the order of the argument (stuck it at the end) in order to make it a default argument.

**Comment by ramramps** [comment]
@QilongTang 
I am not sure whether 2.0 nugets actuals are released....if it is 2.0.0-beta, then we are good, because the package will be released as 2.0.0 again.

**Comment by QilongTang** [comment]
@ramramps This is unfortunate. Dynamo Nugets 2.0.0 are all out this morning since we need an official RC to test. Two options here in my mind:
1. We do not include this in 2.0 ( I am not sure if we have decided to include it yet @Racel ?)
2. We release nuget 2.0.0.xxxx to accomadate this change which is pretty easy and just update https://github.com/DynamoDS/Dynamo/pull/8723/ We have never done that but according to sementic versioning, it is valid because what is out there currently is treated as 2.0.0.0000

**Comment by ramramps** [comment]
@QilongTang Thanks. 2.0.0.xxxx after @aparajit-pratap changed the method signature?

**Comment by mjkkirschner** [comment]
@aparajit-pratap LGTM 👍 nice tests.

**Comment by mjkkirschner** [comment]
@Racel should this get cherry picked to RC 2.0?
what do you guys think?

**Comment by jnealb** [comment]
Plan A: merge to master, and we can test over the weekend and then merge to RC. Just in case QA pushes back.

**Comment by QilongTang** [comment]
@aparajit-pratap @mjkkirschner @jnealb I am merging in now in case we need to cherry-pick this in the last minute.

**Comment by jnealb** [comment]
will test it when the build is posted

**Comment by Racel** [comment]
@QilongTang @mjkkirschner  If it has not been done yet, please cherry pick. This should be in 2.0 release. Regarding the nuget packages, can't you just "delete" the one we released with out this fix?

**Comment by QilongTang** [comment]
@Racel There is not **delete** function there so it is not doable

**Comment by Racel** [comment]
@QilongTang - "Hide" then?

**Comment by QilongTang** [comment]
@Racel Even we hide it, we won't be able to upload 2.0.0 version again. It has to be a different version like 2.0.0.xxxx

**Comment by Racel** [comment]
ah, ok. i think that is ok....

**Pull request merged**
