### PR TITLE
Code Refactor to catch more open file failure cases

### PR DESCRIPTION
**Pull request by QilongTang**
### Purpose

MAGN-9552
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9552

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.

File moved error message:
file moved

File corrupted error message:
corrupted file

Drive ejected or directory moved error message:
drive ejected

Network failure message will be displayed as well depending on the specific IO exception message.

### Reviewers

@ramramps 

### FYIs

@jnealb @mjkkirschner @sm6srw

### CODE REVIEW

**Comment by QilongTang** [comment]
There will be some merge conficts due to the reason I deleted a resource string submitted ealier.

**Comment by ramramps** [comment]
Great. Can you think of a simple test?

**Comment by ramramps** [comment]
Where is the Unit test for this? Please see the comment here. You should address the comment before merging stuff. Appveyor did not build. Did you check that? You should merge only when there is a green light.

**Comment by QilongTang** [comment]
This is not merged yet, resolving conflicts and adding a unit test.

**Comment by QilongTang** [comment]
One failed unit test fixed, self CI passed, I will merge this code in.

**Pull request closed without merging**
