### PR TITLE
graphic helpers - 2.19 hotfix 

### PR DESCRIPTION
**Pull request by dnenov**
### Purpose

This is a hot-fix for an issue preventing Graphic Elements Scale to take effect in Dynamo. The `UseHostScaleUnits` preference that controls if Revit scale units should be used was acting even if Dynamo was used without a host. 
~~**Show Grid** renamed to **Show Helpers**~~

#### Graphic Scale Units under Dynamo and Revit

dyanmo units

revit metric

#### Serializing settings
image

#### Separate settings `.xaml` files for Dynamo and Revit
image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [x] This PR modifies some build requirements and the readme is updated
- [x] This PR contains no files larger than 50 MB 

### Release Notes

- graphic scale units not taking effect in Dynamo - added check to disable host settings interfering with Dynamo settings
~~- renamed resource for Show Grid to Show Helpers~~

### Reviewers

@QilongTang 
@reddyashish 

### FYIs

@Amoursol

### CODE REVIEW

**Comment by QilongTang** [comment]
hi @dnenov Would you split the menu item rename changes to master branch only?

**Comment by QilongTang** [comment]
Also Regressions:
[DynamoCoreWpfTests.CoreUserInterfaceTests.WorkspaceContextMenu_TestIfOpenOnRightClick](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/11180/testReport/junit/DynamoCoreWpfTests/CoreUserInterfaceTests/WorkspaceContextMenu_TestIfOpenOnRightClick/)
[WpfVisualizationTests.HelixWatch3DViewModelTests.HelixWatch3DViewModel_OpenFileWithGridDisabled_EnableGrid_GridDraws](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/11180/testReport/junit/WpfVisualizationTests/HelixWatch3DViewModelTests/HelixWatch3DViewModel_OpenFileWithGridDisabled_EnableGrid_GridDraws/)
[WpfVisualizationTests.HelixWatch3DViewModelTests.HelixWatch3DViewModel_OpenFileWithGridDisabled_GridDoesNotDraw](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/11180/testReport/junit/WpfVisualizationTests/HelixWatch3DViewModelTests/HelixWatch3DViewModel_OpenFileWithGridDisabled_GridDoesNotDraw/)

**Review by reddyashish — APPROVED** [review]

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@dnenov Still two regressions [WpfVisualizationTests.HelixWatch3DViewModelTests.HelixWatch3DViewModel_OpenFileWithGridDisabled_EnableGrid_GridDraws](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/11188/testReport/junit/WpfVisualizationTests/HelixWatch3DViewModelTests/HelixWatch3DViewModel_OpenFileWithGridDisabled_EnableGrid_GridDraws/)
[WpfVisualizationTests.HelixWatch3DViewModelTests.HelixWatch3DViewModel_OpenFileWithGridDisabled_GridDoesNotDraw](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/11188/testReport/junit/WpfVisualizationTests/HelixWatch3DViewModelTests/HelixWatch3DViewModel_OpenFileWithGridDisabled_GridDoesNotDraw/)

**Comment by mjkkirschner** [comment]
@QilongTang @reddyashish  parallel tests passed, are we good to merge this?
@dnenov will you cherry pick to master?

**Pull request merged**
