### PR TITLE
Remove the support for function definition in imperative language block

### PR DESCRIPTION
**Pull request by ke-yu**
### Purpose

Remove the support for function definition in imperative language block. That is, the following syntax is no longer supported:
```
[Imperative]
{
    def foo()  // cannot define function inside imperative language block.
    {
        ...
    }
}
```

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.

### FYIs

@Benglin @sharadkjaiswal @lukechurch

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@ke-yu are there consequences from this change that would limit the ability to use functions inside imperative blocks or just the specific syntax?

**Comment by ke-yu** [comment]
@mjkkirschner no, user is not able to define function inside imperative block now. Do you know if any user is doing that?

**Comment by kronz** [comment]
Wait, why is this being removed?

**Comment by ke-yu** [comment]
@kronz @mjkkirschner: 

User is still able to define function, but not in imperative language block.

**Comment by kronz** [comment]
@ke-yu OK, thanks for the explanation.  That's all I needed

**Pull request merged**
