### PR TITLE
Add Microsoft.Codeanalysis.PublicApiAnalyzer and Github action

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

Add `Microsoft.CodeAnalysis.PublicAPIAnalyzer` to DynamoCore and DynamoCoreWpf and Github action.

References:
https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md
https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md

Findings:
- The `PublicAPIAnalyzer` package works per project and needs to be installed in each of the projects that are intended to have public APIs. If an API boundary for Dynamo can be defined at project-level granularity, then it's easy to use the API analyzer for purely those projects that are meant to be part of the public API.
- The analyzer uses 2 text files - `PublicAPI.Shipped.txt`, which contains the list of APIs that are already delivered to users, and `PublicAPI.Unshipped.txt`, which contains the list that is undeclared and that can change such as obsoleted APIs 
- The analyzer can be used to automatically generate the text files for public functions in projects where the package is installed. **They are first added to the unshipped file and it's up to developers to move them to the shipped file manually.** The analyzer auto-generates these files when the codefix for RS0016 rule is applied in the VS editor.

Notes:
- I did not find a way to exclude certain namespaces or classes from the API analysis. The [documentation](https://github.com/dotnet/roslyn-analyzers/blob/main/docs/Analyzer%20Configuration.md#analyzer-configuration) does mention that we can use `.editorconfig` files for this and use the appropriate options. I tried a few but I was unable to exclude any namespaces leading me to think that there are no options that apply to the RS0016 rule, which is one of the API rules applied by the analyzer.
- The steps needed to maintain the shipped and unshipped API lists are still largely manual, e.g. moving the declared APIs from the unshipped list to the shipped list while maintaining obsolete APIs in the unshipped list but hopefully, it's a one-time exercise for all the projects, we wish to analyze for public APIs, after which it becomes an incremental process for only those APIs that are added/removed/modified. This is a script that can be used if we wish to automate some of this: https://github.com/dotnet/winforms/pull/4837/files
 
TODO:
- If we decide to move ahead with this analyzer and GH action, we would need to add the package to all other projects individually, as well as generate the API list files, and add them to the repo.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by avidit** [comment]
LGTM
Can we update https://github.com/DynamoDS/Dynamo/blob/master/.github/workflows/build_dynamo_all.yml to add API analysis instead of adding new workflow?

**Comment by QilongTang** [comment]
> LGTM Can we update https://github.com/DynamoDS/Dynamo/blob/master/.github/workflows/build_dynamo_all.yml to add API analysis instead of adding new workflow?

We can probably discuss the pros and cons. I think adding it to the build step will make the build step slower? And the results from this job do not necessarily block PR merge?

**Review by avidit — APPROVED** [review]

**Comment by QilongTang** [comment]
I guess more changes needed?
image

**Review by pinzart90 — APPROVED** [review]

**Comment by mjkkirschner** [comment]
@aparajit-pratap some questions

1. When an API breaks - does the build break? Or is it just a warning?
2. If the build does break, how do we resolve it if we need to override in some specific case.
3. can you say a bit more about shipped and unshipped lists, do only shipped API breaks lead to compile time errors and warnings?

I personally feel it's a nice approach and gives us sort of a reset - and the state of what is supported is documented for every single project so we can point at it in our release notes.

**Comment by aparajit-pratap** [comment]
> @aparajit-pratap some questions
> 
> 1. When an API breaks - does the build break? Or is it just a warning?
> 2. If the build does break, how do we resolve it if we need to override in some specific case.
> 3. can you say a bit more about shipped and unshipped lists, do only shipped API breaks lead to compile time errors and warnings?


@mjkkirschner 
1. I'm not 100% sure - My guess is there will be build warnings, and depending on the warning level configured in project settings, there could be compilation errors. It remains to be seen what the warning comments look like in PRs and while building projects. You can see all the rules [here](https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md)
2. Good question, I'm not sure about this. We'll need to keep a lookout for breaking builds if any due to APIs.
3. I believe both lists flag warnings. Again I haven't found more info on these 2 files. From what I saw, they are useful for development - tracking which APIs have already been exposed publicly (shipped) vs which ones are yet to be made public or have to be removed or obsolete (unshipped).

> 
> I personally feel it's a nice approach and gives us sort of a reset - and the state of what is supported is documented for every single project so we can point at it in our release notes.

👍

**Pull request merged**
