### PR TITLE
QNTM-2889 Remove PreviewBubbleVisible_OpenFile Test

### PR DESCRIPTION
**Pull request by alfarok**
### Purpose

[QNTM-2889](https://jira.autodesk.com/browse/QNTM-2889)

The purpose of this PR is to remove the PreviewBubbleVisible_OpenFile test as we no longer serialize a boolean value determining if a preview bubble is pinned or not.   A Json test failure was occurring because preview bubbles do not remained pinned when a graph is saved/opened.  The failing test was `DynamoCoreWpfTests.PreviewBubbleTests.PreviewBubbleVisible_OpenFile`

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [X] Snapshot of UI changes, if any.
- [X] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by ramramps** [comment]
No change in tests?

**Comment by mjkkirschner** [comment]
@alfarok we should not enable this. - We decided to not save this property. CoGs Schema does not have this property.

**Comment by QilongTang** [comment]
@alfarok @mjkkirschner @ramramps As discussed, we will simply remove the test since it is no longer same behavior as RC1.3

**Comment by alfarok** [comment]
Oops sorry, my mistake :)

**Comment by gregmarr** [comment]
If you really want it, it could be in the node view block.

**Comment by alfarok** [comment]
@QilongTang removed the test, let me know if we can merge

**Comment by QilongTang** [comment]
LGTM

**Pull request merged**
