### PR TITLE
Fix for adding duplicate ZT search entries for packages already loaded

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

Fix for this:
image

Regression caused by #9736 

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@aparajit-pratap thank you so much for checking into this right away!
Can we add a test somehow or is this very difficult to test?

**Comment by mjkkirschner** [comment]
@aparajit-pratap we'll also need to cherry pick this to 2.3 branch (guess I jumped the gun, sorry.)

**Comment by aparajit-pratap** [comment]
Sure, I'll add a test and then cherry-pick it.

**Comment by mjkkirschner** [comment]
👍

**Comment by mjkkirschner** [comment]
LGTM!

**Pull request merged**
