### PR TITLE
fix node autocomplete crash

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

fixes https://autodesk.slack.com/archives/C1866AFQB/p1627336769051500

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### CODE REVIEW

**Comment by QilongTang** [comment]
@aparajit-pratap Thanks, can you describe if there is any behavior change?

**Review by QilongTang — APPROVED** [review]

**Review by avidit — APPROVED** [review]

**Comment by aparajit-pratap** [comment]
@QilongTang autocomplete, if it cannot make sense of the type, it now shows the default results:
image

**Comment by aparajit-pratap** [comment]
I can try adding a unit test (WIP)

**Comment by aparajit-pratap** [comment]
@QilongTang actually, I'll put in the test later. I'm in the middle of something else right now. Merging this for the time being.

**Review by reddyashish — APPROVED** [review]
LGTM

**Pull request merged**
