### PR TITLE
[DYN-2767] Use Python logo in the PythonUpdate dialog.

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

We will be using the Python logo in the Python update dialog instead of using an image that is a bit confusing for users. 

Regarding the text size in the dialog, it is consistent with the design in other dialogs that are currently being used. If it is going to be a small change to fix it, do we still want to file a different task for it?

Screen Shot 2020-06-12 at 11 03 56 AM

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Comment by QilongTang** [comment]
@reddyashish Looks much better! Looks like we are not using a dialog template here, were you able to adjust the font for the dialog?

**Comment by reddyashish** [comment]
We have using an API to create the dialog and the font is not set through that. I am looking into it.

**Comment by reddyashish** [comment]
For both the IronPython dialog and the general task dialog, the summaryText font-size is set to 13 and the descriptionText font-size is set to 16. These are the only 2 dialog templates present. https://github.com/DynamoDS/Dynamo/blob/e3d60fbe3a9aa009308fa2233bdd0091eb30caf1/src/PythonMigrationViewExtension/IronPythonInfoDialog.xaml#L45
https://github.com/DynamoDS/Dynamo/blob/e3d60fbe3a9aa009308fa2233bdd0091eb30caf1/src/PythonMigrationViewExtension/IronPythonInfoDialog.xaml#L45

This is how it looks with summaryText size: 15 and descriptionText size: 12. 
Screen Shot 2020-06-15 at 10 00 05 AM
 
Let me know what you guys think.

**Comment by mjkkirschner** [comment]
LGTM

**Comment by reddyashish** [comment]
This is how the crash dialog would look after the new changes:
Screen Shot 2020-06-15 at 1 06 47 PM

**Pull request merged**
