### PR TITLE
Update LIBG 229 in 2.19.5

### PR DESCRIPTION
**Pull request by sm6srw**
### Purpose

This will cherry-pick [DYN-6043](https://jira.autodesk.com/browse/DYN-6043)

All tests passed on master-15.

This will add two new files for the geometry primitives.

I have not seen any side effects but let me know if you think that we should skip this because it can have some unforeseen consequences. 

### Declarations

Just a test for now.

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@sm6srw seems like a lot of unintended changes in this PR.

**Comment by sm6srw** [comment]
Oops, wrong base. Sorry.

**Comment by sm6srw** [comment]
> So this version of libg contains geometryprimitives as well?

Yes, one of the complications.

**Review by aparajit-pratap — APPROVED** [review]
@sm6srw did you do some manual testing on the offset issue in Dynamo with this version of libg?

**Comment by sm6srw** [comment]
> @sm6srw did you do some manual testing on the offset issue in Dynamo with this version of libg?

Yes, I did.

**Pull request merged**
