### PR TITLE
memleak fixes

### PR DESCRIPTION
**Pull request by lukechurch**
@junmendoza @ke-yu 

This needs to be run on the full test cycle and play tested a bit before merge. I haven't had the opportunity to do so.

### CODE REVIEW

**Comment by jnealb** [comment]
@lukechurch @ke-yu @junmendoza How can I help?

**Comment by junmendoza** [comment]
@jnealb Once merged, the regression test times should normalize Yesterday we did notice the test taking longer. @riteshchandawar has mentioned to me, the entire test quite should complete in approx 3.5 hrs. 

The most helpful long term solution to this is a developer having a VM at his disposal to take his changes and run the full test-suite. Running them locally, eats up processor time and resources. This has always been in discussion but keeps slipping through, It need not be an urgent task, but it will be good to kick start some discussion on it.

@riteshchandawar any thoughts?

**Comment by riteshchandawar** [comment]
@junmendoza : Yes, we need to find a solution to make our test run fast and should run parallel on different machines and then combine results in the end.

Couple of things to achieve that.
# Need to identify Smoke Tests for each area so that at-least those test should be executed before submitting the related code.
# Need to find a solution to run all test projects in parallel.
# Each developer should have his own dedicated machine to Run test. (I have mine :) )
# Need to create User Story around it,

**Comment by RodRecker** [comment]
@riteshchandawar We met with Eng Ops team today and need to start fleshing out plans here.

**Comment by junmendoza** [comment]
Btw @lukechurch Im taking this PR and testing on a VM. Will update once done. ritesh is helping out with the VM for this. Will update once done

**Pull request merged**
