### PR TITLE
Add Cancel button to "Cannot download package" dialog

### PR DESCRIPTION
**Pull request by ke-yu**
### Purpose

When installing a package which has some dependencies, Dynamo will firstly try to remove all those dependencies, and requires user to restart Dynamo (and user needs to re-install the package):

image

But there is no option to *cancel* the removal of those dependencies. This PR adds a "Cancel" button to this dialog. If user clicks "Cancel", those dependencies won't be removed. The message of this dialog is changed accordingly:

untitled

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.

### Reviewers

@riteshchandawar @Racel : do you think the message on this dialog is OK?

### CODE REVIEW

**Comment by riteshchandawar** [comment]
@ke-yu I think we need to add the message for Canceling the operation.

something like "Canceling the operation will abort the package installation and dependent packages will be intact."

@Racel feel free to reword, I am not that good. I just want to make sure, sure should understand what will happen if he chooses Cancel. 

BTW, we are introducing the Cancel button for this dialog.

- Ritesh

**Comment by Racel** [comment]
Can we change the language to the text below? I think we should also have "Uninstall" and "Cancel" as the 2 button options.

"You must first uninstall XXXXX and dependent packages to continue installing YYYYY package. Do you want to uninstall? 

After the uninstall, you must restart Dynamo and try to install YYYYY package again. "

- Replace "OK" with "Uninstall" 
- Cancel

**Comment by ke-yu** [comment]
The message has been updated. As for Uninstall button, this message box is sort of a builtin message box, there are some button options: OK, OKCANCEL, YesNoCancel and YesNo. We definitely can create a new dialog, but I think it is little too much for this task. 

untitled

**Comment by Racel** [comment]
@ke-yu - Can you please reword it again? It looks strange. Also, please use "Yes" and "No"

"<Bakery> depends on <Clockwork for Dynamo>. To install <Bakery>, Dynamo needs to remove <Clockwork for Dynamo>. Restart Dynamo to complete the uninstall, then try and download <Bakery> again.

Uninstall <Clockwork for Dynamo>?"

Yes | No

**Comment by ke-yu** [comment]
@Racel , so the message is

"Foo 1.0 depends on bar 0.1, qux 0.2, quux 0.3, xyzzy 0.4. To install Foo 1.0, Dynamo needs to remove bar 0.1, qux 0.2, quux 0.3, xyzzy 0.4. Restart Dynamo to complete the uninstall, then try and download again.

Uninstall bar 0.1, qux 0.2, quux 0.3, xyzzy 0.4?"

?

**Comment by Racel** [comment]
@ke-yu - Let's go with this:

Foo 1.0 has dependencies. To install Foo 1.0, Dynamo needs to first uninstall the following dependent packages: bar 0.1, qux 0.2, quux 0.3, xyzzy 0.4. Restart Dynamo to complete the uninstall, then try and download Foo 1.0 again.

Uninstall bar 0.1, qux 0.2, quux 0.3, xyzzy 0.4?

YES | NO

**Comment by ke-yu** [comment]
Dialog message updated:
untitled

**Comment by Racel** [comment]
This looks good, @ke-yu. One more change though. Can we change the final line to 

"Uninstall the following dependent packages: Clockwork for Dynamo 0.9.x?"

**Comment by ke-yu** [comment]
Try again:

untitled

**Comment by Racel** [comment]
Thanks @ke-yu - This looks good to me

**Pull request merged**
