### PR TITLE
[DYN-3828] Preference's Visual Settings tab expanders alignment

### PR DESCRIPTION
**Pull request by Astul-Betizagasti**
### Purpose

Align the expanders in the Visual Settings tab of the Preferences window to match the ones in other tabs.
I also noticed the expander on the General tab needed to be better aligned too and made that change.
expanders alignment

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

Aaron Tang (@QilongTang )

### CODE REVIEW

**Comment by QilongTang** [comment]
hi @Astul-Betizagasti , can you align the close button of preference dialog to the expanders controls, etc `+` `-`

**Comment by Astul-Betizagasti** [comment]
> 
> 
> hi @Astul-Betizagasti , can you align the close button of preference dialog to the expanders controls, etc `+` `-`

Hi @QilongTang, seeing that the close button is bigger than the expander's symbols, do you want it aligned by the center point or should I resize the close button to fit with the dimensions of the expander's ones?

**Comment by QilongTang** [comment]
@Astul-Betizagasti Thank you. For this one, I feel center align is good enough. @Jingyi-Wen and @Amoursol what do you think?

**Comment by Jingyi-Wen** [comment]
Agreed! Center-aligned looks good!

**Comment by Amoursol** [comment]
Also totally cool with Center-Aligned @Astul-Betizagasti !

**Comment by Astul-Betizagasti** [comment]
@QilongTang, I just updated the close button alignment:
image

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@Astul-Betizagasti can you also cherry-pick this merge commit to RC2.12.0_master branch using another PR?

**Pull request merged**
