### PR TITLE
Add Tooltip to Python Script Editor Engine Selector Dropdown

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

Added Tooltip to Python Script Editor Engine Selector Dropdown.

SS:
Screen Shot 2020-07-21 at 1 38 02 PM

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Comment by QilongTang** [comment]
LGTM. Nice to it work with the new UI 👍

**Comment by zeusongit** [comment]
Should I merge this? The Dynamo SelfServe shows as failed, but clicking on details displays the build status as unstable.

**Comment by aparajit-pratap** [comment]
FYI: @Amoursol

**Comment by mjkkirschner** [comment]
@zeusongit this should be fine to merge - @mmisol is fixing this test failure.

**Comment by mmisol** [comment]
Just merged the build fix to master, sorry about that. You can rebase/merge from latest master to get the fix here.

**Comment by Amoursol** [comment]
LGTM!

**Pull request merged**
