### PR TITLE
Update vote button

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

There is long running issue that the downvote button in Dynamo Package Manager looks too similar than the download button so that user accidentally click downvote while their real intention is download. This PR is minimal work there to replace the button unicode and adjust the dialog based on the new width of buttons. And hopefully as a result of this change, we can truly ask Dynamo users to vote for packages they would love to recommend to other users.

Please find attached screenshot for comparison:
image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
Running
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@Racel @kronz 

### FYIs

@DynamoDS/dynamo @johnpierson @Dewb @gregmarr

### CODE REVIEW

**Comment by kronz** [comment]
LGTM!

**Comment by mjkkirschner** [comment]
so!
some information to consider:
https://emojipedia.org/thumbs-up-sign/
https://emojipedia.org/upwards-black-arrow/

the thumbs up was only added to unicode standard in 2010 vs 2003 for up arrow - does it matter... probably not so much... but worth considering compatibility for at least a moment I think ;)

**Comment by QilongTang** [comment]
@mjkkirschner Thank you for the reminder, this emoji started to appear in Unicode 6.0 out in Oct, 2010. Microsoft then provide windows update after for unicode set update for regular users, I suggest we make this on daily for a while to gather feedback first before put into any release.

**Comment by mjkkirschner** [comment]
LGTM

**Comment by alfarok** [comment]
Sweet, the most downloaded packages will no longer also be the most down-voted!

**Comment by jnealb** [comment]
getting voted off the island?...

**Pull request merged**
