### PR TITLE
DYN-5145: Bump LibG version to 2.16.0.2285

### PR DESCRIPTION
**Pull request by sm6srw**
### Purpose
This pull request does:
* bump the LibG version to 2.16.0.2285
* Includes fix for DYN-5145
* update tests (both tests covered a case that has never worked, I replaced with a case that uses a polycurve as a guide)

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Loft operations now fail with a warning when one or more of the guide curves are invalid. 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by mjkkirschner — APPROVED** [review]

**Comment by mjkkirschner** [comment]
@sm6srw can you update the release notes section of the PR please.

**Comment by sm6srw** [comment]
> 

@aparajit-pratap I am not sure that I understand what you mean. I am reusing the existing dyn files.

**Comment by aparajit-pratap** [comment]
> > 
> 
> @aparajit-pratap I am not sure that I understand what you mean. I am reusing the existing dyn files.

@sm6srw sorry, I thought, you added new dyn files. Can you tell me what changes you made to these files?

**Comment by sm6srw** [comment]
> > > 
> > 
> > 
> > @aparajit-pratap I am not sure that I understand what you mean. I am reusing the existing dyn files.
> 
> @sm6srw sorry, I thought, you added new dyn files. Can you tell me what changes you made to these files?

@aparajit-pratap The third (non working) case in each graph used guides that did not intersect with both profiles so we now get a failure with the new code. The old implementation were silently ignoring this error condition and defaulted to the same outcome as if we were using no guides at all. So it looked alright but was actually failing. I replaced the third case with a case where we were using a polycurve as a guide instead.

**Review by aparajit-pratap — APPROVED** [review]

**Pull request merged**
