### PR TITLE
Update Licence Info in Aboutbox

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Update Licence Info in Aboutbox to remove an entry no longer valid

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

N/A

### Reviewers

@DynamoDS/dynamo 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
@aparajit-pratap @mjkkirschner Please confirm if we still need to list this and how they are used

**Review by aparajit-pratap — APPROVED** [review]

**Review by mjkkirschner — APPROVED** [review]
this was from CEF?

**Comment by QilongTang** [comment]
> this was from CEF?

@mjkkirschner https://autodesk.slack.com/archives/C1866AFQB/p1694787644692569. LibG I guess, what do you think?

**Comment by mjkkirschner** [comment]
> > this was from CEF?
> 
> @mjkkirschner https://autodesk.slack.com/archives/C1866AFQB/p1694787644692569. LibG I guess, what do you think?

LibG likely uses a newer version of the runtime now - I guess mentioning that one cannot hurt.

**Comment by QilongTang** [comment]
> > > this was from CEF?
> > 
> > 
> > @mjkkirschner https://autodesk.slack.com/archives/C1866AFQB/p1694787644692569. LibG I guess, what do you think?
> 
> LibG likely uses a newer version of the runtime now - I guess mentioning that one cannot hurt.

Maybe Turbo team can take this over? I am not sure what to look at. @aparajit-pratap Any idea?

**Comment by aparajit-pratap** [comment]
> > > this was from CEF?
> > 
> > 
> > @mjkkirschner https://autodesk.slack.com/archives/C1866AFQB/p1694787644692569. LibG I guess, what do you think?
> 
> LibG likely uses a newer version of the runtime now - I guess mentioning that one cannot hurt.

@mjkkirschner I don't think we're shipping these anymore, not even newer versions.

**Comment by mjkkirschner** [comment]
did we actually ship them before? I thought they are installed by the vc++ redistributable package?

**Comment by aparajit-pratap** [comment]
> did we actually ship them before? I thought they are installed by the vc++ redistributable package?

Yes, we did, a long time ago: https://github.com/DynamoDS/Dynamo/tree/RC1.3.0_master/extern/LibG_221

And yes, they do seem to be installed by the vc++ redistributable package, and since we don't ship this package either, I'm actually not quite sure now how users without Visual Studio or any other Autodesk products manage to run Dynamo.

**Comment by mjkkirschner** [comment]
we have vc++ redis package listed as a requirement for cef in our utilizing dynamo builds wiki.

**Comment by QilongTang** [comment]
> we have vc++ redis package listed as a requirement for cef in our utilizing dynamo builds wiki.

Sounds like we should update that?

**Comment by aparajit-pratap** [comment]
I have updated the link in the wiki to point to the latest VC++ redistributable package download. This is the new link: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Pull request merged**
