### PR TITLE
Update Nuget Build Instruction

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Update Nuget Build Instruction because the old one is out of date.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 

### FYIs

@ColinDayOrg @alfarok @reddyashish @scottmitchell

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I think we should mention that you must build the install first in release mode before running the script. Also harvest path was not optional for me :(

**Comment by mjkkirschner** [comment]
In the future it would be good to provide instructions here for using a local nuget repo as well I think.

**Comment by QilongTang** [comment]
@mjkkirschner That's strange by looking at the script, if the second param is empty, it should go for the default harvest path.. Building the install in `release` is optional, as long as you build Dynamo in release and specify the bin folder at path

**Comment by QilongTang** [comment]
@mjkkirschner Skipping the second param worked for me. Merging.
```
PS C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet> .\BuildPackages.bat 'template-artifactory'

C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet>if not "" == "" goto :harvestpathdefined

C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet>echo The path to the Dynamo dlls was not specified. Using the dlls in the install directory...
The path to the Dynamo dlls was not specified. Using the dlls in the install directory...

C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet>set harvestPath=..\..\src\DynamoInstall\harvest

C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet>if not exist ..\..\src\DynamoInstall\harvest (
echo Dynamo\src\DynamoInstall\harvest folder not found.
 echo Please build Dynamo\src\Install.sln before running this script!
 exit /b 1
)

C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet>goto :build
Attempting to build package from 'DynamoVisualProgramming.DynamoCoreRuntime.nuspec'.
Successfully created package 'C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet\DynamoVisualProgramming.DynamoCoreRuntime.2.1.0-beta6957.nupkg'.
Attempting to build package from 'DynamoVisualProgramming.SignDynamo.nuspec'.
Successfully created package 'C:\Users\tanga\Documents\GitHub\Dynamo\tools\NuGet\DynamoVisualProgramming.SignDynamo.2.1.0-beta6957.nupkg'.

```

**Pull request merged**
