### PR TITLE
Trust dialog does not fit localized text

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

Make trust dialog wider. Because the layout is static and uses a canvas it is hard to make this responsive now.
😢 
It looks pretty crummy and may still not fit really long localizations, ~~I've tried to strike a balance by centering some of the text~~, at least users will be able to hit `yes` - I think it should be made responsive in master after 2.15.

Screen Shot 2022-06-17 at 4 12 56 PM

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
1. Can we left align the text and check box?
2. For the button, did you test in localized Dynamo, if not, do you need someone from Morpheus to help on this? FYI: @reddyashish

**Comment by mjkkirschner** [comment]
@QilongTang yep, I can put the text back to the left, and no I did not test in localized Dynamo,  I just substituted some random long strings - see the image.

If someone has time to find what the minimal width is that works that would be great.
I'll look at the auto resize thing to see if it's doable, but I don't think it's safe for this release.

**Comment by reddyashish** [comment]
With the latest changes.
Russian:
Screen Shot 2022-06-17 at 4 06 19 PM

Jap:
Screen Shot 2022-06-17 at 4 08 25 PM

Korean:
Screen Shot 2022-06-17 at 4 10 07 PM

**Comment by mjkkirschner** [comment]
@QilongTang @Amoursol @Jingyi-Wen with @reddyashish 's help we shrank this to 500 pixels instead of 600 and I think it looks a lot better, also gave some more margin to the first line of text for some cases where the other localized characters hit the edge of the popup.

**Review by reddyashish — APPROVED** [review]

**Pull request merged**
