### PR TITLE
InCanvasSearch: return focus to seach text box

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-7508](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7508) Can't return to search after browsing menu items in context menu

Solution to this bug is not close context menu, if original sender was TextBox.
This PR should be merged after https://github.com/DynamoDS/Dynamo/pull/4607

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] The level of testing this PR includes is appropriate

### Reviewers

@pboyer 
@Benglin 

### FYIs

@lillismith

### CODE REVIEW

**Comment by ramramps** [comment]
@aosyatnik  - OnInCanvasSearchContextMenuKeyDown and OnInCanvasSearchContextMenuMouseUp - I belive you should use the Sender object and cast to Canvas, instead of using directly the view object. Any thoughts?

OnCanvasClicked -  Why there is a check for Canvas == null? The canvas object is not used here. So, I dont see a point to check this. Also, if you click on the canvas, then canvas object should never be null.

**Comment by aosyatnik** [comment]
Sorry, @ramramps , this was not synchronized with master. Updated it.

**Comment by ramramps** [comment]
@aosyatnik - Did you check the comments I had for this change?

**Comment by aosyatnik** [comment]
@ramramps , canvas is not checked for null now.
KeyDown and MouseUp still use context menu by name.

**Comment by ramramps** [comment]
@aosyatnik  - why KeyDown and MouseUp still use context menu by name? If you have mutiple views, then it will be difficult to check which Canvas is being used. Is it possible to use the sender object and cast to canvas?

**Comment by aosyatnik** [comment]
Hi, @ramramps , thanks for review and suggestion, but canvas can't be sender in any case, since click is handled by `InCanvasSearchControl` or `ContextMenu`. But, since we do not want to use name to determine context menu, I moved handlers layer upper. Now sender is ContextMenu and we do not need to get canvas by name and its' context menu.

**Pull request merged**
