### PR TITLE
Restyle Watch / Preview Bubble

### PR DESCRIPTION
**Pull request by OliverEGreen**
### Purpose

This PR restyles the `Watch` node, `PreviewControl` and `PreviewCompact` views to align with the visual refresh.

TzNZvA4XKF

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Restyles the watch node and preview bubbles.

### Reviewers

@QilongTang @Amoursol 

### FYIs

@SHKnudsen

### CODE REVIEW

**Comment by mjkkirschner** [comment]
171 failures, most like:
```
System.Windows.Markup.XamlParseException : Set property 'System.Windows.Documents.TextElement.Foreground' threw an exception.
  ----> System.ArgumentException : '#FFDCDCDC' is not a valid value for property 'Foreground'.
+++++++++++++++++++
```

**Comment by Amoursol** [comment]
> 171 failures, most like:
> 
> ```
> System.Windows.Markup.XamlParseException : Set property 'System.Windows.Documents.TextElement.Foreground' threw an exception.
>   ----> System.ArgumentException : '#FFDCDCDC' is not a valid value for property 'Foreground'.
> +++++++++++++++++++
> ```

They all have an additional "FF" at the front of the color code, so should be an easy fix for @OliverEGreen :)

**Comment by Amoursol** [comment]
@OliverEGreen can you please also change the hover-color blue in all of these expressions to match our other selection color blue? #6AC0E7

**Comment by mjkkirschner** [comment]
I'm not sure thats the problem, I think it's that Text.Foreground is a brush, not a color, so you have to build a solidColorBursh from a color then assign that.

**Comment by OliverEGreen** [comment]
> > 171 failures, most like:
> > ```
> > System.Windows.Markup.XamlParseException : Set property 'System.Windows.Documents.TextElement.Foreground' threw an exception.
> >   ----> System.ArgumentException : '#FFDCDCDC' is not a valid value for property 'Foreground'.
> > +++++++++++++++++++
> > ```
> 
> They all have an additional "FF" at the front of the color code, so should be an easy fix for @OliverEGreen :)

Wow 171, that's unexpectedly high.
The extra FF is for opacity, it can normally be ignored. Assuming it's an easy fix.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
