### PR TITLE
Update Unresolved Node Icon

### PR DESCRIPTION
**Pull request by OliverEGreen**
### Purpose

This PR updates the icon for unresolved nodes.

image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Updates the unresolved node icon.

### Reviewers

@QilongTang 

### FYIs

@SHKnudsen 
@Amoursol

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by Amoursol** [comment]
@OliverEGreen - Can you also please force on the red color band at the bottom if the icon is showing?

**Comment by QilongTang** [comment]
> @OliverEGreen - Can you also please force on the red color band at the bottom if the icon is showing?

@Amoursol Currently unresolved nodes are in warning states, so once the other warning bar PR merged, this node will appear with a yellow bar. If we want to align the color, we need to think about it. But I am pretty sure in the past, the icon also does not align with node warning state color

**Comment by Amoursol** [comment]
> Current state before PR merged: image
> 
> Dynamo 2.12.0 image
> 
> @Amoursol Currently unresolved nodes are in warning states, so once the other warning bar PR merged, this node will appear with a yellow bar. If we want to align the color, we need to think about it. But I am pretty sure in the past, the icon also does not align with node warning state color

@OliverEGreen as per @QilongTang 's point above, we will want to ensure the existing paradigm (Yellow warning + icon) persists, so can we please change the icon back to yellow? @Jingyi-Wen can provide this. My apologies on the misdirection here.

**Comment by OliverEGreen** [comment]
My fault, I think I got confused between unresolved custom nodes (which show an error) and unresolved package nodes (which show a warning). Icon switched back to yellow:
image

**Comment by QilongTang** [comment]
On a side note, I no longer see the warning associated with the unresolved nodes to show at all, seems to be a major regression to me. FYI: @Amoursol @OliverEGreen @mjkkirschner @reddyashish @zeusongit 
image

**Comment by Amoursol** [comment]
@QilongTang @OliverEGreen - Please do retain any existing error messages :)

**Pull request merged**
