### PR TITLE
DynamoCLI (opening new PR)

### PR DESCRIPTION
**Pull request by holyjewsus**
### Purpose

This PR modifies Program.CS and adds a series of command flags that let a user automate the running of dynamo graphs and the setting of the graph to preset states.

I've modified this PR according to comments below.
* commandLineArguments parsing is now handled by NDesk.Options which we are already include in our repo and which handles / and - command line flags
*  Startup logic, model creation, preloading methods, and locale setting is now handled in Dynamo.Applications namespace
* Dynamo Sandbox and DynamoCLI both reference DynamoApplications to handle these startup activities.
* I've added DynamoCLI and DynamoApplications to the Mono.2013 solution and tested DynamoCLI on mac (it requires being run as sudo as it might create user folders to hold settings)

please see this proposed documentation for more info on available flags:
https://github.com/holyjewsus/Dynamo/wiki/Proposed-Command-Line-Documentation

see a video here:
https://www.dropbox.com/s/3k54qg4udbdmaqz/command%20line%20restorestate.mov?dl=0

### Impact assessment

- [x] Changes the way 3rd party nodes work (Add ikeough to the reviewer list)
- [x] Affects which components of the system depends on which other components (Add pboyer to the reviewer list)

* Link to communications doc (same doc as above): https://github.com/holyjewsus/Dynamo/wiki/Proposed-Command-Line-Documentation

#### Testing strategy

the commandLineRunner class separates out of program.cs the logic for invoking run operations on a DynamoModel, via an array of arguments. There are a basic tests in this PR that check each command flag and run the DynamoTestModelBase model with the command line runner.

There are also tests that invoke the main method of the DynamoCLI with the command line runner class.

### Reviewers

@ikeough 
@pboyer 

### FYIs

@jnealb 
@Benglin

### CODE REVIEW

**Comment by holyjewsus** [comment]
@ikeough I've merged this with latest master PTAL

**Comment by ikeough** [comment]
Comments on the documentation:
- Rename the document to "Dynamo Command Line Interface"
- Move the output of `-h` up to the very top of the document.
- Don't bold your arguments, make them code formatted like `-o`
- Use fenced code blocks whenever writing code or xml. See the markdown docs for how to do this.

**Comment by ikeough** [comment]
@holyjewsus A couple of comments on the documentation, but nothing that should prevent this from going in. Thanks!

**Comment by RodRecker** [comment]
@holyjewsus this looks good. Make sure -l is included in the examples, I suggest having some brief examples for quick reference.

**Comment by holyjewsus** [comment]
@pboyer @ikeough I've run this on the self serve CI and there were no failures, yay! BUT I was doing some final testing and came across the following behavior:

When I run a graph from the CLI that generates geometry I get this exception on shutdown of protogeomoetry:

screen shot 2015-07-15 at 7 17 30 pm

I've spent a bunch of time trying to figure out if I'm not shutting down DynamoModel or disposing of nodes correctly, but cannot find a reason. Is this behavior expected? Any thoughts on where to look?

**Comment by holyjewsus** [comment]
apparently the above behavior is a longstanding bug that occurs with Dynamo as well, I've filed the bug here:
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7915

I've also tested this with an installer- standalone and Dynamo on Revit both seem to work fine, there were also no regressions on the self serve CI, so merging this guy in. Will update the documentation next.
@ikeough @Benglin

**Comment by Benglin** [comment]
Thanks @holyjewsus, I wasn't aware of `NDesk.Options`, I've learnt something today!

**Pull request merged**
