### PR TITLE
MD File Localization Proposal

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Proposal for changes in localizing md files in Dynamo
During my research about adding the .resx files to all the projects for each language noticed that also we need to have the fallback_docs sub-folder for each language.
Then in this PR I'm proposing a change in the DynamoCore.csproj file for copying the md files to the fallback_docs inside each language folder, **not sure if this change is needed** due that we need to be sure that localization team has the changes for translating the md files once they are in this new location.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Proposal for changes in localizing md files in Dynamo

### Reviewers

@QilongTang 
@ZbynekHanak-RWS

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
@ZbynekHanak-RWS any comment on this? 
Not sure if is a good idea to copy the md files to each folder language or leave it as it is right now.

**Comment by ZbynekHanak-RWS** [comment]
Hi @RobertGlobant20 , thank you for this proposal. I created a mapping list of Dynamo Core resources - [Dynamo CL - Mapping cBuild source to CL source](https://wiki.autodesk.com/display/LOCGD/Dynamo+CL+-+Mapping+cBuild+source+to+CL+source) . Seems few more sources need to be globalized, mainly we need to update folder structure. It can be filtered by "Source path/folder structure needs to be updated/globalized?" column. One of these issues is related to .md files installed to fallback_docs sub-folder for each language coming from doc\distrib\NodeHelpFiles folder.

Would it be possible to move the source English .md files to en-US folder (ex. doc\distrib\NodeHelpFiles\en-US)? I will update CL then to deliver the localized .md files to language folders (ex. …\NodeHelpFiles\cs-CZ). Thank you

**Comment by RobertGlobant20** [comment]
> Hi @RobertGlobant20 , thank you for this proposal. I created a mapping list of Dynamo Core resources - [Dynamo CL - Mapping cBuild source to CL source](https://wiki.autodesk.com/display/LOCGD/Dynamo+CL+-+Mapping+cBuild+source+to+CL+source) . Seems few more sources need to be globalized, mainly we need to update folder structure. It can be filtered by "Source path/folder structure needs to be updated/globalized?" column. One of these issues is related to .md files installed to fallback_docs sub-folder for each language coming from doc\distrib\NodeHelpFiles folder.
> 
> Would it be possible to move the source English .md files to en-US folder (ex. doc\distrib\NodeHelpFiles\en-US)? I will update CL then to deliver the localized .md files to language folders (ex. …\NodeHelpFiles\cs-CZ). Thank you

Yes, we can move the md files to the folder  `....doc\distrib\NodeHelpFiles\en-US`
@QilongTang due that the task DYN-7480 is a SPIKE should we create a new task for moving the md files to the `....doc\distrib\NodeHelpFiles\en-US` folder? If that is the case I will create a different PR and close this one since this one won't be valid anymore.

**Comment by mjkkirschner** [comment]
@QilongTang when are we going to stop messing around with all these files and start using resource binaries?

**Comment by QilongTang** [comment]
> @QilongTang when are we going to stop messing around with all these files and start using resource binaries?

Thanks @mjkkirschner for double checking, yeah the plan for Morpheus was updating the localization process first to be source level localization, then look at if we can use resource files in 3.5 or 3.6 release.

**Comment by RobertGlobant20** [comment]
I've submitted a change for moving the files from `doc\distrib\NodeHelpFiles\`  to the folder `doc\distrib\NodeHelpFiles\en-US`
Also I've modified the .csproj file for reflecting this change when building the DynamoCore.csproj project.

**Comment by RobertGlobant20** [comment]
> Hi @RobertGlobant20 , thank you for this proposal. I created a mapping list of Dynamo Core resources - [Dynamo CL - Mapping cBuild source to CL source](https://wiki.autodesk.com/display/LOCGD/Dynamo+CL+-+Mapping+cBuild+source+to+CL+source) . Seems few more sources need to be globalized, mainly we need to update folder structure. It can be filtered by "Source path/folder structure needs to be updated/globalized?" column. One of these issues is related to .md files installed to fallback_docs sub-folder for each language coming from doc\distrib\NodeHelpFiles folder.
> 
> Would it be possible to move the source English .md files to en-US folder (ex. doc\distrib\NodeHelpFiles\en-US)? I will update CL then to deliver the localized .md files to language folders (ex. …\NodeHelpFiles\cs-CZ). Thank you

@ZbynekHanak-RWS based in this request, is this the expected change?

**Comment by ZbynekHanak-RWS** [comment]
Hi @RobertGlobant20 , the change looks good. When the .md files will be in en-US folder I can update the .adsk/ContinuosLocalization.yaml config to allow CL to process these. Looks there will be need to update the DynamoCore.csproj project to pickup the localized .md files later. Seems now it copies the en-US .md to all localized folders using NodeHelpMDFiles property. Thanks

**Comment by RobertGlobant20** [comment]
@ZbynekHanak-RWS I've submitted a fix for copying all the md files inside each language folder, For example copying from `Dynamo\doc\distrib\NodeHelpFiles\en-US` to the output path: `Dynamo\bin\AnyCPU\Debug\en-US\fallback_docs`
See commit: https://github.com/DynamoDS/Dynamo/pull/15543/commits/8d76777fb2e7c4aaed10b69fe597782fc0249fc3
Please let me know what you think.
Thanks

**Comment by RobertGlobant20** [comment]
@ZbynekHanak-RWS any comment in the latest changes?

**Comment by ZbynekHanak-RWS** [comment]
Hi @RobertGlobant20 , it looks good for all the .md files that will be copied from the localized folders in repository to the localized fallback_docs output paths. Please note the .sat and .txt files are not localized. Can you just copy these from source en-US to localized output path instead?

For example copying the .sat and .txt from `Dynamo\doc\distrib\NodeHelpFiles\en-US` to the output path: `Dynamo\bin\AnyCPU\Debug\de-DE\fallback_docs`. Thank you

**Comment by RobertGlobant20** [comment]
@ZbynekHanak-RWS I've submitted a new commit for using just one source (en-US folder) when copying the SAT and TXT files, please let me know your thoughts about this change.
Thanks
commit: https://github.com/DynamoDS/Dynamo/pull/15543/commits/b966b06e7c2327c96fc4c5286dc4946a8e2c7c29

**Comment by ZbynekHanak-RWS** [comment]
Hi @RobertGlobant20 , yes, this change for the SAT and TXT files looks good. I think we can move forward to setup the MD files localization once this PR is merged to master_cl. Thank you

**Comment by ZbynekHanak-RWS** [comment]
Hi @RobertGlobant20 ,

This **master_cl** was created to setup CL (Continuous Localization) pipeline for Dynamo Core product.

- Localization team usually doesn't merge the changes in sources. This PR should be merged by Dev team.
- Similarly to update this branch with the latest changes from master.
- Regarding to merging **master_cl** to master it could be done once CL setup is finalized.

Meanwhile, Localization team will support the existing localization process to avoid any issue with the master branch.

Thank you.

**Comment by QilongTang** [comment]
@RobertGlobant20 Did you check the self serve yet?

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
