### PR TITLE
[DYN-6455] Add warning text to selection node's initial warning

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

Add warning text to selection node's ghost warning.
Initially when no element is selected, the node state is in Warning state, but no text was displayed, this PR adds the text `Nothing selected` to the warning info state.

Revit_arSWxM3B7l

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

- Add con(text) to selection node initial warning.

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Comment by QilongTang** [comment]
But somehow warning bubble is still not enabled for selection nodes?

**Comment by zeusongit** [comment]
> But somehow warning bubble is still not enabled for selection nodes?

@QilongTang For the warning bubble to appear we had to set persistent flag as true, or else the bubble is not update and the flow is returned at this linehttps://github.com/DynamoDS/Dynamo/blob/3354472b463154e20bcbc4e282e4eff97c349fa5/src/DynamoCoreWpf/ViewModels/Core/NodeViewModel.cs#L1478, since the select face node is not involved in execution initially.

But after setting the warning as persistent, the warning is shown even after an element is selected.

**Review by QilongTang — APPROVED** [review]

**Comment by zeusongit** [comment]
Tracked here: https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/13714/

**Comment by zeusongit** [comment]
Passed, merging!

**Comment by QilongTang** [comment]
@zeusongit Please cherry-pick this one to RC3.0.2

**Pull request merged**
