### PR TITLE
QNTM-3261: Prevent variable redefinition in function definitions and associative blocks

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

Prevent variable redefinition in function definitions and associative blocks

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@pboyer 

### FYIs

@jnealb

### CODE REVIEW

**Comment by pboyer** [comment]
This looks good. It would be good to have a unit test or two to prevent regression.

**Comment by mjkkirschner** [comment]
@aparajit-pratap is this going to land before release cut?

**Comment by ramramps** [comment]
@aparajit-pratap Can you provide an update?

**Comment by aparajit-pratap** [comment]
@pboyer @ramramps @mjkkirschner added tests, merging ...

**Pull request merged**
