### PR TITLE
Integrate List@Level into sample files

### PR DESCRIPTION
**Pull request by yeexinc**
### Purpose

This PR is to address [DYN-428](https://jira.autodesk.com/browse/DYN-428). The only existing sample file that used List.Map or List.Combine nodes was `Core_PassingFunctions.dyn`, and the node was replaced with use of List@Level.
In addition, a sample file about List@Level is added. Please check the file `Core_ListAtLevel.dyn` included in the zipped folder.
[SampleFiles.zip](https://github.com/DynamoDS/Dynamo/files/760137/SampleFiles.zip)

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@riteshchandawar 

### FYIs

@Racel

### CODE REVIEW

**Comment by Racel** [comment]
@yeexinc - For the List@Level example, a few things:

- The file was saved in a zoomed in state. You may want to zoom to fit so that the users can see more of the graph.

- Can we add a part of this that does count and/or flatten comparisons? 

- Also, you might as well and set the List.GetItemAtIndex to @L2 so that the List.Map comparison already matches. That tripped me up. You also might want to group the list@level work so that the user understands what they are comparing. Use the same color.

**Comment by yeexinc** [comment]
Thank you for the detailed review @Racel , I have made some changes to the file. Please check the attached file below.
[Core_ListAtLevel.zip](https://github.com/DynamoDS/Dynamo/files/765794/Core_ListAtLevel.zip)

Do let me know if further amendments are required, thanks.

FYI @riteshchandawar

**Comment by yeexinc** [comment]
@riteshchandawar - The version of the files and some of the notes have been updated as discussed. Thanks!

**Comment by riteshchandawar** [comment]
LGTM from my side, @Racel once you review this we can merge this PR.

Thanks,
Ritesh

**Comment by Racel** [comment]
@yeexinc @riteshchandawar - I took a look at the file. Can we break it up into 3 files (one for each workflow)? The List@Level file is huge. As a rule of thumb, we should make it so that every node can be read on "zoom to fit" for sample files. Let me know if you need help.

**Comment by yeexinc** [comment]
@Racel - I can break it up into separate files, but I noticed that some of the other sample files like CoreCodeBlocks, CoreRangeSyntax and CoreStrings are relatively huge and have many nodes as well.

Should we break them up into multiple files, too? Though I personally find that having all the information in one file can be good too, as each file acts like a single chapter (especially the CoreCodeBlocks file).

**Comment by Racel** [comment]
Hi @yeexinc - let's just try to break up the list@level stuff into separate files. Since the other samples have been there for a while, I don't think we need to do anything to those. I just think we should go with the "smaller" file approach from now on.

**Comment by yeexinc** [comment]
@Racel - I've broken it up into three files, as attached here:
[CoreListAtLevel.zip](https://github.com/DynamoDS/Dynamo/files/795472/CoreListAtLevel.zip)

Here's how the menu looks like with the three files - will this be good?
listatlevelsample

**Comment by Racel** [comment]
@yeexinc - Sorry about the back and forth. I took a closer look at your samples, and I think we can just simplify them and have 1 sample file. I modified your original file. See attached. Can you and @riteshchandawar take a look and let me know what you think?

If we just have this one simplified file, we can get rid of the numbers at the end of the name.

[CoreListAtLevel.dyn.zip](https://github.com/DynamoDS/Dynamo/files/796727/CoreListAtLevel.dyn.zip)

**Comment by yeexinc** [comment]
@Racel - Thank you for taking the time to review the file and for even modifying it, I think it's good that it's more concise this way. I personally prefer to have the numbers at the end of the file names to be removed too.
I've committed the file to this PR, the only thing I changed is the name of the file to `Core_ListAtLevel.dyn` to be consistent with the other sample files.
@riteshchandawar - Any other changes required?

**Comment by riteshchandawar** [comment]
@Racel Example looks great now. Do we need to add an example for replacement of  List.Combine? 

I am merging this PR, do let us know if any additional changes required for List.Combine.

**Comment by riteshchandawar** [comment]
@yeexinc There is one Test Failing for PassingFunctions, see if that is because of your changes or not. Here are the details about test failure.

 Test Failure : Dynamo.Tests.DynamoSamples.Core_PassingFunctions
     Expected: 17
  But was:  16

It means one of the node got deleted from the old file.

Once that is fix, I will merge this PR.

**Comment by yeexinc** [comment]
Thanks @riteshchandawar , it was due to the node being replaced by the use of List@Level feature.
I've updated the test case for it.

**Comment by riteshchandawar** [comment]
Awesome, merging this in.

**Pull request merged**
