### PR TITLE
set camera back to defaults...

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose
http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9956

These basic samples were created in .7x of Dynamo and did not have a camera element in the .dyn. When they were re-saved in 90 they had a camera element added.

I've simply added a camera element with the same values as the default values of the camera so the camera will be placed in the same position as the older samples.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.

### Reviewers

@QilongTang 

### FYIs

@jnealb

### CODE REVIEW

**Comment by QilongTang** [comment]
@mjkkirschner  Are these the same values as 9.2?

**Comment by mjkkirschner** [comment]
@QilongTang yes, I believe so, these are the default values the camera uses, and since the samples in 92 didnt have a camera element they were defaulting to these.

**Comment by QilongTang** [comment]
Cool. LGTM.

**Comment by QilongTang** [comment]
@mjkkirschner Please cherry pick this one into 1.0 branch.

**Pull request merged**
