### PR TITLE
Hide notes section in pull request markdown preview

### PR DESCRIPTION
**Pull request by avidit**
### Purpose

Hide notes section in pull request markdown preview

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
Any screenshot for preview? Is change making them disappear or folded?

**Comment by avidit** [comment]
> Any screenshot for preview? Is change making them disappear or folded?

preview

**Comment by QilongTang** [comment]
Can we fold this section somehow or move this section to the bottom instead of removing it? We still want to encourage 3rd party contributions and the notes there are pretty important info

**Comment by avidit** [comment]
> Can we fold this section somehow or move this section to the bottom instead of removing it? We still want to encourage 3rd party contributions and the notes there are pretty important info

We are not removing the notes section. It will be there in `write` tab same as before, where the creator of the pull request can read it. With this change it will be hidden only in the `preview` tab.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
