### PR TITLE
DYN-5386: Switch CER feature flag from the old "CER" to "CER_v2"

### PR DESCRIPTION
**Pull request by sm6srw**
### Purpose

This pull request does:
* change the feature flag for CER from CER to CER_v2
* default CER to send Dynamo log and settings files

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by pinzart90** [comment]
@sm6srw can you manually test the new flags ?
In debug builds we have a debug mode that can cause a crash on demand.
Please check if the CER report includes the log file and the settings file.

Also looks like a non-related test is failing.

**Comment by sm6srw** [comment]
> 

Will do.

**Comment by sm6srw** [comment]
All tests passed here: https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/7642/

**Comment by sm6srw** [comment]
@pinzart90:  The CER report did show up on the CER site. See report ID 333422183. The settings file and log file is now part of `Report.zip`

**Review by pinzart90 — APPROVED** [review]

**Pull request merged**
