### PR TITLE
Serialize Dictionaries to XML in CLI

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

This PR reverts the change to the CLI in #8593 due to CLI test failures.

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [X] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 

### FYIs

@smangarole

### CODE REVIEW

**Comment by ramramps** [comment]
that PR had other changes - `GetDataOfValue` in utils.

**Comment by aparajit-pratap** [comment]
@mjkkirschner @ramramps I couldn't figure out how to fix the failure in CLI so I reverted the change only in CLI.

**Comment by mjkkirschner** [comment]
:( okay, thanks for looking into it. @alfarok @varvaratou  @mrahmaniasl are we okay with CLI serializing differently?

what does a dictionary serialized from CLI look like today?

**Comment by mjkkirschner** [comment]
@aparajit-pratap should we merge this so the build is fixed and then discuss the state of CLI output?

**Comment by mjkkirschner** [comment]
@aparajit-pratap - another thought, we could just duplicate your logic for dictionaries in the string output method so that CLI output is actually useful right?

**Comment by aparajit-pratap** [comment]
@mjkkirschner PTAL

**Comment by mjkkirschner** [comment]
LGTM please merge if this is ready @aparajit-pratap 
FYI @mccrone @mrahmaniasl

**Comment by mjkkirschner** [comment]
@aparajit-pratap gonna merge this now to get a build, if it's not ready please revert.

**Pull request merged**
