### PR TITLE
Added several preview tests.

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-9397](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9397) Write tests for Preview bubble

### Declarations

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.

### Reviewers

@ramramps

### CODE REVIEW

**Comment by ramramps** [comment]
@aosyatnik - Looking good. Did you run the self service CI? If not run the self service CI , if there are no errors then merge it,

**Comment by aosyatnik** [comment]
@ramramps Self CI stuck on
***** Dynamo.Tests.ListTests.LaceLongest_Simple
var_5da40769ffc8408b94bb8c5dff31132e = { { 2 }, { 8 }, { 14 }, { 19 } }
***** Dynamo.Tests.ListTests.LaceShortest_NegativeInput
Warning: Internal error, please report: Method 'DoEvaluation()' is invoked on an invalid object. (fa006d2b)
Warning: Internal error, please report: Method 'DoEvaluation()' is invoked on an invalid object. (fa006d2b)
Warning: Internal error, please report: Method 'DoEvaluation()' is invoked on an invalid object. (fa006d2b)
Warning: Internal error, please report: Method 'DoEvaluation()' is invoked on an invalid object. (fa006d2b)

I had to abort it. Although tests pass on my machine. How that can be?...

**Comment by ramramps** [comment]
sometimes self service CI test behaves like this. restart the test and check. you can do that today if you have time or do it tomorrow.

**Comment by aosyatnik** [comment]
Run self CI. No fallen tests.

**Pull request merged**
