### PR TITLE
Viz manager cleanup

### PR DESCRIPTION
**Pull request by ikeough**
The Visualization Manager has not been cleaned up in some time. Prior to the usage of tasks for the purpose of aggregating render packages, the visualization manager was responsible for aggregating render packages. The visualization manager is no longer responsible for this, but was still processing one method responsible for aggregating render packages without then triggering the events which would use those render packages.

All Visualization Manager tests continue to pass.

PTAL:
- [x] @pboyer

### CODE REVIEW

**Comment by ikeough** [comment]
@pboyer Out of band PR. There is no associated YT issue. This was just pissing me off.

**Comment by ikeough** [comment]
@pboyer ping.

**Comment by jnealb** [comment]
@ikeough @pboyer PTAL at my latest findings in MAGN-6100 - the issue is now much less random and I have provided more Snoop details.

**Comment by pboyer** [comment]
I'm always down to remove code.  I'm guessing you've done a lot of playing around with this.  Please make sure @jnealb can hammer on it by creating a YT task and assigning to him for testing.

**Pull request merged**
