### PR TITLE
Integer slider overflow max 

### PR DESCRIPTION
**Pull request by ramramps**
If the integer slider value exceeds the 32 bit limit, then it resets the value to 0.

This fix will reset the value to 2^32 - 1, if the value exceeds the 32 bit limit. 
For Maximum the limit is set to 2,147,483,647 and for minimum the value is set to -2,147,483,648.

int.TryParse will return false, if there is an overflow or if the value is not a number. For all false condition, now
the function checks whether every character is a number. If the number is negative, the check starts from first position instead of zero-th position.  Depending on the sign, the function returns a max or min value.

- [ ] @pboyer

### CODE REVIEW

**Comment by ramramps** [comment]
- [ ] @pboyer  - Can you please review this?

**Comment by ramramps** [comment]
@ikeough 
Ian, I made few changes in integer slider. The changes are to make sure that value is never greater than 2,147,483,647. 
Also, I made the Value on BasicInteractive class as Virtual, so that Value can be overridden in IntegerSlider class.  I made this change because say if the value is 2147483648, first time the value will be updated in UI to 2147483647, which is correct. But again the value is changed to 2147483648, the value will not be updated in UI to 2147483647. The condtion !this.value.Equals(value) is always true in that case and hence   RaisePropertyChanged("Value") will not be raised. Please let me know if this is OK, or I should do it differently.

**Comment by ikeough** [comment]
@ramramps Just a couple of small questions, then LGTM.

**Comment by ramramps** [comment]
@ikeough  - Int32.Tryparse will default the value to 0 if the value is greater than Int32,Maxvalue. 
But in our case, I had to change the value to Int32.Maxvalue (or Minvalue) if the value entered is greater than the Int32 limits.

**Comment by ikeough** [comment]
@ramramps Does it make more sense to let the value go to '0' instead? Will the user understand that the value that is then set is the maximum 32 bit integer value?

**Comment by ramramps** [comment]
@jnealb  @ikeough  - Tagging Neal in this case. Neal mentioned that value should not be 0, instead it should default to Max (or Min) value.

**Comment by jnealb** [comment]
@ikeough @ramramps That was just a suggestion at the time, based on usage cases in other products. Ideally a message is displayed indicating overflow and min/max values are populated, since probably the user wanted to get the big nums, and flooring to 0 sets them back. But this is geometry, which I am less experienced with, so I defer to Ian.

**Comment by ramramps** [comment]
@jnealb  @kronz  @ikeough  - But neal, this particular task is created to address that. If we say it has to set to 0, then this task becomes obsolete. During our initial discussion, instead of a message popping up, it was agreed to set the value to max (or min). If we say we dont want that feature, then I don't think we need this particular task.

**Comment by jnealb** [comment]
@ikeough @kronz @ramramps This is a Product Owner task, no?

**Comment by ikeough** [comment]
@ramramps, @neal has a good point. If we reset to 0, we'll probably break the user's geometry. If possible, it would be nice to set to Max-1, then present an warning message on the node. I'll let @kronz break the tie.

**Comment by ramramps** [comment]
I will show the feature to @kronz  tomorrow....

**Comment by kronz** [comment]
@ramramps Please set to Max/Min, not zero.  It would be nice to have a warning, but is not needed for this fix.  The nice thing about setting to Min/Max when the limit is violated is that it should illustrate to the user that there is a limit. 
Thanks
Z

**Comment by ramramps** [comment]
@ikeough  - Shall I merge this PR?

**Pull request merged**
