### PR TITLE
Add more tooltips in Preferences panel

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Per https://jira.autodesk.com/browse/DYN-5344, add more tooltips in preferences panel.

image

image

image

image

image

image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

@DynamoDS/dynamo 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by reddyashish — APPROVED** [review]

**Comment by QilongTang** [comment]
@hwahlstrom please review the content

**Comment by hwahlstrom** [comment]
@QilongTang Suggested updates:

**Use hardware acceleration**
Before: 
This means that WPF applications get the benefits of hardware acceleration for smoother graphics and all-around better performance (due to work being offloaded to graphics processing units [GPUs] instead of central processing units [CPUs]
After: 
Hardware acceleration improves performance and smoothness of graphics.

**Isolate selected geometry**
Before: 
This means selection of geometry node will highlight the geometry produced from such node only among the graph from geometry background.
After: 
When toggled on, selecting a geometry node will highlight the geometry it produces in the background 3D preview.

**Show edges**
Before: 
This means display more detailed edge on geometry from topology subtypes.
After: 
When toggled on, more detailed edges will be displayed for geometry from topology subtypes.

**Show CodeBlockNode Line Numbers**
Before: 
This means the line number on the left of Code Block  Node enditor will be displayed or not.
After: 
When toggled on, line numbers will be displayed in the Code Block node editor.

**Show preview bubbles**
Before: 
This means the preview bubble below node will be displayed or not.
After:
When toggled on, a preview of the node’s output will be displayed when hovering over the bottom of a node.

**Comment by QilongTang** [comment]
> 

hi @hwahlstrom I think all the other ones looks good but I cant agree on the first one, I think the short version over simplified things. Hardware acc is just an option but not a magic bullet that for sure will improve things, I think the short version make it sounds like user should always turn it on.

**Comment by hwahlstrom** [comment]
@QilongTang Updated version for hardware acceleration: 

When toggled on, Dynamo benefits from hardware acceleration to improve smoothness of graphics and overall performance, as work is offloaded from central processing units (CPUs) to graphics processing units (GPUs).

**Pull request merged**
