### PR TITLE
add workflow test to test csv

### PR DESCRIPTION
**Pull request by zora-wang**
### Purpose
[The  commit is to add test to test NurbsCurve.byPoints node : with negative input value, the Dynamo wont crash]

### Reviewer:
@monikaprabhu  @aparajit-pratap 
capture

### CODE REVIEW

**Comment by monikaprabhu** [comment]
Zora- the PR needs to be separate into two as one is automation test and other is bug fix in localization.

**Comment by monikaprabhu** [comment]
LGTM.

**Comment by riteshchandawar** [comment]
Why this test case gets added to ComplexTests.cs, this should get added to GeometryDefects.cs. Please do not spoil the intend fo ComplexTests categories.

@zora-wang : Can you please make me a reviewer for all your PR's which are related to Geometry and Revit.

Thanks,
Ritesh

**Comment by monikaprabhu** [comment]
@riteshchandawar - because nobody intentionally creates a nurbs curve with -ve value as degree, but that happens when you have some workflow or a function which output -ve value  accidentally.  To simulate that Zora is reading values from excel  and passing it to nurbs curve, which is  ok with me to add in complex tests. Additionally you can add a simple nunit test with -ve value as input in GeometryDefects.cs

**Comment by riteshchandawar** [comment]
Defect Relates test cases should go to GeoemtryDefect.cs for easy understanding and managing.

**Comment by monikaprabhu** [comment]
@riteshchandawar - If its a requirement please create a document with regards to best practices and share it with the team.

**Pull request merged**
