### PR TITLE
remove xml to markdown flow and infrastructure

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

Remove appveyor publish
Remove gitsubmodules
Remove xmlToMarkdownProject (debatable if we want to remove this as part of a cleanup)

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@QilongTang 
@smangarole 
@zeusongit

### CODE REVIEW

**Comment by QilongTang** [comment]
@mjkkirschner I am ok removing `XmlDocToMarkdown`, I feel like we should redirect to other pages for Dynamo API if we do this cleanly though..

**Comment by mjkkirschner** [comment]
@QilongTang I will redirect to fuget for now - but removing this code will not bring the site down - so we can do that later if we wish.

**Comment by QilongTang** [comment]
@mjkkirschner shall we?

**Comment by mjkkirschner** [comment]
yes, lets see if anything breaks.

**Pull request merged**
