### PR TITLE
Dyn 2501 - Fix Increase Code Coverage Migration folder

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Increased the code coverage for the project DynamoCore/Migration folder.
Related GitHub issue or JIRA story
https://jira.autodesk.com/browse/DYN-2501

**There was an issue in the method TestWorkspaceMigrationAttribute(), because after setting the flag DynamoModel.EnableMigrationLogging = true the next test methods started to fail, then i did a fix for setting the flag back to false and after that i was able to execute successfully the failing test cases.**

### Declarations

Check these if you believe they are true

- [ X] The codebase is in a better state after this PR
- [ X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ X] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ X] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@QilongTang 

### FYIs
@alfredo-pozo

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
This is a screenshot of the tests executed **before** my fix (when the tests cases after migration were failing).
image

**Comment by RobertGlobant20** [comment]
This is a screenshot **after** my fix, and shows that all the tests cases are executed correctly.
image

**Comment by mjkkirschner** [comment]
nice work tracking this down.

**Comment by QilongTang** [comment]
Good job. LGTM

**Pull request merged**
