### PR TITLE
MAGN-8244 Remove support for Revit 2014

### PR DESCRIPTION
**Pull request by ikeough**
### Purpose

This PR addresses [MAGN-8244](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8244). 

### Declarations

The standard template declarations do not apply as this is a change to the installer.

### Reviewers

@sharadkjaiswal

### CODE REVIEW

**Comment by sharadkjaiswal** [comment]
LGTM

**Comment by ikeough** [comment]
@sharadkjaiswal A couple of remaining questions:

1.  Is anything additional required for the Wix project? It seems that the Wix project only harvests what is available in the build directories. If the Revit2014 assets are not there, the .msi will not have Revit2014. Is this correct? Is there more to do here?

**Comment by sharadkjaiswal** [comment]
I think that's correct. Harvesting is done based on createInstaller batch file. BTW there is a wix project at our internal git repo.

**Comment by ikeough** [comment]
@sharadkjaiswal is the one in the public repo dead then? It seems like that one makes Dynamo core. But we don't ever use an .msi for core. I'll take a look at the internal one and edit it as well if there are Revit 2014 specific references.

**Pull request merged**
