### PR TITLE
MAGN-8832 Fix Dynamo API Documentation header text on mobile

### PR DESCRIPTION
**Pull request by ramramps**
### Purpose

The purpose of this PR is to improve Dynamo API Documentation site (esp. with mobile / ipad) . As part of this PR, media queries were added to css. While fixing the CSS, the other task to change the hover color is also fixed.

Link : http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8832
Link : http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8776

### Testing
 The changes are published to http://ramramps.github.io/DynamoAPI/. You can go to chrome and press Ctrl + Shift + M and test against the devices. 

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@ikeough 
@Racel

### CODE REVIEW

**Comment by Racel** [comment]
@ramramps - I checked the code, and it looked fine. But, the media queries do not seem to be working on desktop when the width of the window is resized. See image below. Can you take a look?
screen shot 2015-10-15 at 5 43 53 pm

**Comment by Racel** [comment]
@ramramps - everything looks good to me. You can merge whenever you and @ikeough are ready.

**Comment by ramramps** [comment]
@ikeough - Can you please check this one  too?

**Comment by ramramps** [comment]
@ikeough  - published the latest version to 
http://ramramps.github.io/DynamoAPI

**Comment by ramramps** [comment]
@ikeough  - published the latest version to 
http://ramramps.github.io/DynamoAPI.  Can you please check now?

**Comment by ikeough** [comment]
@ramramps LGTM.

There are a number of mobile formatting issues, but we'll track those separately. The title text looks good.

**Pull request merged**
