### PR TITLE
[DYN-5916] Move workspace reference extension code from code-behind to extension class

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

Moving the code for better accessibility.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Comment by zeusongit** [comment]
> I find it hard to spot the actual difference in the code here besides just moving the methods around - can you point out what actually changed to accomplish the task?
> 
> Since I can't spot that code I can't give concrete advice - but my general thinking is that it would be nice if there was an API the migration extension could call to disable the workspace references view from showing while doing it's work, and then reset that pref after.
> 
> Something like:
> 
> WorkspaceRefs.Settings.ReactToWorkspaceChanged= false; //do migration work WorkspaceRefs.Settings.ReactToWorkspaceChanged= true;
> 
> IE, it's still a useful feature for users to see the workspace refs when opening graphs.

Yes, nothing changed, except I moved the code to the view extension class, so that it will be accessible via Dynamo view model. This is still a **WIP**. 
JohnP is using this command to open graphs: https://github.com/DynamoDS/DynamoGraphMigrationAssistant/blob/64229732cfdaf8eb5a3187ba696a70143fce5f10/DynamoGraphMigrationAssistantViewExtension/ViewModels/GraphMigrationAssistantViewModel.cs#LL977C21-L977C21
That is directly accessible via DynamoViewModel, which means he can also access the extension class, where I will be adding the pref setting.

**Comment by zeusongit** [comment]
> The fact that view extension authors need to rely on this hack: https://github.com/DynamoDS/DynamoGraphMigrationAssistant/blob/64229732cfdaf8eb5a3187ba696a70143fce5f10/DynamoGraphMigrationAssistantViewExtension/ViewModels/GraphMigrationAssistantViewModel.cs#L331
> 
> is a bummer, I would not add more dependencies on accessing the DynamoViewModel directly, instead expand the extension and view extension APIs to achieve what they need.
> 
> DynamoViewModel is only accessible to view extensions because of WPF - it's a mistake, not a design.

Got it, thanks for the insights, will proceed accordingly.

**Comment by zeusongit** [comment]
I have a question, following up on slack.

**Comment by aparajit-pratap** [comment]
How about adding a new API to `ViewLoadedParams` in which you get a hold of the dynamoView.viewextensionanager, then get all the view extensions that are loaded, then filter them by name or ID. So the API can look like:
```
class ViewLoadedParams
{
...
IViewExtension GetExtensionByName(string name);
}
```

**Comment by QilongTang** [comment]
> How about adding a new API to `ViewLoadedParams` in which you get a hold of the `dynamoView.viewextensionanager`, then get all the view extensions from the manager that are loaded, then filter them by name or ID. So the API can look like:
> 
> ```
> class ViewLoadedParams
> {
> ...
> IViewExtension GetExtensionByName(string name);
> }
> ```

Yeah @aparajit-pratap That makes sense, we discussed it. Then we need to add generic disable or enable API on extension level unless we introduce dependency so Graph migration assistant knows what API to call on Workspace References ViewEX.

**Comment by QilongTang** [comment]
@aparajit-pratap @zeusongit @mjkkirschner @reddyashish As we discussed, let's move on. This PR will only be about code refactor on the Workspace References View EX. More granular framework to be implemented in another SPIKE as follow up

**Pull request merged**
