### PR TITLE
Dynamo Manipulator implementation

### PR DESCRIPTION
**Pull request by sharadkjaiswal**
### Purpose

This submission introduces Direct Manipulation feature in Dynamo. Using this feature users can now manipulate some of the geometry in 3D view and eventually update the graph automatically.

**Point Manipulators:**
- A point can be manipulated with the help of Gizmo created at the position of the point. 
image
- Based on the degree of freedom of the point axis of the Gizmo is shown. e.g. If `x` and `y` input are same for the point then point can be manipulated along `x=y` line only in the `xy plane` however, it can also be manipulated in `z` axis if it's unconstrained.
- The points that can be manipulated are shown in `red`. When such a point is selected, the appropriate gizmo is shown.
- The gizmo can be moved along an axis as well as along a plane.
- Points created using `Point.ByCoordinates` and `Curve.PointAtParameter` nodes can now be manipulated. 

**Direct Manipulation Framework:**

- `DynamoManipulationExtension` implements `IViewExtension` interface and provides the entry point of the Dynamo Manipulator framework. It receives view specific event notification and subsequently controls the lifetime of manipulators as well as delegates mouse event to the manipulators.
- The interface `INodeManipulatorFactoryLoader` is defined to initialize the list of manipulator factories based on node type.
- The interface `INodeManipulatorFactory` is defined to create a set of manipulators for the given node.
- The interface `INodeManipulator` represents a manipulator for a given node type.
- The interface `IGizmo` represents visuals of the manipulator and provide hit test as well as mouse move offset calculations.
- The abstract class `NodeManipulator` implements interface `INodeManipulator`. This class provides the basic framework for mouse event handling and updating the input nodes due to manipulation. The derived class implements logic for assigning and updating the input nodes, the creation of gizmos, handling gizmo click and move events, updating gizmo positions, etc.
- `MousePointManipulator` and `PointOnCurveManipulator` are two concrete implementation of `NodeManipulator` class.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.

### Reviewers

- [ ] @ikeough
- [ ] @aparajit-pratap

### CODE REVIEW

**Comment by mjkkirschner** [comment]
cool!

**Comment by aparajit-pratap** [comment]
@sharadkjaiswal I am assuming this is just moving the code from DynamoStudio to Dynamo open source. If that's the case, I think most of it is already reviewed?

**Comment by ikeough** [comment]
@sharadkjaiswal, I agree with @aparajit-pratap. If this has already been reviewed, and this is solely to move this code into this repo, then LGTM.

**Comment by sharadkjaiswal** [comment]
@ikeough yes we need to put some thought into writing some tests, and we are working on a test framework for this.

**Pull request merged**
