### PR TITLE
Turning on Preview Bubble for Rest of Revit Selection Nodes

### PR DESCRIPTION
**Pull request by Racel**
### Purpose

In a previous PR, only the "All Elements of" Selection nodes had their
Preview Bubbles turned on. This turns the Preview Bubble on  for the
remaining Selection nodes. Once merged, this will need to be cherry-picked into 1.2.3 RC.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner  @QilongTang 

### FYIs

@jnealb @kronz 

image

### CODE REVIEW

**Comment by QilongTang** [comment]
@Racel It seems this change will turn on preview bubble on all of the selection nodes in Dynamo. Did you recall why we disabled this way from begining? I'm just concerned there is some initial assumption we are breaking here.
FYI: @mjkkirschner

**Comment by Racel** [comment]
@QilongTang - I'm not sure. That was before my time. What are the other selection nodes that are not part of Revit selection? I checked those and they looked fine.

**Comment by QilongTang** [comment]
@Racel I went through the current library briefly and did not found any node with drop down list, if you know any of those and they look fine. Then we should call this switch-on safe. I do not see anything preventing us merging this one. LGTM.

**Comment by Racel** [comment]
@QilongTang - I found some Units nodes and the ObjectFilter node. But, I think it is ok if they show their preview bubble. Please merge if you think it is ok.

**Comment by QilongTang** [comment]
I think some of the nodes like unit conversion node already has the preview bubble on even before your change. They are under different node categories. I think this change is fine. Merging.

image

**Comment by QilongTang** [comment]
@Racel Please cherry-pick this to RC1.2.3 branch as well.

**Comment by kronz** [comment]
Hurray!  Thanks @Racel

**Pull request merged**
