### PR TITLE
[DUI] Imported dlls are missing description even though the source has the descriptions

### PR DESCRIPTION
**Pull request by aosyatnik**
I've been thinking... It seems I found workaround.

Reviewers
@Benglin , what do you think?

Link to YouTrack:
[MAGN-6577](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6577) [DUI] Imported dlls are missing description even though the source has the descriptions

### CODE REVIEW

**Comment by Benglin** [comment]
Thanks for the proposal, @aosyatnik! I would recommend @ramramps to help reviewing this as he may have more understanding of the original issue than I have. @ramramps, over to you, thanks! :)

**Comment by ramramps** [comment]
Thanks Anna. When you reverted the change, I remember you had removed certain tests. 
Do you think we need to have those tests around?  
I am OK with this change - I tested your branch and the search looks good.  
@Benglin - If this does not require any tests, then LGTM !

**Comment by aosyatnik** [comment]
@ramramps , I think you are right... I added test for constructor.

**Comment by Benglin** [comment]
Thanks for helping with the review, @ramramps, and @aosyatnik for fixing this :)

**Pull request merged**
