### PR TITLE
OOTB Samples Updates

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Updates to Dynamo OOTB samples per Dynamo visual refresh effort.

Examples:
image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Update Dynamo OOTB samples

### FYIs

@DynamoDS/dynamo

### CODE REVIEW

**Comment by saintentropy** [comment]
@QilongTang Are you adding thumbnails and descriptions to the files

**Comment by QilongTang** [comment]
> @QilongTang Are you adding thumbnails and descriptions to the files

I dont mean to, if there is a need, we can

**Comment by saintentropy** [comment]
@QilongTang it is something we are talking about with all the player samples as that UI is now very visible

**Comment by QilongTang** [comment]
@ZiyunShang I am updating the OOTB Dynamo samples, once you feel comfortable, would you update the DynamoRevit ones as well?

**Review by mjkkirschner — APPROVED** [review]
looks ok to me

**Comment by QilongTang** [comment]
> looks ok to me, except for the test failures.

Thanks, mostly just moving nodes around so they do not overlap and add graph author as Dynamo Team. Merging.

**Comment by QilongTang** [comment]
Oops, three regressions reported 
```
Test Result (3 failures / +3)
Dynamo.Tests.WorkspaceOpeningTests.ManipulatingWorkspaceDoesNotAffectZoom
Dynamo.Tests.WorkspaceOpeningTests.OpeningWorkspaceSetsPosition
Dynamo.Tests.WorkspaceOpeningTests.OpeningWorkspaceSetsZoom
```
These could be related to zoom level, I will take a look

**Comment by ZiyunShang** [comment]
> @ZiyunShang I am updating the OOTB Dynamo samples, once you feel comfortable, would you update the DynamoRevit ones as well?

Hi @QilongTang , do I just need to open the existing DynamoRevit Sample file with the new Dynamo and save it as the latest version? Can I do this in this PR, or do I submit a new PR to Dynamo myself?

**Comment by QilongTang** [comment]
> > @ZiyunShang I am updating the OOTB Dynamo samples, once you feel comfortable, would you update the DynamoRevit ones as well?
> 
> Hi @QilongTang , do I just need to open the existing DynamoRevit Sample file with the new Dynamo and save it as the latest version? Can I do this in this PR, or do I submit a new PR to Dynamo myself?

Yes, please save it in latest DynamoRevit so the tracedata still preserved. Either new PR or part of this PR works, thannks!

**Comment by ZiyunShang** [comment]
> > > @ZiyunShang I am updating the OOTB Dynamo samples, once you feel comfortable, would you update the DynamoRevit ones as well?
> > 
> > 
> > Hi @QilongTang , do I just need to open the existing DynamoRevit Sample file with the new Dynamo and save it as the latest version? Can I do this in this PR, or do I submit a new PR to Dynamo myself?
> 
> Yes, please save it in latest DynamoRevit so the tracedata still preserved. Either new PR or part of this PR works, thannks!

OK, I will do it soon.

**Comment by ZiyunShang** [comment]
Hi @QilongTang , I have a PR here - https://github.com/DynamoDS/Dynamo/pull/12315 , it upgrade 10 files in Revit folder. Is that OK? Can you review it?

**Pull request merged**
