### PR TITLE
DYN-5923: Remove unnecesary configurations from solutions

### PR DESCRIPTION
**Pull request by Cristhian-Marin-asdk**
### Purpose

To remove unnecesary configurations in solutions

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

- DynamoCore.net6.sln: remove any other configuration but 'NET60_Windows' and 'NET60_Linux' configurations 
- Dynamo.All.sln: remove any other configuration but 'Any CPU'

### CODE REVIEW

**Review by JimmySanchezGlobant — APPROVED** [review]
LGTM.

**Comment by mjkkirschner** [comment]
sorry @Cristhian-Marin-asdk I created some conflicts here though I think I did the same thing in my PR, can you check if I missed something?

**Comment by Cristhian-Marin-asdk** [comment]
> sorry @Cristhian-Marin-asdk I created some conflicts here though I think I did the same thing in my PR, can you check if I missed something?

everything seems to be fine, I only changed the Dynamo.All.sln file

**Comment by mjkkirschner** [comment]
@sm6srw @pinzart90 I've removed the last of the lingering x64 configs in the net48 all solution - PTAL.

**Comment by mjkkirschner** [comment]
@pinzart90 I am closing this PR in favor of your https://github.com/DynamoDS/Dynamo/pull/14221

**Pull request closed without merging**
