### PR TITLE
fix code block when code statement is only comments

### PR DESCRIPTION
**Pull request by iAliJ**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Fix an error in code block as shown in #10847.

The expected behavior is when only comments are left in a code block all the inputs and output ports should be removed as seen below.

ezgif-2-9e2e1d9f7f7b

I ran CodeBlockNodeTests after these changes.

Dynamo tests

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers
@Amoursol 
@QilongTang

### CODE REVIEW

**Comment by iAliJ** [comment]
> 
> 
> > > @iAliJ Oh I saw there are some build errors. I noticed that you removed those files instead reverting the changes. I would like to inform you that deleting the file in Github term does not mean delete such change in your PR. Most likely you will need to bring those files back by reverting some of you changes and touch the files again. Sorry about the inconvenience.
> > 
> > 
> > Sorry my bad, do you mind telling me how to revert the changes.
> 
> @iAliJ I think you can use the following commands to revert changes to these files:
> 
> ```
> git checkout -- src/AssemblySharedInfoGenerator/AssemblySharedInfo.cs
> git checkout -- test/DynamoCoreTests/DynamoCoreTests.csproj
> ```
> 
> and then push again.

Thanks, how about getting back the deleted files.
I need to get them back then checkout?

**Comment by iAliJ** [comment]
I restored the files, all the checks have passed now, I apologize for all the miss going on 😀

**Comment by QilongTang** [comment]
> I restored the files, all the checks have passed now, I apologize for all the miss going on 😀

Thanks, now if you dont mind, would you revert those changes unintended? You can use VisualStudioCode or any text editor to open those files locally and revert those. If you use Visual Studio to do it, you will need to unload the project before editing it.

**Comment by iAliJ** [comment]
> 
> 
> > I restored the files, all the checks have passed now, I apologize for all the miss going on 😀
> 
> Thanks, now if you dont mind, would you revert those changes unintended? You can use VisualStudioCode or any text editor to open those files locally and revert those. If you use Visual Studio to do it, you will need to unload the project before editing it. Once that is done, I think this PR is good to go 👍🏻

Done that, hope all are fine now.
For my future reference, I have to always revert back those files to origin?

**Comment by QilongTang** [comment]
> > > I restored the files, all the checks have passed now, I apologize for all the miss going on 😀
> > 
> > 
> > Thanks, now if you dont mind, would you revert those changes unintended? You can use VisualStudioCode or any text editor to open those files locally and revert those. If you use Visual Studio to do it, you will need to unload the project before editing it. Once that is done, I think this PR is good to go 👍🏻
> 
> Done that, hope all are fine now.
> For my future reference, I have to always revert back those files to origin?

Hi, unless intended, we usually do not touch csproj files. There has been cases that new settings added by user with newer version of Visual Studio does not really work for those with older version of VS. Changes in AssemblySharedInfo.cs are version number based on date the build was generated so we also usually leave it not committed. Hope it make sense to you!

**Review by QilongTang — APPROVED** [review]

**Comment by iAliJ** [comment]
@QilongTang Can #10847 be closed too?

**Pull request merged**
