### PR TITLE
Global Context Menu Styling

### PR DESCRIPTION
**Pull request by OliverEGreen**
### Purpose

This PR centralises all context menu styling to a single style (except the NodeView, which has special requirements).
The `ContextMenuStyle` in `DynamoModern.xaml` contains a single style for `MenuItems` and `Separators`.

The following context menus were found in Dynamo and updated: 

- Node Context Menu (with customisations)
- Groups Context Menu
- Workspace Context Menu
- Watch 3D Node Context Menu
- Pin Context Menu
- Note Context Menu
- Package Manager Search Sort Menu
- Package Manager Search Filter Menu

eLtVUfMbS0

Note: This PR also fixes some minor annoying behaviour where a submenu appears to the left, instead of the right. 

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Updates global context menu styling.

### Reviewers

@QilongTang 

### FYIs

@Amoursol
@SHKnudsen

### CODE REVIEW

**Comment by Amoursol** [comment]
@QilongTang @mjkkirschner - Do you think there are any other context menus out there that wouldn't be caught in a search for <ContextMenu> tags?

**Comment by OliverEGreen** [comment]
> @QilongTang @mjkkirschner - Do you think there are any other context menus out there that wouldn't be caught in a search for tags?

I also searched for "new ContextMenu" btw :)

**Comment by reddyashish** [comment]
Dynamo console also a context menu, not sure if we are using the default windows menu for that.

**Review by reddyashish — APPROVED** [review]
Looks good to me and nice that you have unified all of it. @QilongTang @mjkkirschner tagging you to make sure we are not missing any other context menus.

**Comment by QilongTang** [comment]
I think there is a context menu in geometry view (refer to the switch between graph/geometry in upper right corner)?

**Comment by reddyashish** [comment]
Yeah verified that the geometry view context menu is also addressed here

Screen Shot 2021-12-08 at 9 55 06 AM

.

**Comment by QilongTang** [comment]
Thanks @reddyashish @OliverEGreen Then, once the conflicts are done, let's move this forward

**Comment by QilongTang** [comment]
@reddyashish @OliverEGreen All self CI passed, merging

**Pull request merged**
