### PR TITLE
DYN-5322 Update ML NodeAutocomplete Documentation

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Update ML NodeAutocomplete Documentation
I updated the NodeAutocompleteDcoumentation.html to match the docx document attached to the Jira task. For the GIFs/PNG updated I did the next actions:
- Modified the original images resolution to 450 x XXX (according to the aspect ratio).
- Compressed the modified image/GIF so it will use the minimum size in the html file when converted to Base 64 (otherwise the WebView2 component was crashing).
- Convert the Image/GIF to Base64 content and put it in the HTML file.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Update ML NodeAutocomplete Documentation

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
This is a GIF showing the Documentation updated.
DocMLNodeAutocomplete (1)

**Review by reddyashish — APPROVED** [review]

**Comment by QilongTang** [comment]
This looks good, @RobertGlobant20 can you hook this up to the preferences panel? There was a question mark with hover over tooltip of Learn More about NodeAutoComplete, but clicking on it does not show this doc

**Comment by RobertGlobant20** [comment]
GIF showing that after clicking the question mark symbol in the Preferences panel the documentation will be opened.
Preferen esDocMLNodeAutocomplete

**Comment by RobertGlobant20** [comment]
> This looks good, @RobertGlobant20 can you hook this up to the preferences panel? There was a question mark with hover over tooltip of Learn More about NodeAutoComplete, but clicking on it does not show this doc

@QilongTang fixed in the next commit: https://github.com/DynamoDS/Dynamo/pull/13602/commits/bb1eb9ae7ec28298afbbac0f5cbca0bc392d8be9

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
