### PR TITLE
Commit .npmrc file to the Notifications project.

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

When you build Dynamo locally from the source repo while connected to VPN, the build fails during npm install in notifications project. It builds fine when you are not on VPN. 

@aparajit-pratap pointed out that if we have the .npmrc file in the notifications project, Dynamo builds fine on VPN. Committing the .npmrc file to the repo. Tested it locally. 

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes
Commit .npmrc file to the Notifications project.

### Reviewers
@QilongTang @aparajit-pratap 

### FYIs
@DynamoDS/dynamo

### CODE REVIEW

**Comment by QilongTang** [comment]
But this would time out still when not connecting to VPN right? I think we tried this in the past for librarie.js and we can't win in both cases :(

**Review by aparajit-pratap — APPROVED** [review]

**Comment by QilongTang** [comment]
As you can see the Github action build failed right away @aparajit-pratap @reddyashish

**Comment by reddyashish** [comment]
@QilongTang builds fine for me when I am not connected to VPN. Can you verify again?

**Comment by avidit** [comment]
> @QilongTang builds fine for me when I am not connected to VPN. Can you verify again?

@reddyashish can please you clean npm cache and try again?

**Comment by QilongTang** [comment]
Here is the error log
```
NpmRunBuild:
  npm install --prefix ./ @dynamods/notifications-center@latest
  npm ERR! code ENOTFOUND
  npm ERR! syscall getaddrinfo
  npm ERR! errno ENOTFOUND
  npm ERR! network request to https://art-bobcat.autodesk.com/artifactory/api/npm/autodesk-npm-virtual/@dynamods%2fnotifications-center failed, reason: getaddrinfo ENOTFOUND art-bobcat.autodesk.com
  npm ERR! network This is a problem related to network connectivity.
  npm ERR! network In most cases you are behind a proxy or have bad network settings.
  npm ERR! network 
  npm ERR! network If you are behind a proxy, please make sure that the
  npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\Users\runneradmin\AppData\Local\npm-cache\_logs\2022-08-25T20_45_33_362Z-debug-0.log
```
I am pretty sure we have run into exactly the same issue before, I dont think ADSK npmrc would work for clean machine not connected to VPN

**Comment by reddyashish** [comment]
Thanks @QilongTang. I missed it during the first time. My understanding was, we need to connect to VPN to download the dependencies for the first time but when you have the dependencies downloaded already, it should build fine when you are on VPN or not. 
Even though I have the dependencies in node_modules, build fails when connect to VPN without this change. 

Since we cannot resolve both ends now, converting this into a draft.

**Pull request closed without merging**
