### PR TITLE
DYN-7720. Add Help file documentation for Mesh Nodes from Meshtoolkit

### PR DESCRIPTION
**Pull request by saintentropy**
### Purpose

Documentation files are included for the new Mesh Nodes.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Documentation files are included for the new Mesh Nodes.

### Reviewers

@LongNguyenP 

### FYIs

@Amoursol

### CODE REVIEW

**Comment by QilongTang** [comment]
My only concern is about all these geometry nodes' name lengths. I think sometime ago, @sm6srw had to convert long named files to be in hashed value. I forgot if C3D team or Revit team documented a limitation somewhere but I would encourage us using hashed value when we can.

**Comment by saintentropy** [comment]
@QilongTang not sure what the limit is...  Currently the longest Mesh file `Autodesk.DesignScript.Geometry.Mesh.Translate(mesh.vector.distance)_img.jpg` is shorter then other geometry help files like `Autodesk.DesignScript.Geometry.TSpline.TSplineSurface.BySphereBestFit_img.jpg` and `Autodesk.DesignScript.Geometry.PanelSurface.ByCustomOrthogonalLattice_img.jpg`.

**Comment by saintentropy** [comment]
@QilongTang I can't find the number yet that we convert files to hashed values.  Since we are not longer then others I will merge and add this for follow up

**Comment by johnpierson** [comment]
> @QilongTang not sure what the limit is... Currently the longest Mesh file `Autodesk.DesignScript.Geometry.Mesh.Translate(mesh.vector.distance)_img.jpg` is shorter then other geometry help files like `Autodesk.DesignScript.Geometry.TSpline.TSplineSurface.BySphereBestFit_img.jpg` and `Autodesk.DesignScript.Geometry.PanelSurface.ByCustomOrthogonalLattice_img.jpg`.

I wanted to add to this that right now we are building automations for checking these files and they currently need to follow naming of the DYN. So the `.` in the parentheses in these examples is causing a few issues at this time.

`Autodesk.DesignScript.Geometry.Mesh.Translate(mesh.vector.distance)_img.jpg` should read as ``Autodesk.DesignScript.Geometry.Mesh.Translate(mesh, vector, distance)_img.jpg`.

But if we were to use hashed values, we need to account for that in our automation as well. 🤔

**Pull request merged**
