### PR TITLE
Default category for custom nodes

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-7648](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7648) DYF/DYN fails to open from recent file list for the second time

I've added new default category name in resources. Now if we load uncategorized node, it will be loaded as member of "Custom nodes" category.

Result:
image

Is it appropriate default category name?

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] The level of testing this PR includes is appropriate

### Reviewers

@pboyer 
@Benglin 

### FYIs

@kronz 
@monikaprabhu

### CODE REVIEW

**Comment by Benglin** [comment]
Thanks for the fix, @aosyatnik. Does that mean any loaded custom nodes that are not categorized will be saved as `Custom nodes` category? I suppose that is okay thing to do, what say @kronz and @riteshchandawar?

**Comment by kronz** [comment]
@aosyatnik @Benglin You can't actually create a custom node without a category currently.  In what situations would this become apparent?

**Comment by aosyatnik** [comment]
Hi, @kronz , this bug has been fixed not so long ago. [MAGN-7311](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7311) Create Custom node throws exception if Category is not entered
And users had opportunity to create node without category. Now they don't have. But they can open custom node file in Notepad and remove category manually.

**Comment by kronz** [comment]
@aosyatnik if users manually edit the files in notepad, that is definitely something where the "expected" behavior will be bad.  It's like trying to make sure a car has a smooth ride even if the driver replaces the tires with home-made plywood discs that they bolt on themselves :)  Sounds like we need to focus on making sure they can't make a Custom node without category, and I think having a default category just in case something goes wrong is just fine.

**Comment by aosyatnik** [comment]
@Benglin , if everything is ok, could you please merge it? And PR for 0.8.1? Thanks!

**Comment by pboyer** [comment]
Merging this in so we can get the testing story started.

**Comment by Benglin** [comment]
Thanks @aosyatnik and @pbidenko.

**Comment by RodRecker** [comment]
@Benglin @aosyatnik Do we have this in 0.8.1?

**Comment by aosyatnik** [comment]
@RodRecker , Yes!

**Pull request merged**
