### PR TITLE
Update Package Manager Client (Greg) version

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

Update Package Manager Client (Greg) version

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Update Package Manager Client (Greg) version

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by QilongTang** [comment]
@zeusongit Is there a way to find the different feature set between the greg versions?

**Comment by mjkkirschner** [comment]
@zeusongit maybe we should revert to the /3 hour single hour digit version scheme first?

**Comment by zeusongit** [comment]
> @zeusongit Is there a way to find the different feature set between the greg versions?

@QilongTang this is the diff
Screen Shot 2022-06-14 at 2 33 35 PM

**Comment by zeusongit** [comment]
> @zeusongit maybe we should revert to the /3 hour single hour digit version scheme for greg.dll first?

Sure, https://github.com/DynamoDS/PackageManagerClient/pull/71

**Review by QilongTang — APPROVED** [review]

**Comment by mjkkirschner** [comment]
so we should wait until 2.3 is referenced - yes?

**Comment by zeusongit** [comment]
Yes, indeed @mjkkirschner

**Comment by QilongTang** [comment]
@zeusongit Do we need to cherry-pick this?

**Pull request merged**
