### PR TITLE
ProtoInterface library cleanup

### PR DESCRIPTION
**Pull request by sharadkjaiswal**
### Purpose

This PR moves the `ProtoInterface` project from LibG to Dynamo core, so that it can be maintained as Dynamo Core library. All the geometry related interfaces are removed from this implementation and will be moved to `LibGInterface` library at LibG.

This is to address: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6615

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.

### Reviewers

- [ ] @Benglin 
- [ ] @Randy-Ma 

### FYIs
@aparajit-pratap 
@ikeough 
@ke-yu

### CODE REVIEW

**Comment by ikeough** [comment]
:+1:

**Comment by ke-yu** [comment]
I LOVE IT!

**Comment by mjkkirschner** [comment]
@sharadkjaiswal is this associated with task? If not can we link it to one?

**Comment by sharadkjaiswal** [comment]
https://github.com/DynamoDS/Dynamo/pull/6296 Kills ProtoInterface and moves all the interfaces and attributes to DynamoServices, just to keep one zero touch API library.

**Pull request closed without merging**
