### PR TITLE
MAGN-6384 Graph is incorrectly zoomed when reloading its dyn after panning it

### PR DESCRIPTION
**Pull request by ikeough**
This PR addresses [MAGN-6384](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6384). 

When the workspace constructor's signature was changed during refactoring, it did not honor the "zoom" property saved in the .dyn. This PR sets the zoom property during loading of .dyns to ensure that the zoom is honored.

PTAL:
- [ ] @ramramps 

FYI:
@jnealb

### CODE REVIEW

**Comment by ikeough** [comment]
@ramramps ping!

**Comment by jnealb** [comment]
@ikeough @ramramps We also have reports of "vanishing" dyn loads (7.5 loaded into 7.6, for example) i.e. neither pan nor zoom can bring them into view. Could the zoom property be the root cause?

**Comment by ramramps** [comment]
@ikeough - This works fine if the panning is not made on any node
You open a graph, click the pan and then click on any of the node /note and drag the graph. Now close the workspace and open the same graph, and you see the Zoomissue. This is because, DynamoSelection.Instance.Selection is not cleared when the workspace is closed. This causes the problem in FitViewInternal function.

**Comment by ikeough** [comment]
I've removed the fit to view so that it doesn't screen with the zoom factor saved in the file. Perhaps @Benglin could make an argument for why we need it. I've also added clearing of the selection when clearing the workspace, just to be sure.

**Comment by jnealb** [comment]
@ikeough @ramramps @Benglin @RodRecker @sharadkjaiswal Can we pull this across the finish line for Inga?

**Comment by ramramps** [comment]
@ikeough 
Well, this solves the problem with zoom. I am good with this.

**Comment by Benglin** [comment]
@ikeough, @jnealb the fit view code was meant to fix the following defect, as long as it stays fixed, this look good:

MAGN-5745 Geometry samples can load with definitions off of the screen

**Pull request merged**
