### PR TITLE
Data Manager: Object.Type node.

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-8183](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8183) Provide a method to extract the type of an object

Results:
image

### Declarations

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@lukechurch 

### FYIs

@mccrone

### CODE REVIEW

**Comment by sharadkjaiswal** [comment]
@aosyatnik Can you please test this by passing a FunctionObject, i.e a node without any input?

**Comment by aosyatnik** [comment]
Hi, @sharadkjaiswal , did you mean to test it in Dynamo or write test case?

If we leave input port blank, then we get next result:
image

**Comment by mccrone** [comment]
Nice!

**Comment by mjkkirschner** [comment]
@aosyatnik what happens if you try this on a dynamic object like a python object?

**Comment by aosyatnik** [comment]
I tried Formula (node in scripting class).
image

I don't know how python node works, I tried empty python node:
image

**Comment by mjkkirschner** [comment]
@aosyatnik Hi It looks pretty good :), 
but I wanted to have some discussion first - @lukechurch feel free to chime in. 

comments:

1: I think we should have an icon for this node, @Racel do this task require that?
2: Right now since the input is an object we replicate over lists... thats kind of strange and results in things like this:

screen shot 2015-09-03 at 11 38 40 am

I would expect, and I think our users would expect that we would get a List or arrayList of some kind as the result. I think you can use [ArbitraryDimensionArrayImport] on the input parameter.

3.I think putting a null check for the object and providing a nice message is better than the operation failed exception.

**Comment by mccrone** [comment]
If we did not replicate over lists, then the result of this node will almost always be "list," no?

**Comment by mjkkirschner** [comment]
that's correct, unless it is mapped or replicated using a code block. 
another solution... is a node that checks if an object is a list...

**Comment by mccrone** [comment]
Maybe there should be another node for that then.  Otherwise, this node would not quite satisfy it's epic: "improving list manipulation tools"

**Comment by mccrone** [comment]
It could go well with the nodes already there:
Object.isNull
Object.isList

**Comment by mjkkirschner** [comment]
@mccrone thanks for the clarification, I think thats another worthwhile task, but like you said, let's leave the functionality of this as it is: @aosyatnik please disregard point 2.

**Comment by Racel** [comment]
@mjkkirschner-there is already a task for creating all the new list management icons. i can work on that tomorrow. MAGN-8314

**Comment by aosyatnik** [comment]
@mjkkirschner , I added error message to Resource file.
image

**Comment by mjkkirschner** [comment]
Thanks @aosyatnik  LGTM!

**Pull request merged**
