### PR TITLE
Continuously trigger Node AutoComplete

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Continuously trigger Node AutoComplete on all ports available on Dynamo graph.
ContinuousNodeAutoComplete

Update: Addressed comments to make sure search field focus is setup correctly everytime feature gets triggered

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@DynamoDS/dynamo 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by zeusongit — APPROVED** [review]
LGTM

**Comment by reddyashish** [comment]
@QilongTang I noticed that when you trigger the autocompletion switch to another port, the focus is not being set on the search bar. The focus is being set only for the first time when the window is opened.

**Comment by QilongTang** [comment]
> @QilongTang I noticed that when you trigger the autocompletion switch to another port, the focus is not being set on the search bar. The focus is being set only for the first time when the window is opened.

Any idea how I can keep the focus there.

**Comment by reddyashish** [comment]
SearchTextBox.Focus() should have been called. I think this is being called before the autocompletion candidates are being populated.

**Comment by QilongTang** [comment]
> SearchTextBox.Focus() should have been called from here: https://github.com/DynamoDS/Dynamo/pull/11755/files#diff-53da72c0cb9017a75bf93dd30e45f5f7b867e15b0b01e33958315898c6bc3a54R140. I think this is being called before the autocompletion candidates are populated.

Oh I see.. In this case, `OnNodeAutoCompleteSearchControlVisibilityChanged` is not called since what we are doing here is hide and show again.. I will look further

**Comment by QilongTang** [comment]
@reddyashish @zeusongit I have addressed the comments, PTAL

**Review by reddyashish — APPROVED** [review]
LGTM

**Pull request merged**
