### PR TITLE
Python Node Editor Visual Update

### PR DESCRIPTION
**Pull request by dnenov**
### Purpose

This PR ensures Python node's UI color and styling are set in such a way as to homogenize with new sidebar extension theming. For more information on the task, refer to the following [Figma](https://www.figma.com/file/1q7EWQGYO7pPDhyLf8nuwW/Python-node-editor-restyling?node-id=0%3A1&t=hza6p2ojgiYIgFqO-0) link.

This PR will be followed by further development and implementation of all the required changes and updates.

#### UI Before
before

#### UI After (with user interactions)
after

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

- overall theme update
- icons update
- icons hover interaction 
- tooltip update
- color scheme for highlight syntax update
- Escape key now closes the editor
- TODO: check for unsaved changes on 'esc'. Update: this is handled in a follow-up PR based on this one. 

### Reviewers

@sm6srw 
@Amoursol 

### FYIs

@Jingyi-Wen

### CODE REVIEW

**Comment by Amoursol** [comment]
@mjkkirschner - Are there any performance issues (I'm assuming so) of taking 32x32 pixel icons and scaling them down to 16 x 16 pixels in code? They do appear crisper than native 16 x 16 pixels, but we want to know at what cost, performance or otherwise. @dnenov is currently doing this process.

**Comment by dnenov** [comment]
> @mjkkirschner - Are there any performance issues (I'm assuming so) of taking 32x32 pixel icons and scaling them down to 16 x 16 pixels in code? They do appear crisper than native 16 x 16 pixels, but we want to know at what cost, performance or otherwise. @dnenov is currently doing this process.

I can confirm that this was an oversight on my part. The following PR contains the actual icons, which are in native 24x24px to be displayed in the same resolution. No up or down scaling will take place.

**Comment by sm6srw** [comment]
Any icon adjustments will be in the part 2 PR.

**Review by sm6srw — APPROVED** [review]
LGTM!

**Comment by dnenov** [comment]
> > @mjkkirschner - Are there any performance issues (I'm assuming so) of taking 32x32 pixel icons and scaling them down to 16 x 16 pixels in code? They do appear crisper than native 16 x 16 pixels, but we want to know at what cost, performance or otherwise. @dnenov is currently doing this process.
> 
> ~I can confirm that this was an oversight on my part. The following PR contains the actual icons, which are in native 24x24px to be displayed in the same resolution. No up or down scaling will take place.~
> 
> Actually, it looks like I wasn't building with the updated icons, so this issue is not resolved. Below is a test between two resources from Figma, one at 24x24px vs the other at 48x48px.


It was decided to keep the 48x48, this is done in https://github.com/DynamoDS/Dynamo/pull/13763

**Comment by chuongmep** [comment]
@ team, all people have felt red color is better ? Can we have any option to change color ? It looks like my eyes are a bit poor at the moment

**Comment by QilongTang** [comment]
> @ team, any people have felt red color is better ? Can we have any option to change color ? It looks like my eyes are a bit poor at the moment

Do you mean red color for `save and run`?

**Comment by dnenov** [comment]
> > @ team, any people have felt red color is better ? Can we have any option to change color ? It looks like my eyes are a bit poor at the moment
> 
> Do you mean red color for `save and run`?

Just to help out the conversation, this is what we are currently working towards:

image

The `save and run` color repeats the Dynamo `run `color.

**Comment by chuongmep** [comment]
> 
@QilongTang no, I mean is color of code.

**Comment by dnenov** [comment]
> > 
> 
> @QilongTang no, I mean is color of code.

Just as a reference, [this](https://github.com/DynamoDS/Dynamo/pull/13783) is the final PR part of this design effort, which deals exclusively with the color scheme of the reserved words. On our side it is @Amoursol and @Jingyi-Wen that should be able to shed more light on the decision about colors.

**Comment by chuongmep** [comment]
Thanks @dnenov for clearly information, I will look to this.

**Comment by Jingyi-Wen** [comment]
> > 
> 
> @QilongTang no, I mean is color of code.

Hi @chuongmep! Just to clarify - do you mean the keywords such as "import" and "from" should be red? The reason we are changing the color scheme is to have better contrast. The new pink-ish color does have a better contrast ratio,  compared to the previous red-ish dark pink.

**Comment by chuongmep** [comment]
> 
Hi @Jingyi-Wen, I not ignore that color is not good, just about combine color problem inside code, but I think a pull request for part 2 is to do that : https://github.com/DynamoDS/Dynamo/pull/13783,  this also is color i using every day in rider IDE

**Pull request merged**
