### PR TITLE
Disable MSWebBrowser library view drag and select Web elements

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Per [This Bug](https://jira.autodesk.com/browse/DYN-4097), this is a regression from CefSharp implementation of library. The drag and select was disabled there but enabled in MSWebBrowser based library. As a result, the bug was not really about scrolling but drag/select element with mouse move.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@DynamoDS/dynamo 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mjkkirschner** [comment]
If this change is made, and there are issues with our DPI/zooming script the library becomes unusable.

**Comment by QilongTang** [comment]
> If this change is made, and there are issues with our DPI/zooming script the library becomes unusable.

@mjkkirschner Is there a way to validate that case in your mind? Would be glad to test

**Comment by mjkkirschner** [comment]
> > If this change is made, and there are issues with our DPI/zooming script the library becomes unusable.
> 
> @mjkkirschner Is there a way to validate that case in your mind? Would be glad to test


for example, try increasing DPI to a large amount, I believe there are certain parts of the lib ui that do not get scaled by our script. It may be a non issue.

**Comment by QilongTang** [comment]
> > > If this change is made, and there are issues with our DPI/zooming script the library becomes unusable.
> > 
> > 
> > @mjkkirschner Is there a way to validate that case in your mind? Would be glad to test
> 
> for example, try increasing DPI to a large amount, I believe there are certain parts of the lib ui that do not get scaled by our script. It may be a non issue.

I did test DPI as high as 400 in a remove environment but that does not make a difference for my laptop. Also I cant seem to change DPI on my laptop, I will request a branch build and ask for help from QA

**Comment by mjkkirschner** [comment]
sounds good

**Review by zeusongit — APPROVED** [review]
LGTM. Tested in DynamoCoreRuntime_2.13.0.2595

**Pull request merged**
