### PR TITLE
DYN-6292 Upload artifact after build

### PR DESCRIPTION
**Pull request by avidit**
### Purpose

- Upload artifact after build.
- Another workflow will be added which will download this artifact and run tests.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
@avidit Would you document where would the action upload to?

**Comment by QilongTang** [comment]
@avidit LGTM just want to confirm this publish and store service is free for open source repo correct?

**Comment by mjkkirschner** [comment]
Why do we need this? Don't we already have builds of net6 master? How does this relate to test complete tests?

**Comment by avidit** [comment]
I will look into action cache option as well. As far as understand it is free service.

**Comment by avidit** [comment]
Updated PR 
- to add artifact retention for 3 days
- add repository dispatch event to trigger workflow in DynamoTestCompleteTests repo

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
