### PR TITLE
Issue - [DYN 4358] - Wire from collapsed nested group is hidden when collapsing/expanding parent group.

### PR DESCRIPTION
**Pull request by M-JULIANI**
### Description

This PR fixes the visibility of the wire of a collapsed nested group when parent group is collapsed/expanded.

_Fixed behaviour:_
Issue-Fix-GroupShow-WireOfCollapsedGroup

_Previous behaviour:_
nested_group_wire

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers
@QilongTang 

### FYIs
@SHKnudsen 
@Amoursol

### CODE REVIEW

**Comment by QilongTang** [comment]
@M-JULIANI We were talking about creating proxy ports for the output port in group b as well when parent group a collapsed. Would you look at it as well?

**Comment by SHKnudsen** [comment]
> @M-JULIANI We were talking about creating proxy ports for the output port in group b as well when parent group a collapsed. Would you look at it as well?

Hi @QilongTang just chiming in on this one, I think we will handle the extra proxy ports separate from this PR. I've already started that work but need some inputs from Ashish before it's ready, i have a chat with him tomorrow.

**Comment by QilongTang** [comment]
> > @M-JULIANI We were talking about creating proxy ports for the output port in group b as well when parent group a collapsed. Would you look at it as well?
> 
> Hi @QilongTang just chiming in on this one, I think we will handle the extra proxy ports separate from this PR. I've already started that work but need some inputs from Ashish before it's ready, i have a chat with him tomorrow.

Thanks for the clarification.

**Comment by M-JULIANI** [comment]
> @M-JULIANI Is it too much to ask for a unit test for this :)

Sure will add.

**Comment by M-JULIANI** [comment]
@QilongTang added unit tests asserting that the connectors coming out of nested group nodes are visible on parent group expand. If nested group is collapsed, they come out of the nested group proxy port and are visible. If the nested group is expanded, they are visible.

**Pull request merged**
