### PR TITLE
Upgrade NUnit from v2.6.2 to v2.6.3 to align with NuGet version

### PR DESCRIPTION
**Pull request by alfarok**
### Purpose

Related to:
[QNTM-4186](https://jira.autodesk.com/browse/QNTM-4186)
[D4R-2068](https://github.com/DynamoDS/DynamoRevit/pull/2068)
[RevitTestFramework-84](https://github.com/DynamoDS/RevitTestFramework/pull/84)

This PR removes replace NUnit framework v2.6.2 with v2.6.3.  It was discovered that the Dynamo Core NuGet package used by developers requires v2.6.3 even though v2.6.2 is used in Core.  This was causing issues with running unit tests that also referenced the Dynamo Core NuGet package (such as Dynamo Samples).  Ideally we would stop relying on the local dependency switching to the NUnit NuGet package, however this seems to have additional issues with the build machine and self-serve configurations.

`C:\..\Dynamo\extern\NUnit` v2.6.3 Updates:
- nunit.framework.dll
- nunit.framework.xml
- nunit-console-runner.dll
- nunit-gui-runner.dll
- nunit.core.dll
- nunit.core.interfaces.dll
- nunit.ui.exception.dll
- nunit.uikit.dll
- nunit.util.dll
- log4net.dll (no changes)

Removed: (unable to locate references to any of these in the code base)
- nunit.mocks.dll
- NSubstitute.dll
- NSubstitute.xml
- Rhino.Mocks.dll
- Rhino.Mocks.xml

### Testing
All tests in Dynamo Samples and the Dynamo self-serve CI are passing.
[Self-Serve CI Results](https://ecwest.autodesk.com/commander/link/jobDetails/jobs/3e2a309f-69a6-11e8-b641-a0d3c1eff5a4?)

image

image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 

### FYI

@smangarole

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@alfarok I don't think it's a good idea to mix different versions of nunit's dlls in this folder. If we are going to upgrade some of them to 2.6.3 we should update them all.

**Comment by alfarok** [comment]
@mjkkirschner After doing a quick audit of what is included in that `C:\..\Dynamo\extern\NUnit` folder:

2.6.3 NUnit NuGet:
- nunit.framework.dll
- nunit.framework.xml

2.6.3 NUnit.Runners NuGet:
- nunit.framework.dll (same as above)
- nunit.framework.xml (same as above)
- nunit-console-runner.dll
- nunit-gui-runner.dll
- nunit.core.dll
- nunit.core.interfaces.dll
- nunit.ui.exception.dll
- nunit.uikit.dll
- nunit.util.dll
- log4net.dll

Not Included:
- nunit.mocks.dll
- NSubstitute.dll
- NSubstitute.xml
- Rhino.Mocks.dll
- Rhino.Mocks.xml

It appears all the contents from the NUnit.Runners NuGet were manually copied into that folder.  I am still trying to determine how many of these files are actually required or used.  I am not sure where the items on the bottom were derived from yet.

**Comment by alfarok** [comment]
https://jira.autodesk.com/browse/QNTM-4440 for moving to NuGet in the future and working out self-serve/build machine issues.  I wasn't able to find any references in the code base to the excluded files listed above.  I am going to remove them and run the self-serve once more to make sure there are no issues.

**Comment by alfarok** [comment]
@mjkkirschner All tests still passing after removing the dependencies listed above

**Comment by alfarok** [comment]
@mjkkirschner I think these are all finally aligned and ready for review.  The only additional task is to update the version of NUnit on the build machine.

[DynamoCore-8914](https://github.com/DynamoDS/Dynamo/pull/8914)
[D4R-2068](https://github.com/DynamoDS/DynamoRevit/pull/2068)
[RevitTestFramework-84](https://github.com/DynamoDS/RevitTestFramework/pull/84)

**Pull request merged**
