### PR TITLE
DYN-7268 Package manager loading fix when no IDSDK is available

### PR DESCRIPTION
**Pull request by chubakueno**
### Purpose

When there's no IDSDK available, IDSDKManager.cs raises a `DynamoConsoleLogger.OnLogMessageToDynamoConsole`. This eventually ends up invoking a `HomePage.DynamoViewModel_PropertyChanged`. Issue arises when this process starts from a background thread, for example loading the list of packages: `PackageManagerSearchViewModel` starts a new `RefreshAndSearch` Task in the Thread Pool, which most likely won't be scheduled in the Main Thread.

Thus this commit safeguards `HomePage.DynamoViewModel_PropertyChanged` from accessing `dynWebView?.CoreWebView2` UI element from a background thread and raising an `Exception` by changing the shortcirtuited evaluation order and first checking the changed property is `ShowStartPage`, which currently only gets invoked from the Main Thread.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Fix dynamo package manager loading when there's no IDSDK installed.

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by mjkkirschner** [comment]
I think while this fix is efficient, it does not get to the root of the problem, others may recreate the same issue anywhere in the application - so while we have resolved this one crash, we have not helped improve the codebase or helped other devs avoid the issue or learn about it.

**Comment by chubakueno** [comment]
> I think while this fix is efficient, it does not get to the root of the problem, others may recreate the same issue anywhere in the application - so while we have resolved this one crash, we have not helped improve the codebase or helped other devs avoid the issue or learn about it. (I think a better solution is to dispatch the access check for the webview to the UI thread) - Perhaps even wrap the getter in our own util.

Yes issue would arise if any UI-interacting event handler is invoked from a background thread. `Dispatch.Invoke` will create a deadlock, so `Dispatch.BeginInvoke` is necessary, but this may create unexpected asynchronicity for the developer raising the event. We could guard this event handler in particular with `BeginInvoke` since it only affects `ShowStartPage`, but I think a general refactor of event handling/invocation would be needed to manage the general case.

**Review by RobertGlobant20 — APPROVED** [review]
LGTM

**Comment by avidit** [comment]
@QilongTang Can we merge this one. There is one failure but it looks unrelated, can you PTAL? https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16430/testReport/junit/Dynamo.Tests/ExcelTests/ReadChangeFilename/

**Pull request merged**
