### PR TITLE
Create What's New page for Topology

### PR DESCRIPTION
**Pull request by YanmengLi**
### Purpose

Reference: [MAGN-9385](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9385) create What's New page for Topology

screenshotwhatsnew

### Declarations

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.

### Reviewers

@Racel 

### FYIs

@sharadkjaiswal @riteshchandawar @kronz

### CODE REVIEW

**Comment by riteshchandawar** [comment]
@Racel Can you please review this PR.

Thanks,
Ritesh

**Comment by Racel** [comment]
@riteshchandawar @YanmengLi @kronz - Please remove the alphabetical text from the image (this will not work well for localization). Also, please change the description text so that is  1-2 sentences long explaining what the benefits are of the new improvements. Let me know if you want me to review the new sentence.

**Comment by riteshchandawar** [comment]
@Racel description looks ok to me. She has removed the text from Image.

-Ritesh

**Comment by Racel** [comment]
@YanmengLi @riteshchandawar - Let us work on fixing the description text together while I am in Singapore. The current description for this page deviates from the other pages and does not explain the customer benefit.

**Comment by Racel** [comment]
@YanmengLi @riteshchandawar - I worked with @aparajit-pratap on changing the description text. Can you please update it to:

Find adjacent geometries by using Dynamo's brand new nodes.  You will now be able determine which edges are connected to a vertex, which faces are connected to an edge, and if geometries have common topology.

Also, please don't forget to update the readme to include Topology improvements.

**Comment by YanmengLi** [comment]
#6061 I have created a new pull request. Thanks Racel.

**Pull request merged**
