### PR TITLE
DYN-5992: Project migrations

### PR DESCRIPTION
**Pull request by sm6srw**
### Purpose

This pull request migrate:
* LibraryViewExtensionWebView2
* GraphNodeManagerViewExtension
* PackageDetailsViewExtension
* LintingViewExtension
* GraphMetadataViewExtension
* NodeAutoCompleteViewExtension
* PythonMigrationViewExtension
* DocumentationBrowserViewExtension

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [X] This PR contains no files larger than 50 MB 

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@sm6srw some conflicts remain.

**Comment by mjkkirschner** [comment]
@sm6srw do you think this can mirror the structure of the existing sln and add the extensions into an extension solution subfolder? (Or does this already do that?) Maybe a viewExtensions one?

**Comment by sm6srw** [comment]
@mjkkirschner Let me check that. The sln was funky so I might need to move stuff around.

**Comment by sm6srw** [comment]
@mjkkirschner Looks like they show up in the same place as in the orig solution.

**Review by aparajit-pratap — APPROVED** [review]

**Comment by pinzart90** [comment]
@sm6srw could you also move over the net48 specific References into a net48 ItemGroup 
Example <Reference Include="PresentationCore" /> is not needed for net6 and it causes warnings.
We have very few Assembly References for net6 (as opposed to packagereferences) - only Microsoft.Xaml.Behaviors I think

**Comment by sm6srw** [comment]
@pinzart90 Will do...

**Review by pinzart90 — APPROVED** [review]

**Pull request merged**
