### PR TITLE
Remove migration popup

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

Remove migration popup as it's no longer needed.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I guess this would be useful if we started copying packages again between point versions of Dynamo as requested by some users - but at the moment if this is causing some timing bug I'm okay getting rid of it. I'd like to know the root cause though.

**Comment by QilongTang** [comment]
@aparajit-pratap @mjkkirschner @pinzart Can you remind the reason for removing the migration popup again? Our team also have a task to update the visuals

**Comment by aparajit-pratap** [comment]
> @aparajit-pratap @mjkkirschner @pinzart Can you remind the reason for removing the migration popup again? Dont we have to deal with legacy graph with IronPython node? Our team also have a task to update the visuals of it next sprint

@QilongTang the migration will continue to work and all that's being migrated in this case is the preference settings from a previous version to the current one. The only thing this removes is the popup UI that tells the user that settings are being migrated. As this is almost instantaneous I don't feel there's a need for the UI. Additionally, on my machine (and perhaps it could be experienced with others as well), in 2.14, for some reason, this UI is causing the freeze.

**Comment by QilongTang** [comment]
@aparajit-pratap @mjkkirschner I am still not sure why we commit to the removal of code without knowing the real cause? Our team had plan to look at the migration experience and enhance it in a way that users can point to a different location for preferences files. It seems we will have to start from stretch after this PR... Is there any kind of communication of this and what would it mean to customers?

**Pull request merged**
