### PR TITLE
Update library.min.js with library improvements

### PR DESCRIPTION
**Pull request by alvpickmans**
### Purpose
Update librarie.min.js file according to mock-up changes and PR https://github.com/DynamoDS/librarie.js/pull/167
dynamo-library

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes
Libraries.js design has been updated according to latest mock-ups
- Reduce font size to base of 12px
- Reduce negative space between search bar and library categories section

### Reviewers
@QilongTang 

### FYIs
@SHKnudsen

### CODE REVIEW

**Comment by mjkkirschner** [comment]
It would be great if this integration could be tested at various display scaling settings (100% to ~300%)

**Comment by reddyashish** [comment]
@alvpickmans I pulled in your changes locally and library view looks little zoomed out.

Screen Shot 2021-11-29 at 1 06 55 PM
.

**Comment by mjkkirschner** [comment]
@reddyashish @alvpickmans - not sure if you are familiar with the `adapatDPI` code, it's actually on the Dynamo side: 
https://github.com/DynamoDS/Dynamo/blob/master/src/LibraryViewExtensionMSWebBrowser/web/library/library.html#L138

**Comment by alvpickmans** [comment]
Good catch, I overlooked that method and was only investigating on the css side.
The latest librarie.js has most if not all font-sizes and key dimensions relative to the html font-size (using `rem` units), so using media queries in librarie.html we can conditionally scale up the component without js.


**100%**
image


**150%**
image


**200%**
image

**Comment by reddyashish** [comment]
The scaling looks good now. One of the things I noticed: After you enter a query in the search box, the first item returned is highlighted even though you hover on other items. Then when you go back to the search box and press Enter this node is placed in the workspace. If you think this needs more changes, feel free to add this to a new task. 

Library
.

**Comment by mjkkirschner** [comment]
@alvpickmans @reddyashish  please continue investigating the adaptDPI function - there are two locations (or more) where it is called from the c# side:
⚠️ 
https://github.com/DynamoDS/Dynamo/blob/2f9354254b83e9265d45a192a4e6e69c5d629eae/src/DocumentationBrowserViewExtension/DocumentationBrowserView.xaml.cs#L44
https://github.com/DynamoDS/Dynamo/blob/864dd6f565d3a64ea808b30a2d59766409e1b90b/src/LibraryViewExtensionMSWebBrowser/LibraryViewController.cs#L382

**Comment by reddyashish** [comment]
@alvpickmans Created a new task for all the library UI related issues: https://jira.autodesk.com/browse/DYN-4396.

**Comment by SHKnudsen** [comment]
Hi @mjkkirschner @reddyashish,

@alvpickmans managed to get the library.js side working for the search item icons. The highlighting of the last selected search item is existing behaviour that we have not touched and probably won't have the capacity to look at this side of Christmas.

I updated the js file and removed the `adaptDpi` calls from the libraryExtension as it shouldn't be needed any more, it is still there in the DocumentationBrowser.
LibraryFix

**Comment by SHKnudsen** [comment]
Margin updates
CC @reddyashish @Amoursol 
LibraryFix-v2

**Review by reddyashish — APPROVED** [review]

**Pull request merged**
