### PR TITLE
update node icons

### PR DESCRIPTION
**Pull request by pinzart90**
https://jira.autodesk.com/browse/DYN-5073
https://jira.autodesk.com/browse/DYN-5244

### Purpose

Fix icon sizes for :
Solid.Repair, Surface.Repair 
Curve.NormalAtParameter
PolyCurve.Heal

### CODE REVIEW

**Review by aparajit-pratap — APPROVED** [review]
Thanks!

**Comment by pinzart90** [comment]
@aparajit-pratap looks like we need to add all new icons to the GeometryUIWpf/ProtoGeometryImages.resx file in order for them to be displayed in dynamo.
Not sure why there are a bunch in src/Resources/ProtoGeometry/  too

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Reported regression is sporadic, merging. Please also cherry pick it

**Comment by aparajit-pratap** [comment]
> @aparajit-pratap looks like we need to add all new icons to the GeometryUIWpf/ProtoGeometryImages.resx file in order for them to be displayed in dynamo. Not sure why there are a bunch in src/Resources/ProtoGeometry/ too

I don't think that the png files are required in `src/Resources/ProtoGeometry/` as they are embedded resources, however, If I'm not wrong, I believe they are submitted in order to track them easily.

**Pull request merged**
