### PR TITLE
remove retain folder structure option during package publish

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

Removes the retain folder structure option during package publish as it does not yet fully work as intended.
https://jira.autodesk.com/browse/DYN-6589 has been filed to re enable it in the future.

toggle is removed from this view.

Screenshot 2024-01-04 at 4 15 48 PM

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

removes retain folder structure option until it's fully baked.

### CODE REVIEW

**Comment by hwahlstrom** [comment]
If this toggle is removed, we should also remove the section in the package documentation help (in the doc browser) that explains this setting.

**Comment by mjkkirschner** [comment]
> If this toggle is removed, we should also remove the section in the package documentation help (in the doc browser) that explains this setting.

Hi @hwahlstrom how does a user access that documentation?

**Comment by QilongTang** [comment]
@mjkkirschner You will need to build latest master or RC3.0.1 to access it because it was just restored:
image

**Comment by mjkkirschner** [comment]
test runner is still crashing, so not sure if theres any failures here or not, holding off on merging until I get a passing build - then will cherry pick to 3.0.2

**Comment by mjkkirschner** [comment]
this passed on master-15, but the test system is still flaky (runner crashes) - @QilongTang @sm6srw I'm going to merge this and send a cherry pick - but please feel free to revert this PR if it seems to increase the frequency of test runner crashes.

**Pull request merged**
