### PR TITLE
Make DefaultBrandingResourceProvider public

### PR DESCRIPTION
**Pull request by ikeough**
The DefaultBrandingResourceProvider is a required input to the StartConfiguration. As such, any attempts to sub-class DynamoViewModel, like we've done in the linked PR, fails because the Start method cannot be replicated without the ability to construct the DefaultBrandingResourceProvider.

This PR is a prerequisite for:
https://github.com/DynamoDS/DynamoRevit/pull/195

How dangerous is it to make this class public?

PTAL:
- [x] @aparajit-pratap

### CODE REVIEW

**Comment by ikeough** [comment]
@sharadkjaiswal @aparajit-pratap ping!

**Comment by aparajit-pratap** [comment]
@ikeough Revit does not really need to know about `DefaultBrandingResourceProvider` since it will use it via `DynamoViewModel` anyway. I therefore suggest moving this line: 
`var resourceProvider = startConfiguration.BrandingResourceProvider ?? new DefaultBrandingResourceProvider();` 
from `Start()` to the `DynamoViewModel` constructor. Since `DynamoViewModel` constructor is called from `DynamoRevitViewModel` it should work. 

In `DynamoRevitViewModel::Start()` method, you could simply say:


```
public static DynamoRevitViewModel Start(StartConfiguration startConfiguration)
{
            ...

            return new DynamoRevitViewModel(model, watchHandler, vizManager, startConfiguration.CommandFilePath, startConfiguration.BrandingResourceProvider, startConfiguration.ShowLogin);
}
```

Then you will change `DynamoViewModel`s constructor to:
```
protected DynamoViewModel(DynamoModel dynamoModel, IWatchHandler watchHandler,
            IVisualizationManager vizManager, string commandFilePath, IBrandingResourceProvider resourceProvider, 
            bool showLogin = false)
{
...
...
this.BrandingResourceProvider = resourceProvider ?? new DefaultBrandingResourceProvider();

...
}
```

**Comment by ikeough** [comment]
@aparajit-pratap Thanks! That makes total sense. And the change is in.

**Comment by aparajit-pratap** [comment]
Thanks @ikeough , LGTM.

**Pull request merged**
