### PR TITLE
Introduced CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pboyer**
### Purpose

This introduces a new CONTRIBUTING.md file.  A link to this file will be shown whenever forming a new issue or pull request, like this:

screen shot 2015-05-24 at 3 46 06 pm

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] The level of testing this PR includes is appropriate
  - Just adding docs - no tests

### Reviewers

@ikeough 

### FYIs

@lukechurch @Benglin @jnealb @riteshchandawar @monikaprabhu

### CODE REVIEW

**Comment by Benglin** [comment]
Looks good to me.

**Comment by lukechurch** [comment]
I'm not sure I understand the comment at the end of this 

```
+Unless otherwise noted, the Go source files are distributed under
+the MIT license.
```

**Comment by pboyer** [comment]
I updated the note on the license.

**Comment by pboyer** [comment]
Merging this in without the go-ahead from Travis / AppVeyor because this won't affect the build.

**Pull request merged**
