### PR TITLE
Create custom view model, if search element is custom node.

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-8250](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8250) Top Search item doesn't show Icon for custom node but that custom node actually have the icon in below list.

When we create copy of top node, it should be `NodeSearchElementViewModel`, if it's usual node and `CustomNodeSearchElementViewModel` if it's custom node.

### Declarations

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

?

### FYIs

@riteshchandawar

### CODE REVIEW

**Comment by ramramps** [comment]
@aosyatnik - this requires some unit testing. If it has one ,please point this PR to that.

**Comment by aosyatnik** [comment]
Hi, @ramramps , added test. Please, take a look, thanks!

**Comment by ramramps** [comment]
@aosyatnik  - Can you please fix the merge? Check the Engops build.

**Comment by aosyatnik** [comment]
Sorry, @ramramps , fixed!

**Pull request merged**
