### PR TITLE
WIP:  Extension framework

### PR DESCRIPTION
**Pull request by pboyer**
### Concept

This PR introduces the *revolutionary* concept of an Extension.  

This provides different startup hooks and dependency injection for extensions to the Dynamo without polluting core. 

- [ ] Design Review
- [ ] Testing strategy
- [ ] API Review

### Future tasks

- [ ] Move Package Manager to DynamoPackages.dll
- [ ] Pass Package Manager Extension as argument to DynamoModel at startup
- [ ] Update DynamoCoreWpf for removal of PackageManager from core

FYI @ikeough @Benglin @lukechurch

### CODE REVIEW

**Comment by ikeough** [comment]
Can we add startup and shutdown methods on the extension interface? It is often the case that an application extension needs to do other initialization/teardown.

**Comment by pboyer** [comment]
On Startup:

This is what `Load` is supposed to do.  I think it should be a bit more general, though.  I also would like to remove the `CustomNodeManager` from the input.  

On Shutdown:

`IExtension` implements `IDisposable`, is that sufficient?

Logging is done by `IExtension` implements `ILogSource`.

**Comment by ikeough** [comment]
We should consider how this works with the UI. If I wanted to write an extension which was a separate visualization window, a charting control for example. I want the chart control to be visible in the lower right hand corner of the WorkspaceView. Can I get access to the workspace view to add some custom UI?

**Comment by ikeough** [comment]
I wrote the startup and shutdown comment before I realized you had Load and Dispose. Those should work.

**Comment by pboyer** [comment]
Yeah, I haven't even thought about UI, yet.  I think that will be in a follow up piece.

**Comment by Benglin** [comment]
I once dreamt of a concept called *Dynamo Remote Extension* (which I started working on [this branch](https://github.com/DynamoDS/Dynamo/compare/master...Benglin:RemoteExtension)) and it made use of sockets to do interprocess communication (this way even when the UI freezes up, the remote extension can potentially cancel the evaluation by setting the cancelation flag). The same extension can be extended to do many cool stuff without adding to the weight of Dynamo (e.g. analyzing the tasks gone into schedule and the way they are actually executed, how much time, and dependency graph analysis, data analysis by a third party software, etc. etc. etc.)

But then for some reasons I got involved more in dealing with *management side of stuff* for *the other product*, and I just ran out of steam on the remote extension work. If only I can deal with just codes :(

**Comment by pboyer** [comment]
@Benglin we need to repair that!  You should have lots of time to write good code!

**Comment by Benglin** [comment]
I'm so sorry, do you expect me to look at this further? I may have misunderstood your original intents of this PR.

**Pull request closed without merging**
