### PR TITLE
Upgrade DynamoSample rvt to 2023 after Revit DDFreeze. (#12507)

### PR DESCRIPTION
**Pull request by ZiyunShang**
### Purpose

Upgrade DynamoSample.rvt to Revit 2023 final version.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

@QilongTang @mjkkirschner 

### FYIs

@Amoursol

### CODE REVIEW

**Comment by QilongTang** [comment]
Hi @ZiyunShang Do you need the nugets to be updated with this change?

**Comment by ZiyunShang** [comment]
@QilongTang yes, we need a new package contains this upgraded sample file in Revit 2023.

**Comment by QilongTang** [comment]
> @QilongTang yes, we need a new package contains this upgraded sample file in Revit 2023.

Do you think 2.14beta nugets would work? My only concern is that we have already released the nugets for 2.13 and the version number would not match

**Comment by ZiyunShang** [comment]
> > @QilongTang yes, we need a new package contains this upgraded sample file in Revit 2023.
> 
> Do you think 2.14beta nugets would work? My only concern is that we have already released the nugets for 2.13 and the version number would not match

I think it should be OK. And I can only specify the version of DynamoSamples package in D4R CICD, or use 2.14-beta lib for DynamoRevit building. But I remember that there is an issue about LibraryView https://autodesk.slack.com/archives/C186YR8SH/p1639461667130500 . Will there be a new 2.13 package to solve this problem?  If yes, I think this rvt can go with it.

**Comment by QilongTang** [comment]
> > > @QilongTang yes, we need a new package contains this upgraded sample file in Revit 2023.
> > 
> > 
> > Do you think 2.14beta nugets would work? My only concern is that we have already released the nugets for 2.13 and the version number would not match
> 
> I think it should be OK. And I can only specify the version of DynamoSamples package in D4R CICD, or use 2.14-beta lib for DynamoRevit building. But I remember that there is an issue about LibraryView https://autodesk.slack.com/archives/C186YR8SH/p1639461667130500 . Will there be a new 2.13 package to solve this problem? If yes, I think this rvt can go with it.

Hi @ZiyunShang I may need to confirm with team, but I believe we do not have plan to put it as hotfix for 2.13. Currently there is no plan for any hotfix yet

**Comment by ZiyunShang** [comment]
OK, if there is no hotfix for 2.13, you can close this PR, and I will use 2.14-beta package.

**Comment by QilongTang** [comment]
@ZiyunShang I closed this PR and triggered a build on 2.14 to publish nugets

**Pull request closed without merging**
