### PR TITLE
MAGN-9022 Rename DSCoreNodesUI to CoreNodeModels

### PR DESCRIPTION
**Pull request by marimano**
### Purpose

Rename `DSCoreNodesUI` to `CoreNodeModels`. 
Migration for nodes within `CoreNodeModels` library is implemented with specifying `AlsoKnownAs` attributes.
Test case is added for checking several CoreNodeModels nodes are correctly loaded.

### Declarations

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.

### Task link

[MAGN-9022 Rename DSCoreNodesUI to CoreNodeModels](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9022)

### Reviewers

@mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@marimano this PR looks pretty good to me, a bunch of nodes don't have icons though, it seems there names were DScore.xxx and were not renamed correctly.

here are some examples:
screen shot 2016-01-03 at 9 12 52 pm
screen shot 2016-01-03 at 9 12 36 pm
screen shot 2016-01-03 at 9 12 20 pm
screen shot 2016-01-03 at 9 12 00 pm

can you track these down and make a fix?

**Comment by mjkkirschner** [comment]
@marimano also- please add all the changes to the api changes wiki document:
https://github.com/DynamoDS/Dynamo/wiki/API-Changes

**Comment by marimano** [comment]
Hi @mjkkirschner, before I started renaming I had saved my build in a separate folder. When I opened DynamoSandbox, these nodes didn't have icons either.
Then I discussed this icon issue with @aosyatnik and she told she had been working on it and she will update [her PR](https://github.com/DynamoDS/Dynamo/pull/5901) when this PR is merged in

**Comment by marimano** [comment]
@mjkkirschner I have updated Libraries section in the api changes wiki document. Please let me know if I made mistakes there or I missed something

**Comment by mjkkirschner** [comment]
@marimano please follow the pattern laid out in the the API changes doc for the other renames where we name all members that have been changed.

**Comment by marimano** [comment]
@mjkkirschner I have mentioned all members of CoreNodeModels library, please take a look at the wiki document again

**Comment by mjkkirschner** [comment]
@marimano looks good to me

**Pull request merged**
