### PR TITLE
Alphabetical sequence:  "overflow" input 

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-8184](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8184) Provide a method to create a series of characters in an alphabetical sequence

Results:
image

image

image

image
image

### Declarations

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@mjkkirschner 
@lukechurch 

### FYIs

@Racel 
@jnealb

### CODE REVIEW

**Comment by Racel** [comment]
@aosyatnik - Looks good. Can you please update the warnings to say : "Letters of the same case are required."?

**Comment by Racel** [comment]
@aosyatnik - Also, please make sure to fix the issue with the Sequence icon in the library/tooltip. See the updated description of MAGN-8184 for more info.

**Comment by aosyatnik** [comment]
@Racel , yes, I remember.
image

**Comment by mjkkirschner** [comment]
@lukechurch where did we land on the final implementation and review of this task, would you like me to review this work as it stands with the understanding we'll only be creating a node for this functionality and not modifying the engine (builtinfunctionEndPoint) or wait until you have implemented that?

**Comment by aosyatnik** [comment]
Close it. We will create zerotouch node.

**Pull request closed without merging**
