### PR TITLE
2.13.1 fix ui hang when concurrent run and save.

### PR DESCRIPTION
**Pull request by mjkkirschner**
cherry pick:
https://github.com/DynamoDS/Dynamo/pull/12564

### CODE REVIEW

**Comment by mjkkirschner** [comment]
tests are running.

**Review by QilongTang — APPROVED** [review]
LGTM. Do you also have some auto-formatting add-in installed?

**Comment by mjkkirschner** [comment]
I formatted with visual studio at some point 😢

**Comment by QilongTang** [comment]
> I formatted with visual studio at some point 😢

Oh no worries. I scanned through the whole PR and found it's purely about removing the heartbeat which is good

**Review by pinzart90 — APPROVED** [review]

**Comment by mjkkirschner** [comment]
there is another change @QilongTang - 
`if (this is HomeWorkspaceModel homeWorkspaceModel && homeWorkspaceModel.RunSettings.RunEnabled)`

**Comment by mjkkirschner** [comment]
tests passed, merging.

**Pull request merged**
