### PR TITLE
Fix number format in node previews - Github issue #7707

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose
This PR fixes number formatting in node previews, Github issue: https://github.com/DynamoDS/Dynamo/issues/7707

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
image

- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@ke-yu 

### FYIs

@riteshchandawar @kronz @Racel

### CODE REVIEW

**Comment by jnealb** [comment]
@aparajit-pratap @riteshchandawar @kronz @Racel Not merging to 1.3, correct? We need to communicate about any 1.3 merges at this stage, thanks.

**Comment by aparajit-pratap** [comment]
@jnealb it's for master

**Comment by mjkkirschner** [comment]
@Racel @kronz is this really the behavior we want to have for numbers display. While this PR unifies the preview values, I think this rounding is very confusing for users when doing things like optimization. Maybe a compromise to add more digits of precision to the number settings.

**Comment by Racel** [comment]
@aparajit-pratap @mjkkirschner See my cooments in #7707

**Pull request closed without merging**
