### PR TITLE
Node info state - IntegerSlider

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

This is a dup of https://github.com/DynamoDS/Dynamo/pull/12700. 

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Node info state - IntegerSlider

### CODE REVIEW

**Comment by reddyashish** [comment]
The self-serve passed here: https://master-15.jenkins.autodesk.com/view/DYN/job/DYN-DevCI_Self_Service/948/. Opening this pull request.

**Comment by reddyashish** [comment]
@QilongTang PTAL, I have addressed the comments from old PR.

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@zeusongit Any more comments?

**Review by zeusongit — APPROVED** [review]
LGTM

**Pull request merged**
