### PR TITLE
Notification bell hover color to match with rest of the dynamo elements

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

Task: https://jira.autodesk.com/browse/DYN-5240

Before:
dyn-5240

After:
notification bell hover

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes
Notification bell hover color to match with rest of the dynamo elements

### Reviewers
@QilongTang @Amoursol

### CODE REVIEW

**Comment by Amoursol** [comment]
@reddyashish can we please also change the icon on hover to blue? If @Jingyi-Wen is still on vacation, Helena should be able to help!

**Comment by reddyashish** [comment]
For this use-case, we are not loading the bell icon as an image directly. I think that is because we are getting it from the HIG package. Dynamo loads it by converting it into font awesome code. There are only 2 images for bell outline, one for enable and the other was disable. Will confirm with @QilongTang.

**Comment by QilongTang** [comment]
> For this use-case, we are not loading the bell icon as an image directly. I think that is because we are getting it from the HIG package. Dynamo loads it by converting it into font awesome code. There are only 2 images for bell outline, one for enable and the other was disable. Will confirm with @QilongTang.

Yes, fontawesome icons. We discussed at standup and will try change the forecolor when mouse hover. If it does not allow for fontawesome icon, then we will go with the current state.

**Comment by reddyashish** [comment]
Foreground color applies to the text control and dint make any difference in our case.

**Comment by QilongTang** [comment]
> @QilongTang Foreground color applies to the text control and did not make any difference in our case.

Thanks, I think I also tried that when I implement it. Make sense

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@reddyashish would you cherrypick this when you have time?

**Pull request merged**
