### PR TITLE
Expand file operations nodes

### LINKED ISSUE #7977: Add "Append" Input to WriteText node
Could we get an additional Input for the Core WriteText node that would allow us to Append to a file in addition to overwriting the file?
I envision this as a simple Boolean after the filePath and text Inputs:
   filePath: string
   text: string
   **append: boolean**
Inside the node, it would simply use the "a" parameter at the file open instead of the "w" option.
default if it the input isn't wired would be false so any existing graphs would still work as is without any changes

Yes, I know this could be done in Python, but rather than have a custom node that almost duplicate a Core node it seems like this would be a simple addition to the existing Core node. 
(I hate it when people say that)
Further discussion on the DynamoBIM forum here:
https://forum.dynamobim.com/t/wish-add-append-option-to-writetext-node/12489

### PR DESCRIPTION
**Pull request by radumg**
fixes #7977
replaces #8035 (PR on wrong base)

### Append text node
adds a node allowing users to append to files instead of write, as requested by community :

- https://forum.dynamobim.com/t/wish-add-append-option-to-writetext-node/12489
- https://forum.dynamobim.com/t/append-new-data-to-end-of-text-file/10919?source_topic_id=12489

This this is a much safer option than adding a boolean switch to control write/append behaviour as it removes the possibility of accidentally overwriting files (by forgetting or not understanding what the switch does).

append text

Have also added a test for the new `AppendText` method.

### Get directory contents recursive
adds an optional input to the `GetDirectoryContents` node, allowing users to look in subdirectories as well, not just top-level directories.

- there's a few popular packages that add this but it's basic functionality that should be part of the core and not require Python nodes to achieve
- new input defaults to false so current behaviour is not affected, ensuring it's backwards-compatible with existing graphs

getdirectorycontents recursive

Have also added a separate test for the new recursive behaviour of  `GetDirectoryContents` method.

## Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

## Reviewers

@QilongTang 

## FYIs
@Racel 
@DavePlumb

### CODE REVIEW

**Comment by Racel** [comment]
Thanks @radumg - We will take a look probably next week or so.

**Comment by radumg** [comment]
Thanks @Racel !

**Comment by QilongTang** [comment]
@radumg Thanks for the PR. I looked at the excellent code and unit test and also tested the new node a bit. Looks awesome. I hope you do not mind that I touched the unit test `File_AppendText` a bit so that as soon as `AppendText()` is called, file existence is checked. Other than that, this one looks good to me

**Comment by radumg** [comment]
Hi @QilongTang, thank you for the feedback, really appreciate it!
Of course i don't mind, i'm always keen to learn. The test change totally makes sense in retrospective, I was introducing a dependency on a different unit too.
Cheers,
Radu

**Comment by Thomas84** [comment]
is the node File.AppendText included in 1.3.2 ? I cannot find it

**Comment by jnealb** [comment]
@Thomas84 FileSystem.AppendText?

**Comment by Thomas84** [comment]
@jnealb is the node "FileSystem.AppendText" available for you in 1.3.2 (ootb)?

**Comment by jnealb** [comment]
@Thomas84 No, it is a 2.0 feature only.

**Pull request merged**
