### PR TITLE
DYN-7716 Fixing Flaky Tests

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

DYN-7716 Fixing Flaky Tests
Fixing flaky tests that sometimes are failing and sometimes are not failing.
There are some tests that sometimes are failing and sometimes are not failing so those test were marked as Category[Failure].
So in this fix I'm removing that Category and make changes to fix the tests and get more info about why are failing.
This is the list of tests failing

- LuceneSearchTSplineNodesOrderingValidation()
- NodeSuggestions_OutputPortBuiltInNode_AreCorrect()
- NodeSuggestions_CanAutoCompleteOnCustomNodesOutPort_WithSpaceInPortName()

I've run the DYN-DevCI_Self_Service job two times without any test failing (also local tests in VS2022 are passing) but I will continue checking if in the jobs there are failing test in this PR

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Fixing flaky tests that sometimes are failing and sometimes are not failing.

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by QilongTang** [comment]
@RobertGlobant20 There is one regression reported but not related to the tests you turning on as part of this PR, can you check if that pass locally?

**Comment by RobertGlobant20** [comment]
@QilongTang the test failing is (I think is not related to this change):
```
[Test]
[Category("FailureDynCore")]
public void FeatureFlagsShouldReturnRealDataAfterCache()
```
"FailureDynCore" means that will be failing on DynamoCore? 

Thanks

**Comment by QilongTang** [comment]
> that will be failing on DynamoCore?

Not sure what that means, you will need to check with who added the test. I will approve the PR for now

**Review by QilongTang — APPROVED** [review]

**Comment by RobertGlobant20** [comment]
> > that will be failing on DynamoCore?
> 
> Not sure what that means, you will need to check with who added the test. I will approve the PR for now

The job passed here:
https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16865/

**Pull request merged**
