### PR TITLE
DYN-6447 Resize splash screen

### PR DESCRIPTION
**Pull request by avidit**
### Purpose

Resize splash screen to accommodate content in different languages
diff

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
@avidit The screenshot feels too wide of a change to me, can we make the button text visible by updating the css style so that the text could take the whole button space if possible?
Also @Jingyi-Wen Curious about your thoughts.

**Comment by avidit** [comment]
> @avidit The screenshot feels too wide of a change to me, can we make the button text visible by updating the css style so that the text could take the whole button space if possible? Also @Jingyi-Wen Curious about your thoughts.

I agree. I think it would be better to move up the button, checkbox and loading time text.

**Comment by zeusongit** [comment]
Also, maybe test with German for the widest text?

**Comment by Jingyi-Wen** [comment]
I agree we should 

> @avidit The screenshot feels too wide of a change to me, can we make the button text visible by updating the css style so that the text could take the whole button space if possible? Also @Jingyi-Wen Curious about your thoughts.

I agree this width ratio seems strange and having text fill more space in the button might be better. Also, agree with Abi's suggestion on moving the buttons up slightly to avoid the crowd at the bottom part. 
I did check a few other languages including German, but nothing longer than what's shown here (I believe is Italian?)

**Comment by avidit** [comment]
Thank you everyone for the input. I will close the PR in favor of updating the design on [DynamoDS/NotificationCenter](https://github.com/DynamoDS/NotificationCenter) side.

**Pull request closed without merging**
