### PR TITLE
Add removed files

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose
Add removed config files to prevent patch installer issues for integrators.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by zeusongit — APPROVED** [review]

**Comment by QilongTang** [comment]
There is a couple dll.config not under bin folder but under nodes folder, not sure if we need to make additional changes for that

**Comment by aparajit-pratap** [comment]
> There is a couple dll.config not under bin folder but under nodes folder, not sure if we need to make additional changes for that

`TestUINodes.dll.config` is the one that is missing from `nodes` folder. I believe this list of files covers all of the missing files from both locations that were reported by the Civil3D team.

**Comment by aparajit-pratap** [comment]
@QilongTang do I need to cherry-pick this PR into master?

**Comment by QilongTang** [comment]
@aparajit-pratap Did you verify locally? From https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/DynamoCore.csproj#L143, it does not seem your changes would work?

**Comment by aparajit-pratap** [comment]
> @aparajit-pratap Did you verify locally? From https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/DynamoCore.csproj#L143, it does not seem your changes would work?

@QilongTang done, please take another look. The files now seem to be copied to the respective output folders as expected on building the solution.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
