### PR TITLE
Fix type checking for integers on IsOutput serialization

### PR DESCRIPTION
**Pull request by saintentropy**
### Purpose

The purpose of this PR is to correct a bug in the serialization of nodes using the IsOutput UI.  Previously nodes with a return type of integer were being set as _Unknown_.  This issue is tracked with  
[QNTM-4085](https://jira.autodesk.com/browse/QNTM-4085) and is a dependency of [QNTM-3458]( https://jira.autodesk.com/browse/QNTM-3458).

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [X] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@QilongTang @ramramps 

### FYIs

@nonoesp

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@saintentropy can you also fix this in the inputNodeData class - will it matter there?

**Comment by jnealb** [comment]
@saintentropy @mjkkirschner @smangarole @ramramps @aparajit-pratap  I have to ask one last time: is this code flaw possibly anywhere else?

**Comment by mjkkirschner** [comment]
InputNodeData.cs

**Comment by saintentropy** [comment]
NodeInputData.cs has the same enum types [here](https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Graph/Nodes/NodeInputData.cs#L94)... The reason it wasn't required is that we type the integer slider with an `int` [here in Integer.cs](https://github.com/DynamoDS/Dynamo/blob/master/src/Libraries/CoreNodeModels/Input/Integer.cs#L8).  Does that type need to be something else?  The value gets serialized as an Int32

**Comment by jnealb** [comment]
Our integer type is int64 in 2.0

**Comment by mjkkirschner** [comment]
yeah, I think it might be an improvement to change slider to int64.

**Comment by saintentropy** [comment]
@mjkkirschner... Let's do this.  Let me change the enum of supported types on NodeInputData.cs so that we are covered on type checking regardless of what happens on the Slider.

**Comment by saintentropy** [comment]
@QilongTang Test added :-)

**Comment by QilongTang** [comment]
@saintentropy Hi, I saw test files added but no unit tests code change, did we miss some commits here?

**Comment by saintentropy** [comment]
@QilongTang This code is validated via the serialization tests.

**Comment by jnealb** [comment]
@saintentropy @QilongTang @Racel @smangarole @mjkkirschner Note that despite the mention of 2.0.1 above the JIRA task QNTM-4085 is marked for 2.1. Is this correct?

**Comment by QilongTang** [comment]
@saintentropy Thank you for the confirmation, changes LGTM

@jnealb That is correct, I removed the 2.0.1 tag of this PR. So this will be a 2.1 issue only

**Pull request merged**
