### PR TITLE
Fix for DS Variable Argument Function node views: MAGN-5920

### PR DESCRIPTION
**Pull request by aparajit-pratap**
Hi @pboyer this PR attempts to fix an issue with `DSVarArgFunction` nodes such as `List.Join` and `String.Join` nodes which have [broken views at the moment] (http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-5920). Some analysis showed that the node-view customization for these node types was not implemented (the implementation for `CustomizeView()` was empty). It appears that these node views should be identical to those for `VariableInputNode`s. Therefore a simple solution for me was to simply copy the same customization code from `VariableInputNodeViewCustomization` and stick it into that for `DSVarArgFunctionNodeViewCustomization` instead of trying to mess with all the clever reflection logic and reroute the calls somehow to the `CustomizeView()` implementation for `VariableInputNodeViewCustomization`. Is it as simple as this, I'm not sure? I guess it would have worked naturally if `DSVarArgFunction` node was in the same class hierarchy as `VariableInputNode`, however that is not the case although from a UI standpoint that makes sense. You would obviously be the best person to advise a more appropriate fix for this. Therefore sending it to you for review. Thanks.

### CODE REVIEW

**Comment by pboyer** [comment]
Hi @aparajit-pratap!

Check out the `CreateListNodeViewCustomization`:

```csharp
public class CreateListNodeViewCustomization : VariableInputNodeViewCustomization, INodeViewCustomization<CreateList>
{
    public void CustomizeView(CreateList model, Dynamo.Controls.NodeView nodeView)
    {
        base.CustomizeView(model, nodeView);
    }
}
```

This is a better approach.

**Comment by aparajit-pratap** [comment]
@pboyer thanks. The problem is that `DSVarArgFunction` does not inherit `VariableInputNode` unlike `CreateList`. Therefore I cannot derive `DSVarArgFunctionNodeViewCustomization` from `VariableInputNodeViewCustomization`. I had to therefore resort to replicating the same implementation for UI customization in  `DSVarArgFunctionNodeViewCustomization`. Other than factoring out the customization code into a common static function that can be used in both customization classes, I don't see yet another way to do this better? Do you?

**Comment by aparajit-pratap** [comment]
@Benglin

**Comment by pboyer** [comment]
Ah @aparajit-pratap, I didn't realize that was the case.

This looks reasonable and the extra code-sharing is probably unnecessary.  Also, thanks for adding the test case.

LGTM.

**Comment by aparajit-pratap** [comment]
Thanks a lot @pboyer

**Pull request merged**
