### PR TITLE
Style Workspace References consistently

### PR DESCRIPTION
**Pull request by mmisol**
### Purpose

Changed the styles of the workspace references extension window to be
more consistent with respect to Dynamo. Particularly, buttons that used
default WPF button style were switched to now use the same style as in
the "Geometry Scaling" window. Also, refresh is no longer a button, to
get rid of the undesired hover style, and the image foreground is
changed on hover.

Here is how it looks like now:

workspace_references

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [x] This PR modifies some build requirements and the readme is updated

### Reviewers

@QilongTang @aparajit-pratap 

### FYIs

@Amoursol

### CODE REVIEW

**Comment by Amoursol** [comment]
Hi @mmisol - Is it possible to make the button a little smaller? It currently takes up significant real-estate. Image shows before and after. 

image

**Comment by QilongTang** [comment]
@mmisol About @Amoursol 's request, does that need a new template for button?

**Comment by mmisol** [comment]
@QilongTang Unfortunately yes. While there is the possibility to create a style based on another, it does not allow to slightly change the template, so I'm creating a new one. It's an easy change anyway.

**Comment by QilongTang** [comment]
> @QilongTang Unfortunately yes. While there is the possibility to create a style based on another, it does not allow to slightly change the template, so I'm creating a new one. It's an easy change anyway.

That is actually good, I mean still better than the inline style we have right now

**Comment by mmisol** [comment]
It's looking like this now. What do you guys think? @Amoursol  @QilongTang 

smaller_button

**Comment by QilongTang** [comment]
@mmisol Can you test in German and some language with long strings? If they can be displayed correctly, I am good with this change

**Comment by mmisol** [comment]
@QilongTang I'm pretty sure I went back to the same size and spacing as before. Could you do the comparison again @Amoursol ?

**Comment by Amoursol** [comment]
> @QilongTang I'm pretty sure I went back to the same size and spacing as before. Could you do the comparison again @Amoursol ?

Looks good to me now @mmisol ! 
image

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
