### PR TITLE
Preview bubble 2

### PR DESCRIPTION
**Pull request by aosyatnik**
I couldn't resolve merge conflict in old PR: https://github.com/DynamoDS/Dynamo/pull/5692
This PR is copy of the old one.

FYI:
@ramramps

### CODE REVIEW

**Comment by ramramps** [comment]
@aosyatnik - Please check any of the LIST values. I think the style is removed that make the LIST values unreadable.  The list values should be "[0]  List" and not "[0]List".  Take any of the 9.0 builds and compare.

**Comment by ramramps** [comment]
@aosyatnik - Also check the scroll on the lists.

**Comment by ramramps** [comment]
@aosyatnik - Please let me know what is fixed here.

**Comment by aosyatnik** [comment]
Hi, @ramramps , I think you should look here: https://github.com/DynamoDS/Dynamo/pull/5786

**Comment by ramramps** [comment]
@aosyatnik - My bad. Just saw there is another PR. I will take a look

**Pull request merged**
