### PR TITLE
Add system.windows.interactivity nuget reference

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

Add `system.windows.interactivity` reference from nuget. This is required since there is a dependency on `EventTrigger` here: https://github.com/DynamoDS/Dynamo/blob/52557ec8dbd729d658dca8df69fbe5c721c2ceae/src/DynamoCoreWpf/UI/HandlingEventTrigger.cs#L5

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### FYIs
@DynamoDS/dynamo

### CODE REVIEW

**Comment by mjkkirschner** [comment]
what is the difference between interactivity.eventTrigger and https://docs.microsoft.com/en-us/dotnet/api/system.windows.eventtrigger?view=netframework-4.8

**Comment by mjkkirschner** [comment]
https://docs.microsoft.com/en-us/previous-versions/visualstudio/design-tools/expression-studio-4/ff726539(v%3Dexpression.40)

**Comment by aparajit-pratap** [comment]
> https://docs.microsoft.com/en-us/previous-versions/visualstudio/design-tools/expression-studio-4/ff726539(v%3Dexpression.40)

Not sure. They're apparently used for the list@level UI on the input ports. Tried replacing with `System.Windows.EventTrigger` and was crashing.

**Comment by QilongTang** [comment]
Thank you and couple question: 
1. Do we need to align with the version in Revit?
2. Do we want to switch to use project reference which have better support starting from VS 2019

**Comment by mjkkirschner** [comment]
maybe we can figure out how to get rid of this!?

**Comment by aparajit-pratap** [comment]
@QilongTang could we have you share with the team what you know about project references in VS2019?

**Comment by QilongTang** [comment]
@aparajit-pratap Sorry I mean package reference. Check this out! https://github.com/DynamoDS/Dynamo/pull/9664/files. This would be essentially similar to Dynamo packages. Nuget packages referenced by different solutions will be downloaded on a central location in userfile instead of each solution folder. And sln file will be cleaner, something to consider :)

**Pull request closed without merging**
