### PR TITLE
2.13 binary changes - don't ship test dependencies

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

do not copy test deps to bin folder

```
{ Name: \DynamoVisualProgramming.DynamoCoreRuntime\lib\MASK\Microsoft.Diagnostics.Runtime.dll, Type: Assembly, ChangeType: New, Description: N/A, Trace: N/A }
{ Name: \DynamoVisualProgramming.DynamoCoreRuntime\lib\MASK\System.Buffers.dll, Type: Assembly, ChangeType: New, Description: N/A, Trace: N/A }
{ Name: \DynamoVisualProgramming.DynamoCoreRuntime\lib\MASK\System.Memory.dll, Type: Assembly, ChangeType: New, Description: N/A, Trace: N/A }
{ Name: \DynamoVisualProgramming.DynamoCoreRuntime\lib\MASK\System.Numerics.Vectors.dll, Type: Assembly, ChangeType: New, Description: N/A, Trace: N/A }
{ Name: \DynamoVisualProgramming.DynamoCoreRuntime\lib\MASK\System.Runtime.CompilerServices.Unsafe.dll, Type: Assembly, ChangeType: New, Description: N/A, Trace: N/A }
```

these were getting pulled in because 
1. `Microsoft.Diagnostics.Runtime.dll` was not marked private
2. msbuild copies the dependencies of a referenced projects even if those projects deps are marked copy local = false, if that project reference is marked copy local = true. This was the case with some test projects referencing DynamoCoreTests csproj.
### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Don't distribute new dependencies of ADP tests.

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@mjkkirschner Thanks for addressing this!

**Comment by mjkkirschner** [comment]
@QilongTang thanks - please give me a few minutes before merging - checking if any other binary changes have occurred that I do not expect.

**Review by pinzart90 — APPROVED** [review]

**Comment by pinzart90** [comment]
@mjkkirschner thanks for the fix. My bad. ..

**Comment by mjkkirschner** [comment]
serial tests and parallel are both running:
https://master-15.jenkins.autodesk.com/view/DYN/job/DYN-DevCI_Self_Service/916/console

**Review by sm6srw — APPROVED** [review]

**Pull request merged**
