### PR TITLE
Cherry pick FixAddingClassesFromCustomDLL

### PR DESCRIPTION
**Pull request by aosyatnik**
This PR is copy of [that](https://github.com/DynamoDS/Dynamo/pull/4163), but with 1 commit to `RC0.8.0_ds`.

@Benglin , please, take a look.

### CODE REVIEW

**Comment by Benglin** [comment]
LGTM, thanks a lot @aosyatnik! Waiting for approval before merging this in...

**Comment by aosyatnik** [comment]
I tried it with FFITarget.dll

**Comment by aosyatnik** [comment]
@Benglin , also tried "structural analysis for dynamo" package (package mentioned by @kronz ) in standalone. Everything works properly.

**Comment by kronz** [comment]
@aosyatnik @Benglin Thanks!  Very glad this is getting into Studio

**Comment by Benglin** [comment]
Okay with @kronz approval, this is getting merged. Thanks again, @aosyatnik! :)

**Pull request merged**
