### PR TITLE
Duplicate connections using ctrl + click

### PR DESCRIPTION
**Pull request by yeexinc**
### Purpose

This PR is to address [DYN-622](https://jira.autodesk.com/browse/DYN-622).
Multiple connections can be created by holding down the control key and clicking on the desired ports.
gif2

- Multiple connections can be created only when the starting port (the first port clicked while starting the connection) is an output port, since input ports cannot accept multiple connections.
- As the starting port is an output port, the subsequent ports selected (to complete the connections) must be input ports. This is because output port -> output port connections are not supported.
- Ctrl + click can be cancelled by clicking on the canvas.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@riteshchandawar 

### FYIs

@Racel

### CODE REVIEW

**Comment by Racel** [comment]
Very nice @yeexinc. One thing that maybe we should consider regarding this and the multi-ouput port reconnect functionality is being able to hit ESC to completely get out of the command. Let me know what you think. Can't wait to play with this.

**Comment by riteshchandawar** [comment]
@Racel Hitting Esc in the current scenario is same as what we do with Single wire connection. 

For Ctrl+Click hitting Esc will terminate the duplicating operation, I hope that is what expected here.

Do let us know if you have additional comments.

**Comment by Racel** [comment]
@riteshchandawar - I believe that hitting ESC should terminate the duplicating operation. Will it disconnect the wires that were connected during the operation?

Regarding the multi-ouput port reconnect feature, I think ESC should place the wire back where it came from.

**Comment by yeexinc** [comment]
Hi @Racel , currently the ESC button only cancels the current connection (and does not place the wire back). This is the same behaviour as pressing ESC while doing single wire connection as mentioned by @riteshchandawar . It will not disconnect the other wires that were connected during the operation. 

The user can obtain the previous connections by hitting undoes, though. Each undo will restore one connection. E.g. if the user makes 4 connections using ctrl + click, then 4 undoes will be needed to restore the previous state.

**Comment by Racel** [comment]
@yeexinc - This behavior is fine for this duplicate connection feature. But, I plan on filing a separate task to adjust the behavior of the multi-output port reconnect.

**Comment by Racel** [comment]
@yeexinc - This looks good. When are you all planning on merging so we can try out?

FYI @wynged - thanks for your ideas on this

**Comment by yeexinc** [comment]
@Racel - I think the PR needs to be reviewed. @riteshchandawar Would you mind taking a look?

**Comment by Racel** [comment]
@riteshchandawar - Please review so that we can test :)

**Comment by riteshchandawar** [comment]
Looks good to me, I am merging this now.

**Pull request merged**
