### PR TITLE
Node Autocomplete first time experience Update

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

First time Dynamo users will get the following gallery of Dynamo introduction. Starting from Dynamo 2.12.0, Node Autocomplete will become the first page. 
image

Screenshot designed by @Jingyi-Wen

Let me know if you have any suggestions for description to cover.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@DynamoDS/dynamo 

### FYIs

FYI: @Amoursol  @mjkkirschner

### CODE REVIEW

**Comment by zeusongit** [comment]
Just curious, is it possible to get a gif on this page?

**Comment by QilongTang** [comment]
> Just curious, is it possible to get a gif on this page?

Sure, here is how to trigger it if you copy the content to the right folder locally. Usually this i done by Dynamo integrators. To fake a first launch of Dynamo, one need to touch preference setting but I did not bother doing it. The following gif shows how to access it manually. For first time user, gallery will launch it self when using Dynamo
NodeAutoCompleteGallery

**Comment by zeusongit** [comment]
> > Just curious, is it possible to get a gif on this page?
> 
> Sure, here is how to trigger it if you copy the content to the right folder locally. Usually this i done by Dynamo integrators...

Sorry, I meant that instead of a static image on the startup screen, can we get a gif of the node autocomplete in action?

**Comment by QilongTang** [comment]
> > > Just curious, is it possible to get a gif on this page?
> > 
> > 
> > Sure, here is how to trigger it if you copy the content to the right folder locally. Usually this i done by Dynamo integrators...
> 
> Sorry, I meant that instead of a static image on the startup screen, can we get a gif of the node autocomplete in action?

hi @zeusongit , I gave it a try and the gallery view in Dynamo does not support gif. Also searched online, there is no built in support for gif in WPF. In gallery view, we are using image control which does not support gif OOTB

**Review by reddyashish — APPROVED** [review]
LGTM

**Review by zeusongit — APPROVED** [review]

**Comment by QilongTang** [comment]
The self serve is failing due to known issues. Merging

**Pull request merged**
