### PR TITLE
Record the node selected from search if user has opted in

### PR DESCRIPTION
**Pull request by lukechurch**
### Purpose

This records the item selected from the search menu if the user has opted in to detailed usage reporting, i.e. instrumentation. It is needed for the UX work being done to improve the search UI.

### Declarations

- [x] The code base is in a better state after this PR
- [x] The level of testing this PR includes is appropriate

### Reviewers

@Racel PTAL

### FYIs

@sharadkjaiswal @RodRecker This will need to be cherry picked into 082.

### CODE REVIEW

**Comment by pboyer** [comment]
@lukechurch Is `InstrumentationLogger` guaranteed non-null?

**Comment by lukechurch** [comment]
@pboyer yes. These are static methods.

**Comment by Racel** [comment]
@lukechurch - LGTM

**Comment by lukechurch** [comment]
Thanks all

**Comment by Racel** [comment]
@lukechurch - Tested and verified. LGTM. For the future, we may also want to consider what node is selected after a user hits 'enter' in the library or in-canvas search.

**Pull request merged**
