### PR TITLE
Add package links to Package details view

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

https://jira.autodesk.com/browse/DYN-4893
Display site URL and repository URL on package details view if available.

Screen Shot 2022-05-12 at 2 26 09 PM

GIF:
DynamoSandbox_LSQnpg9QMR

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

- Add package links to Package details view

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Comment by zeusongit** [comment]
@QilongTang @Jingyi-Wen 
I displayed the whole link, it was unclear from the mockup, if we want the actual link or some clickable hyperlink like `Site URL` that opens the URL. Let me know if that is what was required, I will update the PR. Thanks.

**Comment by Jingyi-Wen** [comment]
> > > @QilongTang @Jingyi-Wen I displayed the whole link, it was unclear from the mockup, if we want the actual link or some clickable hyperlink like `Site URL` that opens the URL. Let me know if that is what was required, I will update the PR. Thanks.
> > 
> > 
> > Yeah this is intended. LGTM!
> 
> @Jingyi-Wen I believe we intend to have hyper links? No?

Oh my apologies I missed it, yes they should be hyper links

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
LGTM, can you also record a gif for demo purposes and maybe look for unit test possibilities for the two new properties you add? If we dont unit test them right now, I am fine skipping

**Review by QilongTang — APPROVED** [review]
LGTM

**Pull request merged**
