### PR TITLE
Show dialog box when opening corrupt file

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

Show correct error dialog box when user opens a corrupt file.
To do this we are just throwing the error to the outer catch block where it is handled appropriately.

DynamoSandbox_BzgLFDZSjQ

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

- [Fix] Display error message when a corrupt file is opened, the inner exception is exposed.

### Reviewers

@BogdanZavu

### CODE REVIEW

**Comment by QilongTang** [comment]
@BogdanZavu Would this change work for you?

**Review by aparajit-pratap — APPROVED** [review]

**Comment by aparajit-pratap** [comment]
@zeusongit is there a way we can test this?

**Comment by BogdanZavu** [comment]
> @BogdanZavu Would this change work for you?

Yes, looks like the right change. It is a change in API behavior for the OpenFile command maybe it should be noted somewhere in the release notes when the time comes.

**Review by BogdanZavu — APPROVED** [review]

**Comment by mjkkirschner** [comment]
@zeusongit can this use the messagebox service for the themed message box?

**Comment by zeusongit** [comment]
> @zeusongit can this use the messagebox service for the themed message box?

If by that you mean the new message box service complying by the visual refresh then it is being updated as part of another PR by @reddyashish in #12705

**Comment by zeusongit** [comment]
> @zeusongit is there a way we can add a test for this?

I think this could be tested by adding an UI Automation test. I will add the test.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
