### PR TITLE
DYN-: Dyn 6808 node icons p4 p5 errors manual

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Fix that includes changes in the Update Node Icon tool and also changes done manually in icons with errors reported by the tool.
Includes a fix for an edge case in the Update Node Icon tool in which the resource contains a path to the image instead of the base64 value, so we will be reading the image content and get the base64 value.
Also includes a change for some of the icons reported with errors by the Update Node Icon tool for P4 and P5 folder (P6 didn't have errors), this changes were done completely manually because the tool was not able to process them.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Fix that includes changes in the Update Node Icon tool and also changes done manually in icons with errors reported by the tool

### Reviewers

@QilongTang @zeusongit

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
This is a list of the node icons reported with errors by the` Update Node Icon `tool, the greens are the ones fixed in this PR the yellow ones are still under definition waiting feedback from the UX Designer 
image

**Comment by RobertGlobant20** [comment]
This are screenshot of the icons processed in this PR, showing the comparison between before my change and after my change.
image
image
image

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
the failures looks like sporadic ones, restarting the test job

**Comment by QilongTang** [comment]
https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16127/ passed, merging

**Pull request merged**
