### PR TITLE
Updated version to 2.0.0

### PR DESCRIPTION
**Pull request by Benglin**
Updated version to 2.0.0

### CODE REVIEW

**Comment by ikeough** [comment]
@Benglin I think we're going to 2.0 :) Can you please check with @kronz to confirm?

**Comment by mjkkirschner** [comment]
@ikeough thanks for catching this.

**Comment by Benglin** [comment]
You're absolutely right, @ikeough, we're gonna go `2.0` for sure. The [usual practice](https://git.autodesk.com/Dynamo/DynamoForRevit/wiki/Release-Branch-Creation#step-3-update-master-branch-version) of having `master` branch only one *build version* higher than the RC branch is to ensure `2.0` exists in the market before we eventually go there. So instead of having `2.0` out on `dynamobuilds.com` after we released `1.2.1`, we have general cutting edge public using `1.2.2` instead. And then in the event that we still need `1.3.0` to be released, we will not have issues with people already having `2.0` in the market and end up with upgrade issues.

Does that make sense? :)

**Comment by ikeough** [comment]
@Benglin Normally, yes, that would make sense. But, we've introduced API-breaking changes that must necessarily be under version 2.0. More of these changes will be coming shortly, as in https://github.com/DynamoDS/Dynamo/pull/7301.

**Comment by Benglin** [comment]
Gotcha, @ikeough. That means we can also go nuts with `master` branches then? I'll update the version number soon as we stop posting daily `master` builds. Thanks for highlighting this.

**Comment by ikeough** [comment]
@kronz FYI we are incrementing to 2.0. Please comment today, or I'm going to recommend that Ben merge this.

**Comment by kronz** [comment]
@Benglin @ikeough moving to 2.0 is the right thing to do from a release perspective.  If we need to do a release before 2.0 is ready, it will be for critical bug fixes and therefore will need to be something that is directly derived from the 1.2.1 branch.  The only weird part about this is that we will have daily builds being published on DynamoBIM for MUCH longer than we usually do, so I will message out about this.  As usual, there are development issues that should be worked out when we branch that have nothing to do with release schedule.  
- Cleanup issues related to removing deprecated APIs before or after branching?
- Language Cleanup that should happen ?
But I leave that discussion to Dev.  @QilongTang, @Racel and others on Dynamo west team have expressed some concerns about this

**Comment by Benglin** [comment]
If we need another release to address critical issues, then `1.2.2` can be based on `1.2.1` that is going out soon. Supporting additional Revit functionality may go into `1.2.2` branch provided it does not break compatibility, although one can argue that such _new functionality_ should go into `1.3.0` instead of `1.2.2` (either way we should not have any issue, except the fact that we can no longer base our intermediate releases on `master` branch).

If we choose to go with `2.0`, here are the relevant PRs that should be merged together (alongside this PR):

https://github.com/DynamoDS/DynamoRevit/pull/1366
https://github.com/DynamoDS/DynamoRevit/pull/1367
https://github.com/DynamoDS/DynamoRevit/pull/1368
https://github.com/DynamoDS/DynamoRevit/pull/1369

**Comment by ikeough** [comment]
@Benglin I'm not sure I understand why we can't base our intermediate releases on the master branch? By intermediate releases, do you mean 1.2.2 etc.? If so then yes, those will have to be built from branches. But it was my understanding that we already build releases from release branches. If you mean 2.0, then no, we can continue to build "dailies" from master. There will be breaking changes and people who choose to use that version will have to accept those breaking changes. Otherwise, they can stay at 1.2.

**Comment by gregmarr** [comment]
@ikeough I think @Benglin means that a 1.3.x release, if it were to exist, would need to be based on the 1.2.x branch instead of master, as master would have changes that couldn't go into 1.3.x.

**Comment by ramramps** [comment]
@Benglin is correct. It is good to have a branch from  which we can build  the intermediate releases.  But those intermediate releases should include critical bug fix and not for new features. Otherwise it is difficult to maintain the changes in two different branches.

**Comment by ikeough** [comment]
@Benglin I believe we're on the same page. Please bring this in before it gets too stale :)

**Comment by Benglin** [comment]
Hi @ikeough, I had a few word with the team and it appears that the move to `2.0` goes beyond just version number change. First of the product code needs to change, and side-by-side installation should be supported/tested. I need to have a discussion with them before this can go in (and before we can resume `master` build posting). Thanks!

**Comment by QilongTang** [comment]
@ikeough @Benglin Sure. Also it comes to my mind that we need to reset the base of Backward Compatibility test to 2.0, and better already clean up the deprecated APIs at that time. These are definitely tasks need to be planned before we actually push master 2.0 daily builds out.

**Comment by ikeough** [comment]
@QilongTang If backward compatibility tests simply test that workspaces from previous versions open correctly, then they should continue to pass. What else do they do?

**Comment by mjkkirschner** [comment]
@ikeough they test that methods are not missing ( they are semantic versioning tests)

**Comment by ikeough** [comment]
A major version update will, by definition, break APIs. This set of tests will break EVERY TIME we do a major version update. I would recommend that we remove these tests and be diligent about reviewing and documenting API changes.

**Comment by QilongTang** [comment]
@Benglin @kronz @ikeough  Where are we now at Dynamo2.0? Seems master builds posting has been resumed but all the version changes have not been merged, this is resulting that the exe installer we are delivering not up-to-date. See picuture attached:
image
This is because even the installer is a DynamoRevit installer but the name is based on DynamoCore version. DynamoRevit is currently on 1.2.2 and DynamoCore is still on 1.2.1. That is causing the weird situation. We need to fix this by aligning the versions ASAP!

**Comment by Benglin** [comment]
Hi @QilongTang, all set to go, I'm merging this in as soon as @ellensi is done with the studio side of product code update. Thanks and sorry for the delay!

**Comment by QilongTang** [comment]
@Benglin Great! Can't wait.

**Pull request merged**
