### PR TITLE
MAGN-7070 Can't see group title editing when zoomed out

### PR DESCRIPTION
**Pull request by ramramps**
### Purpose
 This PR fixes the issues with Group title Edit on Zoom.  When you Zoom Out, you will get a Edit window to edit the Title. When Zoom In (after Zoom out) the textbox is visible today. This PR will show the Title (its a textblock) and not the textbox. (This is only during Zoom out and Zoom in).

YT: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7070

### Declarations
- [x] The code base is in a better state after this PR.
          Added a converter that controls the visibility of textblock and textbox based on the Zoom factor.
- [] The level of testing this PR includes is appropriate
            
### Reviewers
- [ ] @ikeough

### CODE REVIEW

**Comment by ikeough** [comment]
@ramramps How does this relate to the zoom factor? I must be missing something. The converter seems to toggle the visibility of a textbox/block based on whether a converter parameter has a fixed value.

**Comment by ikeough** [comment]
@ramramps Can you also include a link in the PR description to the YT task for which this work is being done. It makes it easier to get to the issue quickly.

**Comment by ramramps** [comment]
@ikeough  - This is a bug. You can see that from YT task. 
 Group Title has Textblock and textbox. Double click on the group will get the textbox. You can click inside or outside the group to populate the title. But the behavior is different when you zoom out and then zoom in. There is a converter that controls this behavior. If the Zoom * font size  is less than 7.0 then title should not be visible. So, double clicking the title will get the edit window. The bug here is , when you double click the title, you get the edit window, but when you zoom in, you can still the textbox.  Ideally you should see textblock and not the textbox.  I controlled the behavior in XAML using converter (I did that for mouse click as well) otherwise, I had to rewrite the XAML and mouse click behavior.

**Comment by ikeough** [comment]
Ok. Thanks @ramramps. Is it possible to put in one system test that toggles the zoom and ensures that the visibility is correct?

**Comment by ramramps** [comment]
@ikeough  - TestAnnotationMouseClickEvent - this test handles all the Zoom related converters. I tested this and GroupTitleVisibilityConverter behaves as expected.

**Comment by ikeough** [comment]
Thanks @ramramps. LGTM.

**Pull request merged**
