### PR TITLE
update libg to disable breaking change from ASM

### PR DESCRIPTION
**Pull request by pinzart90**
### Purpose

update libg to disable breaking change from ASM

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. Use N/A to indicate that the changes in this pull request do not apply to Release Notes. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by aparajit-pratap — APPROVED** [review]

**Comment by mjkkirschner** [comment]
@pinzart90 what other changes does this move to 3.2.1? Just the change for polycurve x at parameter queries?

**Comment by pinzart90** [comment]
> @pinzart90 what other changes does this move to 3.2.1? Just the change for polycurve x at parameter queries?



> @pinzart90 what other changes does this move to 3.2.1? Just the change for polycurve x at parameter queries?

I think so. The libg commit was based on latest master

https://git.autodesk.com/Dynamo/LibG/commit/d19933c44c7d3db0cdc3c3f18ea9298f4b452be0

**Comment by aparajit-pratap** [comment]
> @pinzart90 what other changes does this move to 3.2.1? Just the change for polycurve x at parameter queries?


I suppose we should get into the habit of creating release snapshots (branches) of libg as well just like we do for Dynamo so we can easily create hotfixes based on them.

**Comment by pinzart90** [comment]
> > @pinzart90 what other changes does this move to 3.2.1? Just the change for polycurve x at parameter queries?
> 
> I suppose we should get into the habit of creating release snapshots (branches) of libg as well just like we do for Dynamo so we can easily create hotfixes based on them.



> > @pinzart90 what other changes does this move to 3.2.1? Just the change for polycurve x at parameter queries?
> 
> I suppose we should get into the habit of creating release snapshots (branches) of libg as well just like we do for Dynamo so we can easily create hotfixes based on them.

YEah, sounds like a good idea. For this case, I think  polycurve x at parameter queries is very low risk. We should be ok keeping it

**Pull request merged**
