### PR TITLE
Add node to convert string to Title Case

### PR DESCRIPTION
**Pull request by mmisol**
### Purpose

Adds a node that allows to convert a string to title case, i.e. "stay at home" becomes "Stay At Home".
This is based on the changes in #10470 by @chuong9x, making the following changes:
- Code is moved to CoreNodes.String. String.String was not really used so the project was deleted.
- Several other unused projects were deleted.
- Added unit tests for the new node.
- Added icons for the new node.
- Added the node to the library.

**Node in library**
Screen Shot 2020-04-08 at 5 46 13 PM

**Node in action**
Screen Shot 2020-04-08 at 5 47 33 PM

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner @QilongTang 

### FYIs

@chuong9x @Amoursol

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@mmisol nice cleanup, coreNodeUI folder always confused me.... Since you're in here already... can you also delete DynamoPackagesUI? I think thats another project that is not built.

**Comment by QilongTang** [comment]
LGTM

**Comment by QilongTang** [comment]
@mmisol Did we close the original PR?

**Comment by mmisol** [comment]
@QilongTang I just did. Thanks for the reminder

**Pull request merged**
