### PR TITLE
DYN-7364 Update BuildPackages.bat and remove Beta keyword for 3.3 release

### PR DESCRIPTION
**Pull request by QilongTang**
### Purpose

Remove beta keyword for official DynamoCore 3.3.0 release

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Remove beta keyword for official DynamoCore 3.3.0 release

### Reviewers

@DynamoDS/dynamo

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by RobertGlobant20 — APPROVED** [review]
LGTM, then this fix is just for the RC3.3.0 branch, right?

**Comment by QilongTang** [comment]
> LGTM, then this fix is just for the RC3.3.0 branch, right?

Yes

**Comment by QilongTang** [comment]
FYI: @twastvedt This is one of the final release step

**Comment by QilongTang** [comment]
I dont believe the failed PR check has anything to do with this PR. @avidit looks like tests are version specific, is there a way to run different tests on different RC branch? Something to keep in QA backlog maybe..

**Pull request merged**
