### PR TITLE
DYN-6603 decrease weight for tspline nodes

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Decreasing t-spline nodes weight during search so we will see nodes under a specific category at the top and later t-spline nodes.
I've changed the weight of Spline nodes at indexing time so when using criteria like "sphere" will show first the nodes under the Sphere category and later the T-Spline nodes which has the text "sphere" in the name. For implementing  the expected behavior I've decreased the weight of the fields Description and SearchKeywords just for t-spline nodes.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Decreasing t-spline nodes weight during search so we will see nodes under a specific category at the top and later t-spline nodes.

### Reviewers

@QilongTang @reddyashish

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
Screenshot showing results before and after my fix:
image

**Comment by RobertGlobant20** [comment]
Screenshot showing results before and after my fix:
image

**Review by QilongTang — COMMENTED** [review]
Thanks, looks good, can you add a unit test about the order of a geometry search results?

**Comment by RobertGlobant20** [comment]
> Thanks, looks good, can you add a unit test about the order of a geometry search results?

@QilongTang I've added a unit test that will validate the order of nodes (when t-spline nodes were added).
commit: https://github.com/DynamoDS/Dynamo/pull/14965/commits/aa45115247e0a489173406bf6c7f9ab606c1da26

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
