### PR TITLE
MAGN-5458 All Elements of Type fails for DimensionTypes #3083

### PR DESCRIPTION
**Pull request by AndyDu1985**
There are two "DimensionTypes" in Assembly, but in different namespace.
And one is public and the other non-public. Of course, we want the
public one.
However, we should consider that two public one in different namespace.
This will be done later. Not in this change list.

### CODE REVIEW

**Comment by AndyDu1985** [comment]
@ShengxiZhang

**Comment by AndyDu1985** [comment]
@LiangweiHuang,@XiaojieZhang

**Comment by AndyDu1985** [comment]
@LianweiHuang

**Comment by AndyDu1985** [comment]
@XiaojieZhang

**Comment by ShengxiZhang** [comment]
Looks good!

**Comment by AndyDu1985** [comment]
@KikiZhang

**Comment by LianweiHuang** [comment]
Great!

**Comment by AndyDu1985** [comment]
@Randy-Ma

**Comment by Randy-Ma** [comment]
@AndyDu1985 
Great! Thanks a lot for the fix!

**Pull request merged**
