### PR TITLE
Revise File format checking utils

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Revise some changes introduced to the API of `isValidJson` and `isValidXML` so that caller does not always need to wrap this call with try-catch, the exception comes with it will be one of the out param. Caller can check the exception type and decide if they want to re-throw it to the UI layer.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@ColinDayOrg 

### FYIs

@mjkkirschner

### CODE REVIEW

**Comment by QilongTang** [comment]
This changed fixed the failure on master branch now, also running self CI now

**Comment by QilongTang** [comment]
All tests pass now
image

**Comment by ColinDayOrg** [comment]
Generally these changes look like they will function as expected, enough that LGTM.

However, I am not sure of the functionality or correctness of returning the exception though. The places in the XML and JSON loading low-level methods are the only place where an exception may be "expected" in this case (if the file format is not correct). So I would expect the exception handling in those methods to handle any "expected" exceptions and just re-throw any other exceptions.

**Comment by QilongTang** [comment]
@ColinDayOrg I see your point. I am deferring the exception handling in the caller and asking this utility to only give back a bool with potential exception which is a slightly different version. One big reason is that I want to avoid the case that caller have to always wrap this call with try-catch.

**Comment by QilongTang** [comment]
As discussed with @ColinDayOrg, will merge this as it is

**Pull request merged**
