### PR TITLE
Display previews for selected nodes

### PR DESCRIPTION
**Pull request by Benglin**
Background
-----
Support the ability to [preview multiple selected nodes at once](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-1172) (an internal task).

Video
-----
[But it ain't 2014 no more...](http://youtu.be/H5Bkq95i6Wc)

@ikeough

@kronz @mccrone

### CODE REVIEW

**Comment by kronz** [comment]
Uh, oh . . . I think we had a big miss here in communication.  The intention of this story was the manipulation of the Preview state of nodes, as currently accessed in the contextual menu on a per node basis (show/don't show geometry in backround/watch3d).  Looks like you have addressed the Preview Bubble display, which is completely different.  Let's talk directly and re-adjust.

**Comment by Benglin** [comment]
Urgh! Okay, sure we can work on those, too. I constantly see people clicking around for previews, so this may be useful. What do you think of this one as a feature, @kronz? Sorry about misinterpreting the requirement!

**Comment by kronz** [comment]
@Benglin @elayabharath While I can certainly see the utility of exposing preview bubbles for a number of nodes all at once, we can't add a menu category (Selection) with a single item in it (Display Previews).  The original intention of the User Story was that there would not need to be any "new" ui but just that selections of groups of nodes would have right click context menu options that have some of the tools available in single node selection context menus.  



So, we can add the Display Preview Bubble control to the context menu as well for selections of groups of nodes, but the real intention here is to allow Preview (as currently expressed in the single node selection context menu) to be exposed in the context menu for group selections.

**Comment by Benglin** [comment]
Hi @kronz, the reason I opt for a ```Selection``` menu because there are so many things we could do with a selection (e.g. ```Preview```, ```Preview Upstream```, ```Lacing```, node alignment...). If I recall correctly, Photoshop has this *Select* menu for such types of operations.

Few things to ponder:

1. When user right-clicks on one of the many selected node, its context menu is shown (the one with ```Preview``` option), but this context menu is meant for that single node (let's call it *Node Menu*). User may imagine that the operation is applied to selection (try ```Delete``` and you'll see what I meant).

2. Context menu that shows up for empty spots on the graph is for the entire graph (let's call it *Graph Menu*). We can't quite merge them both, for example, ```Rename Node``` is applicable for a node, while ```Fit to Screen``` works for the whole graph.

3. Code paths for *Node Menu* and *Graph Menu* are residing in different locations and therefore needs restructuring/unification. Nothing too ground breaking here, but code movements can arrive in batches for easy reviews.

I will have a word with @elayabharath later to get a rough proposal, then have the ```Selection``` menu removed.

**Comment by ikeough** [comment]
@Benglin What's happening with this?

**Comment by Benglin** [comment]
Hi @ikeough, due to the work required, this has become [another more involved user story](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-5738#tab=Linked%20Issues). The work is starting in another two days. I'm keeping this open as various work from this PR will be applicable to the new work too.

**Comment by ikeough** [comment]
@Benglin Is this dead?

**Comment by Benglin** [comment]
Pretty much dead, @ikeough. Closing it for now.

**Pull request closed without merging**
