### PR TITLE
DYN-1573: Address 3 failing Custom node WpfVisualizationTests

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

This PR is to address the 3 failing Custom node WpfVisualizationTests. 
1) InsideInstance_AllGeometryFromInstancesOfThisCustomNode_Alive()
2) InsideInstance_HiddenInHomeSpace_NoGeometry()
3) InHomeWorkspace_CustomNodeInstance_HasGeometry()

The values in the tests have been modified accordingly and I think these have not been run from a long time. 

In short:
The points, lines and the meshes for the graph are stored in the ModelDictionary object inside the BackgroundPreviewGeometry object. Now when these points/lines/meshes are being rendered to the geometry window, all the points/lines for a particular node have the same "id".  
https://github.com/DynamoDS/Dynamo/blob/f42e4e71bd4c02c81a5770dd952587daafb2015d/src/DynamoCoreWpf/ViewModels/Watch3D/HelixWatch3DViewModel.cs#L1598
In line 1609 after that, the points are added to the model dictionary and are grouped per each node as the key is the same for those points. Similar logic is applied to the lines as well (Line: 1635).  

But for meshes, 
https://github.com/DynamoDS/Dynamo/blob/f42e4e71bd4c02c81a5770dd952587daafb2015d/src/DynamoCoreWpf/ViewModels/Watch3D/HelixWatch3DViewModel.cs#L1682

"RequiresPerVertexColoration" flag is true, so the "id" for each of the mesh object's is different. 
(some_id:0, some_id:1, some_id:2 and so on). They are stored individually in the ModelDictionary object as the key is different here for each object. 

In these tests, the graph has 2 FiveCubes.dyf custom nodes(each custom node draws five cuboids). As a result, 10 points, 10 lines, and 10 meshes are drawn. But the points/lines are grouped per node. That's why we get 2 points, 2 lines and 10 meshes from these 2 custom nodes. I am curious about the difference in logic for points/lines to that of the meshes. 

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@alfarok @mjkkirschner @QilongTang @aparajit-pratap

### CODE REVIEW

**Comment by alfarok** [comment]
@reddyashish Nice investigative work! 👍  This make sense and I feel much better knowing why the meshes are grouped differently.  The changes LGTM, but you may want to see what's up with your git history.  It seems like it's showing a bunch of old commits.  

You may want to rebase your branch or fork to Master and apply your minor test changes again.  I am not sure if this is a big deal or not.  Now that we squash before merging the git history on a branch or fork gets out of sync and shows old commits that were condensed to a single commit.  Others may have more insight into the appropriate strategy.

**Comment by QilongTang** [comment]
LGTM. But moving forward you may want to always start from a branch on your fork or sync your master cleanly, you can check out https://help.github.com/en/articles/syncing-a-fork or borrow practices from others

**Comment by reddyashish** [comment]
@alfarok @QilongTang Yes, I will clear the commit history to avoid confusion.

**Comment by mjkkirschner** [comment]
@reddyashish can points and lines be made transparent? I wonder if it has to do with sorting.

**Comment by reddyashish** [comment]
Yes i think they can be transparent. Sorry, did not understand the sorting part.

**Pull request merged**
