### PR TITLE
"Manage Customizers..." button.

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-8064](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8064) "Manage Customizers..." button

Result:
image

### Declarations

- [x] The code base is in a better state after this PR
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@pboyer 

### FYIs

@Racel

### CODE REVIEW

**Comment by Racel** [comment]
@aosyatnik @pboyer - Would it be possible to make some slight modifications to this dialog to make it easier for the user to parse? See my proposal below:
 - Add dividing line between Publish and Share link areas
 - Remove 'Manage Customizers' button and replace with link text (this is not one of the primary actions of this dialog)

publishcustomizer

**Comment by pboyer** [comment]
I like this @racel. Let's do it.

Also, this should also be a menu item under "Publish Customizers.." in the
file menu. So you don't have to go to this dialog to hit this button.

**Comment by aosyatnik** [comment]
@pboyer , @Racel  that's how Publish Customizer window will look like:
image

Also added menu item:
image

**Comment by Racel** [comment]
@aosyatnik - LGTM. Thanks for the changes. If you have time, I would also adjust the size of the
 'Copy Link' button height to be the same as the Share Link text field. (See below, the background of the button extends to match the text field background) This is minor, so I don't think its necessary before you merge. @pboyer- any thoughts?

screen shot 2015-08-12 at 8 21 57 am

**Comment by aosyatnik** [comment]
Updated. Now Share and copy have the same width.
image

**Comment by Racel** [comment]
Thanks, @aosyatnik. LGTM

**Comment by pboyer** [comment]
Cool, thanks @aosyatnik!

**Pull request merged**
