### PR TITLE
Dyn 5444 splash screen keyboard

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose

Implementing the improvement https://jira.autodesk.com/browse/DYN-5444

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Reviewers
@QilongTang 

### FYIs
@reddyashish
@RobertGlobant20 
@Enzo707

### CODE REVIEW

**Comment by jesusalvino** [comment]
enter_key

**Comment by QilongTang** [comment]
Can user dismiss splash screen by pressing Ecs?

**Comment by QilongTang** [comment]
Hi @jesusalvino If you check the second AC of the Jira task, it includes that catching key press to exit splash screen. For now, I would like to simply include that `When user press Esc at the static splash screen, Dynamo exit, which is equivalent of pressing the cross on the top right corner`. Let me know if that make sense to you

**Comment by jesusalvino** [comment]
> Hi @jesusalvino If you check the second AC of the Jira task, it includes that catching key press to exit splash screen. For now, I would like to simply include that `When user press Esc at the static splash screen, Dynamo exit, which is equivalent of pressing the cross on the top right corner`. Let me know if that make sense to you

@QilongTang  Done.

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
LGTM

**Comment by reddyashish** [comment]
@QilongTang Do we want to close dynamo when user presses esc or just lose focus from the screen? Generally imo, closing the app is not the behavior expected when user presses esc.

**Comment by QilongTang** [comment]
> @QilongTang Do we want to close dynamo when user presses esc or just lose focus from the screen? Generally imo, closing the app is not the behavior expected when user presses esc.

Usually `Esc` is for calling out the main menu in App, but we dont have that for splash screen, I believe the user request behind the Jira task was to quit Splash screen. In terms of what it should do in Dynamo, we need to discuss and implement later. let me know if it make sense.

**Comment by reddyashish** [comment]
Sorry Aaron, I meant closing the splash screen only by hitting escape. Alt+f4 is used to close any window app, so i was thinking esc should just lose focus of the screen. Is that requested from a customer?

**Pull request merged**
