### PR TITLE
start running serialization view tests again

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

Nunit3 has different behavior when it comes to catching assertions than nunit 2 - they still mark the test a failure, so we ignore the results of a few different nodes whose behavior actually changes depending on where the graph is executed from.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by sm6srw — APPROVED** [review]
LGTM, Should we create a follow-up for the remaining ones?

**Comment by mjkkirschner** [comment]
sorry @sm6srw did I miss some failures?

**Comment by sm6srw** [comment]
@mjkkirschner No, it was late last night. You are good.

**Comment by mjkkirschner** [comment]
adds 30 minutes to the tests, but it passes everywhere - if we want to run less of these for faster test runs in the future I'm okay with that.

**Pull request merged**
