### PR TITLE
Dynamo.Scheduler namespace.

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-8861](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8861) Create and refactor Dynamo.Scheduler namespace.

If I understood task right, then I had to create next folder structure:
DynamoCore/Scheduler/DynamoScheduler
DynamoCore/Scheduler/SchedulerThread

And move:
* ISchedulerThread.cs and SchedulerThread.cs
* DynamoScheduler.cs and DynamoSchedulerInternals.cs

And create namespaces:
`Dynamo.Scheduler.DynamoScheduler`
`Dynamo.Scheduler.SchedulerThread`

Revit PRs:
https://github.com/DynamoDS/DynamoRevit/pull/750
https://github.com/DynamoDS/DynamoRevit/pull/751
https://github.com/DynamoDS/DynamoRevit/pull/754
https://github.com/DynamoDS/Reach/pull/106
Unfortunately I don't have Revit 2017.

### Declarations

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.

### Reviewers

@ikeough

### CODE REVIEW

**Comment by aosyatnik** [comment]
All tests passed. (except Mutation)
image

**Comment by ikeough** [comment]
@aosyatnik That mutation test failed for me on on another branch as well, but passes locally. I wouldn't  worry about it.

**Comment by ikeough** [comment]
@aosyatnik I apologize that I didn't make this more clear. This is a good start. Here's what I think should happen...

1. Move all of `Dynamo.Core.Threading` into a new namespace `Dynamo.Scheduler`. Don't worry about sub-namespaces right now.
2. Make sure this builds with Reach as well.

**Comment by aosyatnik** [comment]
Hi, @ikeough , I've updated this PR and others.
I moved all files from Threading into Scheduler namespace and folder.

**Comment by ikeough** [comment]
Thanks @aosyatnik. LGTM. I'll get to work merging :)

**Pull request merged**
