### PR TITLE
about box updates part 2

### PR DESCRIPTION
**Pull request by mjkkirschner**
fixed formatting
fixed colors
fixed broken links

### Purpose

@smangarole noticed there were some broken links and invisible colored text in the about box.

### Declarations

I know this diff is hard to review ... 
I have gone through and clicked every link to make sure they work - and updated some old ones that moved from codeplex to github.

Screen Shot 2019-03-26 at 8 42 35 PM

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@smangarole  @alfarok @scottmitchell 

### FYIs

@kronz

### CODE REVIEW

**Comment by scottmitchell** [comment]
The SharpDX license link doesn't work for me.
[https://github.com/sharpdx/SharpDX/blob/master/License.txt/](https://github.com/sharpdx/SharpDX/blob/master/License.txt/)

**Comment by scottmitchell** [comment]
Looks like it's changed to [https://github.com/sharpdx/SharpDX/blob/master/LICENSE](https://github.com/sharpdx/SharpDX/blob/master/LICENSE)

**Comment by mjkkirschner** [comment]
@scottmitchell thanks for catching it! will update it.

**Comment by scottmitchell** [comment]
Also take a look at the `Microsoft Public License` link. Somehow this is causing Dynamo to crash for me!?

**Comment by scottmitchell** [comment]
Besides those two links, everything else looks good.

**Pull request merged**
