### PR TITLE
DYN-6263 Revert avalonedit version

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

DYN-6263: Revert avalonedit version

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Would you check our internal dependency spread sheet and make sure the version there is correct as well? Appreciate it

**Comment by aparajit-pratap** [comment]
> Would you check our internal dependency spread sheet and make sure the version there is correct as well? Appreciate it

Done.

**Comment by aparajit-pratap** [comment]
@sm6srw will DynamoSelfServe run as a PR check against this branch?

**Comment by QilongTang** [comment]
> @sm6srw will DynamoSelfServe run as a PR check against this branch?

It will, just these days, the delay is insane sometimes :)

**Pull request merged**
