### PR TITLE
Is input2

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

related to this reverted PR: https://github.com/DynamoDS/Dynamo/pull/5671

This PR returns false for ` IsInputNode` on Codebloccks - thus removing the the checkbox that lets a user set the node as an input for Customizer.

Codeblocks are also counted as a input in the case of presets so a preset can be made containing nothing but codeblocks. The type of node is checked during filtering and codeblocks are removed from nodes to filter.

I've also renamed `IsSelectedInput` to `IsSetAsInput` to help clarify the difference between the two `Input` properties, though it is still serialized as  IsSelectedInput to dyn files.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards) <b>n/a</b>
- [ ] The level of testing this PR includes is appropriate <b>n/a</b>
- [ ] All tests pass using the self-service CI.

### Reviewers

@pboyer please see the related Reach PR:

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@pboyer the conflict is the reach.dll - I will fix it - needs to be updated with @marimano latest fix.

**Comment by marimano** [comment]
@mjkkirschner, as I see all needed changes in Reach are merged and my latest merge with update of Reach.dll contains all changes merged before today. So you can simply resolve conflics here by chosing Reach.dll from dynamo:master

**Comment by mjkkirschner** [comment]
thanks @marimano, but I also need to make some changes to the reach .dll on top of your changes.

**Comment by mjkkirschner** [comment]
@pboyer ptal

**Comment by pboyer** [comment]
LGTM - make sure you update with the latest Reach.dll.

**Pull request merged**
