### PR TITLE
Update TestSessionConfiguration.cs

### PR DESCRIPTION
**Pull request by mjkkirschner**
@QilongTang @smangarole 
try to get the tests running again.

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I'm not confident this will fix anything, but it should be done anyway for consistency.

**Comment by QilongTang** [comment]
@mjkkirschner I believe lookup logic always go from newer versions to older, otherwise as a typical dev setup, when running these unit tests locally, with R2019 or R2020, they will never pass right?

**Comment by QilongTang** [comment]
@mjkkirschner Sure, thanks!

**Comment by QilongTang** [comment]
Closing since we don't have to remove the legacy version anymore seems.. If we do, this probably should be part of that PR

**Pull request closed without merging**
