### PR TITLE
[DYN-2834] Fix the issue where package manager extension object was being null 

### PR DESCRIPTION
**Pull request by reddyashish**
#Purpose

This PR fixes the regression introduced in 2.7. 

When the package is being installed from the workspace references, the SetPackageState() looses the reference to the pmExtension object and it is null. So it is throwing a null pointer exception and as a result of this the nodes are not being resolved. 
When you open the Search for a Package window, you can see this message.
Screen Shot 2020-06-17 at 5 59 17 PM

The package is actually downloaded but failed to load in Dynamo. 

So, reverting this part of the code to as it was before. 

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@QilongTang @mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I'm confused how this change introduced the regression?
Look's like it came from a code smell PR?

**Comment by mjkkirschner** [comment]
ahhh @reddyashish here's the issue:

https://github.com/DynamoDS/Dynamo/blob/0b8f36629c516ec318b8acb2a1966f12429b416f/src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerClientViewModel.cs#L188

this class has another field with the same name as that local variable - thats why this compiles at all - just change add the pmExtension as a parameter, change the name, or set the field, no need to revert the change.

**Comment by QilongTang** [comment]
@mjkkirschner @reddyashish Shall we just change this line to set the field instead of defining a local one? https://github.com/DynamoDS/Dynamo/pull/10779/files#diff-87708e28021df7b325448575f92c8e69R712

**Comment by mjkkirschner** [comment]
nice!
@reddyashish do you think you can write a test for this that would have failed?

**Comment by QilongTang** [comment]
@mjkkirschner Do you still prefer a test written before merging?

**Comment by reddyashish** [comment]
@QilongTang Discussed with Mike, about adding the test in a different PR because there are some issues with writing the test for this workflow. I am creating a task to followup it up. So merging this to unblock 2.7

**Pull request merged**
