### PR TITLE
[WIP] Update Dictionary Node Icons

### PR DESCRIPTION
**Pull request by Racel**
This is not updating in the library. Not sure what is going on since I needed to create a new resx.

https://jira.autodesk.com/browse/QNTM-3096

Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

(FILL ME IN) This section describes why this PR is here. Usually it would include a reference 
to the tracking task that it is part or all of the solution for.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@ramramps 
@alfarok 
@QilongTang

### CODE REVIEW

**Comment by Racel** [comment]
See the description above. Not sure what is going wrong. Also, do I need to add the Builtin.csproj to this PR?

**Comment by saintentropy** [comment]
@Racel I think you need to wait for Peters PR

**Comment by alfarok** [comment]
@Racel I can take a look at this tomorrow after Peters PR is merged since `Builtin` will be changing to `DesignScriptBuiltin`.  Can you also upload the .svg icon for the top level to google drive?

**Comment by alfarok** [comment]
We also need to update `libraryItems.json` with the additions or the tests will fail

**Comment by saintentropy** [comment]
@alfarok Lets talk in the morning because I did some work after talking to Racel

**Comment by saintentropy** [comment]
@Racel Sorry I pushed my changes to your branch.  Nothing bad just I thought I was pushing to my fork.   Anyway these changes will work after Peter's PR is merged.  Icons look good

screen shot 2018-03-06 at 10 23 32 pm

**Comment by saintentropy** [comment]
@Racel Do you have an icon for the top level Dictionary

**Comment by ramramps** [comment]
@saintentropy Are we good with this task? Can we merge this?

**Comment by aparajit-pratap** [comment]
@Racel @saintentropy could you undo the changes from Peter's PR? His PR is not being merged in. I'm making a new one such that the "Builtin" assembly (project) will not have to be renamed. Thanks.

**Pull request closed without merging**
