### PR TITLE
LibG Binaries Update

### PR DESCRIPTION
**Pull request by DynamoEngOps**
__LibG226__ 
CommitInfo:Martin Misol Monzo - Bump up version to 2.9 (#1012) 
SHA:[7e2e35129d86caefaa47e4069a56e18eaca56fb1](https://git.autodesk.com/Dynamo/LibG/commit/7e2e35129d86caefaa47e4069a56e18eaca56fb1)
Reviewer: Martin Misol Monzo

### CODE REVIEW

**Comment by mmisol** [comment]
I'll merge this to bump the version to 2.9 in master.

**Comment by aparajit-pratap** [comment]
@mmisol, I would wait for @alfredo-pozo's PR, which uses the latest LibG Nuget packages in the Dynamo build.
We are transitioning to the new nuget package way of consuming LibG binaries and will be discontinuing these PR drops.

**Comment by aparajit-pratap** [comment]
This was the PR I was talking about: https://github.com/DynamoDS/Dynamo/pull/11049

**Comment by mmisol** [comment]
I saw your comment a minute after I merged. Sorry about that.

**Pull request merged**
