### PR TITLE
Update Greg

### PR DESCRIPTION
**Pull request by pinzart**
### Purpose

includes fixes for increasing timeout to enable large package uploads.

### Declarations

Check these if you believe they are true

### CODE REVIEW

**Comment by mjkkirschner** [comment]
thanks @pinzart  - please don't update these package.config files manually - use visual studio `manage nuget packages` for the .sln so that all project references and the config files are updated together.

**Comment by mjkkirschner** [comment]
https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio

**Comment by mjkkirschner** [comment]
@pinzart all the builds checks are failing with:

```
"C:\projects\dynamo\src\Dynamo.All.sln" (default target) (1) ->
2298"C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj.metaproj" (default target) (2) ->
2299"C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj" (default target) (4) ->
2300(CoreCompile target) -> 
2301  Extensions\StartupParams.cs(5,7): error CS0246: The type or namespace name 'Greg' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2302  Core\AuthenticationManager.cs(3,7): error CS0246: The type or namespace name 'Greg' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2303  Core\AuthenticationManager.cs(4,7): error CS0246: The type or namespace name 'Greg' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2304  Models\DynamoModel.cs(39,7): error CS0246: The type or namespace name 'Greg' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2305  Core\AuthenticationManager.cs(19,29): error CS0246: The type or namespace name 'LoginState' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2306  Core\AuthenticationManager.cs(32,18): error CS0246: The type or namespace name 'LoginState' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2307  Core\AuthenticationManager.cs(48,16): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2308  Core\AuthenticationManager.cs(105,42): error CS0246: The type or namespace name 'LoginState' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2309  Core\AuthenticationManager.cs(14,26): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2310  Core\AuthenticationManager.cs(57,38): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2311  Extensions\StartupParams.cs(18,16): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2312  Extensions\StartupParams.cs(19,26): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2313  Extensions\StartupParams.cs(60,30): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2314  Models\DynamoModel.cs(494,13): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2315  Models\DynamoModel.cs(519,20): error CS0246: The type or namespace name 'IAuthProvider' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dynamo\src\DynamoCore\DynamoCore.csproj]
2316
2317    299 Warning(s)
2318    15 Error(s)
2319
2320Time Elapsed 00:00:17.16
2321
```

does this actually build locally?

**Comment by mjkkirschner** [comment]
perhaps something has gone wrong with the uploaded nuget?

**Comment by pinzart** [comment]
Builds fine locally...I'll take a look at it

**Comment by pinzart** [comment]
A lot of packages were not properly updated...
I guess I should have cleaned up the existing packages before trying to update to the new Greg.
All seems good now

**Pull request merged**
