### PR TITLE
DYN-5813-fix-failing-librariejs-builds

### PR DESCRIPTION
**Pull request by Enzo707**
### Purpose

This implements [DYN-5813](https://jira.autodesk.com/browse/DYN-5813) to fix failling librariejs builds

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB 

### Release Notes

This PR updates librariejs buils that didn't pass the jenkins tests

### Reviewers

@RobertGlobant20 @QilongTang 

### FYIs

@zeusongit

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by reddyashish** [comment]
@QilongTang @mjkkirschner Now we have another test failing with the same ASM loading exception: https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/8862/testReport/WpfVisualizationTests/.

**Review by QilongTang — CHANGES_REQUESTED** [review]
My bad @zeusongit noticed that this is not the minified version. Please update this PR

**Comment by reddyashish** [comment]
@Enzo707 You don't need the librarie.js, just the minified version.

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Well it also looks like the minified version of js is the same :) but still good spirit to update it after each change, merging

**Comment by reddyashish** [comment]
Cherrypick into 2.18?

**Comment by QilongTang** [comment]
> Cherrypick into 2.18?

I think no need

**Pull request merged**
