### PR TITLE
Moved various search tags to resource files

### PR DESCRIPTION
**Pull request by Benglin**
This pull request finishes what was left of [the original pull request](https://github.com/DynamoDS/Dynamo/pull/3583) from January.

Hi @pboyer, please have a look, thanks for catching the older one anyway!

### CODE REVIEW

**Comment by sharadkjaiswal** [comment]
Do we want to localize the search tags? If not we should not move them to resource file, unless we have a mechanism to tag them as non translatable.

**Comment by Benglin** [comment]
We have moved all search tags to `*.resx` file as part of the localization process. This enables us to do one thing, say if we have a way to search for *length* in a different language with the names `lorem` or `ipsum`, then the search tags can be appended to like this:

```
variable;argument;parameter;lorem;ipsum
```

**Comment by sharadkjaiswal** [comment]
but then it will fail to search for length in localized build.

**Comment by Benglin** [comment]
`NodeSearchTags` attribute class will handle the additional entries since it tokenizes them, so `lorem` and `ipsum` will be included in the search. Let me get this in to avoid confusion.

**Pull request merged**
