### PR TITLE
InCanvasSearch: right click on workspace

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-7197](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7197) DUI: Right click on canvas should bring up inline search bar

On right click on the canvas (blank canvas or groups) and not on the nodes, the library search bar should show up above the canvas menu.

This PR doesn't support pressing arrow keys when there are no search terms.
Result:
image

This PR should be merged after that: https://github.com/DynamoDS/Dynamo/pull/4511

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] The level of testing this PR includes is appropriate

### Reviewers

@pboyer 
@Benglin 

### FYIs

@lillismith

### CODE REVIEW

**Comment by pboyer** [comment]
@lillismith @elayabharath From my perspective, this seems unnecessary.  Why have two ways of doing the same thing?

**Comment by Benglin** [comment]
Ping @lillismith @elayabharath

**Comment by lillismith** [comment]
Let's try it.  I agree it's a little odd. I do think we need it on the context menu though for discoverability. Could just be "Search..." on the context menu, but that is an extra step.  Again, let's try EB's design for starters.

**Comment by elayabharath** [comment]
Very reluctant to add extra step to search from canvas menu even if this UI is a bit odd.

I actually think more people will use the right click and just start typing for search more than Shift + double click (unless this is replaced with a keyboard-only shortcut). 

Let's see how it is in action and take a call?

**Comment by aosyatnik** [comment]
@elayabharath , now they are the same.
image

**Comment by kronz** [comment]
@pboyer is not going to be available to review this (I don't THINK), and @Benglin is probably going offline.  Is there another person who could review this today?

**Comment by ramramps** [comment]
@aosyatnik  :  Value="{x:Static viewmodels:SearchViewModel+ViewMode.LibraryView}">  - Is this correct?  why there is "+" ?  
Also, you have to use "DataContext" and not refering the Viewmodel in XAML.
Sample: Binding="{Binding Path=DataContext.ViewMode.LibraryView, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:SearchView}},"

**Comment by aosyatnik** [comment]
Hi, @ramramps .
That is how enum sets in trigger: `{x:Static namespace:ClassName+EnumName.EnumValue}`

If Current mode is LibraryView, we show context menu items, otherwise we show found members of InCanvasSearch.

**Comment by ramramps** [comment]
@aosyatnik - Cant we use converter?  I would suggest using a converter rather than computing something on the XAML.

**Comment by ramramps** [comment]
@aosyatnik  like this 

<DataTrigger Binding="{Binding Path=DataContext.ViewMode, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:LibrarySearchView}}, Converter={StaticResource SearchViewConverter}}"
                         Value="true">

**Comment by aosyatnik** [comment]
Hi, @ramramps , thank you for review. I've added new converter and test for it. Please, take a look.

**Pull request merged**
