### PR TITLE
Bring Back Dummy Node Image

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

The dummy node image is missing since https://github.com/DynamoDS/Dynamo/pull/12504 so bring it back.
image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Bring Back Dummy Node Image, this is a regression from 2.13.0

### Reviewers

@DynamoDS/dynamo 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Review by zeusongit — APPROVED** [review]

**Comment by pinzart90** [comment]
@QilongTang  I found a couple more
https://github.com/DynamoDS/Dynamo/pull/12504/files?file-filters%5B%5D=.csproj&show-deleted-files=true&show-viewed-files=true#diff-51b5b124df8e1f4c98e626da934e8b6443ab158d85f0ca81534c8689e86c0769L133

**Comment by QilongTang** [comment]
@pinzart What's the best way to make sure we are not missing any resources from that previous PR?

**Comment by pinzart90** [comment]
> @pinzart What's the best way to make sure we are not missing any resources from that previous PR?

Well not sure if it is the best way...but I opened the previous PR...and loaded all the file diffs.
Then I searched for "Resources\" to located any removed resource items.

**Comment by QilongTang** [comment]
> > @pinzart What's the best way to make sure we are not missing any resources from that previous PR?
> 
> Well not sure if it is the best way...but I opened the previous PR...and loaded all the file diffs. Then I searched for "Resources" and "png" to located any removed resource items.

Thanks, I will add the missing ones all in this PR

**Pull request merged**
