### PR TITLE
Connector Visibility Fix When Nested group is not expanded.

### PR DESCRIPTION
**Pull request by M-JULIANI**
### Description

This PR fixes the bug illustrated below which was introduced in #12341.

_Bug:_
GroupExpand-ConnectorsPrevious

_Fix:_
GroupExpand-ConnectorsFix

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Fix Connector Visibility When Nested group is not expanded.

### Reviewers

@QilongTang 

### FYIs

@SHKnudsen 
@Amoursol

### CODE REVIEW

**Review by reddyashish — APPROVED** [review]

**Comment by Amoursol** [comment]
@M-JULIANI - Looks like the issue isn't fixed in the GIF's, was this just the wrong GIF uploaded?

**Comment by M-JULIANI** [comment]
> @M-JULIANI - Looks like the issue isn't fixed in the GIF's, was this just the wrong GIF uploaded?

@Amoursol the issue is in the first GIF. Notice the floating connector early on (the GIF is too long...)

**Comment by Amoursol** [comment]
@M-JULIANI - Ah! I see. Had confused this with the black wire dots being on the higher Z-value :)

**Comment by reddyashish** [comment]
Can you change the base branch to master first, so that we can verify there are no regressions.

**Comment by M-JULIANI** [comment]
> Can you change the base branch to master, so that we can verify there are no regressions. We can then cherrypick to 2.13

Done @reddyashish. Few conflicts to solve.

**Comment by M-JULIANI** [comment]
> according to commit history, this branch does not look clean, maybe based on RC2.13.0?

Yeah was told to base all future fixes based off RC2.13.0...

**Comment by QilongTang** [comment]
> > according to commit history, this branch does not look clean, maybe based on RC2.13.0?
> 
> Yeah was told to base all future fixes based off RC2.13.0...

I see, then let's use RC2.13 as merge base and cherrypick to `master` later

**Comment by reddyashish** [comment]
Self-serve has passed, @QilongTang Merging this.

**Comment by QilongTang** [comment]
@reddyashish I was going to ask for a unit test.. Can we make sure we do that in `master`? Maybe that can be merged to the cherry-pick PR by @M-JULIANI ?

**Comment by reddyashish** [comment]
Oh yes, we can do that. I will close the cherry-pick PR. @M-JULIANI Can you look into adding the test.

**Pull request merged**
