### PR TITLE
DYN-7435 Corrupted Chars ON CHS OS

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Fix for not showing weird characters in DocumentationBrowser in a CHS OS
When using a Windows 10 OS installed in Chinese Traditional if you open DocumentationBrowser several times for each node in the workspace, the DocumentationBrowser starts to show weird characters and the html layout seems different, this was happening due that the Md2Html.Convert and Md2Html.Sanitize methods were not executed, after my fix now they were executed but was still showing weird characters (due that Md2Html encoding was in Chinese Traditional). Then for fixing this problem I had to encode the info using base64 and decoded when is needed.
There was a freeze reported in the Jira task but I was not able to reproduce it after my fix.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Fix for not showing weird characters in DocumentationBrowser in a CHS OS

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
This is a GIF showing the behavior BEFORE my fix.
BeforeMyFix

**Comment by RobertGlobant20** [comment]
This is a GIF showing the behavior AFTER my fix
AfterMyFix

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
LGTM, Send this to @sm6srw to also review. 
Also, @RobertGlobant20 would you take a look at the self serve job? I suspect there might be some regressions related to the sanitization process

**Comment by RobertGlobant20** [comment]
> LGTM, Send this to @sm6srw to also review. Also, @RobertGlobant20 would you take a look at the self serve job? I suspect there might be some regressions related to the sanitization process

The net

**Pull request merged**
