### PR TITLE
Added New Getting Started Pages for 1.0

### PR DESCRIPTION
**Pull request by Racel**
### Purpose

Added New Getting Started Pages for 1.0 for http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9219

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any. See attached pdfs

### Reviewers
@kronz @riteshchandawar @Benglin - Please check these new pages. There are 2 versions of the images and xml files. The ones with a "-L" suffix are for localization. See attached pdfs for what each page contains.

[GettingStarted-1.0-Localized.pdf](https://github.com/DynamoDS/Dynamo/files/225145/GettingStarted-1.0-Localized.pdf)
[GettingStarted-1.0.pdf](https://github.com/DynamoDS/Dynamo/files/225144/GettingStarted-1.0.pdf)

### CODE REVIEW

**Comment by Racel** [comment]
@kronz @Benglin @riteshchandawar @monikaprabhu @jnealb - With this change, I realized that we need to also change the text on the Start Page from "What's New" to "Getting Started". We also need to add a menu item in the Help dropdown called "What's New". Can someone please help with these fixes? I am not sure how to do this. I will add this comment to the YT.

**Comment by Racel** [comment]
@kronz @Benglin @riteshchandawar @jnealb @monikaprabhu @QilongTang - I have updated this PR and removed the en-us version of images and xml. Only the images/xml that are ready for localization have been kept. I also changed the text on the Start Page.

@kronz - This is ready to merge after the checks pass. Let me know if it is ok.

**Comment by Racel** [comment]
All checks have passed. Closing and pushing to testing before cherry-picking into 1.0.

**Comment by kronz** [comment]
@Racel LGTM

**Pull request merged**
