### PR TITLE
DetectDynamoRuntimeCore

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Cherry-picking https://github.com/DynamoDS/Dynamo/pull/7417 in RC1.3.3_master branch so RC1.3.3 could use Dynamo.Config to detect runtime DynamoCore as well.

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### FYIs

@mjkkirschner @smangarole

### CODE REVIEW

**Comment by mjkkirschner** [comment]
so why is this required? I thought that this was added to the 2.0 branch as it builds on top of nugets, but the 1.3.3 branch requires building on top of dynamo repo, and should be copied there when built.

So, whats the point of this config?

**Comment by QilongTang** [comment]
@mjkkirschner This change has nothing to do with building itself but is required only for adding D4R as part of Revit package build. With RC1.3.3, on a computer without Dynamo Installation, currently there is no way to correct DynamoCore runtime.

**Comment by QilongTang** [comment]
@mjkkirschner To Clarify a bit more, with this change. D4R under Revit->Addin folder can refer to `Dynamo.Config` to lookup a local path containing DynamoCore. So Revit QA does not need to have DynamoCore installed locally as long as both DynamoCore and D4R comes with the package build of Revit.

**Comment by mjkkirschner** [comment]
gotcha

**Comment by QilongTang** [comment]
@mjkkirschner All check passed, I also finished my testing locally. Merging to unblock D4R integration work

**Pull request merged**
