### PR TITLE
DYN-6769 Improving Dynamo Load Graph II

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

With this change only will be executing the DefaultAutocompleteCandidates functionality only once at Dynamo startup, then when a graph is loaded won't be executed.
### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

With this change only will be executing the DefaultAutocompleteCandidates functionality only once at Dynamo startup, then when a graph is loaded won't be executed.

### Reviewers

@QilongTang

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Hi @RobertGlobant20 LGTM, can you demonstrate the performance improvement also as part of this PR?

**Comment by RobertGlobant20** [comment]
> Hi @RobertGlobant20 LGTM, can you demonstrate the performance improvement also as part of this PR?

I'm still trying to get the performance improvement numbers, basically the problem is that improvement is in the range of seconds but when I run dotTrace and Dynamo opening a dyn file, the loading time has a lot of variation (between each sample) so is hard to show the performance improvement.

**Comment by QilongTang** [comment]
> > Hi @RobertGlobant20 LGTM, can you demonstrate the performance improvement also as part of this PR?
> 
> I'm still trying to get the performance improvement numbers, basically the problem is that improvement is in the range of seconds but when I run dotTrace and Dynamo opening a dyn file, the loading time has a lot of variation (between each sample) so is hard to show the performance improvement.

Maybe use the timer to time the time spent on searching on each of the predefined keyword in the query, we are saving that much of time with each workspace open

**Comment by RobertGlobant20** [comment]
> > > Hi @RobertGlobant20 LGTM, can you demonstrate the performance improvement also as part of this PR?
> > 
> > 
> > I'm still trying to get the performance improvement numbers, basically the problem is that improvement is in the range of seconds but when I run dotTrace and Dynamo opening a dyn file, the loading time has a lot of variation (between each sample) so is hard to show the performance improvement.
> 
> Maybe use the timer to time the time spent on searching on each of the predefined keyword in the query, we are saving that much of time with each workspace open

I've used a StopWatch timer to get the time consumed when executing the Search for DefaultNodeAutocompleteCandidates, as you can see with my fix we are saving around 5 seconds due that the Search is executed only once (when Dynamo opens is executed two times and when a graph is opened is executed another two times).
image

**Comment by QilongTang** [comment]
@RobertGlobant20 Please also cherry-pick this

**Pull request merged**
