### PR TITLE
Improved integrity/privacy message in customizer dialogs

### PR DESCRIPTION
**Pull request by pboyer**
### Purpose

New privacy messages are propagated to both the invite and publish dialog for the customizer. 

With some style updates and workflow description: 

capture

The text is also in the publish dialog:

publish2

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@lukechurch 

### FYI

@Racel

### CODE REVIEW

**Comment by Racel** [comment]
LGTM, Peter. I would suggest a few styling tweaks, but I don't think they are critical to closing this task. We can discuss them later or when you want to do another pass at these UI elements.

**Comment by pboyer** [comment]
@Racel I'm open to style tweaks. Fire away.

**Comment by lukechurch** [comment]
lgtm

**Comment by Racel** [comment]
@pboyer- here are my suggestions. I have also attached the icons in varying forms. Let me know what you think and if the icons work for you.

dialogupdate-01

Icons:
dialogupdate-02
dialogupdate-03
dialogupdate-04
dialogupdate-05
dialogupdate-06
dialogupdate-07
dialogupdate-08
dialogupdate-09

**Comment by pboyer** [comment]
@racel yes!

**Comment by lukechurch** [comment]
I don't actually mind the warning text being a bit louder than usual. I don't want to give the impression this is just generic text that people don't need to read.

We'll be able to de-emph later on when we're out of test phase.

The other improvements are great.

**Comment by Racel** [comment]
Sounds good @lukechurch!

**Comment by sharadkjaiswal** [comment]
Can we use a simpler name for customizer, such as Dynamo playground?

**Comment by pboyer** [comment]
@Racel 

updated

b

**Comment by Racel** [comment]
@pboyer - LGTM!

**Pull request merged**
