### PR TITLE
Compile all UI nodes to static methods

### PR DESCRIPTION
**Pull request by ke-yu**
### Purpose

This PR restores PR #7178 - compile all UI nodes to static method. Detailed information please refer to #7178.

There are some regressions caused by this PR, but they should be fixed by PR #7773 
### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@aparajit-pratap

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
LGTM after #7773

**Comment by QilongTang** [comment]
@ke-yu Ping. Any reason not to merge this?

**Comment by aparajit-pratap** [comment]
@QilongTang we are under discussions with Zach, Racel, and Peter to merge pending language changes.

**Comment by aparajit-pratap** [comment]
This PR has been cross-merged here: https://github.com/DynamoDS/Dynamo/pull/8075

**Pull request closed without merging**
