### PR TITLE
DYN-7442 Search Nodes with Special Characters

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Fixing Search bug that is happening when searching nodes in which the name contain special characters.
When Searching nodes with special characters in the Name when Dynamo is in a different language than English was not getting the expected results, the problem was related to the Analyzer being used. In this fix I'm using the CustomAnalyzer providing the Dynamo language as a parameter, this will allow using the expected character set.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Fixing Search bug that is happening when searching nodes in which the name contain special characters.

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
GIF showing expected behavior in Spanish
vmPNu8tDrU

**Comment by RobertGlobant20** [comment]
GIF showing expected behavior in German.
aMoWXmACA3

**Comment by QilongTang** [comment]
@RobertGlobant20 There are two build errors from the build action, please address

**Comment by RobertGlobant20** [comment]
> @RobertGlobant20 There are two build errors from the build action, please address

I've submitted a fix for updating the public API, commit: https://github.com/DynamoDS/Dynamo/pull/15513/commits/2955a8fbb0cf6990abe235371470a5df445deb10

**Comment by QilongTang** [comment]
There are some regressions but seems unrelated, would you re-run https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16491/?

**Comment by RobertGlobant20** [comment]
> There are some regressions but seems unrelated, would you re-run https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16491/?

After re-running the job now is passing.
https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16493/

**Pull request merged**
