### PR TITLE
QNTM-3393: Performance issue in this VW graph

### PR DESCRIPTION
**Pull request by ColinDayOrg**
### Purpose
One of the hypothesized reasons for the performance issues in the VW graph is due to the saving of backup files while running Dynamo. The save time for this graph is extremely long (~33-36 seconds under the debugger). The reason for this was found to be due to testing for trace data to be saved. This PR makes the testing more efficient and reduces the save time (to ~2-3 seconds). Hopefully testing with D4R will show that the functionality is actually faster and not just broken for some reason by these changes.

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] All tests pass using the self-service CI.
- [X] Snapshot of UI changes, if any.
- [X] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@mjkkirschner 

### FYIs
@alfarok

### CODE REVIEW

**Comment by mjkkirschner** [comment]
also totally ok with getting this in for testing and writing a test in another PR.

**Comment by QilongTang** [comment]
@ColinDayOrg You mentioned we may want to skip backup saving while computing or there is no changes, do you plan to put that change in a separate PR?

**Comment by ColinDayOrg** [comment]
Ok, thanks. I am currently looking into testing this manually in D4R, and after I can verify that it actually works as intended I will take a look into the unit test. If it seems that it would be straight-forward to write the test I will write one, otherwise I will file a task to create one at a later date.

**Comment by ramramps** [comment]
@ColinDayOrg Agree on the unit test in separate task. I would like to get this PR at the earliest.

**Comment by ColinDayOrg** [comment]
@QilongTang If this fix works as intended then skipping the save of the backup while running may not be necessary any more. Note that this will require further testing, especially with a large graph with many notes. It will most probably be a separate JIRA task (if needed).

**Comment by ColinDayOrg** [comment]
@ramramps Ok, I will focus on manual testing first then.

**Comment by ColinDayOrg** [comment]
should these changes be merged? (i.e. before the unit test is created, a JIRA task has been filed for that)

**Comment by mjkkirschner** [comment]
@ColinDayOrg im okay with this coming in now.

**Pull request merged**
