### PR TITLE
Cherry Pick DYN-1476: AllowRankReductionAttribute on Zero Touch Properties (#9542)

### PR DESCRIPTION
**Pull request by scottmitchell**
* update

* Brought truncated search results and full query search out from behind debug menu. Deleted debug menu items.

* Added CheckForRankReductionAttribute() method to FFIMemberInfo

* Cleaned up CheckForRankReductionAttribute

* Added AllowRankReductionAttribute tests

* Comments. Change method name.

* Update tests, method name

* Corrected test names

* Fixed annoying diff

### Purpose

Cherry Pick [this PR ](https://github.com/DynamoDS/Dynamo/pull/9542) to 2.2.0

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### CODE REVIEW

**Comment by QilongTang** [comment]
LGTM 👍

**Comment by mjkkirschner** [comment]
lets wait on this until we resolve the failing test / question about where to use this attribute.

**Comment by aparajit-pratap** [comment]
@scottmitchell please update this test: https://github.com/DynamoDS/Dynamo/blob/0dbc0cc413cfa662f76879e3c496ef470b84b5ae/test/Engine/ProtoTest/Associative/MicroFeatureTests.cs#L1159 as the `Values` property has the `AllowRankReduction` attribute.

**Comment by mjkkirschner** [comment]
@aparajit-pratap - @scottmitchell and I wanted to talk to you first - and see what you thought about 
1.  why that attribute was used here in the first place and 
2. will is potentially break people's graphs
3. is it worth deferring until later? (3.0) to preserve current behavior. (ie, we remove the attribute to keep `values` working as it is today)

**Comment by aparajit-pratap** [comment]
@mjkkirschner I'm okay with removing the attribute from the `Values` property altogether, especially because its name indicates its plural and it therefore should be okay for users to expect that it will always return a list, even if it is a list of a single value.

**Comment by scottmitchell** [comment]
@mjkkirschner @aparajit-pratap Sounds good, I'll create a PR removing the attribute from Dictionary.Values, and I'll add a TODO to look at adding this for 3.0

**Comment by mjkkirschner** [comment]
so we can close this?

**Comment by scottmitchell** [comment]
@mjkkirschner Yeah we can close this. I wasn't sure if it was better to change this PR or just close it and make a new one.

**Comment by scottmitchell** [comment]
Or wait.. Do you mean merge this one? And then we'll cherry pick the follow up PR also?

**Comment by mjkkirschner** [comment]
no I meant close this PR without merging and then on the 2.2 branch all we need to do is cherry pick the other change right?

**Comment by mjkkirschner** [comment]
either is fine I guess. your call.

**Comment by scottmitchell** [comment]
Ok that makes sense. Closing this one.

**Comment by aparajit-pratap** [comment]
Wait, I'm confused. Why has this been closed? I thought this fix was for planned 2.2 also.

**Comment by QilongTang** [comment]
@mjkkirschner @aparajit-pratap @scottmitchell Sorry for the confusion but we only need to cherry-pick one more change into this PR and we are done. I think it makes best sense to do both changes from master in a single PR to 2.2.0

**Comment by scottmitchell** [comment]
@QilongTang @mjkkirschner @aparajit-pratap Both PRs are cherry picked. I'll merge once the checks complete.

**Comment by QilongTang** [comment]
@scottmitchell Glad it worked!

**Pull request merged**
