### PR TITLE
MAGN-8513 Ctrl + drag to duplicate nodes, groups, and notes

### PR DESCRIPTION
**Pull request by marimano**
### Purpose

When some nodes, groups, and notes are selected, they can be dragged by mouse with CTRL button pressed. 
During dragging semitransparant image of selection goes with mouse and becames real nodes, groups, notes when mouse is relesed. 
This operation can be undone by ctrl+z as any other operation in Dynamo.
Also it does not override Dynamo clipboard, i.e. is something was copied before, after dragging selection that copied content still is able to be pasted.

### Screenshot

Created by Windows Steps recorder to show mouse cursor.
drag

### Reviewers

@ikeough

### CODE REVIEW

**Comment by ikeough** [comment]
@marimano This is really cool. There is one feature that would be great to have, if possible. During the drag, can the connectors stay connected to their original ports and update as you drag? Currently they disconnect and stick out of the nodes, as seen here:

image

If Adorners don't support this, then can we hide the connectors during dragging, and only show them again, once the nodes have been pasted?

**Comment by marimano** [comment]
Hi @ikeough, to make connectors stay connected to their original ports it requires additional manipulating of dragged content relatively its dragged parent. As far as I use existing connector models and just create additional views for them to show inside dragged adorner, if I change its coordinates it will affect origin connectors. So it needs to create new connector models. But there is no way to manipulate connector coordinates other than to change coordinates of parent node. So it also needs to create fake parent nodes for those connectors whose one parent node is not selected and handle their positions.

As for me, this implementation requires much efforts when the improvement is not so substantial.
On the other hand, dragged selection without connectors at all feels incomplete.
I would prefer to show only connectors having both start and and node selected.

Please let me know if you have any objections as to my suggestion

**Comment by marimano** [comment]
@ikeough please take a look at the updated PR

**Comment by ikeough** [comment]
@marimano This feels much better without the ghost connectors. And it's pretty snappy for large selections. I was able to briefly get it into a state where the adorner didn't show up when I pressed `ctrl` and dragged a node. But I can't reproduce.

Your propsal is sensible. I've tried a number of configurations with connected and unconnected nodes, and it makes sense.

**Pull request merged**
