### PR TITLE
Update ScopeIf description

### PR DESCRIPTION
**Pull request by Amoursol**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

This PR updates the description of the **ScopeIf** node to better reflect it's behavior. Users should be able to better know when to use this node after this change.

ScopeIf_Description_Update

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@mjkkirschner
@QilongTang

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]
Warm welcome to @Amoursol 's first PR. LGTM. One thing to note is that, we can usually leave the changes in `AssemblySharedInfo.cs` out. Let's not bother in this PR though.

**Comment by Amoursol** [comment]
@mjkkirschner - does this description update accurately reflect your thoughts on the ScopeIf node?

**Comment by mjkkirschner** [comment]
@Amoursol two things
1. It appears the build failed - connection to the build agent was interrupted here: (check the log by clicking Dynamo SelfServe)
`10:54:20  Cannot contact Dynamo_Win_Perf: java.lang.InterruptedException`

I will kick off another build of this PR

what about
2.     `<value>Returns the result of either True or False input depending on what boolean value is toggled in the test input. Supports recursion which requires that only a single branch be executed. It's critical that that both True and False branches are isolated and do not interact with each other!</value>`

just to drive the point home?

**Comment by Amoursol** [comment]
> what about
> 2. `<value>Returns the result of either True or False input depending on what boolean value is toggled in the test input. Supports recursion which requires that only a single branch be executed. It's critical that that both True and False branches are isolated and do not interact with each other!</value>`
> 
> just to drive the point home?

Agreed @mjkkirschner - updated to your revised text.

**Comment by Amoursol** [comment]
@mjkkirschner should be ready for merge now if you are happy with it.

**Pull request merged**
