### PR TITLE
Aligns Styling of All ToolTips

### PR DESCRIPTION
**Pull request by OliverEGreen**
### Purpose

This PR aligns the styling of all tooltips in Dynamo to be `GenericToolTipLight`, except for any ToolTips currently using the `DynamoToolTip` UserControl (such as input/output ports).

l5QWFXEyTF

- Removed `SelfWrappingToolTip` style, since no longer in use.
- Removed `GenericToolTipDark` style, since no longer in use.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Updates styling of all ToolTips.

### Reviewers
@QilongTang 

### FYIs
@Amoursol 
@SHKnudsen

### CODE REVIEW

**Comment by QilongTang** [comment]
One regression
```
DynamoCoreWpfTests.ConverterViewModelTests.ConverterViewModel_TooltipTest
```

**Comment by mjkkirschner** [comment]
besides the failure this looks good.

**Comment by mjkkirschner** [comment]
@OliverEGreen @QilongTang I looked at this test - I'm actually not sure this test is possible to fix - so far I have not found a way in WPF to get the content of a tooltip without opening it when the tooltip itself is not a string (that is the change that @OliverEGreen made to the DynamoConverterXaml class) - 

BUT - this class is now obsolete anyway - I think it's acceptable to just remove that part of the test that checks this tooltip - it was apparently not even set to anything - the setter is never called except in this test...

**Comment by OliverEGreen** [comment]
Removed a single `Assert` statement in the test.

**Review by reddyashish — APPROVED** [review]

**Pull request merged**
