### PR TITLE
Fix location show form owner inside uninstall package

### PR DESCRIPTION
**Pull request by chuongmep**
### Purpose

this is a problem same with #12540, Fix location show message form uninstall package.
Before :
DynamoSandbox_Rf1C3QTSWj
After fixed

fuX7PE7Snj

image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Always initialize uninstall package dialog with the right owner window

### Reviewers

@QilongTang

### CODE REVIEW

**Comment by QilongTang** [comment]
Running self CI at https://master-15.jenkins.autodesk.com/view/DYN/job/DYN-DevCI_Self_Service/935/

**Comment by QilongTang** [comment]
1) Failed : DynamoCoreWpfTests.PackageManagerUITests.PackageManagerUninstallCommand
  Expected: ScheduledForUnload
  But was:  None
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at DynamoCoreWpfTests.PackageManagerUITests.PackageManagerUninstallCommand() in E:\Builds\chuongmep_Dynamo\owner_deletepackage\Dynamo\test\DynamoCoreWpfTests\PackageManagerUITests.cs:line 840

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
@chuongmep FYI:https://github.com/DynamoDS/Dynamo/wiki/Writing-Unit-Test-Libraries-for-Dynamo

**Comment by chuongmep** [comment]
> @chuongmep FYI:https://github.com/DynamoDS/Dynamo/wiki/Writing-Unit-Test-Libraries-for-Dynamo
Many thanks @QilongTang help me add test, may be I will down to VS2019 because NUnit 2 Test Adapter not yet in VS2022

**Pull request merged**
