### PR TITLE
MAGN-6964 Code changes to enable configuration of edge rendering for solids

### PR DESCRIPTION
**Pull request by ikeough**
### Purpose

This PR addresses [MAGN-6964](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6964). 

The Settings menu now contains a menu item for "Show Edges". When selected, the rendering in the view will automatically update to include edges of surfaces. The user's preference is saved in dynamo's preferences file. The next time the application is opened, the preference is set to its last saved state.  

## NOTE
**Reviewers must review all linked PRs. Approval of this PR is approval for the linked PRs.**

Show Edges = True
image

Show Edges = False
image

#### LibG
The signature for `IGraphicItem.Tessellate` is now `Tessellate(IRenderPackage package, TessellationParameters parameters)`. The `MaxTessellationDivisions` and `Tolerance` properties have been moved to the `TessellationParameters` object and an additional property, `ShowEdges` has been added. And instance of `TessellationParameters` is now stored on the `IRenderPackageFactory`.  
https://git.autodesk.com/Dynamo/LibG/pull/84
https://git.autodesk.com/Dynamo/LibG/pull/86
https://git.autodesk.com/Dynamo/LibG/pull/87

#### Reach  
Reach has been updated to use the `TessellationParameters` object.  
https://github.com/DynamoDS/Reach/pull/26

#### Revit  
Revit has been updated to use the `TessellationParameters` object.  
https://github.com/DynamoDS/DynamoRevit/pull/403
https://github.com/DynamoDS/DynamoRevit/pull/404
https://github.com/DynamoDS/DynamoRevit/pull/405

### Impact assessment

- [x] Changes the way 3rd party nodes work (Add ikeough to the reviewer list)
  - Third party nodes which implement IGraphicItem will need to be updated.
- [ ] Includes migrations (Add ikeough to the reviewer list)
- [x] Changes a public interface (Add lukechurch to the reviewer list)
- [ ] Affects which components of the system depends on which other components (Add pboyer to the reviewer list)
- [ ] Introduces new components (Add lukechurch to the reviewer list)
- [ ] Has a performance impact (Add keyu to the reviewer list)
- [ ] Changes the installer (Add sharadkjaiswal to the reviewer list)

#### Testing strategy

Automated Tests:
`PreferenceSettings_ShowEdges_Save()`
`PreferenceSettings_ShowEdges_Toggle()`
`PreferenceSettings_ShowEdges_DefaultFalse()`
`ViewSettings_ShowEdges_Toggled_GeometryIsCorrect()`

### Review staging

- [ ] Architectural Design Review
- [ ] UI Review

### Reviewers

@lukechurch - Architectural review of changes to ProtoInterface required for this work.
@pboyer - Architectural review of the changes to Reach for this work.
@lillismith - UI review for the Settings menu.

### CODE REVIEW

**Comment by lillismith** [comment]
Ian - are edge colors the same color as their display color? Not sure about the pink edges in the image above. I thought we had decided on just making them black.

**Comment by ikeough** [comment]
@lillismith, The edge colors are the default edge color (purple-ish) unless you're using `Display.ByGeometryColor` which colors them. We had not yet verified that the default edge color is black. It should be :)

**Comment by lukechurch** [comment]
@ikeough do we already have a TessellationParameters class? You don't seem to be defining it - unless I'm missing something very obvious.

**Comment by ikeough** [comment]
@lukechurch The `TessellationParameters` class is defined in the linked PR for LibG

**Pull request closed without merging**
