### PR TITLE
New Dynamo Logo with 3D Style

### PR DESCRIPTION
**Pull request by Thomas84**
### Purpose

* A new style of the Dynamo logo
* Added a 3D effect
* Adjusted the color tones
* 2 versions: Single Logo and Logo with text
* Provided for each a SVG file

Any suggestions are welcome. Apologies for bad practice - I'm not a professonal graphic designer.

Pictures are not used in the repo yet - this is just a call for feedback!

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [X] Snapshot of UI changes, if any.
- [X] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### CODE REVIEW

**Comment by QilongTang** [comment]
Thank you @Thomas84 , I will ask our dedicated UX - the professonal graphic designer you mentioned to review this if you dont mind :)

**Comment by eyount** [comment]
Hi @Thomas84 -- UX designer popping in here :) Thanks so much for submitting these ideas! A few questions:

1. What is the intended use of this new logo? (replacing the current one? for a particular part of the app? etc)
2. Is there a specific use-case you have in mind for a 3D logo for - where were you thinking this would fit in the UI?

**Comment by Thomas84** [comment]
> Hi @Thomas84 -- UX designer popping in here :) Thanks so much for submitting these ideas! A few questions:
> 
> 1. What is the intended use of this new logo? (replacing the current one? for a particular part of the app? etc)
> 2. Is there a specific use-case you have in mind for a 3D logo for - where were you thinking this would fit in the UI?

Hi @eyount, thanks for helping out! I think it looks more modern (similar to the other Autodesk Apps with the 3D letters). The main reason for me to create was to have a scalable svg for websites and a high resolution png for presentations. But I think it would be nice to have a new logo for Dynamo 3.0 that represents the improvements visually as well. Maybe you have other ideas? Is there a official "UI designer story" behind the logic of the logo? Connecting with dots? I have added the 3D effect, because I can xD No worry, please don't hesitate to tell me if a new logo is a bad idea :) I can reproduce the old look as well

**Comment by chuongmep** [comment]
I like your idea, changing the icons a little makes them easy to distinguish, I'm really tired of rolling out recent Revit versions with identical icons.

**Comment by johnpierson** [comment]
If I could be a bit honest here, I don't really like the 3d look. While a lot of other logos for products are 3d, I don't think Dynamo's needs to follow suit.

### To elaborate a bit more:
Dynamo's original logo is composed of connected links and represents the linking of software that dynamo is capable of, (Revit, AutoCAD, FormIt, etc).

### The new 3d logo does not represent this linking well at all because it is all joined (see below):
image

### Another thing I feel is important to emphasize:
Dynamo's simple flat logo represents what I think the community should be. Simple, but linked. Adding 3d into the mix strays away from this concept quite a bit. For reference, building geometry similar to the proposed logo is not something a beginner dynamo user would even do. 

One criticism I have often heard about the Revit splash screens is, **"Can you model that in Revit?"**.


### Proposed Logo Appearances

With that all being said, I think it is great for @Thomas84 to be looking at this and sparking this discussion. One thing I have to say is with this being a "proposed logo" it is a bit odd to be seeing it popping up in various places and can be very misleading or confusing to users..

Already Being Used on the LinkedIn Page:
image


---

Sidenote: the logo also reminds me of "bubble letters" and gives the logo too much of a balloon animal feel to me. _(this portion is really just opinion though)_
image

**Pull request closed without merging**
