### PR TITLE
record test for custom node automation-MAGN-6821"

### PR DESCRIPTION
**Pull request by zora-wang**
@monikaprabhu 
These are record test case for custom node conversion.
I just try to use NUnit to run test cases, but find lots of test cases in DynamocoreUItest are failed 
 
1.Custom Node without Input
Scenario:
    1. Create CBN and convert that into CustomNode
    2. Place this custom node and execute
    3. Verify the results of custom node instance are correct

2Create one input node
Scenario
    1.  Create one input node
    2.  Create one output node
    3.  Connect the above with single node in between
    4.  Place the custom node instance and connect with relavant inputs    

3.Create Multiple Input nodes
Scenario: 
     1. Create custom node with multiple input nodes
     2. Connect them to complete the graph
     3. Create instance of custom node and Execute.

4.Create Multiple Instances nodes
Scenario:
    1. Create custom node with multiple input nodes
    2. Connect them to complete the graph
    3. Create multiple instances of custom node and Execute.
    4. verify the results are correct

5 Single Instance
Scenario: Create a custom node inside another one

### CODE REVIEW

**Comment by sharadkjaiswal** [comment]
@zora-wang, Can you please summarize the scenarios that have been covered in these tests? That will help reviewers and other audience understand this PR better.

**Comment by Benglin** [comment]
@zora-wang @monikaprabhu, any updates on this one? It'll be nice if we can conclude this in the sprint.

**Comment by zora-wang** [comment]
@Benglin  The recording test cannot be tested due to custom node conversion.I close this PR first and reopen it  later after the custom node conversion bug is fixed

**Comment by zora-wang** [comment]
@monikaprabhu , Hey Monika, The custom node conversion has been updated, please help to review it ~~~

**Comment by monikaprabhu** [comment]
@zora-wang 
1. Please move the test scenario to inside RecordedTests.cs. Its should be easier to debug the test in the future. Fr eg: 
+        public void Defect_MAGN_6821_withoutInput()
+        {
+          
+                //1.Custom Node without Input
//Scenario:
//1. Create CBN and convert that into CustomNode
//2. Place this custom node and execute
//3. Verify the results of custom node instance are correct

2. If the tests are passing , please remove [Category("Failure")]

**Comment by monikaprabhu** [comment]
1. Please update the title of this PR "record test for custom node: test cases are failed" to "record test for custom node automation-MAGN-6821"

**Comment by monikaprabhu** [comment]
Zora, also run the entire .dll to check, other tests run without any error.

**Comment by monikaprabhu** [comment]
LGTM

**Pull request merged**
