### PR TITLE
Update ADP csharp wrapper to 4.0

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

updates ADP wrapper to version 4

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Updates ADP to version 4.0

### CODE REVIEW

**Comment by QilongTang** [comment]
@mjkkirschner Could you attach a screenshot of actual binary version?

**Comment by mjkkirschner** [comment]
Screen Shot 2021-11-22 at 3 44 24 PM

@QilongTang @pinzart90 does it make sense to increment the ADP analytics version to 2.13.1 or is 2.13 ok?

**Comment by QilongTang** [comment]
@mjkkirschner @pinzart I think 2.13.0 would be cool to keep in sync with Dynamo

**Review by QilongTang — APPROVED** [review]

**Comment by mjkkirschner** [comment]
I've moved this to draft, as I would like to discuss deprecated APIs in ADP 4 I was not aware of.

**Pull request closed without merging**
