### PR TITLE
InCanvasSearch: tooltip

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-7495](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7495) Enable tool tips in in-canvas search

Link to design document: 
http://adsk-oss.myjetbrains.com/youtrack/_persistent/In-CanvasSearchToolTips.pdf?file=65-6135&v=0&c=true

Result:
image

At the right edge of screen:

image

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] The level of testing this PR includes is appropriate

### Reviewers

@Benglin 
@pboyer 
@ramramps 

I don't know whom I should assign, that's why I assign everyone :)

### FYIs

@lillismith

### CODE REVIEW

**Comment by ramramps** [comment]
@aosyatnik - Can you have a unit test for this? You can simulate MouseEnter / leave behavior on a workspace.

**Comment by aosyatnik** [comment]
Hi @ramramps , I'm stuck. I wrote test and it passed. But next test, that uses UI-Dynamo part fails with null exception in Dispatcher. Maybe, you meant to wrote test in some other way? Could you, please, take a look. But don't merge it!

**Comment by ramramps** [comment]
@aosyatnik  - Can you tell me which test fails? The test you wrote is good. But I am worried why that has to fail another test.

**Comment by ramramps** [comment]
@aosyatnik - Not sure why this odd behavior. Remove the unit test for now and submit the request. We can check this later.

**Comment by aosyatnik** [comment]
@ramramps , I deleted test.

**Comment by ikeough** [comment]
@aosyatnik As @ramramps said, this LGTM. Let's bring it in. What's the error that you are getting when you run the test?

**Comment by aosyatnik** [comment]
Hi, @ikeough . If I run test separately, I don't get any error. But if I run my test with any other test, which class is derived from `DynamoTestUIBase` (e.g. `NodeViewCustomizationTests`). The next test will fail with `NullReferenceException` in  `Dispatcher`.

**Comment by ikeough** [comment]
Ok. Thanks @aosyatnik. Let's bring this in now. @Benglin or @riteshchandawar  might have some insight because they've looked at some of these back-to-back test problems before

**Comment by Benglin** [comment]
Those back-to-back issues we looked at before was due to resolving `nodes` folder location, not quite related to `Dispatcher`. What about `AnnotationViewTests`? It is also derived from `DynamoTestUIBase`, I don't see how yours is drastically different from `AnnotationViewTests`.

**Comment by aosyatnik** [comment]
Yes, I agree that `AnnotationViewTests` look similar to mine. I've tried use `DispatcherUtil.DoEvents()` as it was done in `AnnotationViewTests`. But it didn't help... I don't know... Maybe it's because I generate context menu in test... Or because I  force WPF to draw list box items...

**Pull request merged**
