### PR TITLE
Visual refresh shader update

### PR DESCRIPTION
**Pull request by Amoursol**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

As per https://jira.autodesk.com/browse/DYN-3958, updated the background geometry preview selection color to Blue 500 - a HIG aligned color that is more cohesive with the Visual Refresh project. 

**Existing color:**
image

**New color: Blue 500**
image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Updated background preview geometry selection color to align with visual refresh update. 

### Reviewers

@DynamoDS/dynamo 

### FYIs

@mjkkirschner

### CODE REVIEW

**Comment by Amoursol** [comment]
@QilongTang - My apologies on the AssemblyInfo update on this one, I had it ready to go and did a last minute rebuild. Let me know if you want me to resubmit the PR.

**Comment by mjkkirschner** [comment]
@saintentropy @aparajit-pratap - when you guys updated the shaders did you modify any of the settings? Like the disable optimizations flag?

Also curious about the changing sizes here, but I looked back in the history and the file size seems to bounce around historically.

**Review by mjkkirschner — APPROVED** [review]

**Comment by Amoursol** [comment]
> > @QilongTang - My apologies on the AssemblyInfo update on this one, I had it ready to go and did a last minute rebuild. Let me know if you want me to resubmit the PR.
> 
> All good, devs forgot about it sometimes and we still review it as regular PR. On the other hand, all the binary changes in this PR, how are they produced? I will add @mjkkirschner as reviewer as well

All of the binary changes were created with the CompileShaders.bat file - located here: https://github.com/DynamoDS/Dynamo/tree/master/src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource

**Comment by mjkkirschner** [comment]
@Amoursol  @aparajit-pratap  @QilongTang  - it's interesting that the image comparison tests did not fail here, they use a pretty big color fuzz factor so I guess color is close enough - @Amoursol ideally you should update them as well as part of this PR, I can walk you through that.

**Comment by Amoursol** [comment]
> @Amoursol @aparajit-pratap @QilongTang - it's interesting that the image comparison tests did not fail here, they use a pretty big color fuzz factor so I guess color is close enough - @Amoursol ideally you should update them as well as part of this PR, I can walk you through that.

More than happy to update! And would appreciate the help in the walkthrough 😊

**Comment by QilongTang** [comment]
@mjkkirschner Should we merge this or wait until the changes on other repo also merged?

**Comment by mjkkirschner** [comment]
The Changes to the images are in this repo, so we should wait.

**Comment by Amoursol** [comment]
@mjkkirschner this is updated now :) LMK if there is any additional stuff to do!

**Comment by mjkkirschner** [comment]
@Amoursol tests are running now, lets wait for them to pass.

**Pull request merged**
