### PR TITLE
Core utils api - DNM

### PR DESCRIPTION
**Pull request by junmendoza**

### CODE REVIEW

**Comment by junmendoza** [comment]
@aparajit-pratap - this is the PR for coreutils - whether you just merge it in or take the code, i dont mind. I just need to create a PR to track the youtrack issue

**Comment by lukechurch** [comment]
Tests?

**Comment by junmendoza** [comment]
@lukechurch sure specific tests will come. 
For now, it mainly here for @aparajit-pratap  to be able to try and integrate to his code and try out. It may end up being someplace else(i.e. not as a util function).
Marking it DNM for the moment.

**Comment by aparajit-pratap** [comment]
@junmendoza I have tested this code. Thanks. There are however cases where there are nested `IdentifierListNode`'s such as `Line.ByStartPointEndPoint(Point.ByCoordinates(...), Point.ByCoordinates(...));`. Such ASTs break as the traversal does not recurse into `IdentifierListNode`s.

**Comment by aparajit-pratap** [comment]
This has been merged into: https://github.com/DynamoDS/Dynamo/pull/3255

Closing ...

**Pull request closed without merging**
