### PR TITLE
REACH-295 Flood erroneously sends GetNodeGeometryMessage when unrelated node is added

### PR DESCRIPTION
**Pull request by marimano**
### Purpose

Marking modified nodes is already implemented in Dynamo. But there is no resetting `IsUpdated` property for the other nodes. In this PR `IsUpdated` property is reset right before re-evaluation. After re-evaluation is done, `IsUpdated` property will be set to true only for modified nodes, so it will have correct value.

It fixes not only [REACH-295](http://adsk-oss.myjetbrains.com/youtrack/issue/REACH-295), but [REACH-265](http://adsk-oss.myjetbrains.com/youtrack/issue/REACH-265) as well.

### Declarations

- [x] The code base is in a better state after this PR
- [ ] The level of testing this PR includes is appropriate

### Reviewers

@pboyer

### CODE REVIEW

**Comment by pboyer** [comment]
@Benglin - Could this cause any issues?  It looks very sensible...

**Comment by pboyer** [comment]
@marimano Can you run this PR on the self-service CI first?

**Comment by Benglin** [comment]
It looks naive enough but I'm a little uncertain simply because our `UpdateGraphAsyncTask` gets sent too many times and it's hard to tell what would happen. Worst case I can image here is: the first update graph request comes in, generates a bunch of AST, then sets `IsUpdated = false`. When the `UpdateGraphAsyncTask` completes, it sets `IsUpdated = true`. Immediately after this, another `UpdateGraphAsyncTask` gets generated and sets `IsUpdated = false`. This causes `UpdateRenderPackageAsyncTask` to do nothing (as a result it does not generate any graphics for a given node).

I would suggest testing (in Desktop Dynamo) upstream CBN with multiple statements that send values to downstream custom nodes. These custom nodes should generate geometries internally. Then update the code block node (probably also connect/disconnect the output connectors) to see if the custom node continues to generate desirable geometries.

If not, I'd suggest updating this instead of what you do:

```csharp
var nodeModel = initParams.Node;
if (!nodeModel.IsUpdated)
    return false; // Not has not been updated at all.

// Only reset here when the UpdateRenderPackageAsyncTask is generated
nodeModel.IsUpdated = false;
```

Let's see how the testing goes for this. Thanks!

**Comment by marimano** [comment]
hi @pboyer, I run those tests and the result is "9261 tests, 0 test errors, 2 test failures, 147 tests ignored". But in the log I cannot clearly see those two failed test cases. Is there any simpler way to see failed test cases rather than reading whole log, line by line?

**Comment by marimano** [comment]
hi @Benglin, I've got your idea, what about making reset of `IsUpdated` during execution of `UpdateGraphAsyncTask`? In this case `UpdateRenderPackageAsyncTask` will "see" correct values of `node.IsUpdated`, when it is being executed

**Comment by Benglin** [comment]
The mistake we currently made in our system is that accesses to `NodeModel` (or any model classes, for that matter) are not completely done on the UI thread, when they should be. Take for example, `UpdateGraphAsyncTask.HandleTaskCompletionCore` is guaranteed to be called on the `ISchedulerThread` context (and for `DynamoSandbox.exe`, that means a separate thread), and this is what it does today:

```csharp
protected override void HandleTaskCompletionCore()
{
    foreach (var modifiedNode in ModifiedNodes)
    {
        modifiedNode.IsUpdated = true;
        if (modifiedNode.State == ElementState.Warning)
            modifiedNode.ClearRuntimeError();
    }
}
```

And that is not thread-safe, imagine another UI component accesses these flags from the UI thread, the behavior is undefined. This is the source of the problem, we do not have a deterministic way to look at this, which brings me to my original point when I said *it's hard to tell what would happen*. We need to fix this.

If we were to do this right, we might have quite a bit of refactoring to do (I'm not suggesting that it needs to be done here, it's a long-time problem):

1. Move the contents of `UpdateGraphAsyncTask.HandleTaskCompletionCore` out into `HomeWorkspace.OnUpdateGraphCompleted` method, place it at the very beginning of `OnUpdateGraphCompleted`.

2. Move the new contents of `OnUpdateGraphCompleted` method into an `Action` and execute it through `Dispatcher.BeginInvoke` method, so all the method body gets called from a UI thread.

3. Keep the `EngineController.ReconcileTraceDataAndNotify` in `OnUpdateGraphCompleted` method (so it will execute before other UI codes) since it accesses `EngineController` and its underlying data.

I'm just looking at the code to arrive at the above observation, it obviously needs more thinking to be done (e.g. what if DynamoCore runs in headless mode where we don't have the concept of "UI thread"?).

For now I think it is safe is we do `IsUpdated = false` inside `UpdateRenderPackageAsyncTask.Initialize` when it is done reading its value (since `IsUpdated` is meant primarily for `UpdateRenderPackageAsyncTask`).

Does that make sense?

**Comment by marimano** [comment]
@Benglin , I'm not sure if I got it correctly:
> For now I think it is safe if we do IsUpdated = false inside `UpdateRenderPackageAsyncTask.Initialize` when it is done reading its value (since IsUpdated is meant primarily for UpdateRenderPackageAsyncTask).

Initially, all nodes has `IsUpdated=false`. When `UpdateGraphAsyncTask` task completes, it sets `IsUpdated = true` for a part of nodes. Then, `UpdateRenderPackageAsyncTask` sets this property to `false`, and we have `IsUpdated = false` for all nodes in the end. Therefore in Reach, we again cannot select modified nodes for `ComputationResponse`

**Comment by pboyer** [comment]
@marimano The self-service CI should have sent you an e-mail with the specific build results.  I'll try it again, tomorrow.

@Benglin I'll try and shepherd this in as carefully as possible.  Does that make sense?

**Comment by pboyer** [comment]
I'm running these tests now.

**Comment by Benglin** [comment]
Hi @pboyer @marimano, I'm okay with this if we do the following:

```csharp
class UpdateRenderPackageAsyncTask : AsyncTask
{
    internal bool Initialize(UpdateRenderPackageParams initParams)
    {
        ...

        var nodeModel = initParams.Node;
        if (!nodeModel.IsUpdated)
            return false; // Not has not been updated at all.

        // Reset the updated flag so we don't unnecessarily generate 
        // another UpdateRenderPackageAsyncTask later on.
        nodeModel.IsUpdated = false;
    }
}
```

Unfortunately this is the kind of things our test cases cannot catch due to the difference in threading behaviors. So if we can make this change, and then run the test, that'll be great. But thanks a lot for checking anyway, I suck at responding :(

**Comment by pboyer** [comment]
@marimano Can you update this in correspondence to @Benglin's suggestion?

**Comment by marimano** [comment]
@pboyer, @Benglin, the changes are done. But now it requires appropriate changes in Reach

**Pull request merged**
