### PR TITLE
PR - Jira Issues: [DYN-4017] Connector visibility from ports fix

### PR DESCRIPTION
**Pull request by M-JULIANI**
### Purpose

*Please merge #12016 before merging this PR. 

This PR addresses and fixes the following Jira issue:

[DYN-4017] https://jira.autodesk.com/browse/DYN-4017 Port hide/unhide wires flips the visibility. The way it now works is that port control of connector overrides individual control. However if an individual connector's control is switched, it will switch it for that connector. To normalize all of them to same visibility again, either use the menu->display->connectors->show connectors(on/off), or use the port control.
Port-Connector-VisibilityControlFixed

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers
@QilongTang 

### FYIs
@SHKnudsen

### CODE REVIEW

**Comment by QilongTang** [comment]
@M-JULIANI I am still confused by the gif you are showing. In the gif you have the first wire hidden, then when you got to the output port, the command still display as hide wires, what determines if Dynamo displays `hide` or `unhide` there when we have a mix of hidden, shown wires?

**Comment by M-JULIANI** [comment]
> @M-JULIANI I am still confused by the gif you are showing. In the gif you have the first wire hidden, then when you got to the output port, the command still display as hide wires, what determines if Dynamo displays `hide` or `unhide` there when we have a mix of hidden, shown wires?

@QilongTang as I understand it, I think it makes the most sense for the port command to be an `overwrite hide` or `overwrite show` command. That way it cares little for the state of the connectors. Having it do one or the other based on the connectors state would be very tricky as you could have any number of connectors and states.

**Comment by QilongTang** [comment]
> > @M-JULIANI I am still confused by the gif you are showing. In the gif you have the first wire hidden, then when you got to the output port, the command still display as hide wires, what determines if Dynamo displays `hide` or `unhide` there when we have a mix of hidden, shown wires?
> 
> @QilongTang as I understand it, I think it makes the most sense for the port command to be an `overwrite hide` or `overwrite show` command. That way it cares little for the state of the connectors. Having it do one or the other based on the connectors state would be very tricky as you could have any number of connectors and states.
> 
> I think it makes sense for the port command to be a somewhat global control, but if you would need granular visibility control of a single connector, then you would specify that at the connector level.

Thanks, that's a smart way to go. @Jingyi-Wen are you OK with that?

**Comment by QilongTang** [comment]
image

**Comment by Jingyi-Wen** [comment]
> > > @M-JULIANI I am still confused by the gif you are showing. In the gif you have the first wire hidden, then when you got to the output port, the command still display as hide wires, what determines if Dynamo displays `hide` or `unhide` there when we have a mix of hidden, shown wires?
> > 
> > 
> > @QilongTang as I understand it, I think it makes the most sense for the port command to be an `overwrite hide` or `overwrite show` command. That way it cares little for the state of the connectors. Having it do one or the other based on the connectors state would be very tricky as you could have any number of connectors and states.
> > I think it makes sense for the port command to be a somewhat global control, but if you would need granular visibility control of a single connector, then you would specify that at the connector level.
> 
> Thanks, that's a smart way to go. @Jingyi-Wen are you OK with that?

Yes, I think this makes the most sense!

**Comment by M-JULIANI** [comment]
> Looks like somehow this branch contains changes in #12016 as well? I will take a final look there again

Yeah I think once #12016 is fixed we can rebase to it, no? @QilongTang

**Comment by QilongTang** [comment]
> > Looks like somehow this branch contains changes in #12016 as well? I will take a final look there again
> 
> Yeah I think once #12016 is fixed we can rebase to it, no? @QilongTang

Tough to say.. It depends on if there will be additional changes there

**Comment by QilongTang** [comment]
@M-JULIANI Oops now this PR is no longer clean since some changes are already in master 😉

**Comment by M-JULIANI** [comment]
> @M-JULIANI Oops now this PR is no longer clean since some changes are already in master 😉 If you plan to make another PR you can either cherry-pick your changes there or fix this one

@QilongTang cool just resolved those conflicts.. Now we wait for it to build 😉

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
