### PR TITLE
Make RequestLaunchDynamo public

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

This PR is to make the RequestLaunchDynamo public on SplashScreen, which will be used by integrators.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section** 

### Reviewers
@QilongTang @zeusongit

### CODE REVIEW

**Comment by reddyashish** [comment]
PR on DynamoRevit: https://github.com/DynamoDS/DynamoRevit/pull/2891

**Review by zeusongit — APPROVED** [review]
Can you take a look at the failing check

**Comment by reddyashish** [comment]
This security job 'security/semgrep' seems to be failing for all PR's. No logs in there to see what is happening. Any idea?

**Comment by reddyashish** [comment]
Passed now.

**Pull request merged**
