### PR TITLE
REACH-292 Ensure Python nodes build/run on Linux Reach

### PR DESCRIPTION
**Pull request by pbidenko**
### Purpose

Task link: http://adsk-oss.myjetbrains.com/youtrack/issue/REACH-292

This PR moves the PythonNodeModel classes into a new library called PythonNodeModels and the Python WPF NodeViewCustomization implementations into PythonNodeModelsWpf.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] The level of testing this PR includes is appropriate

### Reviewers

@pboyer

### CODE REVIEW

**Comment by pboyer** [comment]
@pbidenko This looks really great!  You even checked to make sure that the syntax highlighting resources were properly migrated.  That makes my life so much easier.

The major risk here is migration of existing user's files.  We want to be sure that they can be opened correctly in Dynamo.  Can you confirm that this is the case?  There are two dyn files here that should work:  https://github.com/DynamoDS/Dynamo/tree/master/test/core/python

I should also recommend that you do a sanity check global search for the old assembly names to ensure that they are not referenced somewhere else.  

It also looks like DynamoRevit depends on DSIronPython, so we may need to make a PR for that as well.  Do you think you can do that?  

If you can confirm that is done, we should be able to merge this.

**Comment by pbidenko** [comment]
Hi @pboyer,

I've checked files from https://github.com/DynamoDS/Dynamo/tree/master/test/core/python, and they work fine, also I've opened file from https://github.com/DynamoDS/Dynamo/tree/master/test/core/WorkflowTestFiles/06%20Python and that file migrates successfully. So `PythonNodes` from files less than v6.3 (Dynamo.Nodes.Python) and less than v8.2 (DSIronPythonNode.PythonNode) should work fine.

Also I did "sanity check" and didn't find any references to the old assembly.

As for `DynamoRevit`, it should work fine, because it refers only one python library - 'DSIronPython.dll' and this library is still on its place and has necessary `IronPythonEvaluator` class. (DynamoRevit with references to the new libraries built successfully)

So I think we could try to merge this.

**Comment by pboyer** [comment]
@pbidenko Sorry for the enormous wait here. Do you think you could fix the merge conflict? This looks good to me.

**Comment by pboyer** [comment]
@pbidenko Can you please investigate why the appveyor build did not complete? I can't merge this...

**Comment by pbidenko** [comment]
@pboyer I've created <a href="https://github.com/DynamoDS/Dynamo/pull/5295">another PR</a> for this

**Pull request closed without merging**
