### PR TITLE
Some old files have been removed.

### PR DESCRIPTION
**Pull request by aosyatnik**
@Benglin , as discussed I have removed old files from Legacy folder. I ran tests, nothing seems to be broken.

Please, take a look.

### CODE REVIEW

**Comment by Benglin** [comment]
Hi @aosyatnik, thanks. Since `BrowserItem`, `BrowserInternalElement` and `SearchElementBase` are still used, we can move them out of `Legacy` folder and put directly under `src\DynamoCore\Search` folder.

Hi @pboyer, I'm just wondering if these are public classes and they are being used for code outside of main Dynamo repository? If not we'll proceed with the removal (and later made `internal` so that they can't be used anywhere else). Thanks!

**Comment by aosyatnik** [comment]
@Benglin , I moved `BrowserItem`, `BrowserInternalElement` and `SearchElementBase` under `src\DynamoCore\Search` folder.

**Comment by pboyer** [comment]
Hi @Benglin,

This looks good to me.  Today, these classes are used by the package manager.  I believe it's okay to make them `internal`.

**Comment by Benglin** [comment]
Thanks @pboyer for confirming it, merging this in!

**Pull request merged**
