### PR TITLE
Change default group font size

### PR DESCRIPTION
**Pull request by wynged**
Change the default font size to 30.

### CODE REVIEW

**Comment by Racel** [comment]
@wynged - I am changing this to 36...We think this is a better font size. But, I will check one more time before I change and merge. Thanks for this.

**Comment by andydandy74** [comment]
Would be way nicer to have this as a setting or at least have Dynamo remember the last font size that was used (see #5144).

**Comment by Racel** [comment]
@wynged @kronz - After reviewing large workspaces with @saintentropy, 36 looks better for bigger workflows when people would probably be grouping things more often. Can you please change to 36? Then we will merge.


@saintentropy is looking into @andydandy74's suggestion for both font and color. But, that will have to be handled in a separate PR.

**Comment by Racel** [comment]
Thanks @wynged! This PR LGTM. Merging and closing.

**Pull request merged**
