### PR TITLE
Asm225 support

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

* Cross merges release binaries of new libg branch to extern folder.
* simplifies dynamoCore project post copy step to copy all libG folders implicitly
* adds 225_0_0 to supported version list

### Declarations

Tests have not yet been run on self serve.

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@aparajit-pratap 
@alfarok 
### FYIs

@QilongTang @smangarole

### CODE REVIEW

**Comment by alfarok** [comment]
@mjkkirschner Looks good, I did notice there is no updated `ProtoGeometry.XML` file but it could just be that there are no changes from 224.4.0

**Comment by QilongTang** [comment]
Looks good, at some point we need to remove LibGs we are not going to test in the list which is a different task.

**Comment by QilongTang** [comment]
@mjkkirschner Can you fix the folder name to be libg instead of libG? It is not consistent and my local testing failed because our libg folder look up code is case sensitive 😉 
image

**Comment by mjkkirschner** [comment]
Aaron - it should not be case sensitive if you are using paths as this should be on windows - the folder names in the external folder are all upper case and my change to how they are copied moves them directly I believe .... unless it doesn’t ? Maybe it’s case sensitive ? Will look.

**Pull request merged**
