### PR TITLE
Update Open Template hotkey label

### PR DESCRIPTION
**Pull request by zeusongit**
### Purpose

Update hotkey label for open template.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

(FILL ME IN) Brief description of the fix / enhancement. **Mandatory section**

### Reviewers

@avidit @QilongTang

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by zeusongit** [comment]
> My bad, I think I noticed from last PR but forgot to point it out 👍🏻

I also found the conflicting hotkey:
https://github.com/DynamoDS/Dynamo/blob/765542d227f6d9ce810eb8b1823b2f2f25bd1b00/src/DynamoCoreWpf/Views/Core/DynamoView.xaml#L185

**Comment by QilongTang** [comment]
> > My bad, I think I noticed from last PR but forgot to point it out 👍🏻
> 
> I also found the conflicting hotkey:
> 
> https://github.com/DynamoDS/Dynamo/blob/765542d227f6d9ce810eb8b1823b2f2f25bd1b00/src/DynamoCoreWpf/Views/Core/DynamoView.xaml#L185

Oh I am pretty sure we obsoleted presets function so maybe we can just take the shortcut instead of using `Shift`. You can search the code for that command, I bet no reference?

**Comment by zeusongit** [comment]
> > > My bad, I think I noticed from last PR but forgot to point it out 👍🏻
> > 
> > 
> > I also found the conflicting hotkey:
> > https://github.com/DynamoDS/Dynamo/blob/765542d227f6d9ce810eb8b1823b2f2f25bd1b00/src/DynamoCoreWpf/Views/Core/DynamoView.xaml#L185
> 
> Oh I am pretty sure we obsoleted presets function so maybe we can just take the shortcut instead of using `Shift`. You can search the code for that command, I bet no reference?

The command is referencing this method:
https://github.com/DynamoDS/Dynamo/blob/765542d227f6d9ce810eb8b1823b2f2f25bd1b00/src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs#L2541

**Comment by QilongTang** [comment]
I got confirmation from @Amoursol that we can take `Ctrl + T` for template function because preset function should have been deprecated

**Comment by zeusongit** [comment]
> I got confirmation from @Amoursol that we can take `Ctrl + T` for template function because preset function should have been deprecated (We were supposed to remove all the code related in 3.0 but did not have scope)

Alright, I will amend the PR accordingly.

**Comment by zeusongit** [comment]
Is it fine to mark `ShowNewPresetStateDialogAndMakePreset` as obsolete:

**Comment by QilongTang** [comment]
> Is it fine to mark `ShowNewPresetStateDialogAndMakePreset` as obsolete?

Yes

**Pull request merged**
