### PR TITLE
Corrected minor mistakes in gallery content

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

This PR corrects a few minor grammatical mistakes in the "What's New" gallery pages.

### Reviewers

@kronz  Reviewer 1 
@jnealb   Reviewer 2

### CODE REVIEW

**Comment by jnealb** [comment]
LGTM

**Comment by kronz** [comment]
LGTM

**Comment by kronz** [comment]
@aparajit-pratap not sure if there is anything else to do on this.

**Comment by aparajit-pratap** [comment]
@kronz thanks for reviewing this. I have cross-merged this into RC_081 as well.

**Pull request merged**
