### PR TITLE
Remove *.2012.sln files, rename Dynamo.All.2013 -> Dynamo.All

### PR DESCRIPTION
**Pull request by pboyer**
### Purpose

Our 2012 solution often ends up out of sync. This PR simply removes it.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@sharadkjaiswal @aparajit-pratap 

### FYIs

@ikeough

### CODE REVIEW

**Comment by ikeough** [comment]
@pboyer LGTM. As long as none of the CI projects use the 2012 solution.

**Comment by aparajit-pratap** [comment]
@pboyer thanks! Let me confirm with the EngOps team before we merge this in. Will update soon.

**Comment by pboyer** [comment]
@aparajit-pratap Ping!

**Comment by ikeough** [comment]
@aparajit-pratap @pboyer I got confirmation from @limrzx that we are only using the 2013 solution. We should merge this.

**Comment by aparajit-pratap** [comment]
@limrzx we need to update all CI settings to align with the new .SLN filename, i.e. change `Dynamo.All.2013.sln` → `Dynamo.All.sln`

**Comment by aparajit-pratap** [comment]
@pboyer please go ahead with merging this. Will follow up with @limrzx to update CI.

**Comment by DynamoEngOps** [comment]
Noted, i will update CI once this is merged.

**Comment by pboyer** [comment]
@aparajit-pratap as you're colocated, do you think you could merge this so
that @limzrx can quickly update the ci? I don't want to destabilize the
builds...

**Comment by DynamoEngOps** [comment]
i have created #5512 to update build.xml with the new sln file name. That's all we need. @aparajit-pratap please merge both together to avoid build failure in CI.

**Pull request merged**
