### PR TITLE
Fix non-array item search for dot operation

### PR DESCRIPTION
**Pull request by mmisol**
### Purpose

When an array is passed to the dot operation, it needs to get an item
to determine the actual class being processed. This was done in
ArrayUtils.GetFirstNonArrayStackValue, but the function only checked
the first item of the array and its descendants. This caused the dot
operation to failed when passed an array that contained an empty array
as its first item.

In order to fix the problem, the function was changed to check for
non-array items in the entire array. The function should stop as soon
as the first non-array item is found.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@mmisol can you design a pathologically bad test case for this change?

**Comment by mjkkirschner** [comment]
I think we'll need to be careful here regarding performance - I remember that @reddyashish and @aparajit-pratap implemented a few solutions that worked but had surprising performance issues with actual user data.

**Comment by mmisol** [comment]
@mjkkirschner Do you have any suggestions? Just wanted to note that the function is not slower than what it was in scenarios where it actually worked.

**Comment by mjkkirschner** [comment]
@reddyashish might remember better than me, or @Amoursol may have a better sense for a general limit to nesting in common user workflows.

What happens if the array only contains an empty array 1000 levels deep as the last item? Will it iterate through the entire array?

**Comment by mmisol** [comment]
> What happens if the array only contains an empty array 1000 levels deep as the last item? Will it iterate through the entire array?

It would. Should we not use recursion to contemplate that level of nesting?

**Comment by reddyashish** [comment]
I am not aware about the general limit on nesting in user workflows but it makes sense for this function to be recursive. We would need the input type for the zeroth nesting level and that would set the replication criteria. 

Lets run the performance tests with these changes and see if that shows any difference?

**Comment by mmisol** [comment]
@mjkkirschner Would you say these changes are good to go? Let me know if not. Thanks!

**Comment by QilongTang** [comment]
@mmisol Can you talk about the average scale of problem size we are addressing here? I do agree this code is performance sensitive but I also would like to get a sense of how many entries we are iterating usually.

**Comment by mmisol** [comment]
@QilongTang I think I can give you a theoretical idea of the order of this algorithm. Being `n` the number of nodes and `p` the number of levels of the input, you could say best case scenario is `o(p)` and worst case scenario is `o(n)`.

To give you an average I would have to base on an actual dataset, which I don't think we have. However, worst case scenarios are triggered by multi-level and extremely sparse inputs, which my intuition tells me might be uncommon. Therefore I estimate the average would continue being `o(p)`

**Comment by mjkkirschner** [comment]
let's merge it and pay attention to the performance tests.

**Comment by mmisol** [comment]
@mjkkirschner Can you please approve?

**Comment by Amoursol** [comment]
@mjkkirschner @mmisol Did you still need clarity on what kind of nesting users will do with DesignScript?

**Comment by mmisol** [comment]
@Amoursol In the end we settled for running the performance tests after merging this.

I guess the question Mike raised was about how deep was the deepest nested `List` you have seen in practice in Dynamo. For instance, have you ever seen a `List` of `List` of `List` ... of `List` with ... representing a repetition of around 1000 levels? I hope not :)

**Comment by Amoursol** [comment]
The deepest List I've seen in practise is around 4-5 levels - I've seen some random things beyond that on the on the Forum but we probably don't need to worry about it. In reality managing lists that deep is pretty difficult for users. 

Typically it's List / List of Lists / List of List of Lists.

**Pull request merged**
