### PR TITLE
Update the Outport Margin

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose
Update the Outport margin
https://jira.autodesk.com/browse/DYN-4819

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

###Reviewers  
[@QilongTang](https://github.com/QilongTang)

###FYIs  
[@RobertGlobant20](https://github.com/RobertGlobant20) [@filipeotero](https://github.com/filipeotero)

### CODE REVIEW

**Comment by jesusalvino** [comment]
output

**Comment by jesusalvino** [comment]
> Hi @jesusalvino sorry to get to this one late. Can you show us a before and after image somehow? Is the output port now closer to the edge or further away?

The issue was the extra grey hover color to the right of the port

imagen

**Comment by jesusalvino** [comment]
> @jesusalvino Is the last image the current state?

The image has been updated: the first couple of images: normal / on hover are the current state

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Checked there is no real regression. Will merge to make a bit more testing

**Pull request merged**
