### PR TITLE
Updating Node Autocompletion documentation.

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

Update Node Autocompletion documentation.

Task: https://jira.autodesk.com/browse/DYN-4181

Node Autocompletion documentation

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Update Node Autocompletion documentation.

### Reviewers

@QilongTang 

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by QilongTang** [comment]
hi @reddyashish any gif in right side panel needs updating?

**Comment by reddyashish** [comment]
Yes, the layout was changed after that. I will change them too.

**Comment by QilongTang** [comment]
> Yes, the layout was changed after that. I will change them too.

Cool. Once gif updated and screenshots of UI updated in PR. We can move this forward

**Comment by reddyashish** [comment]
Updated the gif's in documentation.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
