### PR TITLE
Remove references from about box

### PR DESCRIPTION
**Pull request by aosyatnik**
### Purpose

Link to YouTrack:
[MAGN-9579](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9579) Remove extraneous references from About box

Result:
image

### Declarations

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.

### Reviewers

@marimano 

### FYIs

@Racel 
@kronz

### CODE REVIEW

**Comment by Racel** [comment]
@kronz - PTAL

**Comment by Racel** [comment]
@aosyatnik - we do not know how to review this based off of the screenshot. We need to see the actual about box.

**Comment by aosyatnik** [comment]
@Racel you need to run Dynamo and open about box.

**Comment by Racel** [comment]
@aosyatnik - Yes, please work with @marimano to merge this task so that we can verify :)

**Pull request merged**
