### PR TITLE
QNTM-5580 - Correct Typo in the Dynamo json serialization to match CoGS API

### PR DESCRIPTION
**Pull request by saintentropy**
### Purpose

The purpose of this PR is to correct a typo in the Dynamo serialization of the `Outputs` property as defined in the CoGS spec.  Currently the `InitialValue` property is written as `IntitialValue`.  This PR corrects that issue so Dynamo will serialize the `Outputs` json in the Dynamo file per the CoGS spec.  Note `IntitialValue` is a public property so it remains in the node but is now marked as Obsolete.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner @alfarok 

### FYIs

@sm6srw @QilongTang @nonoesp

### CODE REVIEW

**Comment by mjkkirschner** [comment]
It appears to me this this PR is using c# 7.0 features. I do not think thats recommended at this time as we have not all updated to 2017 at this point - the build targets 4.5.2 and won't even build without older sdks present. I would use c#6 max and update to 7.0 features if we update to 4.6 or 4.7 target later. I will be looking at that soon (or someone on Plaid will)

**Comment by mjkkirschner** [comment]
please note the failing builds.

**Comment by mjkkirschner** [comment]
@saintentropy whats with the failing engops build?

**Comment by saintentropy** [comment]
@mjkkirschner engops build passes

**Comment by mjkkirschner** [comment]
@saintentropy this looks good to me.

**Pull request merged**
