### PR TITLE
Python Script Tab Folding Strategy update

### PR DESCRIPTION
**Pull request by dnenov**
### Purpose

A follow up PR for the recent changes to the Python script editor. Works on the Tab Folding Strategy to rectify some odd behavior around tabs not appearing when used immediately after another closed tab sequence. The tab folding logic was re-written from scratch and should be simpler to read and executes correctly.

#### Tab Folding 
folding logic

### Declarations

Check the PR to see if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

- rewrote the logic for tab folding
- should follow the regular Python folding behavior
- based on a tab of 4 space values

### Reviewers

@QilongTang 
@reddyashish 

### FYIs

@Amoursol

### CODE REVIEW

**Comment by QilongTang** [comment]
Can we add one unit test for this?

**Comment by dnenov** [comment]
> Can we add one unit test for this? Just hoping the edge case is covered with test since I think you have tests for basic cases already.

Absolutely, I just added one, only it I opted for a UI test, in order to get hold of the Avalon edit instance and assert the number of tabs. If you think that's not a good strategy, let me know what you would have preferred to use her, @QilongTang !

**Comment by reddyashish** [comment]
Tab folding is not working when except keyword always:
Screenshot 2023-04-01 at 12 37 15 AM

**Comment by QilongTang** [comment]
The reported regression is a sporadic one

From our internal discussion https://autodesk.slack.com/archives/C1866AFQB/p1680717374613279, merging this and continuing to work once @dnenov is back.

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
