### PR TITLE
Don't fail to parse urls from warning messages that include repeated warnings.

### PR DESCRIPTION
**Pull request by mjkkirschner**
### Purpose

This PR fixes two issues with the documentation browser:
1. DereferencingANonePointer exception was mis spelled.

2. Sometimes during delta execution warnings will have different expressionIDs assigned for certain nodes that are composed of multiple expressions - like a multi-output node.

The end result is that the warning text is composed of multiple warnings like:

``` Dereferencing null pointer - DereferencingNonePointer.html/n Dereferencing null pointer - DereferencingNonePointer.html/n Dereferencing null pointer - DereferencingNonePointer.html ```

The code that parses url's expected that all warning strings would only be composed of a single single url - instead we make the splitting a bit smarter, by also using the same delimiter that is used to join the warnings. 

This code returns the first url found.

###
TODO 
- [x] tests

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Fixed a bug where documentation for errors could not be found, or reported illegal characters in the documentation browser.

### CODE REVIEW

**Review by sm6srw — APPROVED** [review]
LGTM!

**Comment by pinzart90** [comment]
@mjkkirschner do you think that other parts of dynamo could misbehave because of the `Delta execution warnings will have different expressionIDs` issue ?

**Review by pinzart90 — APPROVED** [review]
LGTM

**Comment by mjkkirschner** [comment]
@pinzart90 - I'm not sure, I actually think that the delta execution behavior is correct, and the first execution only containing a single expressionID is incorrect - it just happened that this masks the documentation issue when testing simple interactions.

**Pull request merged**
