### PR TITLE
090 Whats New Updates

### PR DESCRIPTION
**Pull request by Racel**
Purpose

Updated What's New Pages for 0.9.0. Please take a look and let me know if any changes need to be made. This will need to be cherry-picked into the 090 release branch.

Declarations

Check these if you believe they are true

The code base is in a better state after this PR
Reviewers
@lillismith 

FYIs
@kronz 
@RodRecker 
@jnealb

### CODE REVIEW

**Comment by Racel** [comment]
@lillismith - please merge when you think this is ready

**Comment by Racel** [comment]
@lillismith - Made the changes we discussed. Please take a look and merge when you feel it is ready. I reassigned the task back to you.

**Comment by Racel** [comment]
@lillismith - a few more changes after talking with @jnealb.

**Comment by Racel** [comment]
@lillismith - please take a look again. I updated the text and the last image.

**Comment by kronz** [comment]
Don't forget to cherry pick!

**Pull request merged**
