### PR TITLE
DYN-5149: Pins included in selection

### PR DESCRIPTION
**Pull request by ivaylo-matov**
### Purpose

Small PR that adds related Connector Pins to selection when user uses Tab key to select neighboring nodes.

DYN-5149-fix

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [x] This PR modifies some build requirements and the readme is updated
- [x] This PR contains no files larger than 50 MB

### Release Notes

When selecting a node and hitting "tab" it automatically adds the connected nodes to the selection. This is super handy for moving groups of nodes around.  The selection will now include not only the next connected node, but all pins of the connectors at the same time. 

### Reviewers

@dnenov
@reddyashish

### FYIs

@Amoursol

### CODE REVIEW

**Review by QilongTang — APPROVED** [review]

**Comment by mjkkirschner** [comment]
Tests seem like they would be straight forward to add to this? When the command is invoked ensure the selection is correct?

**Comment by QilongTang** [comment]
Thanks @mjkkirschner , @ivaylo-matov Would you add a unit test for this chang?

**Comment by ivaylo-matov** [comment]
@QilongTang Sure, will do.

**Comment by Amoursol** [comment]
@ivaylo-matov for histories sake, can you please create a super quick GIF showing this behavior in action and put it into this PR?

**Comment by ivaylo-matov** [comment]
@Amoursol, all done! I'll make sure to include gifs from now on.

**Comment by Amoursol** [comment]
> @Amoursol, all done! I'll make sure to include gifs from now on.

Brilliant, and thank you very much. This helps a lot :D So yes please to every PR having them if they can be there.

**Pull request closed without merging**
