### PR TITLE
[DYN-3984] More than three icons in a collapsed group

### PR DESCRIPTION
**Pull request by SHKnudsen**
### Purpose

This PR partially handles [DYN-3984](https://jira.autodesk.com/browse/DYN-3984).
The solution here is build based on the mockup provided here: https://www.figma.com/file/rET1Ey29lUcTspVAwoJ9Vg/Group-New?node-id=0%3A1

Will handle nested groups in a separate PR.

image

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@QilongTang 

### FYIs

@Jingyi-Wen 
@Amoursol

### CODE REVIEW

**Comment by Amoursol** [comment]
Hi @SHKnudsen - Still looks like the icons are 5 here, not 3?

**Comment by SHKnudsen** [comment]
> Hi @SHKnudsen - Still looks like the icons are 5 here, not 3? 

Oh might have misunderstood then... Thought it was max 3 inputs and 3 outputs. Is it 3 in total?

**Comment by Amoursol** [comment]
> > Hi @SHKnudsen - Still looks like the icons are 5 here, not 3?
> 
> Oh might have misunderstood then... Thought it was max 3 inputs and 3 outputs. Is it 3 in total?

Ah yeah in total :) The thought was to have 3 counters, essentially, as the input and output ports show the context. 

So it would be [<count of nodes with inputs created>][<count of nodes inside with no input or output ports>][<cont of nodes with outputs created>] and just have number counters in all of those boxes. I think @Jingyi-Wen has a mockup of this!

**Comment by SHKnudsen** [comment]
> > > Hi @SHKnudsen - Still looks like the icons are 5 here, not 3?
> > 
> > 
> > Oh might have misunderstood then... Thought it was max 3 inputs and 3 outputs. Is it 3 in total?
> 
> Ah yeah in total :) The thought was to have 3 counters, essentially, as the input and output ports show the context.
> 
> So it would be [< count of nodes with inputs created >][< count of nodes inside with no input or output ports >][< count of nodes with outputs created >] and just have number counters in all of those boxes. I think @Jingyi-Wen has a mockup of this!

😥😥😥
Alright, so there was one mockup attached in Jira
image

I assumed the counter here was the "Inbetween" nodes counter, as the figmas look different with node icons
image

There is a lot of figma bords named `DISREGARD` - assuming that those are not valid.

Would be very nice to get the latest mockup, this was a lot of wasted work (because of WPF).

If what is in Jira is the final valid mockup from what i can see that means we just have a single counter that counts all of the groups content

**Comment by Jingyi-Wen** [comment]
> > > > Hi @SHKnudsen - Still looks like the icons are 5 here, not 3?
> > > 
> > > 
> > > Oh might have misunderstood then... Thought it was max 3 inputs and 3 outputs. Is it 3 in total?
> > 
> > 
> > Ah yeah in total :) The thought was to have 3 counters, essentially, as the input and output ports show the context.
> > So it would be [< count of nodes with inputs created >][< count of nodes inside with no input or output ports >][< count of nodes with outputs created >] and just have number counters in all of those boxes. I think @Jingyi-Wen has a mockup of this!
> 
> 😥😥😥 Alright, so there was one mockup attached in Jira image
> 
> I assumed the counter here was the "Inbetween" nodes counter, as the figmas look different with node icons image
> 
> There is a lot of figma bords named `DISREGARD` - assuming that those are not valid.
> 
> Would be very nice to get the latest mockup, this was a lot of wasted work (because of WPF).
> 
> Is the mockup attached in Jira the final valid mockup? from what i can see that means we just have a single counter that counts all of the groups content

Hi @SHKnudsen  Yes this one on Jira is the latest. Apologize for the confusion of the many disregard pages in Figma. Here's the final design for items that needed to be updated https://www.figma.com/file/rET1Ey29lUcTspVAwoJ9Vg/Group-New?node-id=0%3A1

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
