### PR TITLE
Adjust the back and next button on guided tour popup and add keyboard…

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

This PR is to adjust the click area for back and next buttons on guided tour popup and user can navigate the steps using the keyboard arrow keys. The one thing that needs to be done is that the popup window should be focused to react to keyboard buttons. I am looking into some options for this. 

Task: https://jira.autodesk.com/browse/DYN-3972

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Adjust the back and next button on guided tour popup window.

### Reviewers

@QilongTang @filipeotero @RobertGlobant20

### CODE REVIEW

**Review by RobertGlobant20 — APPROVED** [review]
Looks Good To Me

**Comment by QilongTang** [comment]
@reddyashish Would you add some visuals to this PR?

**Comment by reddyashish** [comment]
GuidedTour

**Comment by QilongTang** [comment]
@reddyashish Perfect! Would you cherry-pick this as well?

**Pull request merged**
