### PR TITLE
Add more access key support in Dynamo

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

Adding more access key support in Dynamo. A detailed technical explanation can be found at https://wpf-tutorial.com/control-concepts/access-keys/

image

- Help using `Alt + H`
- Debug using `Alt + B` since D and E all taken
- Extension using `Alt + X` since E taken by `Edit`
- Save As using `Alt + A` since S taken by `Save`
- Audit of submenu items finished. Updates are part of this PR

image

image

image

image

image

image

image

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Release Notes

Audit of access keys for all main level menu items. Updates are made to unresolved keys.

### Reviewers

@DynamoDS/dynamo 

### FYIs

@Amoursol @Jingyi-Wen

### CODE REVIEW

**Comment by zeusongit** [comment]
Can you clarify if `Save As` is triggered by `Alt + A` or `Ctrl + Shift + S`  or both?

**Comment by QilongTang** [comment]
> Can you clarify if `Save As` is triggered by `Alt + A` or `Ctrl + Shift + S` or both?

`Ctrl + Shift + S` is a direct trigger, access key is for root level menu items, in this case user will need to press `Alt + F` to go to File menu and press `A` without `Alt`. Hopefully it makes sense.

**Comment by zeusongit** [comment]
Ok, thanks, that clears it.

**Comment by mjkkirschner** [comment]
hey @QilongTang can you point me to some docs on the `_` hotkey syntax?

**Comment by QilongTang** [comment]
> hey @QilongTang can you point me to some docs on the `_` hotkey syntax?

There is a good one in PR description, the definition is quite simple: https://wpf-tutorial.com/control-concepts/access-keys/

**Pull request merged**
