### PR TITLE
don't fail to load custom node if engine is null

### PR DESCRIPTION
**Pull request by mjkkirschner**
reported by @phliberato 

### Purpose
a very limited check, which does not throw when creating customnodes.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@QilongTang 

### FYIs

@phliberato @kronz

### CODE REVIEW

**Comment by QilongTang** [comment]
@mjkkirschner Unit test?

**Comment by mjkkirschner** [comment]
@QilongTang will do.

**Comment by mjkkirschner** [comment]
@QilongTang added some tests that check for the case in the task and a sanity check.

**Comment by mjkkirschner** [comment]
@QilongTang can this be merged?

**Comment by QilongTang** [comment]
Yes. LGTM

**Pull request merged**
