### PR TITLE
DYN-5210: Fix column width in custom selection node when no entries.

### PR DESCRIPTION
**Pull request by twastvedt**
### Purpose
| Issue | Fixed |
| ------------- | ------------- |
| issue | fixed |

This PR fixes [DYN-5210](https://jira.autodesk.com/browse/DYN-5210). When the custom selection node's list is empty, the "Display" and "Value" headers would collapse to a minimum width. Now they stay in the same place.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
 
### Reviewers
@avidit

### CODE REVIEW

**Comment by twastvedt** [comment]
@avidit I just saw your note in Jira about preventing deletion of the last list item. I think that makes sense. I'll go ahead and do that and add it here.

**Comment by twastvedt** [comment]
OK, now it's ready @avidit!

**Review by avidit — APPROVED** [review]

**Comment by twastvedt** [comment]
@avidit what's the status of 2.16.1 - should I cherry pick this into there?

**Comment by QilongTang** [comment]
@twastvedt was it supposed to be part of 2.16.1? If yes, please specify early next time. 2.16.1 was released yesterday

**Pull request merged**
