### PR TITLE
QNTM-3423: Update IronPython dependencies from NuGet

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose
Update IronPython dependencies from NuGet package and remove them from the `extern` folder. This also fixes the defect with the Python slice operator not supporting `Int64`'s.

JIRA Link: https://jira.autodesk.com/browse/QNTM-3423

### Declarations

Check these if you believe they are true

- [X] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner @pboyer 

### FYIs

@jnealb

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@aparajit-pratap did this actually fix the issue on the python side? What changes should we make if any regarding the ironPython installer? Do these nugets include the standard python libraries or just the required dlls?

**Comment by aparajit-pratap** [comment]
@mjkkirschner yes, this fixes the issue as you guessed rightly :)
Integers are still of type `Int64`. Still unsure where that changed along the way. According to Yu Ke they were always represented as `Int64`. I have also removed the IronPython from the `extern` folder. The NuGets come with `IronPython.Modules.dll` but not with the Python library that's implemented in `.py` files as those will only come with the IronPython installer I guess.

**Comment by mjkkirschner** [comment]
cool, one worry, if we update our ironPython version here but distribute a different version of ironPython that seems like it could cause trouble - any thoughts there?

**Comment by aparajit-pratap** [comment]
I don't like the idea of distributing the IronPython installer separately. Perhaps we can retain the `extern` folder and distribute the contents of the `IronPython\Lib` folder (that also contains the `.py` files) in it and follow a similar distribution model as grasshopper as suggested [here](https://forum.dynamobim.com/t/distribute-revit-dynamo-with-the-iron-python-standard-library/18996).

**Comment by jnealb** [comment]
@aparajit-pratap @mjkkirschner @smangarole @ramramps Design Script supported 32bit integer arithmetic: overflows etc. Shifting to 64bit would need to be analyzed/understood, no?

**Comment by Racel** [comment]
@aparajit-pratap @jnealb @mjkkirschner @pboyer @kronz - Had a lengthy discussion with @lukechurch about this. A few thoughts/actions because we are low on bandwidth and close to cutting an RC:

- it seems that it would be better if we understood why the shift to 64b was made in the first place. Can we try to make a test graph that only works with int32 and try to figure out which build the switch occurred using a bisect method? Let's start with running the graph in the first 2.0 build and see if it is broken there. If not, then try a build that was created halfway between that one and our current one, etc.

- while we are investigating when and why the switch occurred, lets also get a branch build out to QA so they can test this PR against a representative sample of graphs using Python to see if any breakages occur. It seems like updating to the latest version of IronPython is risky as the current version we are using was released in 2011. A multi-year delta between versions necessitates extensive testing from our end to sure nothing strange will occur in 2.0. It would be less problematic if the gap between versions was smaller. 

Can we do the 2 items above in parallel? Would like to know the reasoning behind the change, when it occurred, and what would happen if we introduced the proposed fix in this PR before we merge. What do you guys think?

**Comment by jnealb** [comment]
@aparajit-pratap Has found the PR: https://github.com/DynamoDS/Dynamo/pull/7224

**Comment by Racel** [comment]
@jnealb - The PR above is from september 2016... are we sure the same behavior is not present in 1.3.3? In other words, is the issue filed in the jira task a regression or not?

**Comment by jnealb** [comment]
@Racel Yes we are sure: the change never made it to 1.3.x. The issue filed in QNTM-3423 is not  a regression.

**Comment by Racel** [comment]
@jnealb - Ok. Thanks. What would happen if we revert @ke-yu 's PR? Is that worse than what is happening now?

**Comment by jnealb** [comment]
@Racel Since external 2.0 users have been relying on 64b integers since the daily builds were released reverting the PR has the potential to break those graphs. More fundamentally, large ints are far better suited to geometric workflows.

**Comment by aparajit-pratap** [comment]
@Racel reverting @ke-yu 's PR's https://github.com/DynamoDS/Dynamo/pull/7224 and https://github.com/DynamoDS/Dynamo/pull/7203 would cause the Github issue: https://github.com/DynamoDS/Dynamo/issues/7218 to reappear. I don't think it's a good idea to revert.

**Comment by jnealb** [comment]
@Racel @aparajit-pratap @smangarole I propose we close out QNTM-3423 and create another task for upgrading Python (which we decide upon soon) because we need to discriminate the two issues.

**Comment by jnealb** [comment]
@Racel There are 2 issues here: int datatype change and potential Iron Python upgrade. We need to track them separately. Please update QNTM-3513 as you see fit.

**Comment by mjkkirschner** [comment]
might be worth checking out this list of changes for this release of ironPython - https://github.com/IronLanguages/ironpython2/compare/ipy-2.7.7...ipy-2.7.8

seems like a large number of bug fixes and testing increases as well as support for .net core... pretty cool.

**Comment by aparajit-pratap** [comment]
@dimven from your experience of IronPython do you foresee any issues in upgrading Dynamo to this version?

**Comment by dimven** [comment]
From what I can tell, the iron languages team has shifted most of their effort into bringing ver. 3.0 into fruition. The 2.x versions of iron python has been shifted to compatibility support and bug fixes for a while now. Ver. 2.7.8 just came out so it will be hard to comment on it specifically, but considering there hasn't been any major new functionality, I don't foresee any unexpected problems with it.

You should really check with @eirannejad and @daren-thomas. Both PyRevit and the RevitPythinShell have been running on 2.7.7 for almost a year now and other than some minor compatibility issues with the ipy version loaded by Dynamo, there haven't been any problems with either.

What I'm more worried about is changing the distribution method for the standard library. My rough guesstimate is  that over 2/3s of the packages on the PM have python scripts in them and a sizeable portion of those will reference the current deployment found in 'C:\Program Files (x86)\IronPython 2.7\Lib' . Any changes here will have a large impact and will need to be properly coordinated with the package developers.

**Comment by aparajit-pratap** [comment]
@dimven thanks for your inputs. Your comment about packages is very useful. It is worthwhile to note that most python scripts in existing packages reference the version of IPy installed in  'C:\Program Files (x86)\IronPython 2.7\Lib'. @mjkkirschner @Racel @smangarole @kronz if we're going ahead with this PR I think it would be best to update the Dynamo installer to install the same IPy version (2.7.8) as the NuGet's in the same `C:\Program Files` location above.

**Comment by dimven** [comment]
Come to think of it, if you copy the standard lib folder and we automatically do a
> import sys; sys.path.append('\\newLibLocation')

call for every new script scope, that should prevent any compatibility issues because the order in which the paths are added is relevant and paths added earlier take precedence.

**Comment by mjkkirschner** [comment]
@dimven thats what I was thinking since you added library cacheing (if I recall correctly) that makes sense for all scripts to have access.

**Comment by aparajit-pratap** [comment]
@alfarok I'm closing this PR as you already merged yours.

**Pull request closed without merging**
