### PR TITLE
MAGN-8774 DynamoAPI documentation page for NotifyPropertyChangedInvocatorAttribute has formatting errors

### PR DESCRIPTION
**Pull request by ramramps**
### Purpose

This  PR fixes the issue around Example in Dynamo Documentation. Removed the extra characters and placed the C# code under the right markdown.

Link : http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-8774
### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@ikeough

### CODE REVIEW

**Comment by ikeough** [comment]
@ramramps The code looks fine. Is it possible to get a screen shot of the updated docs to ensure they are correct?

**Comment by ramramps** [comment]
@ikeough -  published this version. http://ramramps.github.io/DynamoAPI/Dynamo_Annotations/NotifyPropertyChangedInvocatorAttribute/.

**Comment by ikeough** [comment]
LGTM

**Comment by ikeough** [comment]
@ramramps One last change.
image

**Comment by ramramps** [comment]
@ikeough  - Please let me know whether I can merge now.

**Comment by ikeough** [comment]
LGTM

**Pull request merged**
