### PR TITLE
MAGN-8872 Preview geometry settings all set to visible with files downloaded from Customizer

### PR DESCRIPTION
**Pull request by marimano**
### Purpose

Add indicator whether geometry re-computation has been started or not. These changes are needed for Reach

### Reviewers

@pboyer @ramramps

### CODE REVIEW

**Comment by ramramps** [comment]
@pboyer - Can you PTAL at the REACH changes? Dynamo and Flood changes are OK.

**Comment by Racel** [comment]
@marimano - It looks like one of the checks did not pass. Can you take a look?

**Comment by Racel** [comment]
@ramramps - PTAL. @marimano made changes.

**Comment by ramramps** [comment]
LGTM !!

**Pull request merged**
