### PR TITLE
SelectInRegionCommand Removal in One test

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

It has been proved that one of the recorded test using  `DeleteModelCommand` following `SelectInRegionCommand` is not stable and could be VM setting dependent (see https://github.com/DynamoDS/Dynamo/pull/3718 ). This PR updates the test to just use `DeleteModelCommand` in this test because `SelectInRegionCommand` has been tested in multiple other tests and we should not have VM setting dependent test in the suite.

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner @aparajit-pratap

### CODE REVIEW

**Comment by mjkkirschner** [comment]
I wish we could know what this test was testing... but I'm okay with this to get the build going... @jnealb any idea?

**Comment by mjkkirschner** [comment]
lets get the builds going again LGTM. - @kronz how can we get access to this information from you track.

**Comment by kronz** [comment]
@mjkkirschner looks like it's in jira https://jira.autodesk.com/browse/MAGN-520 ?
"Convert all existing Nodes to DS compliant nodes"

**Comment by QilongTang** [comment]
@kronz @mjkkirschner Does not seem to be the same issue, however I found https://wiki.autodesk.com/display/ENGOPS/Dynamo+Test+Knowledge+Base was saying such test will fail when there is no directX installed on test machine, will check with BRE

**Comment by kronz** [comment]
If we need the old youtrack data, there's a process to set up a little server for their particular database we archived

**Pull request merged**
