### PR TITLE
Add workflow test for Curve.SweepAsSolid

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose

Add workflow test for Sweep method fixes in LibG: https://git.autodesk.com/Dynamo/LibG/pull/978

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@DynamoDS/dynamo

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@aparajit-pratap 
```
MESSAGE:
Points.SortPointsAlongCurve is a Unresolved node
Number of dummy nodes found in Sample: 1
+++++++++++++++++++
```

**Comment by aparajit-pratap** [comment]
The test graph has been updated by removing the dependency on external packages (so no unresolved nodes).

**Comment by aparajit-pratap** [comment]
@mjkkirschner the DynamoSelfServe should pass now that the latest LibG has been merged, however I don't think that it will be triggered again on this PR. Can I just merge this?

**Comment by aparajit-pratap** [comment]
> @mjkkirschner the DynamoSelfServe should pass now that the latest LibG has been merged, ~~however I don't think that it will be triggered again on this PR. Can I just merge this?~~

Never mind, I'll trigger it again manually.

**Pull request merged**
