### PR TITLE
Restore Dictionary & Builtin node documentation (alternative)

### PR DESCRIPTION
**Pull request by saintentropy**
### Purpose

This PR restores missing documentation (node descriptions and tooltips) for Dictionary and Builtin nodes. The PR adds the missing documentation for Buintin nodes found in https://github.com/DynamoDS/Dynamo/pull/8624 to the original proposal to _Fix Dictionary documentation by renaming Builtin.dll to DesignScriptBuiltin.dll_ in https://github.com/DynamoDS/Dynamo/pull/8617.  

This PR achieves identical result to https://github.com/DynamoDS/Dynamo/pull/8624 but may address some of the questions raised the implementation for that PR.

JIRA Issue: https://jira.autodesk.com/browse/QNTM-3491

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### FYIs

@aparajit-pratap @alfarok @pboyer

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@saintentropy did you notice this failure of the mono.sln?
```
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GenerateResources target) ->
					/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : Error executing task GenerateResource: Could not find file "/home/travis/build/DynamoDS/Dynamo/src/Libraries/DesignScriptBuiltin/DesignScriptBuiltinImages.resx"
					 174 Warning(s)
					 2 Error(s)
				Time Elapsed 00:00:15.7581990
```

I know the other failure is just an old project that was deleted from the other .sln but we forgot to remove it from the mono .sln

But this error seems related to this PR.

**Comment by saintentropy** [comment]
@mjkkirschner I did notice the failure but wasn't sure as cause... looking into it

**Comment by saintentropy** [comment]
probably case issue I missed

**Comment by alfarok** [comment]
@saintentropy I just pulled the branch, everything looks good in the library.  Let me know if you need another set of eyes on that one failure.

**Comment by saintentropy** [comment]
@alfarok Thanks.  It was the case issue.  It should be fixed now Builtin vs BuiltIn in the file name

**Comment by mjkkirschner** [comment]
LGTM

**Comment by mjkkirschner** [comment]
@saintentropy I think you will also need to update DynamoRevit branches now...

**Comment by saintentropy** [comment]
Yep working on those PR's right now

**Comment by aparajit-pratap** [comment]
LGTM!

**Comment by saintentropy** [comment]
Ok merging now and the DynamoRevit changes

**Pull request merged**
