### PR TITLE
Add JSON.Parse, JSON.Stringify, and JSON.StringifyList to core library

### PR DESCRIPTION
**Pull request by pboyer**
### Purpose

These code changes provide a small, but powerful set of APIs for working with JSON in Dynamo.

The API mirrors that available in JavaScript - `JSON.Parse`, `JSON.Stringify`, and `JSON.StringifyList`. The latter has a signature of `JSON.StringifyList(value: var[]..[])` so it prevents replication.

**JSON.Parse**

screen shot 2018-02-23 at 11 32 18 am

**JSON.Stringify**

screen shot 2018-02-23 at 11 44 18 am

**JSON.StringifyList**

screen shot 2018-02-23 at 2 48 15 pm

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@mjkkirschner 

### FYIs

@Racel @kronz

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@pboyer a couple thoughts:

* what happens if you stringify a complex type like geometry?
* what happens if you stringify a zeroTouch type that uses Json.Net attributes? Do they work? Should They? I assume converters that users specify using attributes won't work as those are not passed to the serializer. Should we allow that?
* is there no string literal notation in the DS parser to avoid the escaping - so someone can easily grab a json string from some other system? Is the escaping required in a string node?
*Does parse work on color? (I don't see it in the parse example)

otherwise looks pretty cool to me.

**Comment by pboyer** [comment]
Some discussion about naming with @kronz . I'm really open to other names. Please suggest:

screen shot 2018-02-26 at 10 34 10 am

**Comment by nonoesp** [comment]
(In relation to the screenshot of the discussion with @kronz.) I think it could make sense to — in lieu of  or in addition to `Dictionary.FromJSON` — have `Dictionary.FromObject`, which would be like packing `JSON.Stringify` and `JSON.Parse` as a custom node.

Then this,



Would be that,

montage

To roundtrip, `Object.FromDictionary` could be useful — but it wouldn't be possible to "guess" what type you want to cast in the object (for instance, both `Point` and `Vector` have `x`, `y`, and `z`).

**Comment by pboyer** [comment]
@nonoesp I really like this proposal conceptually. It would be really nice if we could take any arbitrary object in our system and turn it into a `Dictionary` - a type which has all the benefits of being "just data".

Unfortunately, most types will not benefit from this proposal unless they are designed for serialization (e.g. by having the appropriate property attributes and are represented in normalized form). `Color` is one of the few types in our system which will work nicely with `Dicitonary.FromObject`. As mentioned above, most objects will be serialized simply as "Namespace.TypeName", which cannot be deserialized into a `Dictionary`. 

Hence, I don't think `Dictionary.FromObject` should be implemented as part of the standard library at present because it introduces more API surface area, could be implemented by a user trivially (two nodes), and, at least presently, doesn't provides that much benefit.

**Comment by alvpickmans** [comment]
If welcomed, a few notes from my side:

>is there no string literal notation in the DS parser to avoid the escaping - so someone can easily grab a json string from some other system? Is the escaping required in a string node?

+ If json string is input by copy/paste, I would expect user to use a `string` node as a code block would throw an error if string is not previously escaped anyway. If read from a file/web request, it should parse the string without problem ([example on parsing web request](https://github.com/alvpickmans/JsonData/wiki/Simple-Web-Request))*

+ Regarding naming, it makes sense to follow those on javascript (*parse*, *stringify*, etc.) to be consistent with other platforms. There shouldn't be too much confusion assuming a user who wants to use JSON in Dynamo will be somehow familiar with the terms.
I would only suggest the use of `Json` capitalized instead of uppercased for the class name? I think it is according to the Coding Standards to follow the pascal capitlization convention for classes.

+ Supporting geometries seems to require a deeper thought: Only to/from Dynamo environment will restrain the interoperability character of a JSON file (feasible though), but trying to support different platforms would be like a total new project of cross-platform geometry interoperbility?

**Side Note**: I notice that on the ["Color-Stringify-Parse" example](https://user-images.githubusercontent.com/916345/36684906-c5b23824-1aef-11e8-8620-1b75f9451d4c.png) the output dictionary doesn't keep the key's original order (GABR instead of RGBA). I tested with different key/value pairs and it seems to sort them with no particular rule.

**The example uses the JsonData package which have very similar implementation of parsing json strings.*

**Comment by gregmarr** [comment]
>Side Note: I notice that on the "Color-Stringify-Parse" example, the output dictionary doesn't keep the key's original order (GABR instead of RGBA). I tested with different key/value pairs and it seems to sort them with no particular rule.

JSON objects are unordered, so any order is valid.

**Comment by nonoesp** [comment]
@pboyer that sounds right — completely agree 👌🏻.

**Comment by nonoesp** [comment]
@gregmarr we noticed this in multi-return nodes (but sadly these last ones do have an order which is not respected).

**Comment by alvpickmans** [comment]
@gregmarr I think the issue might be with dictionaries themselves (see picture below). I've just rebuild dynamo with latest commits in case my version was outdated.
image

**Comment by gregmarr** [comment]
@alvpickmans Dictionaries are similarly unordered.
@nonoesp The multi-return node has an order, once the items are in a dictionary, there is no order.  Dictionaries are not a great way to handle multi-return nodes.

**Comment by pboyer** [comment]
@alvpickmans Thanks for chiming in. I'm still on the fence about "JSON" vs "Json". I realize it is .NET convention to use this casing, but the tricky part with Dynamo is that it exposes our API's directly in the user interface - the API naming and user interface are convolved. 

The Json.NET landing page is a great example of this problem: https://www.newtonsoft.com/json They use "JSON" whenever they're talking about the format and "Json" when they're referring to a identifier in the code. For Dynamo, these are one in the same. Still on the fence...

**Comment by pboyer** [comment]
@nonoesp  @gregmarr @alvpickmans Since https://github.com/DynamoDS/Dynamo/pull/8487, multi-return outputs are returned in the order of the outputs:

screen shot 2018-02-26 at 6 01 15 pm

As @gregmarr notes, we do not sort Dictionaries internally. The order is determined by however the .NET. We don't want people to depend on Dictionaries as sorted data structures. You can get the values or keys sorted pretty easily:

screen shot 2018-02-26 at 6 06 19 pm

**Comment by alvpickmans** [comment]
@pboyer I also checked Json.NET before commenting. To me `Json` seems more in line with Dynamo UI/UX but it is true the format is `JSON` according to its standards.

@pboyer @gregmarr @nonoesp My comment wasn't about sorting dictionaries per se, but more related to a WYSIWYG kind of behaviour when creating a new dictionary by keeping the order of the key/value inputs.  It might seem wrong at first glance that your second input is last on the output dictionary if you're not familiar with them. Thanks for clarifying though!

**Comment by Racel** [comment]
@pboyer - Please hold off on merging this until we discuss a bit more.

**Comment by saintentropy** [comment]
@Racel @ramramps Hey are we able to merge this again?  It might be really helpful for the Boulder team to have this

**Comment by saintentropy** [comment]
@mjkkirschner Still DNM?

**Comment by mjkkirschner** [comment]
I think there was still some discussion around where these nodes belong in the library.

**Comment by ramramps** [comment]
I will leave it to @Racel.

**Comment by Racel** [comment]
@saintentropy @mjkkirschner @ramramps We need more discussion/debate on this. There are still quite a few things we need to solve:
(1) do these nodes belong in the OOTB library or do they belong in a "shipped package"? If so, where do they belong in the library? With Dictionary nodes or Web nodes?
(2) proper naming of the nodes so that users understand what they do and are useful for.

Lets discuss internally before this gets merged. I think we need to come up with a strategy for JSON and other Web related nodes first.

**Comment by jnealb** [comment]
Is there a JIRA task for this work?

**Comment by alfarok** [comment]
@Racel do we have a task for trying to get these nodes into 2.1?

**Comment by ColinDayOrg** [comment]
@alfarok QNTM-4330

**Comment by mjkkirschner** [comment]
closing this as https://github.com/DynamoDS/Dynamo/pull/9290 replaces it.

**Pull request closed without merging**
