### PR TITLE
MAGN-6097 Ports added using the new AddPort method do no have their ToolTipData set correctly.

### PR DESCRIPTION
**Pull request by ikeough**
This PR addresses [MAGN-6097](http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-6097).

During the core modularization work, an `AddPort` method was created on `NodeModel`. This method is meant to replace the traditional way of adding ports on a node, which is to add a `PortData` object to the `InPortData` or `OutPortData` collection on the nodes and then calling `RegisterAllPorts`.

The `AddPort` method takes a `PortData` as one of its inputs, but does not put that `PortData` object in the `InPortData` collection. As such, properties like the PortModel's `ToolTipContent` property which accessed the text by way of looking it up in the `InPortData` or `OutPortData` collections, were not able to find it.

This PR sets the `ToolTipContent` directly on the port using the `PortData` object passed into the constructor.

PTAL:
- [x] @pboyer

### CODE REVIEW

**Comment by ikeough** [comment]
@pboyer Ping!

**Comment by pboyer** [comment]
MUCH BETTER!  I'd love a unit test here, as dumb as it might seem.

**Comment by ikeough** [comment]
@pboyer It's not dumb. We should have had these all along. There are a couple now, just to verify that the tooltip content is set - which is the focus of this PR - but there are probably more node construction tests that would be worthwhile.

**Comment by pboyer** [comment]
LGTM

**Pull request merged**
