### PR TITLE
[Need Feedback] Update Download Status Bar Width

### PR DESCRIPTION
**Pull request by QilongTang**
Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

I noticed there is a gap of the download status in DPM. Thought it is a lower hanging fruit but would like to start the discussion by using a PR to illustrate.

DynamoRevit 2.0.2 on Revit 2019
image

Dynamo master branch
image

After the fix on Dynamo master branch
image

### Declarations

Check these if you believe they are true

- [ ] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@DynamoDS/dynamo

### CODE REVIEW

**Comment by mjkkirschner** [comment]
big deal to pull out the 300 and in the stackPanel width as well so it only needs to be updated in one place in the future?

**Comment by QilongTang** [comment]
@mjkkirschner Can you elaborate?

**Comment by mjkkirschner** [comment]
@QilongTang not much more to elaborate - my suggestion is to pull out the constants to the dynamo configuration file.
https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCore/Configuration/Configurations.cs

**Comment by QilongTang** [comment]
@mjkkirschner I searched around and found these properties are not used?

**Comment by mjkkirschner** [comment]
some of them are not, guess people forgot to remove them, but some are:
https://github.com/DynamoDS/Dynamo/search?q=FallbackUiCulture&unscoped_q=FallbackUiCulture

**Comment by QilongTang** [comment]
@mjkkirschner After some investigation, still does not seem proper here. A lot of the other cases has been used in the converter for run-time calculations but the case here is that I only want a const number to reference. The configuration.cs is in DynamoCore which I will not be able to reference in DynamoCoreWpf, so I end up having to use a converter here which defeats the purpose.. An alternative I believe what we should do is that we create a config in DynamoCoreWpf project so I can reference in the xml like
```
        xmlns:configs="clr-namespace:DynamoCore.wpf.Configuration"
        <StackPanel Width ="{x:Static configs:Configurations.PackageManagerProgressBarWidth}" >
```

If you do not object, I would like to merge as it is.

**Comment by mjkkirschner** [comment]
go for it.

**Comment by QilongTang** [comment]
@mjkkirschner Thanks. Merging.

**Pull request merged**
