### PR TITLE
Dyn 4556 alignment tool icons

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose

Adding Icons to the Alignment menu

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers
@QilongTang

### FYIs
@RobertGlobant20 @filipeotero

### CODE REVIEW

**Comment by jesusalvino** [comment]
imagen

**Comment by jesusalvino** [comment]
imagen

**Comment by QilongTang** [comment]
https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/6021/

**Comment by QilongTang** [comment]
Tests passed while the SelfServe check did not update. Merging.

**Pull request merged**
