### PR TITLE
Update Operators.xml

### PR DESCRIPTION
**Pull request by htlcnn**
### Purpose

Fix the description of the **Operators.%** node to match its behaviour

### Declarations

The **Operators.%** node returns the remainder of x/y instead of Boolean values as the current description *Is x divisible by y?*

### Reviewers

@ramramps

### CODE REVIEW

**Comment by ramramps** [comment]
@Racel Ping.

**Comment by Racel** [comment]
The description looks like a good improvement. Looks good to me.

@ramramps - is there anywhere else this description needs to be updated?

**Comment by ramramps** [comment]
@Racel, I think this should be good.

**Comment by htlcnn** [comment]
Is there something more I need to do for this PR @ramramps @Racel ?

**Comment by ramramps** [comment]
Looks good @htlcnn. You can merge it,.

**Comment by htlcnn** [comment]
@ramramps I don't have write access to merge

**Pull request merged**
