### PR TITLE
DYN-6901 Pm - removed dyf files deletion

### PR DESCRIPTION
**Pull request by dnenov**
### Purpose

A small PR to remove and old side-effect of the process of publishing packages where the source of the custom definitions will be deleted. This has caused confusion and potential loss of data while at the same time not adding much value to the publishing experience. 

Initial testing shows that there are no unwanted knock-on effects of removing the logic, however the code is only being commented out for the time being. If there are any issues in the future, this PR can safely be reverted.

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [x] This PR modifies some build requirements and the readme is updated
- [x] This PR contains no files larger than 50 MB

### Release Notes

- removed (commented out) the logic to delete the source for the custom definition during the package creation process

### Reviewers

@QilongTang 
@zeusongit 

### FYIs

@Amoursol 
@reddyashish

### CODE REVIEW

**Review by zeusongit — APPROVED** [review]

**Comment by mjkkirschner** [comment]
Have you guys identified what PR brought this behavior in and why it was implemented?

**Comment by zeusongit** [comment]
> Have you guys identified what PR brought this behavior in and why it was implemented? That would make me feel more confident in removing it.

Here is what we know so far:
The code was originally added by @pboyer when the file was created 9 years ago in this [PR](https://github.com/DynamoDS/Dynamo/pull/4371)
Also some discussion on this [Slack thread](https://autodesk.slack.com/archives/C1866AFQB/p1719503136267509)

**Comment by QilongTang** [comment]
> Have you guys identified what PR brought this behavior in and why it was implemented? That would make me feel more confident in removing it.

yeah we asked around and the reason for the deletion was unknown, both me and @kronz was guessing because of custom node workspace can be modified in multiple places so trying to keep the only source of truth.. The decision to revert the behavior was intentional

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Regressions:
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_CopiesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_CopiesTheOriginalFiles/)
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_DeletesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_DeletesTheOriginalFiles/)
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_DoesExpectedNumberOfOperations](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_DoesExpectedNumberOfOperations/)
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_DoesNotIncludeUnselectedFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_DoesNotIncludeUnselectedFiles/)
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageRetainDirectory_CopiesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageRetainDirectory_CopiesTheOriginalFiles/)
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildRetainPackageDirectory_DeletesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildRetainPackageDirectory_DeletesTheOriginalFiles/)
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildRetainPackageDirectory_DoesExpectedNumberOfOperations](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildRetainPackageDirectory_DoesExpectedNumberOfOperations/)
[Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildRetainPackageDirectory_DoesNotIncludeUnselectedFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildRetainPackageDirectory_DoesNotIncludeUnselectedFiles/)

**Comment by dnenov** [comment]
> Regressions: [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_CopiesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_CopiesTheOriginalFiles/) [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_DeletesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_DeletesTheOriginalFiles/) [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_DoesExpectedNumberOfOperations](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_DoesExpectedNumberOfOperations/) [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageDirectory_DoesNotIncludeUnselectedFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageDirectory_DoesNotIncludeUnselectedFiles/) [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildPackageRetainDirectory_CopiesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildPackageRetainDirectory_CopiesTheOriginalFiles/) [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildRetainPackageDirectory_DeletesTheOriginalFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildRetainPackageDirectory_DeletesTheOriginalFiles/) [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildRetainPackageDirectory_DoesExpectedNumberOfOperations](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildRetainPackageDirectory_DoesExpectedNumberOfOperations/) [Dynamo.PackageManager.Tests.PackageDirectoryBuilderTests.BuildRetainPackageDirectory_DoesNotIncludeUnselectedFiles](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16269/testReport/junit/Dynamo.PackageManager.Tests/PackageDirectoryBuilderTests/BuildRetainPackageDirectory_DoesNotIncludeUnselectedFiles/)

Sorted out now @QilongTang - apologies for the delayed response on this.

**Review by reddyashish — APPROVED** [review]
Waiting for the job to finish.

**Comment by reddyashish** [comment]
One test failing still, is this passing locally? 
Screenshot 2024-07-11 at 10 54 01 AM

**Comment by dnenov** [comment]
> One test failing still, is this passing locally? Screenshot 2024-07-11 at 10 54 01 AM

Yes, it does pass locally ... I don't know how this test can be related.

**Comment by QilongTang** [comment]
Hi @dnenov Please resolve the merge conflict now that other PRs merged

**Comment by reddyashish** [comment]
4 tests have failed in the last job, @dnenov can you check them locally on this branch? Thanks

Screenshot 2024-07-16 at 9 41 53 AM

**Comment by dnenov** [comment]
I think this one passes all the tests now: 
image @reddyashish

**Comment by QilongTang** [comment]
Hi @dnenov I think the previous run did not finish, I re-run it at https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16323/ and found a few regressions, please check

**Comment by dnenov** [comment]
@reddyashish - I checked this test locally, and it passes .. not sure what's going on with this PR.
image

**Comment by reddyashish** [comment]
@dnenov Thanks Deyan. I think this is a flaky test, running the job one last time to be sure.

**Comment by reddyashish** [comment]
Passed: https://master-5.jenkins.autodesk.com/job/Dynamo/job/DynamoSelfServe/job/pullRequestValidation/16330/

**Review by reddyashish — APPROVED** [review]

**Pull request merged**
