### PR TITLE
DYN-6908 string from object float precision

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Calculating the double precision dynamically based in the number of decimals provided in the double value.
When using a double value with more than 15 decimals and passing the value to the StringFromObject node was truncating the output to use only 6 decimals so I did a fix in a way that the precision will be calculated dynamically.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [X] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Calculating the double precision dynamically based in the number of decimals provided in the double value.

### Reviewers

@QilongTang 

### FYIs

@mjkkirschner @jnealb

### CODE REVIEW

**Comment by RobertGlobant20** [comment]
This is a GIF showing the expected behavior.
yYjUNpRHU3

**Comment by mjkkirschner** [comment]
I think that modifying the standard output this node has produced for the last 10 years needs to be considered as a potential API behavior break.

I think a more backwards compatible solution like:
https://jira.autodesk.com/browse/DYN-6225 would be a better approach.

**Comment by QilongTang** [comment]
Hi @mjkkirschner The proposal does make sense, thinking about it, I wonder if this is the case that bug becomes feature.. So I am not sure one way or the other, since this was originally panned for 3.2.0 release, if we took the other approach, how complex it would be? FYI: @Amoursol

**Comment by Amoursol** [comment]
> Hi @mjkkirschner The proposal does make sense, thinking about it, I wonder if this is the case that bug becomes feature.. So I am not sure one way or the other, since this was originally panned for 3.2.0 release, if we took the other approach, how complex it would be? FYI: @Amoursol

Agree with @mjkkirschner that this behavior change will impact legacy graphs that have been built specifically with this kind of output in mind. In other scenarios we have the Dynamo UI showcase numbers graphically that differ from what is actually happening under the hood, so we don't have consistency. 

The more holistic fix is as Mike mentioned, adding a new overloaded node that enables the user to specify the precision. Given the code in this PR, it feels like a pretty simple addition? Can re-use icons, only need to recreate Extended Help and Sample that should be quick enough. 

Thoughts?

**Comment by RobertGlobant20** [comment]
There is already a proposal for fixing this bug in a different way.

**Pull request closed without merging**
