### PR TITLE
update the openifSave command to update the filePath before calling t…

### PR DESCRIPTION
**Pull request by mjkkirschner**
cherry pick:
https://github.com/DynamoDS/Dynamo/pull/9443

### CODE REVIEW

**Comment by QilongTang** [comment]
Restarted EngOps Build

**Comment by QilongTang** [comment]
LGTM

**Comment by mjkkirschner** [comment]
self serve passed.

**Comment by mjkkirschner** [comment]
@QilongTang should this job automatically upload artifacts?

**Comment by QilongTang** [comment]
yup

**Pull request merged**
