### PR TITLE
Add geometry test for ASM fix 

### PR DESCRIPTION
**Pull request by aparajit-pratap**
### Purpose
https://jira.autodesk.com/browse/DYN-1855

This is a workflow test to test a geometry fix in ASM for a [Dynamo bug](https://jira.autodesk.com/browse/DYN-1854) reported by the Alias team.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### CODE REVIEW

**Comment by QilongTang** [comment]
Does the test `GeometryDoesIntersect_WithNurbsSolid_IsCorrect` pass for you locally?

**Comment by aparajit-pratap** [comment]
Ah, this is what I feared would happen. The fix in ASM is present only in ASM 226 upwards and our CI still uses ASM 225, which is why this test fails. @alfredo-pozo how hard is it to change the CI to ASM226 or 227? Can we do that right away?

**Comment by alfredo-pozo** [comment]
Yes, I can do that change, I'll let you know when its ready @aparajit-pratap

**Comment by aparajit-pratap** [comment]
> Yes, I can do that change, I'll let you know when its ready @aparajit-pratap

Thanks @alfredo-pozo!

**Review by QilongTang — APPROVED** [review]

**Comment by aparajit-pratap** [comment]
@QilongTang I have temporarily marked this test as "Failure" as discussed until the CI is not updated to use ASM227.

**Comment by QilongTang** [comment]
@aparajit-pratap That works!

**Comment by aparajit-pratap** [comment]
The CI test failure is unrelated to this PR. Also running the test locally passes on latest master.

**Pull request merged**
