### PR TITLE
Fixed List.Transpose for jagged arrays

### PR DESCRIPTION
**Pull request by aparajit-pratap**
Given a list like:
```
{{1, 2, 3}, {1, 2, 3, 4}}
```
Its transpose using `List.Transpose` node would compute to:
```
{{1, 1}, {2, 2}, {3, 3}, {4}}
```

I'm not sure if this is acceptable especially if you're writing this out to a table such as in Excel; the expected output would be:
```
{{1, 1}, {2, 2}, {3, 3}, {null, 4}}
```

This submission fixes this.

@ke-yu PTAL

### CODE REVIEW

**Comment by ke-yu** [comment]
@aparajit-pratap , don't we have any test cases for this one?

**Comment by aparajit-pratap** [comment]
@ke-yu I have added test cases in `ListTests.cs`

**Comment by ke-yu** [comment]
no, there are some test cases in DynamoCoreTests test old behavior. For example, `TestTransposeNormalInput`. @riteshchandawar could you please take a look to see which behavior is correct.

**Comment by riteshchandawar** [comment]
@ke-yu @aparajit-pratap As discussed we need to check this new behavior with @mccrone and @kronz, because I am expecting some User Workflow might fail because of this change.

But on the other line, it is required to change to fix issue in writing data to Excel for jagged arrays.

**Comment by aparajit-pratap** [comment]
Also this example seems weird with the current behavior of `List.Transpose`. One would expect to get the original array back after performing `Transpose` twice but that is not the case:
image

**Comment by aparajit-pratap** [comment]
On the contrary, the built-in `Transpose` method used internally seems to have the right behavior:
image

**Comment by kronz** [comment]
AHA!  interesting, yes, the built in method looks right to me:

**Comment by mccrone** [comment]
Wow.  Yeah, let's go with List.Transpose being identical to the built-in method.  Can't this also be an excellent opportunity to get rid of another built-in method too, then?!

**Comment by ke-yu** [comment]
@aparajit-pratap , so once `List.Transpose()` is done, you could disable builtin `Transpose()`

**Comment by riteshchandawar** [comment]
In DesignScript time frame all list operation was done using Built-in methods,hence there is a lot of overlap between Built-in methods and in List nodes. We need to resolve that in future to avoid confusion for users. Another point is Built-in methods works very well with List and Single items.

**Comment by aparajit-pratap** [comment]
I have created a ticket to track the task of deprecating the built-in method here: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7309

**Comment by mccrone** [comment]
As we deprecate the built-in methods, will we be sacrificing functionality, re: @riteshchandawar's comment about the built-in functions' ability to deal with lists and items better than other nodes?

**Comment by riteshchandawar** [comment]
@mccrone As long as we get the same functionality in List nodes we are good to deprecate Built-in methods. 

Once we deprecate Built-in method we should validate its output with the similar List node.

Thanks,
Ritesh

**Pull request merged**
