### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Amoursol**
The Dynamo blog (Wordpress website) cannot host .DYN files and we need to do so for a blog post by Colin McCrone on post-COVID office layout.

### CODE REVIEW

**Comment by mmisol** [comment]
HI @Amoursol . There are alternatives to uploading these files other than putting them in the main Dynamo GitHub repository. Given they are not related to the source and the need to upload files for users in the forum will continue to exist after this, I would choose not to go in this direction. Could we at least use another repo? Temporary storage for files can be achieved in a number of ways while we come up with a better solution to the problem.

**Comment by Amoursol** [comment]
Totally cool by me - I can look for a better place to house these :)

**Comment by QilongTang** [comment]
I actually think it is good and better live in Dynamo repo. Given 

- this repo already contains a lot of Dynamo test graphs
- dyn files do not take much space comparing to other binaries cases
- side repos are easy to create but always got forgotten later. 

One alternative is that @Amoursol You can use your personal Github storage for this. The way to do it is that you drag the file to PR which will generate a link for you and you use that link for blog post. But will appear less official than current approach. I am supportive of this way.

However, open for suggestions. @DynamoDS/dynamo Any other ways you can think of or comments?

**Comment by mmisol** [comment]
@QilongTang I would argue this is in a different category than graphs used for tests. If we start taking graphs made by the community, I'm thinking it should not be up to us to maintain them. Also there may be legal implications just by accepting them in our repo.

**Comment by QilongTang** [comment]
@mmisol I forgot to mention the author of this is from ADSK not community if that is your concern. Colin used to work for Dynamo team but now moved on to Forge. I do not think our team plan to store or maintain graphs from community in general.

**Comment by Amoursol** [comment]
Closing this PR as it's not the ideal place to house Wordpress content.

**Pull request closed without merging**
