### PR TITLE
Clean up Player internal visibility assemblies

### PR DESCRIPTION
**Pull request by twastvedt**
### Purpose

- Remove some now-unnecessary internal-visible assembly names.
- Add a namespace to future-proof for a possible more general version of the Forma connector.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Add and modify namespaces for Dynamo Player.

### Reviewers

(FILL ME IN) Reviewer 1 (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

### CODE REVIEW

**Comment by twastvedt** [comment]
@saintentropy - did you have a thought on the name of the future extension?

**Comment by BogdanZavu** [comment]
I don't feel strongly about it but I would say to keep DynamoPlayer.Extension for now at least. Ok will all the other removals.  
If we don't and somehow it turns out that later in 2025 we need some utility or to override something it might complicate things.

**Review by BogdanZavu — APPROVED** [review]

**Comment by QilongTang** [comment]
Hi @twastvedt Do need to tackle the following TODO now or in another PR?
`TODO: Add the name of a possible future Forma extension so it's ready in 3.0.`

**Comment by twastvedt** [comment]
> Hi @twastvedt Do need to tackle the following TODO now or in another PR? `TODO: Add the name of a possible future Forma extension so it's ready in 3.0.`

Was intended to do now. @saintentropy was going to add that to this PR.

**Comment by QilongTang** [comment]
@twastvedt @saintentropy Any updates to this PR?

**Comment by twastvedt** [comment]
> @twastvedt @saintentropy Any updates to this PR?

Yes, sorry, it now looks good to us.

**Review by QilongTang — APPROVED** [review]
LGTM

**Pull request merged**
