### PR TITLE
MAGN-7779 Preset can floor slider fields to 0 when numbers are in scientific notation

### PR DESCRIPTION
**Pull request by ramramps**
### Purpose

This PR fixes the issue with BigNumbers on Double Sliders.

Link to YouTrack:
 http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-7779

### Declarations

- [x] The code base is in a better state after this PR
- [ x ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files

### Reviewers

@holyjewsus

### CODE REVIEW

**Comment by holyjewsus** [comment]
@ramramps this looks okay to me, my understanding is that our big number strings get converted to scientific notation, but our converter to parse them throws away that format, so the fix is just to enable parsing of that format which makes sense...

I want to run this on self serve CI, to make sure no tests fail that were expecting those results from the converter.

I will reply again when I get the green light from the CI

**Comment by jnealb** [comment]
@ramramps @holyjewsus @pboyer Would it be possible to document the rules of the road for this formatting of big nums, e.g when is it triggered, what nodes are affected (only sliders?) etc?

**Comment by ramramps** [comment]
@jnealb - I dont think this is going to affect other places. This is only for Sliders.

**Comment by holyjewsus** [comment]
@ramramps I got a weird result from the CI, can you please run this branch on there, 0 errors and 0 failures, but CI says the run completed with errors...

**Comment by holyjewsus** [comment]
@ramramps it appears there were a bunch of memory access violations in some tests... I'm not sure why these did not come up in the errors log directly, but they are there in diagnostics. Please run this branch on the self serve and see if you get the same errors - maybe it was just a fluke.

**Comment by ramramps** [comment]
@holyjewsus -Yeah I got the same results. I am not sure whether this change is affecting that. this change is mainly used by sliders

**Comment by jnealb** [comment]
@ramramps @holyjewsus Can you please shoot me an email identifying these faulty tests?

**Comment by holyjewsus** [comment]
@ramramps does master have the same errors in the log on the self serve CI?

**Comment by ramramps** [comment]
@holyjewsus - I ran the same for Master and I got the same Access Violation errors.

**Comment by holyjewsus** [comment]
@ramramps if there are no regressions from master and master exhibits the same access violations then we'll have to assume this is a CI setup issue and LGTM on this.

**Pull request merged**
