### PR TITLE
Cherry-pick language changes into 2.0.3 branch for Refinery

### PR DESCRIPTION
**Pull request by reddyashish**
### Purpose

This PR is to cherry-pick language changes that went in after 2.0.3 branch was created. 

Refer to this task for more information: https://jira.autodesk.com/browse/DYN-1879

The commits related to following tasks were cherry-picked:

1) **DYN-1056** : https://github.com/DynamoDS/Dynamo/pull/9388
2) **DYN-1688** :  https://github.com/DynamoDS/Dynamo/pull/9559
3) **DYN-1722** : https://github.com/DynamoDS/Dynamo/pull/9578
4) **DYN-1496** : some of the cases in this task have been fixed using the PR referenced to DYN-1172 https://github.com/DynamoDS/Dynamo/pull/9578
5) **DYN-995** : https://github.com/DynamoDS/Dynamo/pull/9388 (same PR as for the DYN-1056 task)
6) **DYN-1759** : https://github.com/DynamoDS/Dynamo/pull/9632
7) **DYN-1198** : https://github.com/DynamoDS/Dynamo/pull/9408 and https://github.com/DynamoDS/Dynamo/pull/9441

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

@aparajit-pratap @mjkkirschner

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
@reddyashish it looks like your 5th and 6th commits are not in chronological order. Did you come across any conflicts?
1. #9388 merged on Jan 10th
2. #9559 merged on Mar 14th
3. #9578 merged on Mar 25th
4. #9632 merged on Apr 9th
5. #9408 merged on Jan 12th
6. #9441 merged on Jan 18th

**Comment by aparajit-pratap** [comment]
Have you run self-serve on this PR?

**Comment by reddyashish** [comment]
@aparajit-pratap, the self serve has no regressions. The 5th and 6th commits are related to a one task(infinite loop bug) and the changes are made to different files compared to the other 4 commits. So there were no conflicts there.

**Comment by reddyashish** [comment]
Removed the DsCoreDataTests file as this was introduced by a different PR https://github.com/DynamoDS/Dynamo/commits/master/test/DynamoCoreTests/DSCoreDataTests.cs. 

The changes to this file, that were done by this PR(https://github.com/DynamoDS/Dynamo/pull/9388) are being ignored.

**Comment by mjkkirschner** [comment]
@saintentropy PTAL

**Comment by aparajit-pratap** [comment]
LGTM!

**Comment by QilongTang** [comment]
@saintentropy Since we will have daily build after this change, does it make sense for Black Team to also consume this build early and play with it? I expect installer change required still on your end to install Refinery on Dynamo 2.0.3 OOTB. Please check.

**Pull request merged**
