### PR TITLE
Cherry-pick: Display input port type specific default suggestions only (#11268) AND Node AutoComplete suggestions sorted alphabetically within the same group (#11280)

### PR DESCRIPTION
**Pull request by zeusongit**
* input port type specific default suggestions

* test fix

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@zeusongit why does this cherry pick have more changes than the original PR?

**Comment by QilongTang** [comment]
@mjkkirschner This PR cherry-picked two PRs into RC2.10.0

**Comment by mjkkirschner** [comment]
cool - I missed the `AND`

**Review by QilongTang — APPROVED** [review]
@zeusongit LGTM.

**Pull request merged**
