### PR TITLE
changes to specify namespace.properties.resources in NodeDescription

### PR DESCRIPTION
**Pull request by Sancerio**
Hi @Benglin , please review and merge

PTAL
@nguyen-binh-minh @zora-wang

### CODE REVIEW

**Comment by nguyen-binh-minh** [comment]
LGTM

**Comment by Sancerio** [comment]
@holyjewsus please check the latest commit (4e0d20d) . I believe it should be changed

**Comment by Benglin** [comment]
Hi @holyjewsus I need to attend to few other things right now, could you please give a green light when this can be merged? Either you or myself can merge it once it's validated. Thanks in advance!

**Comment by holyjewsus** [comment]
@Sancerio you're right, the diff on github is incorrect, just pulled and built, descriptions show up fine as far as I can tell. @Benglin LGTM

**Comment by Benglin** [comment]
Thanks so much for your help, @Sancerio and @holyjewsus!

**Pull request merged**
