### PR TITLE
MAGN-9389 Crash when adding a file to update a package version

### PR DESCRIPTION
**Pull request by marimano**
### Purpose

The issue which causes crash is that the specified .dyf file contains malformed annotation, i.e. it has a guid among its models which does not correspond to any node.

### Declarations

- [x] The code base is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.

### Reviewers

@aosyatnik

### CODE REVIEW

**Comment by aosyatnik** [comment]
@marimano it looks good to me.
But there is question for Colin.

Hi, @mccrone , how did you create this file (I mean with bad node guid, Point.ByGridAtSun.dyf). It's great, that we add more fixes in Package Manager. But I believe the problem is deeper. The real problem is that user somehow can get a malformed file. And this should be fixed for sure.

I tried adding and deleting nodes from groups, but no success. We need search carefully for this bug.

FYI @jnealb , we have somewhere bug, when node is deleted from workspace, but not from group. For now I couldn't reproduce, but it doesn't mean, that this bug is gone.

**Comment by mccrone** [comment]
@aosyatnik I don't recall doing anything out of the ordinary to make this file.  I certainly didn't do anything outside of the UI.  Is the issue that the custom node has a bad GUID, or is a particular node inside the dyf?

**Comment by mjkkirschner** [comment]
Hmm have we tried creating a custom node from some nodes in a group ?

**Comment by aosyatnik** [comment]
@mjkkirschner , @mccrone , I tried to create group in custom node. Also created custom node from group. Looks like it works fine... Maybe, this file was made sometime ago, when annotations were not so stable. I'm going to merge this fix anyway, but let's be careful about this bug. Maybe, it will show itself in future.

**Comment by mccrone** [comment]
@aosyatnik that's possible!  The content is all new, but I think I started with an older dyn, so it might effectively be an older file.

**Pull request merged**
